### ISSUE TITLE
API method for identifying Styled Components and wrapped/extended Styled Components

### ISSUE THREAD

**Issue by evan-scott-zocdoc** [styled-components/styled-components#1021]
I came across a use case today where there's a component that expects children of a certain type to be provided. It then pulls them out individually and recomposes them in a specific way.

With styled components, this becomes somewhat difficult because there isn't an easy way to say "is this component instance X related to styled component constructor Y?"

In normal React land, you'd do something like this:

```js
if (element.type === ComponentConstructor)
``` 

But for styled components created via `styled(X)`, that's actually buried a level deeper in `element.type.target`. It'd be nice if there was a first-party way to do this type of lookup without having to know how s-c works internally.

Perhaps an API like:

```jsx
// a.js

import styled from 'styled-components';
export const BaseComponent = styled.div``;


// b.js

import React from 'react';
import { elementIsStyledComponent } from 'styled-components';
import { BaseComponent } from './a';

export class Blah extends React.Component {
    render() {
        const children = React.Children.toArray(this.props.children);

        // is BaseComponent in the children?
        if (children.some(child => elementIsStyledComponent(child, BaseComponent))) {
            // yay, do something
        }
    }
}


// c.js

import React from 'react';
import styled from 'styled-components';
import { Blah } from './b';
import { BaseComponent } from './a';

const StyledBaseComponent = styled(BaseComponent)`
    color: blue;
`;

class ConsumerOfStyledBaseComponent extends React.Component {
  render() {
    <Blah>
        <StyledBaseComponent />
    </Blah>
  }
}
```

**Comment by philpl** [comment]
You can actually identify Styled Components how we identify them internally. Using their `styledComponentId` static property.

https://github.com/styled-components/styled-components/blob/master/src/models/StyledComponent.js#L204

You can also just check whether `AbstractStyledComponent` is in the prototype chain, although we don't need this class ourselves anymore, and might delete it at some point.

https://github.com/styled-components/styled-components/blob/master/src/models/AbstractStyledComponent.js

The big reason why we don't add APIs every month, and for small use-cases like these is basically: We don't want to bloat the API, and once we introduce a certain functionality, we have to maintain it **forever**, since we're quite careful not to horribly break backwards-compatibility.

This is a proposal that is not useless, but at the same time not essential. It's certainly useful to be able to do this, if you know what you're doing—in which cases you can do one of the above things—but if we put a first-class API forward, we basically tell people that they **should** be writing their components using this technique. Because this is how styled-components works. It's enforcing and restricting practices to form **best practices** effortlessly. So as we add more bells and whistles, this clear and simple "path of best practices" becomes fuzzier. That is our general concern.

I'm not sure what you would like to achieve using this functionality, but I'm pretty sure it can either be avoided using some restructured and simpler structural components, or using some workarounds in the worst case.

> I came across a use case today where there's a component that expects children of a certain type to be provided. It then pulls them out individually and recomposes them in a specific way.

I've seen a lot of projects do this, most notably react-mapbox-gl (https://github.com/alex3165/react-mapbox-gl), but oftentimes it wasn't actually required to write such an API. It could either be enforced using types or using an implicit contract, or could be avoided with a different API or compositional logic.

All in all—I do have my doubts, but I think it's a valuable discussion :smile:

cc @mxstbr

**Comment by mxstbr** [comment]
I agree, I don't think it's worth adding as an explicit API. `styled-components` just surpassed 1,000,000 downloads and has been out for what, like 8 months?, and we haven't had anybody ask for this API before.

Since you managed to work around it anyway I don't see any need to add an explicitly supported API. I won't say we'll break `element.type.target` but I also won't say we won't-we'll see what the future holds for the library in that regard.

**Comment by probablyup** [comment]
I understand. I'll add unit tests to verify my assumptions about your
internal API then.

Thanks.

**Comment by philpl** [comment]
> just surpassed 1,000,000 downloads and has been out for what, like 8 months?, and we haven't had anybody ask for this API before.

To add a closing comment, or rather a thought; If you or anyone else feels that it's important to discuss this in detail again and would like to make an argument as to why an addition to our API is absolutely essential, we're always open to listen and discuss it.

We have reason to believe that our API is as close to what people want it to be as we can get it, but we might always be wrong about some things :wink:

**Comment by mxstbr** [comment]
Oh yeah sorry, I didn't mean for that to sound as condescending and absolute as it did. If you have a use case please let us know and we'll reconsider if more and more people ask for this!
