### ISSUE TITLE
How to target pseudo elements when using style={} prop?

### ISSUE THREAD

**Issue by dustwise** [styled-components/styled-components#1026]
Hello!

I am able to pass in my style object and it is working properly. That said, when I attempt to target a pseudo element it does not work. I cannot find examples or documentation to explain how to do this. I am currently using:

`{
color: 'black',
'&::after': {
  fontSize: '40px'
  }
}`

The color is applied but pseudo element is ignored. What am I doing wrong? Thanks!

**Comment by philpl** [comment]
styled-components is not built for you to use inline styles. We don't modify or transform them, we just pass them through

All standards, intros, concepts, and best practices can be found on our website: www.styled-components.com

**Comment by dustwise** [comment]
I am attempting to utilize the code implemented here:

https://github.com/styled-components/styled-components/pull/280/files

In these tests it explicitly shows passing in media queries and "&:hover" via the style prop object.

Additionally, in the CHANGELOG it states:

"v1.2.0

Added support for media queries, pseudo selectors and nesting in styles-as-objects."

I am passing in an object as shown and everything works except for pseudo and media queries, which is shown working in the tests. 

Has this functionality been removed?

**Comment by philpl** [comment]
So there's a slight difference here in what it is and how you're using it, I believe. You can clarify this with a code sample :)

Passing something into the style prop doesn't do anything special by default other than passing this on to the styled component's target.

However using a css object as an interpolation will correctly stringify it. You'll have to be careful when using the style prop with this though, since evaluating a prop in an interpolation doesn't stop it from being passed on.

I'll write a quick codesandbox to showcase what I mean

**Comment by dustwise** [comment]
Alright, I appreciate it!

Where can I find the codesandbox? 

Thanks for looking into this/helping alleviate my confusion!

**Comment by philpl** [comment]
https://codesandbox.io/s/0gvo36BML
