### ISSUE TITLE
Idea: static CSS generation based on propTypes

### ISSUE THREAD

**Issue by oreqizer** [styled-components/styled-components#1056]
# What

Add a _provider_ that flags all styled components to render all possible values from a finite set defined by prop type.

### Definition

Possible values would be taken from `propTypes` as so:

```js
const size = {
	small: 10,
	medium: 20,
	big: 30,
};

const Box = styled.div`
	width: ${props => size[props.size]}px;
	height: ${props => size[props.size]}px;
`

Box.propTypes = {
	size: PropTypes.oneOf(['small', 'medium', 'big']).isRequired,
}

export default Box;
```

A class for every possible size (`small`, `medium` and `big`) would be created.

### Extraction

A raw CSS text would then be extractable from the app with all possible classes. It could then be put into a file and loaded.

Instead of changing the CSS in HTML head on runtime, styled components would be flagged by the said provider not to do so, and only update classes on the component. Styles would be provided from the file.

### Limitations

The following would not work with this approach:

```js
const Box = styled.div`
	width: ${props => props.size}px;
	height: ${props => props.size}px;
`

Box.propTypes = {
	size: PropTypes.number.isRequired,
}

export default Box
```

Dynamic values would be left to be handled on runtime, as it is done currently.

# Why

* lighter runtime
* cacheable CSS file
* static analysis

**Comment by philpl** [comment]
I'm currently working on SC v3 and a core preprocessing library https://gist.github.com/philpl/e05ff063869c096a7a9795ca95769576. Static extraction has been a recurring question, that after long discussions and cobsiderations we discovered to not be possible for styled-components as is.

I have a gist here describing the biggest specificity problems that occur with styled-components and mixins that contain dynamic rules: https://gist.github.com/philpl/7b8a021f19ead2ec534091976a1ff6dc#file-2-specificity-md

We can say that static extraction is possible in some cases, but it's value is diminished, since achieving static caching and immediate runtime results  is not possible without SSR. Only including critical css is also hindered by static extraction and as SSR becomes a necessity for these cases, static extraction loses all its value.

The reasons why are documented here: https://github.com/styled-components/styled-components/issues/1018#issuecomment-316827497

Emotion sidesteps this problem partially (or at least did with their extract mode) by making mixins part of the composes property and thus "fixing" their specificity. A mode like this might become viable in our future core library.

The prop types idea is interesting but we repeatedly rejected any API based on them as they're not made to dictate behaviour. Also your case here is trivial but it doesn't work for all kinds of interpolations unfortunately. It just doesn't bring everything to the table for dynamic extracion. Note that your example doesn't actually say anything about static extraction, since it's mostly concerned about the dynamic rules.

cc @mxstbr: I might have to write a post or something about our future direction and reasonings behind preprocessing

**Comment by oreqizer** [comment]
👍  thx for explanation

**Comment by dfguo** [comment]
@philpl do you mind expanding on how Emotion sidestep the mixin issue listed at the bottom of this gist: https://gist.github.com/philpl/7b8a021f19ead2ec534091976a1ff6dc

I'm just starting to read more into this, so this might come off as a stupid question.

**Comment by philpl** [comment]
@dfguo it's not a stupid question at all actually :wink: With the `composes` operator, their mixins used to be "defined" as specificity-less. You can't write static properties that take a higher priority than it, because it's defined to be just a property holding some mixins that are going to be applied.

Now while Emotion doesn't apply this behaviour anymore, it can be really useful for us to be aware of this approach, and maybe bring it back if we ever need to.

cc @tkh44

**Comment by oyeanuj** [comment]
@philpl Did you ever get a chance to write this blog post?

> I might have to write a post or something about our future direction and reasonings behind preprocessing

I'd like to understand the differences between `emotion` and SC more, especially in terms of future directions.

**Comment by philpl** [comment]
@oyeanuj Like my reply on Twitter stated, the differences will shrink and the plan is that both will have the same platform. In essence, we will have stable preprocessing as well, and the gap will shrink. For you as a user not much will change apart from that.

I have to see whether I'll find time to write an article on it.
