### ISSUE TITLE
React Native - Wrapping a pure component and manipulating the passed styled object

### ISSUE THREAD

**Issue by yaronlevi** [styled-components/styled-components#1065]
I am asking this after a couple of days of digging in the issues and articles related to styled components.

When using React Native, I am wrapping and styling a pure stateless component and inside the pure component I want to manipulate the passed styled object like so:
```
const MyViewCustomized = styled(MyView)`  
  background-color: red;
`;

const MyView = ({ children, style }) => (
  //Somehow set a default: 
  //if(!style.background-color){
  // style.background-color=green  
  //}
  <View style={style}>
    {children}
  </View>
  );

```

So the behavior I want to achieve is a default value for background-color. If a background-color was not defined when styling, set it to default green.

But the style object being passed is an obscure array with key 0.

The bigger question is can I inspect or change or do anything else with the passed style object except for passing it as is to the view's style property?

**Comment by philpl** [comment]
You can achieve this with the `defaultProps`. Set the static property on either of the components, the factory's result, or the wrapped `MyView`.

The style object is a value, since that's how style sheets work in React Native. Once these are created they're just references.

We don't allow more obscure stuff like this, since it's not a good idea to introduce side effects like this, that directly manipulate data. You can alternatively pass an array to `style` and specify what needs to be overwritten. Or of course just define any logic you need in your styled component or above.

The general rule and trick for managing your atomic/primitive styled components effectively is to have them be just **presentational**. If you avoid having too many side effects on a low level, or and stop wrapping a component (PFC or else) with the styled factory, then you'll have less problems :wink: 

For a comparison of this, think about the web case. We don't allow you to manipulate the styling from above with side effects from below. That goes against applying the best practices of component-based styling. :smile:

Hope this helps! Btw you mentioned issues and articles. Most best practices and tips are scattered around the docs, while admittedly the content on React native is still a bit thin: https://www.styled-components.com/docs

**Comment by yaronlevi** [comment]
Ok I see what you mean... so basically, I should strive to use the styled-components's primitive in the lower levels, and in my example, the PFC should be above.

> You can alternatively pass an array to style and specify what needs to be overwritten

Can you please explain in detail or small piece of code (-:
