### ISSUE TITLE
Reverse component selectors, CSS mixins, and implicit state

### ISSUE THREAD

**Issue by cyberthom** [styled-components/styled-components#1072]
Hi,

We've got a use case that requires composing together CSS mixins. 

This is so that we can easily swap out the styling for the same components for different brands. (Think Walmart's use case who want to use the same components across all their ecommerce sites like Walmart, ASDA or Sam's Club)

The approach we've spiked is based on composing CSS mixins and using reverse component selectors:

#### Button Component

```JavaScript
const Button = styled.button`
  cursor: pointer;
`

const walmartButtonStyles = css`
  color: {(props) => props.disabled ? 'gray' : 'blue'};
`

const asdaButtonStyles = css`
  color: {(props) => props.primary ? 'green' : 'white'};
`
```

#### ShoppingBag Component

```JavaScript
import Button

const ShoppingBag = (props) => {
    /* Lifecycle hooks, Event handlers */
    return (
        /* Loads of other components */
        <Button>Proceed to purchase</Button>
    );
}

const walmartShoppingBagStyles = css`
  ${Button} {
    ${walmartButtonStyles}
  }
}

const asdaShoppingBagStyles = css`
  ${Button} {
    ${asdaButtonStyles}
  }
}
```

Composing CSS mixins using reverse component selectors works well, is flexible and does exactly what we need. However, we noticed that the props received by the CSS mixin doesn't match that of the component used. For example, the `walmartButtonStyles` CSS mixin does not receive the `disabled` or `primary` props from the `Button` component but instead gets whatever props `ShoppingBag` accepts. 

I assume this is because the CSS mixin is used within the template literal of the `ShoppingBag` styled component. However, that pretty much stops us from using the approach above. 

Are there any workarounds to receive the props of components in the reverse component selector. 

I am happy to send a feature request but wanted to check if this is deemed useful first. 

Alternatively, are we missing any other approaches to solve the issue of re-using complex components? 

#### Options we have dismissed

* Theming isn't flexible enough as it only allows overriding specific properties
* Creating a base component and then exporting different styled components for each brand is also not an option as it would stop us from being able to share complex (composed) components (works well for Atoms, but not for Molecules or Organisms in atomic design):

    ```JavaScript
    const Button = styled.button`/* Base styles */`
    const WalmartButton = styled(Button)`/* Walmart styles */`
    const AsdaButton = styled(Button)`/* ASDA styles */`
    ```

    Can't share Shopping Bag:

    ```JavaScript
    const WalmartShoppingBag = styled((props) => <WalmartButton>Proceed to purchase</WalmartButton>)`/* Walmart styles */`
    const AsdaShoppingBag = styled((props) => <AsdaButton>Proceed to purchase</AsdaButton>)`/* ASDA styles */`
    ```

* Creating higher order components for Organisms that allow overriding Atoms used within the rendering three would work technically but would make them really annoying to use:

    ```JavaScript
    const Button = styled.button`/* Base styles */`
    const WalmartButton = styled(Button)`/* Walmart styles */`
    const AsdaButton = styled(Button)`/* ASDA styles */`
    ```

    Each component within the rendering tree would have to support this kind of overriding and every single component used would have to be passed into the higher order component:

    ```JavaScript
    const createShoppingBag = (ButtonComponent) => (props) => <ButtonComponent>Proceed to purchase</ButtonComponent>
    const WalmartShoppingBag = styled(createShoppingBag(WalmartButton))`/* Walmart styles */`
    const AsdaShoppingBag = styled(createShoppingBag(AsdaButton))`/* ASDA styles */`
    ```

**Comment by philpl** [comment]
You can use the reverse of what you're doing I.e. define the parent for the reverse selector in the child. An example can be found here: https://www.styled-components.com/docs/faqs#can-i-refer-to-other-components

You can also give theming a try instead of dismissing it. It can be really powerful due to its flexibility. Have you tried reversing the theming relationship as described by James Kyle in this issue? https://github.com/styled-components/styled-components/issues/1055

I'm also not quite sure why you haven't given inheritance a try. It also sounds like a great option. I'm not sure whether you're aware of the new extend method. https://www.styled-components.com/docs/basics#extending-styles

**Comment by jracollins** [comment]
Hi @philpl 

Thanks for the quick reply.

Unfortunately we can't refer to the specific parent in the component as these components are designed to be atomic and consumed by multiple "composed components" and so the component will not know what the parent will always be. 

With regard to the theming, despite being powerful, we would still have to dictate the all css properties that are customizable in the component, rather than just writing a new property when we need it.  

I've made a codesandbox to demo the use case we're interested in and the issue we're having.

https://codesandbox.io/s/8qL5zyZKr

The root of the issue is that the props available to the referenced child component in the ```css`` ``` template literal are that of the "top-level" component and so you can't add/override any 'dynamic styles' of referenced child components. Is there any way to access them in this way? 

I'm pretty sure the extend method would also have the same issue?

**Comment by philpl** [comment]
Ok, I see.

> Unfortunately we can't refer to the specific parent in the component as these components are designed to be atomic and consumed by multiple "composed components" and so the component will not know what the parent will always be.

That's fair, yes. You could also just `extend` the component and use that. In fact it's a pretty common pattern to just pull in a component, extend it for the current component's context, and use that instead. So for example, you could create a `ShoppingBagButton`.

> With regard to the theming, despite being powerful, we would still have to dictate the all css properties that are customizable in the component, rather than just writing a new property when we need it.

This kind of brings me to the next problem. Yes, you can't use the parent's props to determine what the child will look like. That's just encapsulation. You can also consider to pass on `active`? I'm not sure about your specific case, so I assume that that's not possible / acceptable in most cases.

The problem is, I believe, that you're applying all your separate constraints to a single atomic, presentational component here. Even the ones that shouldn't concern the `Button` in your example. Instead of referring to the `Button` in the `ShoppingBag`, you should extend it and create a `ShoppingBagButton` to segregate the styling there.

Then there's the problem of the `active` prop. There's no way that the `Button` can implicitly receive a prop in a context that it doesn't know about. This state must come from somewhere I assume, so it's best to pass it on as a prop, or as some kind of less specific state. Depending on your situation.

What's left are the specific branding themes. What I've done in the past is, add the mixins (for example `walmartShoppingBagStyles`) to the theme, and just include it.
 You did say:

> Theming isn't flexible enough as it only allows overriding specific properties

But you can put anything in your themes: Values, rules, interpolations, or even entire mixins. Or just values that indicate what the Button should look like, which is what James Kyle is doing. I assume the latter doesn't work for you, as you'd like to keep the styling of different brands completely separate.

Lastly looking at your example, I can only hint at my earlier point again: "There's no way that the `Button` can implicitly receive a prop in a context that it doesn't know about".

This is a general theme with React. You have some UI state, and that's encapsulated to a component. You have to pass on the prop to distribute that state.

There's also the alternative of using a class, which I really don't want to advise you to do, but it is possible:

```js
// Or of course: `${Button} {}` inside the parent
const WalmartButton = Button.extend`
  .active > & {
    /* this ties the active state to a classname in the parent, not a prop */
  }
`;

// And in your `SubComponent` in the bin; inside the render return element:
<DefaultStyledDiv
  onClick={() => this.toggleState()}
  active={this.state.active}
  className={this.state.active ? 'active' : ''}
>
```

Since setting the `className` there is quite annoying you could also use `.attrs`:

```js
const DefaultStyledDiv = styled.div.attrs({
  className: ({ active }) => active ? 'active' : ''
})`
  /* ... */
`;
```

I think you should take a step back and consider all the options again, ignoring previous assumptions and methodologies that are based on CSS+React, and thinking in terms of state, css-in-js, and styled-components. Then bring back each constraint one by one and eliminate each option based on how the state flows through your app, and how you need to encapsulate styles.

If you do that I'm sure you won't have to use the proposed code above :wink: Alternatively, I'm around in London as well, and always up for a coffee ☕️

**Comment by geelen** [comment]
Yeah I would suggest doing something like the following:

```js
const Button = styled.button`
  cursor: pointer;
  ${ props => props.theme.buttonOverrides }
`

const walmartButtonStyles = css`
  color: {(props) => props.disabled ? 'gray' : 'blue'};
`

const asdaButtonStyles = css`
  color: {(props) => props.primary ? 'green' : 'white'};
`
```

```js
import Button, { walmartButtonStyles, asdaButtonStyles } from './Button'

const buttonOverrides = process.env.BUILD_ENV === 'Walmart' ? walmartButtonStyles : asdaButtonStyles

const ShoppingBag = (props) => {
    /* Lifecycle hooks, Event handlers */
    return (
       <ThemeProvider theme={{ buttonOverrides }}>
          /* Loads of other components */
          <Button>Proceed to purchase</Button>
      </ThemeProvider>
    );
}
```

**Comment by jracollins** [comment]
Thank you both @geelen and @philipl

It didn't occur to me that putting mixins in the theme quite like that would solve our issue (I think I tried but implemented it wrong!), but @geelen your reply put me on the right track - It's a great solution and solves exactly the issue of the 'props scope' where you couldn't access the components props when wanting to extend styles, and now everything works as we originally hoped.

When scoped to an "versioned" object key (exported from the component rather than defining it by the implied imported theme object name and `...composing` the theme object) this completely solves our additional requirement of supporting multiple versions of a component (components are NPM packages in our case) on the page. Eg when a composed component is referencing an older version of one that is on the page.

For anyone else who is interested, the final solution to our original problem is to export the css theme template literal per brand per component, both sharing/referencing the same version key defined in the component. This can then be combined in the main app theme, and everything is scoped correctly.

I've written a psuedo-example below to more clearly illustrate it (largely just building on @geelen's reply!)

```Javascript
// HelloComponent.js
export const versionKey = 'HelloComponent-v1';

function HelloComponent(props) {
    const { className } = props;
    return (
        <div className={className}>
            Hello World!
            /* Any child components */
        </div>
    );
}

export default styled(HelloComponent)`
    ${props => props.theme[versionKey]}
`;
```

```Javascript
// HelloComponentBrand1Styles.js
import { css } from 'styled-components';
import { versionKey } from './HelloComponent';
// Because this component will be an npm package, will be able to other import other component styles at specific versions
import childComponentStyles from 'npmPackage/styles';

const brandStyles = css`
    background: red;
    color: ${props => props.theme.colours.primary};
    border: ${props => props.border ? `5px solid black` : ''};
`;

// All child component styles are now exported with the parent, and so added to the global theme object
const exportedTheme = { [versionKey]: brandStyles, ...childComponentStyles };

export default exportedTheme;
```


```Javascript
// App.js
import HelloComponent from './HelloComponent';
import HelloComponentBrand1Styles from './HelloComponentBrand1Styles';

const additionalOverRide = css`
    background: blue
`;

const AppTheme = {
    colours: {
        primary: 'black',
        secondary: 'white'
    },

    ...HelloComponentBrand1Styles,
};

// We can even now also target and override the component styles directly if we know the versionKey (could also just import it)
Object.assign(AppTheme['HelloComponent-v1'], funnyOverRide);

const App = props =>
    <ThemeProvider theme={AppTheme}>
            <HelloComponent border />
    </ThemeProvider>;
            ```

**Comment by philpl** [comment]
Glad you found a pattern that works for you :)
