### ISSUE TITLE
Pseudo classes aren't receiving the props

### ISSUE THREAD

**Issue by fremfi** [styled-components/styled-components#1075]
`
const IconComponent = styled.i`
    &:before {
        text-decoration: inherit;
        font-weight: normal;
        font-style: normal;
        font-variant: normal;
        text-transform: none;
        speak: none;
        -webkit-font-smoothing: antialiased;
        -moz-osx-font-smoothing: grayscale;
        display: inline-block;
        vertical-align: top;
        text-align: center;
        font-size: 1.14286em;
        font-family: "AppDirectIcons";
        content: ${({ name }) => ICONS_UNICODES[name]};
    }
`;

`
Please help

**Comment by philpl** [comment]
Please submit all the necessary details for me to look into this. Otherwise I'd have to copy this into a CodeSandbox or sth similar myself. Please don't just skip and delete the issue template when opening an issue :wink:

https://raw.githubusercontent.com/styled-components/styled-components/master/.github/ISSUE_TEMPLATE.md

**Comment by fremfi** [comment]
@philpl thank you. I just read it, and will ask my question on the channel. I apologize for skipping it.

**Comment by philpl** [comment]
It's ok to ask a question here if you're frustrated and are searching for an answer. No worries

A reproduction is needed though. I'll reply on Gitter
