### ISSUE TITLE
Best way to comment inside an styled component?

### ISSUE THREAD

**Issue by hmontes** [styled-components/styled-components#1098]
If you comment with Next.js and styled components.

```
const Component.styled.div`
  width: 100%;
  /* ${} */
...
`

```

The line /* ${} */ produces an error. If you don't use the ${} inside the comments the code works well.

This issue is not present in Create-React-App (I think in JEST is present). 

So, What is the best way to comment inside a styled component? With ${/* */} ?

P.D: If you use ` inside of a comment throws an error too.

**Comment by k15a** [comment]
The best way is either use normal CSS comments or we also supper JS Like comments in the styled-components.

**Comment by philpl** [comment]
I’ll need more information to see whether we can improve this behaviour.

Generally the comments should be stripped, even with interpolations, but I don’t think we have tests for it, so I might be wrong and not up to date on this.

Backticks cannot work in general since they’re a JS feature and the comments are just part of the string. That means that the backtick takes precedence and ends the tagged template literal

**Comment by philpl** [comment]
> This issue is not present in Create-React-App (I think in JEST is present).

sounds like an issue with the babel plugin, but this issue didn't adhere to the issue template, so it's hard to pin down.

I'll close this for now due to inactivity

**Comment by funnyjokes** [comment]
Your site has a lot of useful information for myself. I visit regularly. Hope to have more quality items.
[funny jokes](http://tellfunnyjokes.com)

**Comment by aftab221** [comment]
qfqeeaf
