### ISSUE TITLE
css does not filter falsy values

### ISSUE THREAD

**Issue by wmertens** [styled-components/styled-components#1110]
I have a component (Box) that I use _a lot_ in my app, and as such I'd like it to be more optimized.

I replaced the css string with a css object so that I could calculate all values with one function call. 

```js
const Box = styled.div`
	${p => ({
		position: p.relative ? 'relative' : p.absolute ? 'absolute' : false,

		display: p.inline ? 'inline-flex' : 'flex',

		// Size
		width: !(p.fitChildren || p.inline) && `100%`,
        …etc
    })}
```

However, if I don't specify a position, the resulting css has `position: false`. Since the only valid falsy css value is `0`, it would be nice if https://github.com/styled-components/styled-components/blob/master/src/utils/flatten.js#L10 filtered out any falsy values that are not `0`.

Would you accept a PR that does this?

**Comment by philpl** [comment]
Hm, I mean we have the rules for it right below:

https://github.com/styled-components/styled-components/blob/master/src/utils/flatten.js#L20

So it is possible to fix. But I'm kind of stunned by the example. It is pretty contrived, since you could just default to an empty string.

I'm sure anyway that it'd be good practice to fix.

cc @mxstbr

**Comment by geelen** [comment]
Wait, returning `false` should result in an empty string, so you _should_ be getting `position: ;`. Are you saying you get `position: false;` instead? Because that may be an issue with `objToCss` as you mention.

To clarify, the string `false` should never be output, it should be replaced with an empty string. Any other behaviour is a bug.

**Comment by mxstbr** [comment]
That should be a filter, right? We should be doing a `Object.keys(obj).filter(key => key === 0 || Boolean(key))` before the map so we don't even output `position: ;` but skip that rule entirely?

**Comment by geelen** [comment]
Yeah..... I think so! There's... no way an empty value could ever be valid or meaningful, right? Not even if its a media query or nesting or something, if the value is falsey and not 0 you can delete the key. If someone could PR with a test case to cover that would be swell!

**Comment by reznord** [comment]
I'd be happy to take this if it's still free!

**Comment by philpl** [comment]
@reznord Awesome! Feel free to implement the change as suggested by @mxstbr. It should however probably align with the filter logic for false values that flatten is applying. You can probably extract a common function for it and reuse it to filter the object. For the tests, there should already be a test (on my phone& forgot where it is) that tests the object interpolations. (It might just be in the basic test file).

**Comment by wmertens** [comment]
@reznord I implemented it…

I was kind of expecting that it would also work for the ``css`foo: ${p => false}` `` case, but that can't work because s-c doesn't parse the CSS. That should be done by stylis.

**Comment by mxstbr** [comment]
Thanks @wmertens!
