### ISSUE TITLE
Is it possible to convert styled css to jss object format?

### ISSUE THREAD

**Issue by raymondsze** [styled-components/styled-components#1118]
I enjoy using the library styled-components to style my components, especially it supports the style lint checking.

I am now using the latest material-ui for the web development, and I would like to have a style lint checking for my components, but material-ui takes jss as their style soultion. stylelint seems not possible for jss right now.

What I think is there a easy way to have a function **convertToJss** like that?

```
import React from 'react';
import { withStyles } from 'material-ui/styles';
import Button from 'material-ui/Button';
import { css } from 'styled-components'

const buttonStyle = css`
  background: ${props => props.color};
`;

const styles = theme => ({
  black: convertToJss(buttonStyle, { color: theme.palette.common.black }),
});

const BlackButton = ({ classes, ...props }) => (
  <Button className={classes.black} { ...props } />
);

export default withStyles(styles)(BlackButton);
```

**Comment by philpl** [comment]
This is simply not possible right now. Maybe you can actually come up with something as a stylis middleware so that you don't increase your bundle size even more significantly.

In v3 we're working towards the foundation of a shared format that would allows interoperability like this. But right now we don't have anything specific.

To get a little bit more into what you're doing though: Since you've chosen styled-components, while your dependency, material-ui, has chosen jss, you've got the choice: Either stick with styled-components **completely**, or stick with jss. The latter also has a styled-components-like API btw.

But if you want to use styled you should wrap the third party components in our factory, i.e.:

```js
import Button from 'material-ui/Button';
styled(Button)`
  // ...your css...
`
```

There's a section in our docs for this: https://www.styled-components.com/docs/basics#styling-any-components

Otherwise I'm not sure what you're trying there, since this example seems stuck halfway.

Maybe we can also ask @kof

**Comment by kof** [comment]
I would actually love to have stylelint for JSS, but don't have enough time to do it myself.

**Comment by kof** [comment]
Looked into this issue https://github.com/paypal/glamorous/issues/28 looks like there is still no eslint integration for objects based syntax.

**Comment by kof** [comment]
Btw, have you seen this plugin? It allows you to use template literals in JSS http://cssinjs.org/jss-template, it doesn't have full support of what SC is doing, but probably its enough for you?

**Comment by mxstbr** [comment]
I'll close this out since it's not something we'll be actively working towards, hope the answers so far help!
