### ISSUE TITLE
[Feature Request] Both styled.div`...`.attrs({}) and styled.div.attrs({})`` should support

### ISSUE THREAD

**Issue by wood1986** [styled-components/styled-components#1124]
As for the high frequency styling issue in #134 , @mxstbr suggested 
```
const HighlyDynamicComponent = styled.div.attrs({
  style: props => ({
    background: props.bg,
  })
})`
  color: blue;
`
```

Is it possible to have the following pattern declaration?

```
const BaseComponent = styled.div`
  color: blue;
`

const HighlyDynamicComponent = BaseComponent.attrs({
  style: props => ({
    background: props.bg,
  })
})
```

I think the static properties should appear before any dynamic properties. Then we use it afterwards

**Comment by geelen** [comment]
Yeah... nah this isn't possible sorry. I actually tried to implement this but because of the way our constructor works, it's _much_ better if the template string is the last thing that can be called before a component is "complete".

You can do your second option with a sneaky `.extend` though:

```js
const BaseComponent = styled.div`
  color: blue;
`

const HighlyDynamicComponent = BaseComponent.extend.attrs({
  style: props => ({
    background: props.bg,
  })
})``
```

Note the empty template string at the end, too.
