### ISSUE TITLE
withTheme should not break if a default theme is provided

### ISSUE THREAD

**Issue by kutyel** [styled-components/styled-components#1130]
We are migrating a quite big React UI-kit to styled components 🎉 🎉 🎉  but found the following problem, every time we want to do some theming, the code for our components looks like this:

```js
import * as theme from '../Theme'; // this is our fallback theme

const Title = styled.span`
    font-weight: bold;
    color: ${props => props.theme.color || theme.color};
    font-size: {props => props.theme.fontSizeMedium || theme.fontSizeMedium}
`;
```

And the code gets even uglier when you have to adjust the styling to conditional prop values... you can imagine. 

Besides that, when using `withTheme` HOC in components and you don't wrap **everything** in a `ThemeProvider` the component itself breaks.

Is there a better/nicer way to provide a **default ThemeProvider** without having to do all that boilerplate code?

Thanks in advance and awesome work btw! ❤️

**Comment by philpl** [comment]
You can use the `defaultProps` to define fallbacks.

```js
const Title = styled.span`
    font-weight: bold;
    color: ${props => props.theme.color};
    font-size: {props => props.theme.fontSizeMedium}
`;

Title.defaultProps = {
  theme: defaultTheme
}
```

> Besides that, when using withTheme HOC in components and you don't wrap everything in a ThemeProvider the component itself breaks.

It shouldn't actually break but just output a `console.error`:

https://github.com/styled-components/styled-components/blob/master/src/hoc/withTheme.js#L37

**Comment by mxstbr** [comment]
I would recommend you export your own `ThemeProvider` that sets a default theme in case the users don't provide a custom one. Don't even need `.defaultProps` everywhere in that case, but of course if you prefer users are aware of you using `styled-components` using `defaultProps` will work perfectly too!

See this draft documentation we never finished: https://github.com/styled-components/styled-components-experimentation/blob/master/component-libraries/shared-component-libraries.md

**Comment by kutyel** [comment]
I was trying to accomplish that without having to provide an extra `ThemePromider`, anyway, is there a wat to provide such with already a theme obj inside? That way I dont have to export both the first `defaultTheme` and the `ThemeProvider`as well...

**Comment by mxstbr** [comment]
> is there a wat to provide such with already a theme obj inside? 

Sorry I don't quite understand the question?

**Comment by kutyel** [comment]
If I do what the mentioned doc purposes, I end up with something like this:

```jsx
import { ThemeProvider, theme, Button, Link, Title } from 'my-custom-library'

const Foo = ({ children }) => (
  <ThemeProvider theme={theme}>
    {children}
  </ThemeProvider>
)
```

That way I have to export **two things**, and my question is regarding if there is some way to embed that default theme in the ThemeProvider so that I you only have to import the first but not the second.

Thanks for your patience :)

**Comment by mxstbr** [comment]
No worries, just merge the passed-in theme with the default theme:

```diff
// component-lib/ThemeProvider.js
import { ThemeProvider } from 'styled-components';

const ComponentLibThemeProvider = (props) => {
  const theme = {
-    myComponentLib: props.theme,
+    myComponentLib: Object.assign({}, defaultTheme, props.theme),
    // Namespace the theme for the user
  };
  return (
    <ThemeProvider theme={theme}>
      {props.children}
    </ThemeProvider>
  );
}

export default ComponentLibThemeProvider;
```

That way your users can override specific parts of the theme, but for all the rest (or if none is provided, the whole thing) the default theme stays in place!

**Comment by kutyel** [comment]
```sh
Uncaught Error: [withTheme] Please use ThemeProvider to be able to use withTheme
    at WithTheme.componentWillMount (lucentum.js:11)
    at ReactCompositeComponent.js:347
    at measureLifeCyclePerf (ReactCompositeComponent.js:75)
    at ReactCompositeComponentWrapper.performInitialMount (ReactCompositeComponent.js:346)
    at ReactCompositeComponentWrapper.mountComponent (ReactCompositeComponent.js:257)
    at Object.mountComponent (ReactReconciler.js:45)
    at ReactDOMComponent.mountChildren (ReactMultiChild.js:236)
    at ReactDOMComponent._createInitialChildren (ReactDOMComponent.js:703)
    at ReactDOMComponent.mountComponent (ReactDOMComponent.js:522)
    at Object.mountComponent (ReactReconciler.js:45)
```
It breaks evetything without a `ThemeProvider` 😕

**Comment by mxstbr** [comment]
Yep, that's the whole point! Without a `ThemeProvider` your components will look like shit, so we throw an error so your users know what to do and aren't surprised by your horrible looking components :wink: 

I think if you provide a default theme to your `withTheme`d component it shouldn't throw anymore?

```JS
const Component = (props) => <div />

const Wrapped = withTheme(Component);

Wrapped.defaultProps = {
  theme: defaultTheme,
};

export default Wrapped
```

If that doesn't work I think we should change that behavior to render with the default theme.

**Comment by kutyel** [comment]
Yep, that's what I thought, and nope, it does **not** work :)

**Comment by mxstbr** [comment]
Reopening as a bug since that seems like valuable behavior to implement. /cc @iamstarkov @kentcdodds 

PRs very welcome, the line that would need to change is https://github.com/styled-components/styled-components/blob/af7975c146fb2b330585cb7c5e65b265f74d0fef/src/hoc/withTheme.js#L35 I think. Please also add tests for this behavior!

**Comment by kutyel** [comment]
Would like to give it a try, how can I know if a `defaultTheme` prop has been passed? :)

**Comment by philpl** [comment]
@kutyel @mxstbr

> I think if you provide a default theme to your withThemed component it shouldn't throw anymore?

To be referring to my last comment, there's no error being thrown inside `withTheme`: 

https://github.com/styled-components/styled-components/blob/master/src/hoc/withTheme.js#L35

But I agree that it's confusing that we are logging an error even if the prop is defined. This however also reminded me that the behaviour of `withTheme` is very counterintuitive in general as it doesn't match the `StyledComponents`s usage of the `theme` prop/defaultProp.

https://github.com/styled-components/styled-components/blob/master/src/models/StyledComponent.js#L100

These lines here should be adapted to be a generic, reusable function, since it's already used *twice* inside the component. We can reuse this error and log a **warning** if there's both no context, and no `theme` prop.

The resulting component from the `withTheme` HOC should match the logic exactly so that:

- On mount we need to determine whether there's a theme context and subscribe to it
- We need to make sure that the `theme` prop takes precedence over the provided theme (from context) and use it instead, if it was passed
- We need to make sure that the **default** `theme` prop **doesn't** take precedence over the provided theme (from context)
- If no theme context is passed we need to use the `theme` prop at all times
- If all three options are not present we need to log an error/warning (to be defined cc @mxstbr)

So overall this should be a sufficient overview of how to match the `withTheme` implementation to the `StyledComponent` implementation.

cc @mxstbr: Just making sure, I hope this makes more sense than just getting rid of the `console.error`?

**Comment by mxstbr** [comment]
Yeah that makes sense to me, unsure why those ended up being inconsistent but we should 100% align them.

**Comment by kutyel** [comment]
Ok, I want to give this a try but feel a bit lost about the codebase, could someone give me a short tour? 😄

**Comment by lukebelliveau** [comment]
@philpl I'd appreciate your feedback on [this](https://github.com/styled-components/styled-components/pull/1214). I haven't made any changes to withTheme, just the new function you suggested in StyledComponent.

If this is the direction you want, do you picture _one_ function for StyledComponent & withTheme to share? Where should it live, if so?

**Comment by lukebelliveau** [comment]
Note that I've laid the groundwork for this in [#1214](https://github.com/styled-components/styled-components/pull/1214). What's left to do here is to use the determineTheme function in withTheme and add tests!  Use should be similar to as it's used in StyledComponent and StyledNativeComponent.

**Comment by kutyel** [comment]
Ok, awesome, now I understand what needs to be done, can I give it a try and use the new function in the withTheme HOC? 😉  Should I provide some unit tests as well? 🤓

**Comment by philpl** [comment]
@kutyel sure! I’d love to review your PR

Exactly, the withTheme HOC will have to use the new function so that its theme logic matches a StyledComponent exactly. Unit tests will be welcome and will hopefully only require some copy & pasting.

The most important aspects are that components wrapped with the HOC use: the theme provided by context (which it does already) but also accepts the theme prop and the default prop (not fully covered)
