### ISSUE TITLE
CSS Sprite functionnality

### ISSUE THREAD

**Issue by psa-gbellencontre** [styled-components/styled-components#1144]
Hi
I'm using Styled Components for a few days, and I'm searching how to deal with CSS sprites.
I use webpack-spritesmith, but it generates Sass mixins, and I can't use them directly in styled components blocks.

Is there a solution to deal with sprites in styled components blocks ?

**Comment by mxstbr** [comment]
I'd recommend asking thsi question [on StackOverflow with the `styled-components` tag](https://stackoverflow.com/questions/tagged/styled-components)! This is an issue tracker :blush:

**Comment by philpl** [comment]
@psa-gbellencontre Seconding @mxstbr here, since this is really not styled-components related.

To give you a starting point for some ideas though, generally you'd want to use a webpack-plugin that can be used with JS. I'd take a look at this one here: https://github.com/tswaters/webpack-sprite-plugin

You can probably write a utility that uses the coordinates that this outputs
