### ISSUE TITLE
Advice when using innerRef with exported styled component...

### ISSUE THREAD

**Issue by joetidee** [styled-components/styled-components#1151]
Hi, I appreciate that there are some thread/ previous issues mentioning innerRef, but I could really do with some advice on how to get around this issue:

https://stackoverflow.com/questions/46085051/how-to-use-the-styled-component-property-innerref-with-a-react-stateless-compone

**Comment by k15a** [comment]
`innerRef` ist consumed by styled-components so you need to pass another prop (e.g. `_ref`) to the styled-component and then pass it further as ref to the Component.

**Comment by joetidee** [comment]
Would you mind providing a quick example?

**Comment by k15a** [comment]
So you have the following component hierarchy:
- Styled(Button)
- Button
- styled.div
- div

React itself handles the ref prop and attaches it to the Styled(Button).
- Styled(Button) <- ref
- Button
- styled.div
- div

Because React already handles the ref there is no way for styled-components to pass the ref down to the underlying component. That's the reason there is a special property called innerRef for styled-components so we can attach it to the underlying components.
- Styled(Button) <- ref
- Button <- innerRef
- styled.div
- div

So the only way to get the div is to use another prop and pass it down to the Button and the button should attach it then to the styled.div as the innerRef prop. We can use _ref for that.
- Styled(Button) <- ref
- Button <- innerRef
- styled.div <- _ref
- div

https://codesandbox.io/s/48pon8099x
```js
import React from 'react'
import { render } from 'react-dom'
import styled from 'styled-components'

const Component = styled.button``

const Button = ({ _ref, ...props }) =>
	<Component innerRef={_ref} {...props}>
		Click me
	</Component>

const StyledButton = styled(Button)``

class Foo extends React.Component {
	showRefs = () => {
		console.log('ref', this.ref)
		console.log('innerRef', this.innerRef)
		console.log('_ref', this._ref)
	}

	render() {
		return (
			<StyledButton
				ref={node => (this.ref = node)}
				innerRef={node => (this.innerRef = node)}
				_ref={node => (this._ref = node)}
				onClick={this.showRefs}
			/>
		)
	}
}

const App = () => <Foo />

render(<App />, document.getElementById('root'))
```

innerRef is null because it points to a stateless functional component which is always null because it doesn't have methods or properties to access.
