### ISSUE TITLE
[Native] flex:1 shorthand behaves differently than StyleSheet and triggers a FlatList quirk

### ISSUE THREAD

**Issue by Hunsu** [styled-components/styled-components#1158]
## Version
2.1.2

## Reproduction

https://github.com/Hunsu/styled-components-bug-with-flatlist

## Steps to reproduce
Run the app. You won't have the bug if you change line 18 of the component DogCard to `<View style={styles.cardContainer} >`
## Expected Behavior
All images are shown in the list.
## Actual Behavior
The first images are rendered and then disappear and only some are rendered.

**Comment by morajabi** [comment]
You need to add units to your CSS properties in styled-components styles. 
https://github.com/styled-components/styled-components-native-code-mod

**Comment by Hunsu** [comment]
I did that and it didn't fix the problem. I think it should have warned me though. If you could give some indications I could debug further this problem.

**Comment by philpl** [comment]
If you remove `flex: 1` it fixes the issue.

I'm pretty sure that means that the `flex` shorthand in `css-to-react-native` is not resetting correctly, or outputting slightly different values. https://github.com/styled-components/css-to-react-native/blob/master/src/transforms/flex.js

The good news is: You don't need to add it (same for `width`) to make your list work. It's completely unnecessary.

The bad news is: I might've seen this before, and getting the shorthands right has proven to be tricky.

cc @jacobp100

**Comment by jacobp100** [comment]
There's #465, which is similar. (Sorry it goes off topic!)

I'll add to this though,

React Native has two flex models: [non-standard `flex`](http://facebook.github.io/react-native/docs/layout-props.html#flex), and the web-standard `flex{Grow, Shrink, Basis}`. The main differences are that in the non-standard model, a positive `flex` implies a `flexShrink` of `0`, and a negative insteal implies a `flexGrow` of zero. In the web-standard model, the `flexShrink` has a default value of `1`.

Unfortunately, the non-standard `flex` property collides with the flex shorthand. We choose to use the shorthand instead, because we assume people would rather use the web-standard model.

Specific to your case, you switched from the non-standard flex model to the standard model, so your `flexShrink` went from `1` to `0`, which caused your content to collapse. But Phil is right, you don't need the flex property at all (and it's not needed in the linked issue either).
