### ISSUE TITLE
styled-components in React Native render error

### ISSUE THREAD

**Issue by qzm** [styled-components/styled-components#1159]
## Version
2.1.2

## Reproduction

```javascript
import React, { Component } from 'react';
import styled from 'styled-components/native'
const logoWrapper = styled.View`
  flex-grow: 1;
  justify-content: center;
  align-items: center;
`;
const logoImage = styled.Image`
  width: 100;
  height: 120;
`;
export default class Logo extends Component {
  constructor(props) {
    super(props);
  }
  render() {
    return (
      <logoWrapper>
        <logoImage source={this.props.source} />
      </logoWrapper>
    );
  }
}
```

## Steps to reproduce
I use the styled-components for React Native,
if i change the logoWrapper to View and change the logoImage to Image, it works

## Expected Behavior
no error

## Actual Behavior
Expected a component class got [object Object]

![screen shot 2017-09-11 at 10 05 20](https://user-images.githubusercontent.com/2801450/30255923-823149e0-96d9-11e7-8c71-d512d9a2d627.png)

**Comment by qzm** [comment]
is my fault ,sorry

**Comment by qzm** [comment]
I change component names with a capital letters

**Comment by philpl** [comment]
@qzm btw try the Stack Overflow or Spectrum before you open an issue first btw :smile:

In general the rule of thumb is: Is the title / problem very vague? Do you think it is not a library bug? Then it might be a question, not an issue. Of course you can open an issue as a last resort, but since you figured it out on your own, Spectrum might be a good choice for smaller questions :wink: Cheers!
