### ISSUE TITLE
withTheme forces always makes PureComponent update

### ISSUE THREAD

**Issue by MrLoh** [styled-components/styled-components#1162]
When I wrap a pure component with `withTheme` it always receives a new theme prop, no matter wether the theme has changed. 

## Version
2.1.1 native

## Reproduction
Let's say I have a component

````js
const MyComponent = () => {
    console.log('rendering')
    return <Text>test</Text>
}
export default compose(pure, withTheme)(MyComponent);
```

I'd expect it not to rerender, unless the theme changes, but it actually always changes

**Comment by philpl** [comment]
We only update `withTheme`s internal state when the theme changes:

https://github.com/styled-components/styled-components/blob/master/src/hoc/withTheme.js#L43-L45

But on its own the component is not a PureComponent, which is on purpose, since we don't make any assumptions about your practices.

This is why a reproduction is **very important**. Please take a look at the issue template.

There are two unknowns here that could both be causing the issue:

- Assuming that your `compose` function works right-to-left, you're not wrapping your component to be pure, which can be fine.
- `pure` could be checking reference equality of the props object which is always different, instead of checking shallow equality.

Due to how the component works, when `withTheme` rerenders, it'll cause a rerender of its child which you have to block there.

**Comment by MrLoh** [comment]
Sorry, I figured that the mistake was on my side. I was setting the theme wrong accidentally. Thanks for the pointer how `withTheme` works.

**Comment by philpl** [comment]
@MrLoh No worries! Glad you figured it out :smile:
