### ISSUE TITLE
TypeScript SSR: className not match

### ISSUE THREAD

**Issue by lhz516** [styled-components/styled-components#1168]
[babel-plugin-styled-components](https://www.styled-components.com/docs/tooling#babel-plugin) is the solution for matching client and server classNames. However, if I use Typescript, what can I do to solve this issue?

## Version
2.1.2

## Steps to reproduce
1. Set up a Typescript project with React + React Router. Share routes code for client & server
2. Achieve SSR with `styled-components` following [documentation](https://www.styled-components.com/docs/advanced#server-side-rendering)

## Expected Behavior
There's no warning from browser console said `className` not match

## Actual Behavior
Got console warning:
```
Warning: Prop `className` did not match. Server: "sc-kAzzGY ldrcMw" Client: "sc-bxivhb dleuTs"
```
(Because I'm using React 16 beta, the error message is slightly different from React 15)

**Comment by mxstbr** [comment]
Unfortunately, there is no way to get reliable class names without some sort of build step. Can you not use Babel plugins with TypeScript?

**Comment by zapkub** [comment]
@mxstbr I just found a problem today (with next.js), It cause by `babel-plugin-styled-components` cannot transform result from Typescript

```
// Typescript file, before compile
import styled from 'styled-components'
const Input = styled.input`
  width: 100px;
`
```
## Result
```
// result
const styled_components_1 = require("styled-components");
const Input = styled.default.input ` // <<< babel plugin doesnt see this one
  width: 100px;
`;
```

It look like transformer passing `styled.default.input` and the result is broken

# Workaround for this problem is
```
// typescript file
import styledComponent from 'styled-components'
const styled = styledComponent

const Input = styled.input`
  width: 100px;
`
```

so when Typescript compile this snippet it wiil result
```
const styled = styled_components_1.default;
const Input = styled.input ` // <<<<< babel plugin will see this and does it job
  width: 100px;
`;
```

**Comment by mxstbr** [comment]
Mind submitting an issue over at the babel plugin repo? Thanks!

**Comment by philpl** [comment]
I think it should be easy to check the method for `.default`. :+1:

**Comment by serranoarevalo** [comment]
Is this fixed? Still happening to me.

**Comment by zapkub** [comment]
@serranoarevalo can you provide simple repo to reproduce ?

**Comment by kitten** [comment]
@serranoarevalo @zapkub There's several approaches to integrating the babel-plugin with TypeScript and unfortunately none of them lie in our range (i.e. concerns)

What I'd recommend is the use of `@babel/preset-typescript`, since Babel now supports TypeScript transpilation.

See: https://github.com/styled-components/babel-plugin-styled-components/issues/41#issuecomment-410747606

Marking this as a duplicate of: https://github.com/styled-components/babel-plugin-styled-components/issues/41
