### ISSUE TITLE
Specifying class names

### ISSUE THREAD

**Issue by selbekk** [styled-components/styled-components#1180]
Hi!

I work with an organisation that uses React, Angular and regular CMS-based static websites throughout their organisation. They have a common component library (buttons, cards, tables, you name it) that we would love to implement once and use wherever.

Today's solution uses less files, with separate repos for react components. An example is `buttons` and `buttons-react`. 

We'd love to use `styled-components/primitives` to create universal components that can render to both the DOM and Sketch (probably React Native as well on a longer horizon).

In order for us to use `styled-components` (or `glamorous`, for that matter), we need to be able to create CSS files with predictable class names (i.e. `.button` and `.button--primary`) - but I can't really see how this is possible today.

Do you have any hints as to how this can be solved? Re-writing the styles twice (both as CSS / Less and as styled components) aren't a good solution, as it's way too easy to forget to update both sources of truth when you develop new features or fix bugs. I can't imagine my project is the only one which has this challenge.

**Comment by mxstbr** [comment]
Unfortunately, this is not possible given how component-based styling libraries work.

The whole point is that `styled-components` returns a _component_, not a class name, which works beautifully with React. That is the big improvement in development experience you see when using it, that's why it feels so nice.

If you want to get class names back from JavaScript I'd recommend looking at some CSS in JS libraries (e.g. `glamor`, `aphrodite`,...) since many of them are not component-based but return class names.

**Comment by selbekk** [comment]
Understandable :) Thanks for your input!

**Comment by mustefa** [comment]
Why not do both?

**Comment by probablyup** [comment]
@mustefa 

```
const Foo = styled.div``;

console.log(Foo.styledComponentId);
```

**Comment by DominicTobias** [comment]
It's kind of a shame, on the one hand I get it as styles can be unique per instance according to props, on the other it makes it harder for users of a component to modify the styles, other than through the interface the developer thought to expose which is limiting. Sometimes you just need to add or change style properties to suit your implementation, and without named classes there is no good way to delve in deep.
