### ISSUE TITLE
how to target sibling styled component on focus 

### ISSUE THREAD

**Issue by 4886Talga** [styled-components/styled-components#1186]
Just trying to change background-color of an input and a label at the same time on input: focus. but can't do it. Any help will be appreciated!

    const Wrapper = styled.div`
      width: 300px;
    `;

    const Label = styled.label`
      background-color: black;
    `;

    const Input = styled.input`
      background-color: grey;

     &:focus ~ ${Label} {
    background-color: white;
    }

    `;

    <Wrapper>
        <Label>Some text</Label>
        <Input />
     </Wrapper>

**Comment by mxstbr** [comment]
Just gotta put the input before the label and it works!

```JS
<Wrapper>
      <Input />
      <Label>Some text</Label>
     </Wrapper>
```

**Comment by ersel** [comment]
I think documentation is a bit lacking with regards to this.

It only shows a parent-child reference. It would be beneficial to add a sibling example and highlight the fact that you need a wrapper around them.

https://www.styled-components.com/docs/advanced#referring-to-other-components

**Comment by kitten** [comment]
@ersel that's because we'd like to highlight the child to parent relationship (reverse selector pattern). I'd be happy to accept a PR expanding this section with a further parent to child example as long as it highlights that this might introduce coupling that we'd like to avoid in styled-components as a paradigm.

Regarding this issue, it was not a reference to the patterns in general but a simple CSS issue, so maybe this should be an issue on styled-components-website :)

**Comment by lukashala** [comment]
I have a same issue as @aeciolevy 

`${StyledInput}:focus ~ & {...}` is not working.

But `input:focus ~ & {...}` is working fine. Strange.

**Comment by WilliamVelazquez** [comment]
> I have a same issue as @aeciolevy
> 
> `${StyledInput}:focus ~ & {...}` is not working.
> 
> But `input:focus ~ & {...}` is working fine. Strange.

I was having the same problem with the following code:

Not working:
&:active ${StyledSpan}{
    width: 60px;
}

Working:
&:active span{
    width: 60px;
}

Then I discovered that the problem is the order of the Styled Component Definition. I switch the position of my StyledSpan and It worked.

You should declare your inner Styled Component Before the Parent in order the styles to work. 😉
