### ISSUE TITLE
Streaming server-side rendering

### ISSUE THREAD

**Issue by mxstbr** [styled-components/styled-components#1192]
React 16 introduced streaming server-side rendering, which (I think) looks like this:

```JS
import ReactDOMServer from 'react-dom/server';

app.use('*', (req, res) => {
  res.write('<html><head></head><body><div id="root">');
  ReactDOMServer.renderToNodeStream(<App />).pipe(res);
  res.end('</div></body></html>');
})
```

It sends down the generated HTML as it comes along, kinda like as if you were _streaming_ a movie that comes along one piece after another. This allows the browser to already start rendering without having to wait for the full document.

This presents challenges for styled-components since we have to inject CSS as we go along, even before we know the full rendered HTML. By the time we have the CSS generated the document head has already been streamed to the client and we can't just inject stuff there anymore.

I have no idea how streams work, so I have no idea how our API would work or not work in a stream-based setup, but it'd be great to figure out!

Previous discussion: #386 
Previous art: @threepointone with [`glamor-stream`](https://github.com/threepointone/glamor-stream)

**Comment by billykwok** [comment]
Perhaps the design of [styled-jsx](https://github.com/zeit/styled-jsx) can give some insights. Instead of rendering a single huge `<style>` tag in `<head>`, we could render smaller `<style>` tags along with the rendering of DOM.

For each React component, styled-components may potentially render its styles as a `<style>` tag immediately following the component tag. The entire DOM structure would be like:
```html
<body>
  <div id="react-root">
    <div>Group 1</div>
    <style>Group 1's styles</style>
    <div>Group 2</div>
    <style>Group 2's styles</style>
    <div>Group 2</div>
    <style>Group 2's styles</style>
    ...
  </div>
</body>
```

This structure is streamable in nature because styles are generated for each small section of codes and can be piped into a stream without waiting for the rendering result of the entire DOM tree. To avoid duplication when using shared style, the server-side rendering function just has to do a simple check and skip those styles that have been rendered for previous elements.

**Comment by philpl** [comment]
Due to the fact that we can render style tags alongside elements in react 16 it’s definitely possible, but I’m wondering if we can find an elegant fallback for React <16 without a major refactor of our Stylesheet logic

**Comment by mxstbr** [comment]
> I’m wondering if we can find an elegant fallback for React <16 without a major refactor of our Stylesheet logic

I guess we'd just have a `StreamingStyleSheet` that returns a stream or something? I'm unsure what the API there has to look like.

**Comment by philpl** [comment]
@mxstbr afaik the only way is to put style tags into the React tree every time you’d like to add a fragment. So in that case we probably wouldn’t even use a Stylesheet api but just Output marked style tags. Then before rehydration we’ll need to move all styles back into one Stylesheet in the head, if we only want to make minimal changes. This obviously won’t work for React <16 as you can’t return arrays of elements there

**Comment by wmertens** [comment]
I think it's fine to ignore React <16 here…

Also, I'm not sure every browser will be cool with `<style>` tags as children of tags that normally take only specific tags, like `<table>`, `<tr>`, `<dd>`?

**Comment by elrumordelaluz** [comment]
> Also, I'm not sure every browser will be cool with <style> tags as children of tags that normally take only specific tags, like `<table>`, `<tr>`, `<dd>`?

Today only [_Chrome_ (with flags) and Firefox](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/style#Browser_compatibility) supports `<style scoped>` tag

**Comment by faceyspacey** [comment]
I wonder if there will be glitches during client-side rendering as elements would appear before their styles, even if just for a moment. That could get funny, especially since it's happening repeatedly, for every component in the tree.

**Comment by schwers** [comment]
@philpl Just a thought, but I think this might be more feasible with `v3`. Basically my idea would be to precompile styles ahead of time with the `v3` functionality, and generate as many static classes as possible to avoid collecting styles on the server render. We could use `style` attributes on the server render for anything dynamic to avoid creating extra `style` tags inline.  Then once the component has mounted client side it can go back to using generated classnames?

**Comment by faceyspacey** [comment]
@schwers I'm new to the implementation details of the css-in-js libs, so pardon if this is a naive question, but why even bother making classes for dynamic styles, rather than just leave them inline using `style` attributes in the first place?

**Comment by mxstbr** [comment]
Because you can't put things like `:hover` into `style` attributes, which can also be dynamic!

**Comment by elrumordelaluz** [comment]
Also pseudo elements like `:before` or`:after` or `@media` queries and other  _specificity_.

**Comment by schwers** [comment]
d'oh. yeah that would prevent my strategy from working 😅

**Comment by faceyspacey** [comment]
Well, not if you required pseudo selectors *not* to be dynamic. It's less than ideal, but it's also likely a very small percentage of the use-cases going on here. My guess is pseudo selectors are more likely to be static than regular selectors in the first place. It's a use-case that likely makes up .1% to 3% of use-cases. 

So in short, if `renderToNodeStream` SSR was to be taken seriously *(and if streaming styles after component html turns out glitchy)*, this may be the best possible option. 

It seems, before pondering any further, an experiment must be done to see if the styles-after streaming approach works. 

We can put that together statically without having to build a thing: 

- just renderToNodeStream some html
- followed by its styles
- and simulate doing it over a very slow connection.

**Comment by philpl** [comment]
It’s not only the pseudo selectors that are a problem, but any kind of selector.

So while we could offload the pseudo selectors to the end of the stream, that doesn’t apply to all the other selectors that the style attribute doesn’t accept.

I don’t expect this to be:

- easy and a no-brainer to implement that would require major refactors and switched logic for React <16
- doable by finding any other workaround apart from style elements rendered together with their elements
- something that we *definitely* even want to implement

Scopes style tags however are not necessary, due to our generated tags.

Also, we can’t ignore <16, at least the SSR will need to have both ways to work, and the rehydration will then need to be different.

@schwers I do expect this to be easier to do with the v3 plans anyway, as this might need some more CSS transformations potentially.

One thing that would most definitely suck, but would work is streaming script tags if I’m not mistaken? So as we would stream elements they could carry script tags with them that inject the components own styles into a Stylesheet. I’m just going to put this idea here, but it’s not easier than style tags and would need a styled-components js bundle in the head.

Anyway, @mxstbr, how badly do we want this? This might be a novelty feature in the range of static extraction, that is not going to yield tremendously great results for the effort it takes. Especially since SSR can also be cached.

Oh, another idea (that probably won’t work with HTTP 2) I was wondering if a second CSS stream can be served as a url with a unique ID that serves the streamed CSS as a separate file?

**Comment by probablyup** [comment]
Something like this has been brought up as a possible solution by Sasha Aickin: https://www.facebook.com/notes/facebook-engineering/bigpipe-pipelining-web-pages-for-high-performance/389414033919/

Basically creating placeholders and dynamically injecting script tag fragments as css blocks are finalized that go back and replace the placeholders.

**Comment by wmertens** [comment]
So then you need JS support, nullifying a great benefit of SSR…

**Comment by evan-scott-zocdoc** [comment]
There's always a tradeoff :) just sharing one of the solutions proposed by the guy who wrote most of the React streaming impl.

**Comment by wmertens** [comment]
Hmm, now that React has fragments it's feasible to pass along styles
together with the component that uses them; and since you know which
component you're passing (most of the time), you could "hold" styles for
components that can't have <style> as a sibling.

In fact, you can now pass styles either as siblings or additional children,
so perhaps streaming styles can be done like this:


   - Keep track of classes that were already generated/output
   - When you need new classes, put them in a to-output queue
   - When rendering a styled component:
      - For <table>, <dl>, <ol>, <ul>: add a <style> tag with the queued
      classes as a first sibling and return a fragment
      - For <tr>, <tbody>, and all other "intermediate" tags that can't
      have styles as children or siblings: hold the queue
      - For all the rest: pass <><style/>{children}</> as children to the
      component
   - Then, when hydrating on the client, just do the regular thing and
   hopefully the more robust React v16 hydration won't mind that the inline
   style tags disappear.

(Yes, <>...</> is now the official syntax for fragments :) )

(Now I wonder how streaming could work with @graphql - it would be cool if
the stream could be paused until a promise resolves)

**Comment by probablyup** [comment]
Added in 3.1.0!

**Comment by williamli** [comment]
Is it possible to process the styles separately, keeping it out of the streaming content only to deliver them after the rest of the components are streamed?
