### ISSUE TITLE
Bug: error when mapping a styled component without wrapping it in function

### ISSUE THREAD

**Issue by godspeedelbow** [styled-components/styled-components#1196]
## Version
- styled-components: 2.2.0
- react: 16.0
- react-script: 1.0.14
- react-app-rewire-styled-components: 3.0.0

`./config-overrides`:
```js
const rewireStyledComponents = require('react-app-rewire-styled-components');

module.exports = function override(config, env) {
  config = rewireStyledComponents(config, env);
  return config;
}
```
## Reproduction

```js
const items = [0]; //  non-empty array

const Item = () => <div />;
const StyledItem = styled(Item)``;

// works
const List = () => items.map(Item);

// fails
const List = () => items.map(StyledItem);

// works
const List = () => items.map(() => <StyledItem />);

```

## Steps to reproduce

Run the code above, comment out the Lists one by one, see that one fails and the others don't.

## Expected Behavior

They all work.

## Actual Behavior
Using 
```js
const List = ({ items = [] }) => items.map(StyledItem);
```

gives this error:

```
TypeError: Cannot call a class as a function
classCallCheck
node_modules/styled-components/dist/styled-components.es.js:177
  174 | 
  175 | var classCallCheck = function (instance, Constructor) {
  176 |   if (!(instance instanceof Constructor)) {
> 177 |     throw new TypeError("Cannot call a class as a function");
  178 |   }
  179 | };
  180 | 
```

**Comment by mxstbr** [comment]
That is not a bug, that's expected behavior because that's the way React works.

`StyledItem` is a class component (`class StyledComponent extends React.Component`), whereas `Item` is a function component. (`() => <div />`)

When you're running `Array.map(x)`, what you're essentially doing is passing `.map()` a function. The shorthand form looks like this: `.map(() => {})`. (note how to argument is a function) Now when you're passing `StyledItem` to `Array.map`, you're passing a _class_, but `.map` tries to call it as a function.

That's exactly what the error message says: "Cannot call a class as a function". You can reproduce this yourself by manually calling `StyledItem()`, which will throw the exact same error, or even further, manually creating a `class Comp extends React.Component` and trying to call it as a function.

I hope that explains why the way you're doing things doesn't work.

**Comment by godspeedelbow** [comment]
Ah yes, makes total sense. I am so used to not using `class` components anymore that I forget they're not functions ;) Thanks @mxstbr for taking the time!
