### ISSUE TITLE
"Hiding" propTypes due to StyledComponent causing conflicts with other libs

### ISSUE THREAD

**Issue by jony89** [styled-components/styled-components#1199]
Due to creating new `StyledComponent`, the actual `propTypes` of the `WrappedComponent` are "hidden" and this causing conflicts with other libs, such as : 

1. `react doc-gen` needed private solution in order to work ( #945 )
2. incompatibility with `react-styleguidist` ( #945, #637 )
3. few addons from `storybook` (e.g `info` addon) cannot work as they expect propTypes and have none on the `StyledComponent`
4. `react2angular` which should automatically resolve angular attribute into react props is not working due to exposing the StyledComponent without the actual propTypes.

And I'm pretty sure there will be more of those.

I can create PL for this, but first I want to have some discussion, I was wondering maybe just to copy the `propTypes` of the `WrappedComponent` into the `StyledComponent`.

This will solve all of the above issues.

Currently I've tried it without manipulating `styled-components`, like so : (and it works)

```js
const withPropTypes = (StyledComponent: React.ReactNode, WrappedComponent: React.ReactNode) => {
  const StyleComponentWithPropTypes = StyledComponent;
  StyleComponentWithPropTypes.propTypes = Object.assign(
    {}, WrappedComponent.propTypes, StyledComponent.propTypes,
  );
  return StyleComponentWithPropTypes;
};

export default withPropTypes(styled(MyComponent)`
  cursor: pointer;
  svg {
    margin: 0 5px -3px 0;
    height: 18px;
  }
`, MyComponent);
```

**Comment by jony89** [comment]
no answer?

**Comment by mxstbr** [comment]
Can you submit a PR with some tests that demonstrate the usefulness of this? I'm not quite sure I understand why this is necessary.

**Comment by jony89** [comment]
@mxstbr, I can. but first I want you to understand the issue if it's not clear.

I gave few examples. The `react-styleguidist` issue ( #945, #637 ) was discussed few times. so let's talk about issue number 4 .

`react2angular` library ( https://github.com/coatue-oss/react2angular ) is using the `propTypes` defined on the exposed component in order to bind angular attributes to react props. Though, since I use `styled-components`, then the actual exported component, the `StyledComponent`, does not have the `propTypes` of the original component (`MyComponent`) since `MyComponent`, is wrapped by the new component created by `styled-components` lib. Thus, `react2angular` fails to pass the props.

If I created `MyComponent` with `onMyClick` prop, and I define that : 

```js
MyComponent.propTypes = { onMyClick: React.PropTypes.func }
```

And I actually export : 

```js
export default styled(MyComponent)`
  color: blue;
`
```

Then the actual exposed component does not have the same propTypes which causing `react2angular` to fail.

Is this more clear now ?

**Comment by mxstbr** [comment]
I understand that, but the `react-styleguidist` issue won't be solved by passing the `propTypes` on. The libary they use to extract information, `react-docgen`, runs at build time, not at runtime. They use static analysis. So the only way to solve that is to add styled-components compatibility to `react-docgen`, for which there is an open PR iirc.

A very simple way to solve your issue with `react2angular` is to use styled-components as it is recommended to be used:

```JS
const MyComponentWrapper = styled.div`
  color: blue;
`

class MyComponent extends Component {
  render() {
    return (
      <MyComponentWrapper>
        {/* ...more code here ... */}
      </MyComponentWrapper>
    )
  }
}

MyComponent.propTypes = {
  onMyClick: PropTypes.func,
};
```

This is the way styled-components is intended to be used, and if I understand your description correctly it'll perfectly resolve your issues!

**Comment by jony89** [comment]
Yeah that solve the issue, yet it will require from me to create a div and a new `MyComponentWrapper` for every component That has a style. This is the way to go with `styled-components`?

**Comment by philpl** [comment]
@jony89 the styleguidist problem is ultimately going to be solved, so all we're talking about is, like @mxstbr said, hinging on that. Compatibility is being actively worked on and `react-docgen` already merged a necessary PR for this.

Apart from this, hoisting statics is not free, so it would interfere with our ongoing efforts of actually making our runtime a lot faster.

So while this might be desirable from a styleguidist point of view, as long as this issue is unsolved, it doesn't even make much sense for us. The "HOC" pattern of styled-components is actively discouraged, since it makes more sense to use styled-components at the lowest level, meaning as presentational leaf components.

Since @mxstbr has given you the appropriate workaround, we could close this in favour of https://github.com/styled-components/styled-components/issues/945, and the corresponding issue on the styleguidist and react-docgen.

If this is about `react2angular` thought then the answer lies in the same pattern:

> is using the propTypes defined on the exposed component in order to bind angular attributes to react props

It's not a build-time requirement so all you need to do is set your `propTypes` on the exposed component, so on the styled component, although it's more likely that you'll wrap your presentational StyledComponents in structural wrappers, like in Max's example above

 > yet it will require from me to create a div and a new MyComponentWrapper for every component That has a style

This depends. Can you use the styled component directly and set proptypes on it? Can you just use your `withPropTypes` helper?

The way to go is to start to abstract your styled components into structural components upwards as you add more logic. But if you need to use it directly, then whatever needs to be done to make this happen with `react2angular` applies to styled components just as much as to every other component.

Also, isn't the goal of the library to migrate to React in the long term? So as you're abstracting bigger components, you won't have to deal with this on the styled component level anymore, right?

I hope this answers more of your questions :smile:

**Comment by mxstbr** [comment]
Yep, that is the way styled-components is intended to be used. For an example of an app built with styled components see https://github.com/mxstbr/postcss.parts!

**Comment by jony89** [comment]
I got my answers, thanks !
