### ISSUE TITLE
How do you deal with dynamically inputs?

### ISSUE THREAD

**Issue by nikgraf** [styled-components/styled-components#12]
First of all: amazing work!

I have seen this example by @mxstbr 

```js
const Title = styled.h1`
  font-size: 3em;
  color: ${constants.brandColor};
  margin-bottom: 0.25em;
`;
```

From what I understand this would generate CSS, but what would happen in this case:

```js
const MyComponent extends React.Component {

  state = { left: 0 };

  render() {
    const FlyingBall = styled.div`
      position: absolute;
      width: 1rem;
      height: 1rem;
      left: ${this.state.left}
    `;

    return <FlyingBall />;
}
```

I would expect this generates only the CSS with `left: 0;`. Is this correct?

**Comment by mxstbr** [comment]
> I would expect this generates only the CSS with left: 0;. Is this correct?

Yes, and you can also dynamically change it and it will actually change accordingly! 😱

No idea how this works, but it does, after one second left will be set to `50px`:

```JS
const MyComponent extends React.Component {

  state = { left: 0 };

  render() {
    const FlyingBall = styled.div`
      position: absolute;
      width: 1rem;
      height: 1rem;
      left: ${this.state.left}
    `;

    setTimeout(() => {
      this.setState({
        left: 50
      });
    }, 1000);

    return <FlyingBall />;
}
```

**Comment by nikgraf** [comment]
ok, this is cool. No I'm curious if you used a development or production mode … or to rephrase: If I want to provide cacheable CSS file for production how does it work? Do you identify dynamic styles and set them via the style attribute or inject a style tag?

**Comment by mxstbr** [comment]
> inject a style tag?

This, I'm 99% sure. We use aphrodite under the hood, so there's no external CSS file at the moment. Not sure if we want to go down that route…

**Comment by geelen** [comment]
Since #29 (and `0.2.0`), we have simplified this. If you write:

```js
let something;

const X = styled.div`
  ${ something }
`
```

Then the value of `something` will be locked to its initial value. There's no way around it, unless you call `styled.div` _inside a render method_ like @mxstbr does above (you're effectively making a new component each time with whatever the current value of `something` is)

If you want something dynamic, though, just interpolate a function!

```js
let something;

const X = styled.div`
  ${ () => something }
`
```

Now every time `X` is re-rendered that function will be reevaluated and the current value of `something` will be injected. Easy!

**Comment by nikgraf** [comment]
Thanks @geelen for the clarification!
