### ISSUE TITLE
Delays in rendering on iOS Safari / Chrome when styles refer to heavy SVGs

### ISSUE THREAD

**Issue by kachkaev** [styled-components/styled-components#1207]
This issue follows a discussion in https://github.com/styled-components/styled-components/issues/583, in particular a [comment](https://github.com/styled-components/styled-components/issues/583#issuecomment-334190709) by @philpl.

While developing on top of [creacte-react-app](https://github.com/facebookincubator/create-react-app) with styled-components, I noticed that the togglable buttons in my interface took about a second to render on iOS, which made the mobile UX pretty poor. Animation frames were missed only when unique set of props was rendered for the first time, i.e. when the styled-components library added a new CSS rule to the document.

The issue only shows up in iOS versions of Safari and Chrome (iPhone 6s, iOS 10/11). Here's how a stuck frame looks like:

![](https://user-images.githubusercontent.com/608862/30049987-8f9ab93c-9214-11e7-9425-72663e547d49.png)
(the longest event is `styles recalculated` that follows `styles invalidated`)

An attempt to produce an MWE demonstrated that the performance issue only takes place if the styles refer to a rather detailed SVG background (100KB or more). Interestingly, it does not matter if an SVG is a part of a switch that's being toggled or not – the duration of a delay is quite the same for any new state in any styled-component. Here's what's probably happens:

1.  iOS Safari or Chrome rasterizes all SVGs when the initial react tree is rendered.
2.  When a new combination of props is passed to a styled-component, the library appends a few new rules to `<style>`.
3.  The browser considers all the previously declared styles as invalid, reads them from scratch and re-rasterizes the SVGs again. The latter step appears to be quite laborious for mobile browsers (not the desktop ones).

I doubt that this can be considered as the bug of styled-components and I'm also not sure if it can be fixed within the library. 

*  One option would be to somehow list all the expected combinations of the props during the app load so that a complete list of CSS rules is dumped in the very beginning. This feels like a bad idea stragith away.
*  If all the generated CSS selectors currently append to a single `<style>` element, perhaps it could be worth trying to create a new `<style>` elements each time to give mobile browsers a chance to reuse the previously parsed SVGs. But I'm not sure if can work at all.

Thoughts are welcome!

## Version
2.2.1

## MWE

https://github.com/kachkaev/styled-components-with-heavy-svgs-mwe

**Comment by philpl** [comment]
> If all the generated CSS selectors currently append to a single <style> element, perhaps it could be worth trying to create a new <style> elements each time to give mobile browsers a chance to reuse the previously parsed SVGs. But I'm not sure if can work at all.

We have previously implemented batching, but it wasn't as efficient as we've hoped. We are going to implement "speedy mode" (Stylesheet API `insertRule`) next. My suspicion is that this helps iOS Safari to detect that nothing else changes.

The actual slow down is in compositing, so yeah, indeed nothing we can do about.

There's going to be bad performance not only on iOS, but on all devices I suspect, due to some factors:

- Network (Loading such a big SVG file is going to be slow)
- A huge SVG is tedious to render for the browser (It's rendered in a tiny view, so remove some detail)
- It needs to be rasterised every time something changes (Even if just one rasterises that's a problem; Using a PNG or something would be a solution here)

Due to this just being a really hypothetical browser stress test, there is one solution to force every browser to rasterise it and to keep the rasterised version around for as long as possible: `transform: translate3d(0, 0, 0);`. I haven't tested this one on iOS, but it should help

**Comment by mxstbr** [comment]
Going to close this out since it's unfortunately nothing we can help you with :confused: Hoping @philpl's workaround works!

**Comment by kachkaev** [comment]
Makes sense @mxstbr!

@philpl adding `translate(0,0,0)` worked for the MWE, but not for the project I saw the bug in initially. Will try a few other tricks and will let know if anything else except changing the SVGs works.

Hope the existence of this issue and the MWE helps someone to investigate their performance issues and not blame `styled-components` :smile:
