### ISSUE TITLE
Change warning message when creating too many classes

### ISSUE THREAD

**Issue by jjant** [styled-components/styled-components#1212]
The current warning message in this case reads:

```
Over 200 classes were generated for component Component. Consider using style property for frequently changed styles.
Example:
  const Component = styled.div`width: 100%;`
  <Component style={{ background: background }} />
```

The warning should instead recommend using the new `attrs` way, something like this:
```
Over 200 classes were generated for component Component. Consider using the attrs property, together with a style object for frequently changed styles.
Example:
  const Component = styled.div.attrs({
    style: ({ background }) => {
      background,
    },
  })`width: 100%;`

  <Component/>
```

**Comment by mxstbr** [comment]
Great idea!

**Comment by lukebelliveau** [comment]
[This should do it!](https://github.com/styled-components/styled-components/pull/1213)

**Comment by pavloo** [comment]
Guys, I have the next test case in `src/test/attrs.test.js`:

```javascript
it('should update style attribute on property change', () => {
    const background = 'red';
    const Comp = styled.div.attrs({
      style: ({ background }) => ({
        background
      }),
    })``
    class Container extends Component {
      constructor() {
        super()
        this.state = {
          background
        }
      }
      render() {
        return <Comp background={this.state.background} />
      }
    }

    const newBackground = 'blue';
    const rendered = mount(<Container />);
    expect(rendered.html()).toEqual(`<div class="sc-a b" style="background: ${background};"></div>`)
    rendered.setState({
      background: newBackground
    })
    expect(rendered.html()).toEqual(`<div class="sc-a b" style="background: ${newBackground};"></div>`) // this one is failing
  })
```

It's failing because property update and re-render doesn't cause style attribute to be recalculated (as well as other attributes). But according to the recommendation in this issue the test should pass. So I wrote a test case to isolate this issue but I noticed it working on my app.

I'm using styled-components version *2.2.1*.

Thanks

**Comment by pavloo** [comment]
Guys, I added the next test case in `src/test/attrs.test.js`:

```javascript
it('should update style attribute on property change', () => {
    const background = 'red';
    const Comp = styled.div.attrs({
      style: ({ background }) => ({
        background
      }),
    })``
    class Container extends Component {
      constructor() {
        super()
        this.state = {
          background
        }
      }
      render() {
        return <Comp background={this.state.background} />
      }
    }

    const newBackground = 'blue';
    const rendered = mount(<Container />);
    expect(rendered.html()).toEqual(`<div class="sc-a b" style="background: ${background};"></div>`)
    rendered.setState({
      background: newBackground
    })
    rendered.update();
    expect(rendered.html()).toEqual(`<div class="sc-a b" style="background: ${newBackground};"></div>`) // this one still have `red` as background
  })
```
It's failing because property update and re-render doesn't cause style attribute to be recalculated (as well as other attributes). But according to the recommendation in this issue the test should pass. So I wrote a test case to isolate this issue but I noticed it working on my app.

I'm using styled-components version **2.2.1**.

Thanks

PS. I noticed that if I use `shallow` instead of `mount` the test passes.

**Comment by philpl** [comment]
@pavloo switching around between the same prop inputs in a small set (in this case 2) won't trigger a warning, since we're reusing existing classes that have already been injected.

In this case since you only have two background values, it will keep hitting the same two classes.

**Comment by pavloo** [comment]
@philpl this PR fixes my test case and the issue https://github.com/styled-components/styled-components/pull/1219

**Comment by philpl** [comment]
The PR was merged so we can close this issue now :)

**Comment by nicolasletoublon** [comment]
Just a question about it guys, what is the benefit of using attrs with style inline, over just using the `background: ${props => props.background}` ? 
Is there any perf optimization, or anything to get from this ?

**Comment by oomathias** [comment]
@nicolasletoublon for each background values, it's gonna generate a new class. Let's say it can be `black` or `white`, I guess it's OK to generate two classes for the component. If it's a Color picker, it will potentially generate thousands of classes while the user is choosing a color, if that's the case it's better to have one class and `style='background: mycolor;'` inline. Highly dynamic styles should be inlined which can be done with attrs.

**Comment by curran** [comment]
Is it possible to set this to throw an Error instead of logging a warning? I'm having trouble locating exactly which styled component is causing this, of nearly a hundred in my codebase. Throwing an Error would help localize the problem via its stack trace. Has anyone else faced the same issue trying to debug this?

The warning states `Over 200 classes were generated for component styled.div.`, which doesn't provide any localization.
