### ISSUE TITLE
When server render support outputting without style tags

### ISSUE THREAD

**Issue by kevinsimper** [styled-components/styled-components#1231]
When using server render it could support outputting the CSS without <style> tags that would allow you to save it into a .css file. 

This can be useful for caching and running postcss plugins like the flexbugs one. 

I looked and it looks pretty simple to change :)

**Comment by clempat** [comment]
Actually I am looking for something quite similar but for an other reason which I still try to figure out if it is the best solution. I am doing Accelerated Mobile Page version of some pages and looking into the possibility to keep the same technology including styled-components. 

For this reason getting the styles without style tag will allow me to inject it into the special <style amp-custom> tags required for amp pages.

**Comment by kevinsimper** [comment]
@clempat For that you could also use the raw output and then wrap it yourself inside a `<style amp-custom>` 😄

**Comment by clempat** [comment]
🤔 I am missing where the raw output is available? under ServerStyleSheet? for now I will deal with some webpack loader to group the style and put it in the header with the right tag.

**Comment by philpl** [comment]
You can use `concatenateCSS `, but it will miss the information required to rehydrate, which you'd then have to create yourself: https://github.com/styled-components/styled-components/blob/master/src/models/ServerStyleSheet.js#L32

**Comment by clempat** [comment]
OK i will take a look. @kevinsimper I did not want to highjack your request. maybe I missed what you need actually.

**Comment by clempat** [comment]
@philpl this method is not exposed according to the code if I am not mistaken. Anyway I will look further as soon I can.

**Comment by philpl** [comment]
@clempat Oh yea, sorry about that. It's indeed not exposed right now. We could add it, however there wouldn't be a lot of value in doing that as it wouldn't delivery any information for the rehydration.

@kevinsimper This is something that sounds very simple, but is actually not, because of a couple of reasons:

- You can't change the SSR CSS and expect the code (that is now different) in your styled components to work
- You can't remove the rehydration tags and expect rehydration to keep working
- You can't just save it to a CSS file without it being inaccessible in a simple way to the library.

This is probably not something we'd like to pursue. It's also very similar to static CSS extraction, which comes with its own set of problems: https://github.com/styled-components/styled-components/issues/1018#issuecomment-316827497

We might have a partial solution for this at some point, but right now SSR replaces this for us.

In v3 we're planning on releasing a CSS-in-JS pipeline that might be able to be used for transformations, and might enable partial static CSS extraction (although a partial extraction doesn't have any value): https://medium.com/series/with-styled-components-in-the-future-60f52026efd1

**Comment by clempat** [comment]
@philpl Yeah I know, on my side it is for server side only as the amp pages does not allow custom javascript. Maybe I try too much to stick on the tech we use for the "normal application".

**Comment by hilmarragnars** [comment]
@clempat I am also doing Accelerated Mobile Page version of some of my pages and I am using styled-components. Did you find a way to inject the 'amp-custom' attribute to the style tag? 
If you found any other solution could you give me a hint? 
Not too many examples of styled-components with AMP around.

**Comment by probablyup** [comment]
Do a string replace on the front of the style element and inject it

**Comment by kwiss** [comment]
Sad

**Comment by clempat** [comment]
Not better here ☠️ 

```
  // Style hack functions to having it under amp-custom style tag
  const styles = sheet.instance.tags
    .map(tag =>
      Object.keys(tag.components)
        .filter(stripGlobalKeyframeStyles)
        .reduce((styles, k) => styles + tag.components[k].css, '')
    )
    .join('');
  // the following is called in assumption it clear the stylesheet.
  sheet.getStyleTags();
  const minifiedStyles = styles
    .replace(/\/\*.*\*\//g, ' ')
    .replace(/(.sc-[a-zA-z]{6} {})/g, '')
    .replace(/\s+/g, ' ');
```

🙈

**Comment by ChrisBAshton** [comment]
This was our solution:

```jsx
const stylesheets = [...sheet.getStyleElement()];
const inlineCss = stylesheets.reduce((inlineStyles, currentStylesheet) => currentStylesheet
  ? `${inlineStyles}${currentStylesheet.props.dangerouslySetInnerHTML.__html}`
  : inlineStyles
, '');

const inlineStyleAttributes = {};
inlineStyleAttributes[isAmp ? 'amp-custom' : 'data-styled-components'] = '';

<style {...inlineStyleAttributes}>{inlineCss}</style>
```

**Comment by kevinsimper** [comment]
Kind of sounds like this issue should be reopened @geelen 😅 Or somebody could publish a module that does this that people could install
