### ISSUE TITLE
Is there any reason to automatically bump up Stylis versions?

### ISSUE THREAD

**Issue by oliverjam** [styled-components/styled-components#1247]
Apologies if this has come up before, but I couldn't find anything in old issues.

Currently the Stylis dependency version is set to `"3.x"` in the `package.json`. Is there any reason this isn't a standard caret version number?

We have snapshot tests running in our CI pipeline, and because the CI installs the dependencies from scratch every time we often get a new minor release of Stylis without meaning to, which has caused our snapshots to be mismatched with the local versions quite a few times now. The most recent case was a sudden rogue `-webkit-clip-path` (caused by an inadvertent upgrade to [Stylis 3.3.0](https://github.com/thysultan/stylis.js/releases/tag/v3.3.0)).

Is there any reason we would want minor releases (with potentially breaking changes) to happen automatically?

**Comment by mxstbr** [comment]
We literally just merged the change to `3.x`, it's not been released, meaning you could not have been affected by it.

This is an interesting perspective that I didn't think about before merging that change. The reason we changed it is because of issues like #1218, #1230, #1129 and many more that were fixed upstream but users didn't get the fixes because we pinned the stylis version, so they'd require another release from our side, which is kind of annoying.

I think your issue could be fixed by adding `"stylis": "^3.2.0"` to your dependencies? That should force `styled-components` to use that version so your snapshots should never break, and when we push a version `4.x` you'll get a dependency mismatch warning and can upgrade.

**Comment by oliverjam** [comment]
Ah that's interesting. Not sure how this happened then 😕. We actually already have Stylis in our dependencies in an effort to stop this happening but we seem to have acquired the latest release despite this.

I did `npm list stylis` this morning and got
```
─┬ styled-components@2.2.1
   └── stylis@3.3.2
```
I'm not sure how this happened then, but it's clearly not related to the `"3.x"`, apologies!

**Comment by mxstbr** [comment]
Hmm, can you run `cat node_modules/styled-components/package.json | grep stylis` and post the output of that?

**Comment by oliverjam** [comment]
Sure: `"stylis": "^3.2.1"`

We're using Next, and that has a Stylis dependency under styled-jsx, but it's set to `"stylis": "3.2.18"`, so not that either.

**Comment by philpl** [comment]
> We have snapshot tests running in our CI pipeline, and because the CI installs the dependencies from scratch every time we often get a new minor release of Stylis without meaning to, which has caused our snapshots to be mismatched with the local versions quite a few times now.

Are you using lockfiles though? Even patch versions are released all the time, so that's the only way you can be sure. If you're not using a lockfile you could also install any fixed version of stylis that matches both styled-jsx' and our semver range.

**Comment by oliverjam** [comment]
We are using a lockfile. I've just checked our `package-lock.json` and styled-components has
```json
"requires": {
  "stylis": "3.3.2"
}
```
I'm not super familiar with how lockfiles work, but why would it have a much more recent version like that?

**Comment by philpl** [comment]
@oliverjam That is because the caret `^major.minor.patch` satisfies both major and minor bumps when the version is above or equal to `1.0.0`.

This means that `3.3.2` satisfies the old `^3.2.1`. So an upgrade will bring stylis to the newest minor as well.

The tilde `~major.minor.patch` is actually the operator that only allows patches.

@mxstbr I'm actually not clear on why we changed it to `3.x`.

**Comment by oliverjam** [comment]
@philpl Ahh thank you. For some reason I assumed the caret was only for patch bumps. So we should be able to solve our issue by using tilde instead.

For what it's worth we'd prefer not to have `3.x` in there, as we'd like to know when our CSS output is going to mysteriously change/gain some prefixes, but I understand the desire to have Stylis releases with users as fast as possible.

Thanks again for your help 🙏. Feel free to close this, unless you want to discuss the `3.x` change

**Comment by mxstbr** [comment]
>  I'm actually not clear on why we changed it to 3.x.

See my message above, to avoid having issues like "This or that vendor prefix is missing" sitting around for ages even though it's fixed upstream. With `package-lock.json` and being able to pin dependencies that should be fine, honestly.

**Comment by evan-scott-zocdoc** [comment]
https://github.com/styled-components/styled-components/pull/1296
