### ISSUE TITLE
material-ui and styled override specificity issue

### ISSUE THREAD

**Issue by pavel06081991** [styled-components/styled-components#1253]
I'm using material-ui(https://material-ui-next.com/) components library. In this library there is for example component Typography for rendering text, it supports className to override styles. I'm using styled function from styled-components to override default styles of Typography component like this:

```javascript
const StyledTypography = styled(Typography)`
	color: palevioletred;
	font-weight: bold;
        any other styles
`;
```
but some styles are not overridden because of specificity. Maybe because material-ui library adds style tag to the end of head tag after styled-components does the same. I did not find a way except of using !important to override styles. Maybe there is some way to avoid using !important?

**Comment by mxstbr** [comment]
You hit the nail on the head with your analysis, this in indeed because material-ui injects their styles after the styled-components ones.

The way to do this is to increase the specificity, which you could do with `!important` but that's a pain the butt. I'd probably use this hack:

```JS
const StyledTypography = styled(Typography)`
  && {
    color: palevioletred;
    font-weight: bold;
  }
`;
```

Each `&` gets replaced with the generated class, so the injected CSS then looks like this:

```CSS
.StyledTypography-asdf123.StyledTypography-asdf123.StyledTypography-asdf123 {
    color: palevioletred;
    font-weight: bold;
}
```

This bumps the specificity high enough to override the source order without being very tedious to write! :tada:

**Comment by pavel06081991** [comment]
@mxstbr, thanks a lot. Lots of my colleagues faced with this problem and used hacks like this one https://github.com/styled-components/styled-components/issues/860#issuecomment-321710970

I could not find your option anywhere on internet and in styled-components documentation. So maybe you could add it to docs?

P.S. thanks for react-boilerplate

**Comment by mxstbr** [comment]
Yep, a PR to add a FAQ entry ("How to override styles?" maybe? Or "How to work around specificity issues?"? Dunno) would be very welcome: https://github.com/styled-components/styled-components-website

**Comment by unutoiul** [comment]
How can we export the styles from the component.jsx in a separate scss file and then imported with styled?

**Comment by unutoiul** [comment]
also how can you get the material UI theme into my styled?

**Comment by adamchenwei** [comment]
@mxstbr pretty cool and out-of-the-box hack there! love it!

**Comment by oliviertassinari** [comment]
We have added a [documentation section](https://github.com/mui-org/material-ui/blob/28c1f7ab5d60d757c5fbdb8dd11194b3ca0141d2/docs/src/pages/guides/interoperability.md#styled-components. ) for using styled-components with Material-UI. The demo shows how to configure JSS to avoid the `!important` issue.

**Comment by kristojorg** [comment]
If anybody is running into this issue, and can't use the jss comment solution, here is a codemod to add specificity to all styled-components: 

https://gist.github.com/kristojorg/abe305a2ecf49e173c56ef42e977f362

For the record, I ran into this problem because I use [Gatsby](https://github.com/gatsbyjs/gatsby), which renders the base html document template in react, and therefore I couldn't find any way to add a `<-- jss-insertion-point -->`. Instead, I codemoded all my files to add specificity to the generated `styled-components` css. I haven't thoroughly tested the script, but it worked for me so far!

**Comment by oliviertassinari** [comment]
@kristojorg I'm happy to hear you found a solution with Gatsby. I wish we had an example along side Next.js in the repository.
Regarding not beeing able to provide the injection point. I was facing the same issue with codesandbox and with Next.js. You have a different solution available. You can add the HTML comment in JavaScript before the application render.

**Comment by rpellerin** [comment]
Hi! How can this be automated, meaning all `styled` components get a greater specificity? I've been looking at doing this through a babel plugin but could not find how.
Thanks!

**Comment by adamchenwei** [comment]
@oliviertassinari the link on that page https://github.com/mui-org/material-ui/blob/28c1f7ab5d60d757c5fbdb8dd11194b3ca0141d2/customization/css-in-js#css-injection-order
is not working, go to 404.

**Comment by oliviertassinari** [comment]
@adamchenwei https://github.com/mui-org/material-ui/blob/f62796e91495385ecf5d071c1f4f8f22b865bbd5/docs/src/pages/customization/css-in-js.md#css-injection-order

**Comment by oliviertassinari** [comment]
By the way, you can get a styled components API like with Material-UI. It only takes a few lines of code: https://twitter.com/olivtassinari/status/946517606009274369

**Comment by techniq** [comment]
@oliverturner can something like this be used to pass styles to an inner component.  For example, how could you pass `width` to the paper element within `Drawer` from a variable (which might be dynamic, provided by a higher up component)?

For example, [this](https://github.com/paypal/glamorous/issues/354#issuecomment-341860043) kind of works (and `240` could have been read from `props` or a global variable).  I didn't know if there is a better approach using JSS / Material-UI styling?

I ask because I'm working on creating a component to help orchestrate the Drawer and AppBar (show/hide when menu icon is pressed, show/hide based on media query, etc).  I have this working using glamorous, but didn't want to force people to bring in this dependency unnecessarily.

**Comment by oliviertassinari** [comment]
@techniq Material-UI supports a global CSS mode, with explicit deterministic class names. Maybe it can help too.

**Comment by techniq** [comment]
I saw that with the warnings

![image](https://user-images.githubusercontent.com/177476/34582805-4073c8f4-f163-11e7-8e38-be5b4200c917.png)

It's really painful (unless I'm missing something) just to set the width of a Drawer.  It looks like I'll also need to grab all the original styles for [paper](https://github.com/mui-org/material-ui/blob/v1-beta/src/Drawer/Drawer.js#L30) for when I override the `classes.paper` classname?

**Comment by oliverturner** [comment]
@techniq I think you meant to reference @oliviertassinari rather than me 😉

Nevertheless... would this work? 

```
const StyledDrawer = styled(Drawer)`
  & > .paper {
    width: 240px;
  }
`;
```

**Comment by techniq** [comment]
@oliverturner oops, my bad 😄 

Regarding your example, since the paper classname is dynamically generated by JSS (it's not `className="paper"` but something like `MuiDrawer-1234` in dev and `jss1234` in prod) this would not work, but if you declare paper to use a static classname, you could.  This is an idea I had when using glamorous...

```js
const StyledDrawer = glamorous(Drawer, { withProps: { classes: { paper: 'paper' }}})
({
  '& .paper': {
    width: 240,
    backgroundColor: 'blue',
  }
});
```

which something similar could be done using styled-components `attrs` I image, or you can declare your component dynamically, such as this (which was my original approach).

```js
const StyledDrawer = glamorous(({ className, ...props }) => (
  <Drawer className={className} classes={{
    paper: 'paper'
  }} {...props} />
))({
  '& .paper': {
    width: 240,
    backgroundColor: 'green',
  }
});
```

if interested, you can see some of the discussion regarding this approach on this glamorous [issue](https://github.com/paypal/glamorous/issues/354#issuecomment-341860043).

I was hoping to find something similar using Material UI / JSS out of the box for a component I looked to publish to npm and didn't want to bring in a dependency others might not already be using/want (glamor/glamorous/styled-components).

Anyways, this is pretty off-topic on this issue at this point.  Sorry for all the noise.

**Comment by Danilo-Araujo-Silva** [comment]
Looks like we have 3 ways (could be more easy, but not everything is flowers) to override Material UI styles with Styled Components. Here is my [Gist](https://gist.github.com/Danilo-Araujo-Silva/2ce11fd0540dcc7eb3ad3e67fd75d02a).

**Comment by rocketraman** [comment]
I know this is a little off-topic for styled-components, but I'll add one more note that I didn't see anyone point out above...

In some cases, the root of the material-ui component is not the one you want to override, and therefore one cannot use the `&&` trick (see relevant comment from @oliviertassinari here: https://github.com/mui-org/material-ui/issues/9978#issuecomment-359241562).

For example, for the material-ui Drawer, `paper` is not the root element and therefore this does not work:

```
const StyledDrawer = styled(Drawer)`
  && {
    position: relative;
    height: 100%;
    overflow: hidden;
  }
  width: ${props => props.drawerWidth}px;
`
```

In these cases one has to use the method 1 from @Danilo-Araujo-Silva 's gist. This works:

```
const StyledDrawer = styled(({ drawerWidth, ...rest }) => <Drawer {...rest} classes={{paper: 'paper-override'}} />)`
  & .paper-override {
    position: relative;
    height: 100%;
    overflow: hidden;
  }
  width: ${props => props.drawerWidth}px;
`
```

You can even add a `withTheme` wrapper to that to get access to the material-ui theme as `prop.theme`.

**Comment by wmertens** [comment]
Can't the Paper component be interpolated?

**Comment by rocketraman** [comment]
> Can't the Paper component be interpolated?

@wmertens What do you mean? Do you mean:

```
paper {
  ...
}
```

If so, no, because the actual class names are generated at runtime by JSS.

**Comment by wmertens** [comment]
Ah, the battle for the winning css-in-js framework is still raging :)

**Comment by johncmunson** [comment]
I see styled-components and/or emotion as pillars of any React based UI. In my mind, the fact that material-ui doesn't jive well with either of these two libraries means that it is completely ruled out of selection for almost any serious project. I've had far more success by using a combination of [Rebass](https://rebass.now.sh/), [styled-system](https://styled-system.com/), and styled-components.

Still want that "material" look? Fine. Material Design is just a design system/philosophy after all, and the stack mentioned above gives you the primitives to implement Material Design on your own.

**Comment by oliviertassinari** [comment]
@johncmunson This is taking care of in v4. We will continue in the styled-components effort in v5: #6115. Do you have an example of frustration with v3? I want to make sure it's correctly handled in v4.

**Comment by igortas** [comment]
> @johncmunson This problem should already be solved in Material-UI v4: [the](https://next.material-ui.com/styles/advanced/#with-material-ui-core) [examples](https://next.material-ui.com/guides/interoperability/#styled-components).
> 
> ```js
> import styled from 'styled-components';
> import { TextField } from '@material-ui/core';
> 
> const StyledTextField = styled(TextField)`
>   label.focused {
>     color: green; 💚
>   }
>   .MuiOutlinedInput-root {
>     fieldset {
>       border-color: red; 🧡
>     }
>     &:hover fieldset {
>       border-color: yellow; 💛
>     }
>     &.focused fieldset {
>       border-color: green; 💚
>     }
>   }
> `;
> ```
> 
> We will continue the styled-components effort in v5: [mui-org/material-ui#6115](https://github.com/mui-org/material-ui/issues/6115).
> 
> Do you have an example of frustration with v3? I want to make sure it's correctly handled in v4.

v5 mui has issue with specificity, does not override theme settings.

**Comment by IAmStevenHale** [comment]
This is an issue with MUI v5 (^5.15.10). Using "styled-components": "^6.1.8" alongside.

For me it only happens after running next build.

Locally (next dev/npm run dev), all styling works as expected.

Either in production, or after running npm run build > npm run start, the MUI styling is now being applied second or has a higher specificity. Currently, the only way to fix this is to go through and add "!important" or "&&&" to increase the specificity. 

An example, the inspect console on the left is local and the styled(Stack) is taking precedence - you can see the flex-direction row is applied. On the right, which is in production/after building, MUI Stack base styling takes precedence over the styled(Stack) styling.
![image](https://github.com/user-attachments/assets/30f77cf7-6464-465f-a8c1-066e408a1104)

I have tried a few things, updating the _document.js to apply all styling and then apply styled-component styling after everything else. I have tried removing the themeProvider.
The only thing that works is increasing the specificity - which is not ideal as the app is an already established app and would require a bit of work.

This problem should be reopened for MUI v5.

**Example styled component wrapping MUI component - same one as screenshot**
```
const ButtonStack = styled(Stack)`
  flex-direction: row;
  align-items: center;
  gap: 20px;
  @media (max-width: 600px) {
    display: none;
  }
```

**_document.js**
```
import Document, { Html, Head, Main, NextScript } from 'next/document';
import { ServerStyleSheet } from 'styled-components';
import { Children } from 'react';

export default class MyDocument extends Document {
  static async getInitialProps(ctx: any) {
    const sheet = new ServerStyleSheet();
    const originalRenderPage = ctx.renderPage;

    try {
      ctx.renderPage = () =>
        originalRenderPage({
          enhanceApp: (App: any) => (props: any) =>
            sheet.collectStyles(<App {...props} />),
        });

      const initialProps = await Document.getInitialProps(ctx);
      const styledComponentsStyles = sheet.getStyleElement();

      return {
        ...initialProps,
        styles: [
          ...Children.toArray(initialProps.styles),
          styledComponentsStyles, // Ensure styled-components styles are injected last
        ],
      };
    } finally {
      sheet.seal();
    }
  }

  render() {
    return (
      <Html>
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    );
  }
}
```
