### ISSUE TITLE
return class name instead of component?

### ISSUE THREAD

**Issue by rr-kalbeck** [styled-components/styled-components#1273]
emotion has in addition to the styled function another called css that can return a class name..

https://github.com/emotion-js/emotion/blob/master/docs/css.md

does styled-components have a similar feature? if not, would it be easy to implement?

**Comment by philpl** [comment]
You can use injectGlobal, however creating classes for anything else than explicit global styles is something we discourage and is definitely an anti pattern in styled-components.

So this won’t be a feature in the library

**Comment by ConneXNL** [comment]
@kitten , I got a usecase where a component may use a tooltip within a portal (a third party library). I would love to pass `className` and `portalClassName` to my component.

I am trying to use the attrs to set this portalClassName but I have no way to get a class instead of inline css.

const MyStyledComponent = styled(MyComponent).attrs({
    portalClassName: css`
        ...someStyles
    `
})`

Maybe a return to class name could be a nice addition to handle odd use cases where "best practice" isn't possible.

**Comment by mxstbr** [comment]
```JS
const portalClassName = 'portal';

const MyStyledComponent = styled(MyComponent).attrs({
    portalClassName,
})`
  & .${portalClassName} {
    color: blue;
  }
`
```

**Comment by nihgwu** [comment]
@mxstbr That won't solve the other use cases, I created a lot of React components, and I'd like to demo the `className` prop for them, I think the best way is provide a equivalent helper as emotion's `css` to generate a className and then I can use it directly, I think that should be super great as I don't need to create a css file to define the styles, all the things are in the same page, that's why I just switched to `emotion` from `styled-components`, but I'd say I love `styled-components`, hope we can re-consider about this proposal

**Comment by alexkrolick** [comment]
The "framework-agnostic" `css` prop is pretty handy for porting over existing layouts to CSS-in-JS or just sprinkling in a bit of props-dependent CSS without refactoring anything. Needing a babel plugin for the `css=` prop is a pretty heavyweight solution for this problem.
