### ISSUE TITLE
How can make Styled-components classes in a file to an object file???? 

### ISSUE THREAD

**Issue by sw-jun** [styled-components/styled-components#1291]
hello guys! I'm junior programer using React.js with Styled-components.

it's been just 2 months since I have started React, and now developing an mobile web page. 

When I make a component folder, I create two files. An React class file and styled-components file for css.

I make each HTML tag to Styled-component and declare their contents(css) in styled-components file.

then, as you know, I can import them from styled-components file and use.

!!!BUT HERE'S A QUESTION

In a React class file(for a component), I use some other component and and styled-components file.

So I import them and use, But Their form are similar!!

ex) when I use a component               I imported ==> <ExButton (props) />
                            styled-components I imported ==> <ExButton (props) />

like this, they confuse me when I look back my codes.

of Coures, I can decalre styled-components like <StyledExButton />

but i think its too inefficient cause its not good to add 'Styled' to every styled-components.

and importing styled-components code also too looooong!

<img width="1440" alt="2017-11-04 4 11 57" src="https://user-images.githubusercontent.com/29892278/32403370-16e03aa8-c17b-11e7-9aa1-8f36d000dfe8.png">

So i want to use more simple for using styled-components.

it's objectify the styled-components in a file.

so I think if I can use default import  styled-components class like this
   <StyledA.Exbutton />

but i tried objectify the styled-components, but It didn't work.

I couldn't make them as an object like 'StyledComponentJack'.( to use StyledComponentJack.ExButton)

so Here's Summary about question.

1. Confusing using general component(react) and styled-components.
2. Too Looong codes importing styled-components from styled-components file.

thank you for reading this issue!!

**Comment by k15a** [comment]
Just do `import * as Styled from './ProductPageStyles'` and you're good to go.

**Comment by philpl** [comment]
Generally I’d recommend you to go to Our Spectrum, Stackoverflow, or sth similar with this question btw. It’s not related to styled-components, so it’s better left somewhere else, to not create and have too many issues that have to be taken care of while bugs and other issues have a higher priority.

Anyway, it also seems like you’re trying to write this page component with this library like it was a static c HTML page without components. Create some smaller components and build the page up like a pyramid! If you create smaller components where it makes sense (In the screenshot I see at least 7 components relating to a title/header with a box? That can be extracted)

This will allow you to worry about smaller parts of the page instead of the entire thing.

Also, read some Medium articles on structuring styled-components projects. I believe there were some helpful ones.

So last but not least, I love helping junior devs, so feel free to DM me on Twitter. But please read the issue template, write a brief and precise description of your problem, and choose a more accurate title ;)

Luckily we’re also not dealing with an “attention economy”, so we mostly reply to every single issue. So multiple question marks are not necessary ;)

Hope this help 😬

**Comment by sw-jun** [comment]
Thank you so much!

And Sorry. I promise a careful double check When I got problem later.
