### ISSUE TITLE
[typescript] TS2694 Namespace error during tsc 

### ISSUE THREAD

**Issue by IljaDaderko** [styled-components/styled-components#1295]
## Version
2.2.3 [native]

## Reproduction
Building project with `tsx` results in following error that appears to be coming from styled components module (or react native itself? not too sure here)

```
node_modules/styled-components/native/index.d.ts(38,52): error TS2694: Namespace '"/Users/me/Documents/Repositories/project/node_modules/@types/react-native/index"' has no exported member 'NavigatorProperties'.
```

**Comment by morajabi** [comment]
Are you sure package versions match with their `@types/<package>` dependants?

**Comment by IljaDaderko** [comment]
@morajabi 

```
"@types/react": "16.0.20",
"@types/react-native": "0.50.0"
"react": "16.0.0",
"react-native": "0.50.1",
```

They were slightly off, updated to identical, removed and re-installed node modules, still getting same issue :/

**Comment by IljaDaderko** [comment]
@morajabi they released `@types/react-native` v0.50.2, still receiving same issue that seems to be coming from `styled-components/native/index.d.ts(38,52)`

**Comment by wodCZ** [comment]
Yes, styled-components/native typings have to be updated as react-native doesn't have `NavigatorProperties` interface anymore.

As a temporary workaround I have added `--skipLibCheck` parameter to `tsc` call: `tsc --skipLibCheck`.

**Comment by IljaDaderko** [comment]
@wodCZ yep that works, is `--skipLibCheck` a good flag to have for production builds? i.e assuming it is off during dev, it makes sense to me to use in prod build just in case to avoid complications with 3rd party typings.

Just getting into ts, could be wrong.

**Comment by wodCZ** [comment]
@IljaDaderko It's not safe. When you (and all your libraries) have correct type declaration files (*.d.ts), TypeScript checks that libraries you use are compatible. `--skipLibCheck` disables this check, so you may run into incompatibility issues.

react-native doesn't have Navigator since version 0.44 (0.43 is latest that has Navigator)

As long as this is the only typescript issue you have and don't use `styled.Navigator` in your code, you can temporarily use `--skipLibCheck`, but you should stop using this flag once this issue is resolved.

**Comment by mxstbr** [comment]
Ref PR: #1339

**Comment by ChrisDillinger** [comment]
I'm getting this error for Koa. 

 ../node_modules/@types/koa/index.d.ts(104,14): error TS2694: Namespace '"url"' has no exported member 'URL'.

What is going on exactly? What is @types? Is this something maintained by Koa? Is this something generated by typescript?
