### ISSUE TITLE
Using CSS pseudo-class can result in duplicate CSS

### ISSUE THREAD

**Issue by wSLecHayfIeNdock** [styled-components/styled-components#1298]
## Version
2.1.0

## Reproduction

https://codesandbox.io/s/5xwp9x9p1x

## Steps to reproduce
```
const TestRow = styled.div`
    color: white;
    font-size: 14px;
    line-height: 26px;
    &:after {
      content: '${({ text }) => text}';
      display: block;
    }
`;

<div style={{ display: 'flex' }}>
    {Array.from({ length: 8 }, (v, k) => <TestRow key={k} text={7 - k}>{k}</TestRow>)}
</div>
```
## Expected Behavior
```
.PanelRow__TestRow-eMfavc {
    color: white;
    font-size: 14px;
    line-height: 26px;
}

.gDFoFD:after {
    content: '7';
    display: block;
}

.kSihrl:after {
    content: '6';
    display: block;
}
```
## Actual Behavior
![image](https://user-images.githubusercontent.com/16831715/32497230-d727514c-c406-11e7-9b1e-a64816a50797.png)

**Comment by philpl** [comment]
This is expected behaviour. Each change in your styled component's interpolation will generate a different CSS string. This is then injected into the stylesheet if it hasn't been already.

This is important to preserve the specificity, e.g. in your example `&` comes before `&:after`. Often it's of course not necessary, but we enforce this guarantee regardless.

This is not a concern at all, since for SSR gzip will take care of the deduplication, and on the client it's consequenceless (at least it's going to be above 10,000 rules as well, once we finish implementing the speedy injection)
