### ISSUE TITLE
Add helper to convert component to styled component without styles inside template literal

### ISSUE THREAD

**Issue by sanex3339** [styled-components/styled-components#1316]
It's nice to have ability to convert ReactClass or StatelessComponent to styled component without adding template literal empty quotes.

Currently i should do this:
```ts
export const SomeComponent = styled(
    ({children, className}) => (
        <div className={className}>
            {children}
        </div>
    ) 
)``; // <- template literal quotes
```

This styled SomeComponent has no styles but it can be styled inside other component by reference:
```
styled(SomeOtherComponent)`
    width: 100px;

    ${SomeComponent} {
        display: flex; // <- here we can style SomeComponent with specific for SomeOtherComponent styles
    }
`;
```

But this approach requires to add empty template literal quotes to `styled` call. 

It would be nice to have a way to convert component to styled component without adding template literal empty quotes.

**Comment by philpl** [comment]
So, we probably won’t be adding this and the reason for that is that our recommended best practice approaches regarding your patterns are:

- avoid wrapping any React component that is not a styled component, and instead use styled components as basic presentational components, I.e. as lead components in the bottom of the component tree
- use **reverse** component selectors so that a styled component is aware of the parent, and not a making parent style a child

There’s more explanations here: https://github.com/styled-components/styled-components/issues/1302#issuecomment-342788554

**Comment by sanex3339** [comment]
I think it's not good when component knows about parents.

For example common componens (styled) that we using like `lego` blocks and they can be in any place of JSX in many places. 

It's impossible to describe in reverse way all styles rof each common component inside for each parent, because parents can be the same in different pages, but parents of parents can be different.

**Comment by philpl** [comment]
@sanex3339 sure, for common, reusable components, like layouting you could use props to abstract their special behaviour in different places as well.

Or create more specialised components for wrappers in other places. Like flex box wrappers; they don’t necessarily have to be 100% reusable but can also just be created as needed

**Comment by jgoux** [comment]
I'm also interested in referencing non-styled components in my css blocks.

Could a babel-plugin solve this by detecting components referenced in `css` template literals and wrap them into a styled component if they're an instance of React.Component? (I have no idea if it's possible)

This feature with https://github.com/satya164/babel-plugin-css-prop would be a killer combo!
