### ISSUE TITLE
[bug] styled(Comp)`...` doesn't apply styles

### ISSUE THREAD

**Issue by caub** [styled-components/styled-components#1341]
demo: https://jsfiddle.net/crl/LoknjL0p/4/

In the code below, I expect BarStyle to be applied (so the textarea should have a red border), but it's not

code:
```js
const FooStyle = styled.div`
	border: 1px solid blue;
	height: 6em;
	textarea {
		height: 4em;
		width: 95%;
	}
`;
const Foo = ({children}) => (
	<FooStyle>
		<div className="foo">
			{children}
		</div>
	</FooStyle>
);


const BarStyle = styled(Foo)`
	textarea {
		border: 1px solid red;
	}
`;
const Bar = () => (
	<BarStyle>
		<textarea />
	</BarStyle>
);

ReactDOM.render(<Bar />, root);
```

styled-components version: 2.2.4

**Comment by caub** [comment]
It's maybe not a bug, since it works with `const BarStyle = styled(FooStyle)..` https://jsfiddle.net/crl/LoknjL0p/3/

so `styled(Comp)` would work only with components already wrapped with styled?

**Comment by philpl** [comment]
You have to pass on the `className` prop, e.g.:

```js
const Foo = ({className, children}) => (
	<FooStyle>
		<div className={className + " foo">
			{children}
		</div>
	</FooStyle>
);
```

> The styled method works perfectly on all of your own or any third-party components as well, as long as they pass the className prop to their rendered sub-components, which should pass it too, and so on. Ultimately, the className must be passed down the line to an actual DOM node for the styling to take any effect.

This is a snippet from our docs and I can only hope that you'll take questions up there or on Spectrum first the next time :smile: This is just supposed to be a gentle reminder, since we do receive the same questions regularly. So I'll leave you with a link, and if you were aware of the docs but overread this part, please let us know how we can improve them :+1:

https://www.styled-components.com/docs/basics#styling-any-components

**Comment by caub** [comment]
ohh, thanks
