### ISSUE TITLE
[RN] Failed to parse declaration of padding

### ISSUE THREAD

**Issue by yordis** [styled-components/styled-components#1346]
I have to use `padding-vertical`, `padding-horizontal` but I can't use `padding: [number];`

Same for margin

Code example

```js

const ComponentName = styled.View`
  padding: 5;  <--- this fails
`

```

<img width="531" alt="screen shot 2017-12-08 at 9 02 36 am" src="https://user-images.githubusercontent.com/4237280/33776542-90d8f0d0-dbf6-11e7-9f6e-ccc988df53f9.png">

**Comment by philpl** [comment]
I'm not quite sure why the entire error isn't showing up, but you have to add units, i.e.:

`padding: 5px;`

This is because we're now differentiating between `px` and `%`.

> In v2 we support percentages. To make this possible **we need to enforce units for all shorthands**. If you're migrating to v2, a codemod is available.

https://www.styled-components.com/docs/basics#react-native

**Comment by yordis** [comment]
@philpl I am new into RN but as far as I know there is no `px` in RN right? Isn't everything without unit?

**Comment by philpl** [comment]
@yordis this is specific to styled-components; we introduce a lot of CSS shorthands and syntax that you're used to actually :wink:

**Comment by yordis** [comment]
@philpl got it, but doesn't this seems a little bit weird? Shorthands could be `5 5 5 5` or just `5` unless you are using the same underline engine and you didn't want to use different parsers ...

**Comment by philpl** [comment]
@yordis well, in fact, we're basically removing complexity by making it more similar to vanilla CSS :wink: but that's a matter of perspective.

The point is not that we do it because it's a shorthand; We do it to differentiate between units inside shorthands. Otherwise we wouldn't be able to recognise percentages and px values and be able to correctly translate them and split them up later.

Anyway, I hope I've helped you here, and feel free to checkout css-to-react-native if you have some suggestions or issues :smile:
