### ISSUE TITLE
Debugging in Typescript

### ISSUE THREAD

**Issue by iamdanthedev** [styled-components/styled-components#1389]
Hi! I've asked this question on SO, but got no reply. Taking in account that it would no be nice to wrap typescript with a babel-plugin to debug styled-components (e.g. to see components' names in dev-tools), how could I achieve the same functionality?

Thanks

**Comment by rasdaniil** [comment]
Maybe I could monkey-patch it somehow? ;)

**Comment by wmertens** [comment]
AFAIK, you can't use Babel on typescript, so you can't do this :-/ this is
the main reason I don't use typescript…

**Comment by probablyup** [comment]
https://www.npmjs.com/package/babel-preset-typescript

**Comment by philpl** [comment]
@rasdaniil I think @probablyup's suggestion is viable here. You could also attempt to integrate babel into your pipeline and *only* run our plugin. I don't really see other viable options here for the moment.

Since this is more a question for now but not an actionable, as I don't see any replacements for the plugins, I'll go ahead and close this issue for now.

If you have an idea on how to make this possible w/o babel please let us know 👍 :100:

**Comment by rasdaniil** [comment]
Hello
Thanks for suggestions
I've ended adding babel on top of typescript, it works find. At the same time readjusted the pipeline and integrated another useful babel plugin which the pure typescript workflow lacks of (babel-plugin-lodash). Unfortunately I didn't receive notifications from github on new replies here, so I haven't a chance to know about `babel-preset-typescript`, which looks interesting, though I'm not sure it would be a good idea to trade `ts-loader/awesome-typescript-loader` with all their performance features in.

In case anyone decides to do the same here, this is the webpack rule (quite banal though):

```
      {
        test: /\.tsx?$/,
        use: [
          {
            loader: 'babel-loader',
            options: {
              presets: [
                ["@babel/env", {
                  "targets": ["> 1%"]
                }],
                "@babel/react"
              ],
              plugins: [
                // "lodash",
                "babel-plugin-styled-components",
                "babel-plugin-transform-react-stateless-component-name"
              ]
            }
          },
          {
            loader: 'ts-loader',
            options: {
              compilerOptions: {
                jsx: 'preserve',
                module: 'es2015'
              }
            }
          }
        ],
        include: SRC_ROOT
      }
```
Had to skip .babelrc because `storybook` started producing errors when it found custom .babelrc file.

**Comment by AustinBrunkhorst** [comment]
For those interested in using the typescript create react app without babel - I created a rewire plugin that adds a typescript transformer plugin for styled components (thanks to [@Igorbek](https://github.com/Igorbek/typescript-plugin-styled-components)).

[react-app-rewire-styled-components-typescript](https://github.com/AustinBrunkhorst/react-app-rewire-styled-components-typescript)
