### ISSUE TITLE
Feature: Composition by using multiple classes like css modules

### ISSUE THREAD

**Issue by 0xR** [styled-components/styled-components#144]
When I compose style like so:
```js
const PrimaryButton = styled(Button)`
  color: #fff;
  background-color: #337ab7;
  border-color: #2e6da4;
`;
```

I get a new class which contains both the styles for ``Button` and the styles of `PrimaryButton`.

## Reproduction
http://www.webpackbin.com/NysPMW21G

## Expected Behavior
A separate class for the button and the primary button which are both applied to my component. Just like CSS modules does.

That way you can keep composing styles without your CSS growing exponentially. It also fits in nicely with immutable CSS, where you just compose single property styles instead of overriding styles.

**Comment by mxstbr** [comment]
We initially did it this way, but it turns out that this has very inconsistent, buggy behaviour due to CSS injection order. (thanks to @xymostech for the initial bug report) It's highly unlikely that we will change this back again!

See #45 for a detailed bug report and thoughts on this, and #46 for the PR that fixed these issues.

**Comment by xymostech** [comment]
@mxstbr :) Glad to see that you guys fixed it!
