### ISSUE TITLE
SC 3.1.5 Module not found: Can't resolve 'styled-components/lib/models/StyleSheet'

### ISSUE THREAD

**Issue by PlanetIrata** [styled-components/styled-components#1483]
Using StyleSheet to generate styles on client side don't work anymore with SC 3.1.5. Please read https://github.com/styled-components/styled-components/issues/893#issuecomment-362545002

**Comment by mxstbr** [comment]
In v3 we started bundling everything into flat bundles in the `dist/` folder (see #1362) and don't ship a transpiled `lib/` folder anymore. Requiring/importing anything from `lib/` was never officially supported and is at best a hacky workaround.

**Comment by PlanetIrata** [comment]
So there's no way to extract the CSS rules from client side with SC 3 ? It is not a testing issue with Jest in my case, I just want to extract the rules generated by SC and the workaround I posted in #893 with StyleSheet was my unique way to do it.

**Comment by mxstbr** [comment]
<sub>[hint hint hint hint hint](https://github.com/styled-components/styled-components/blob/master/src/secretInternals.js#L6-L8)</sub>

**Comment by PlanetIrata** [comment]
Thanks for the hint @mxstbr , but importing __DO_NOT_USE_OR_YOU_WILL_BE_HAUNTED_BY_SPOOKY_GHOSTS don't work in my app (made with create-react-app). I tried to use the exact same code found in [jest-styled-component utils.js file](https://github.com/styled-components/jest-styled-components/blob/25d3bb54967c6b9bc1fbc3732a3fc310618cfef5/src/utils.js) and no luck, the secretInternals module is not exposed. 

Could this be related to #1438 and the remove of secretInternals from the production bundle ? So that secretInternals could only be used in testing environment ?

**Comment by mxstbr** [comment]
Oh yeah true, we only allow that in test, damn. Remind me of your use case again?

**Comment by PlanetIrata** [comment]
Here is my use case: https://github.com/styled-components/styled-components/issues/893#issuecomment-307339935

**Comment by mxstbr** [comment]
Mind opening a new issue with an explanation of your use case so that we can figure out whether we want to expose `StyleSheet` generally? Thank you!

**Comment by nir-welldone** [comment]
Any progress with exposing StyleSheet?

**Comment by probablyup** [comment]
@nir-welldone https://github.com/styled-components/styled-components/blob/master/src/secretInternals.js#L6-L8

**Comment by kitten** [comment]
@nir-welldone @probablyup we're still not exposing the secret internals in production, but I think we'll just add that in 3.2.0

cc #1487

**Comment by nir-welldone** [comment]
ok. Thanks!

**Comment by jakedeichert** [comment]
Just echoing this: having access to the stylesheet in production would be great. My 3 statically generated sites broke with v3.1 since `insertRule` validates the css and removes parts it doesn't like. 

For example: Chrome removes `::-moz-selection` styles and also ` -webkit-text-size-adjust: 100%;` (which I think mobile safari needs). This prevents me from generating static pages that work cross-browser.

So right now it seems impossible for me to extract the raw css that was added via `insertRule`. Hoping for some solution to this! 👍

**Comment by kitten** [comment]
@jakedeichert I’m planning to send a PR in today that’ll expose it in any environment, also to fix some issues where people are using jest-styled-components in a prod like web environment.

To answer your concern however, the Stylesheet as it worked before and it works now doesn’t keep a copy of the input CSS around. During th refactor I have reimplemented support for all tags (browser tags, server tags, inserts rule tags) to output their CSS, however, to get their predictable results they output the CSS that was injected. For the insertRule Tags that means that they just take the CSS rules that we’re registered on the sheet.

So it will still not output the full CSS code for you. To generate static pages you might want to resort to our SSR. You can also manually reset the Stylesheet and force it into the server mode. I’d be happy to discuss your use case via DMs so we can find a solution :)

**Comment by jakedeichert** [comment]
@kitten thanks for the update! I tried to reach out on twitter a week ago but didn't get a response 😅 

Anyway, I just played around with the latest version and tried to use the secret internal stylesheet to somehow collect all tags being injected. I was mostly successful! I mapped over the `tags` array to collect the `css()` of them all. I ran into a small issue where `injectGlobal` styles are not included in that `tags` array it seems.

Here's the code for that.
```js
import { __DO_NOT_USE_OR_YOU_WILL_BE_HAUNTED_BY_SPOOKY_GHOSTS as sc } from 'styled-components';
const css = sc.StyleSheet.instance.tags.map(t => t.css()).join('');
const styles = document.createElement('style');
styles.appendChild(document.createTextNode(css));
document.head.appendChild(styles);
```

Anyway, this got me thinking further. My use case is very specific: I use headless chrome to crawl all routes to generate my static pages. When updating dependencies, I have snapshot testing set up to ensure the output html is the same as the previous build (this is how i found out v3.1 changed since the style tags were empty).

Since i'm generating static pages and not shipping any js, i'm okay with this ugly/hacky alternative... monkey patching `CSSStyleSheet.prototype.insertRule` 🙊 

```js
<script>
        const cssInserts = [];
        const insertRuleOriginal = CSSStyleSheet.prototype.insertRule;
        CSSStyleSheet.prototype.insertRule = function (...args) {
            cssInserts.push(args);
            return insertRuleOriginal.apply(this, args);
        };
</script>
<script src="/bundle/vendor.bundle.js"></script>
<script src="/bundle/app.bundle.js"></script>
<script>
        const css = cssInserts.map(i => i[0]).join('');
        const styles = document.createElement('style');
        styles.appendChild(document.createTextNode(css));
        document.head.appendChild(styles);
</script>
```

This gets me the entire raw css and should work for *any* css-in-js library that has switched to `insertRules` too!

I actually haven't seen anyone mention this solution yet. Do you have any thoughts on this? Monkey patching is very often looked down upon, but this seems like one of those situations where it works and shouldn't be able to harm anything.

**Comment by cyrus-za** [comment]
For those who come here (a year later) with sc@4 and jest-sc@6 and suddenly find it broken, see the latest comments at styled-components/jest-styled-components#112
