### ISSUE TITLE
Unable to set custom stylesheet

### ISSUE THREAD

**Issue by 0xc0d3r** [styled-components/styled-components#1486]
I've forked this repo and added a function which can set custom stylesheet(which scales font size, paddings, margins, etc. based on screen resolution). 

I've changed few lines of code in [`native/index.js`](https://github.com/styled-components/styled-components/blob/8922e0e08294740fd9d08706a23310ec0c69471b/src/native/index.js#L18) to pass custom stylesheet from config.

```
import config, { setStyleSheet } from '../config'

// NOTE: Here we are passing our custom StyleSheet i.e. VRCStyleSheet
// to enable autoScaling based on screen resolution

const InlineStyle = _InlineStyle(config.stylesheet)

const StyledNativeComponent = _StyledNativeComponent(
  constructWithOptions,
  InlineStyle
)
```

I published above changes to private repository and I'm setting our custom stylesheet in `App.js` and everything worked fine.

Today I merged the latest code of `styled-components` and I'm unable to set custom stylesheet. While debugging I kept console log statements in `setStyleSheet` method and `native/index.js` file. I couldn't see the log which I kept in `native/index.js`. So I'm unable to set custom stylesheet. Any help to fix this issue? 

Thanks!

**Comment by mxstbr** [comment]
Your hacking around styled-components in a very unsupported way, I'm not going to spend time to figure out what your issue is to be completely honest.

If you upgraded from v2, most likely it's #1362, which means `/native/index.js` isn't called and the file you're looking for is `/dist/styled-components.native.js`.

**Comment by 0xc0d3r** [comment]
Is it `/dist/styled-components.native.cjs.js`? I couldn't see below code

```
const InlineStyle = _InlineStyle(reactNative.StyleSheet)

const StyledNativeComponent = _StyledNativeComponent(
  constructWithOptions,
  InlineStyle
)
```

**Comment by mxstbr** [comment]
Yeah I understand what you're doing, and it's not something we officially support :wink: 

Again, see the changes we made in #1362—the file `native/index.js` isn't called anymore because when you import `/native` it actually points to `/dist/styled-components.native.cjs.js`. Make the same change in that file and it should work again.
