### ISSUE TITLE
Support for style-related props (not set via 'style') in React Native

### ISSUE THREAD

**Issue by adamterlson** [styled-components/styled-components#149]
Presently in styled components, there is no way to affect other style-related props in React Native. 

This style-related-prop-not-defined-via-`style` can be found in many third party libraries (such as [React Native Navbar](https://github.com/react-native-community/react-native-navbar)'s `tintColor` prop), in custom components one might write themselves, and in React Native's core components, for example:
- [TouchableHighlight](https://facebook.github.io/react-native/docs/touchablehighlight.html) underlayColor
- [ActivityIndicator](https://facebook.github.io/react-native/docs/activityindicator.html) color and size
- [Slider](https://facebook.github.io/react-native/docs/slider.html) maximumTrackTintColor and minimumTrackTintColor
- [StatusBar](https://facebook.github.io/react-native/docs/statusbar.html) backgroundColor
- [TextInput](https://facebook.github.io/react-native/docs/textinput.html) placeholderTextColor, underlineColorAndroid and keyboardAppearance
- [Switch](https://facebook.github.io/react-native/docs/switch.html) onTintColor, thumbTintColor and tintColor
- ... and a lot more

It's of course possible to simply set these props manually, but styled-component's themes are unable to be leveraged to standardize them across the codebase.

**Comment by irakli-janiashvili** [comment]
This definitely will be a great enhancement!

**Comment by mxstbr** [comment]
Is there a list of the ones that exist somewhere? We should definitely add support for them!

**Comment by adamterlson** [comment]
@mxstbr I'm unaware of any existing list.  The only option would be to go through every available component and manually catalog them

**Comment by irakli-janiashvili** [comment]
I can volunteer to go through and get the list of those items.

**Comment by mxstbr** [comment]
That would be amazing @irakli-janiashvili! 🙏

**Comment by irakli-janiashvili** [comment]
@mxstbr @adamterlson

Here's the list of all possible attributes that can go in styles ->  https://gist.github.com/irakli-janiashvili/dac99f8ceb0c1a9bafa78aad0f19d861

I put a question marks in front of some attrs that I'm not sure we have to put in styles..

**Comment by adamterlson** [comment]
It seems like a lot to maintain manually. 

Why not simply provide a way to generally set any prop desired?

**Comment by mxstbr** [comment]
That's an unnecessary escape hatch @adamterlson, since you can already set any prop desired when rendering. I think with the list @irakli-janiashvili dug up we should be fine to publish a first version with support for these. It doesn't matter if it's not 100% complete, as we can always add more to the list.

Basically, what we should do is have a separate module called `react-native-style-props` which exports an object. This object should be keyed by primitive and each one should have an array of props like this maybe?

```JS
// react-native-style-props/index.js

module.exports = {
  ActivityIndicator: ['color', 'size'],
}
```

Then from `styled-components` we can check at creation time if the current property is supported as a `prop`, and pass it to the underlying primitive. What do you think, does somebody want to go ahead and create that repo?

**Comment by mxstbr** [comment]
This is now finally possible in version two with the `.attrs` constructor!

```JS
const Button = styled.TouchableHighlight.attrs({
  underlayColor: 'red',
})`
  color: blue;
`
```
