### ISSUE TITLE
Unable to encapsulate react-modal component

### ISSUE THREAD

**Issue by NathanielHill** [styled-components/styled-components#1494]
I'm running into a problem trying to encapsulate a react-modal `<Modal>` with styled-components. Neither `attrs` or `defaultProps` pattern work. After looking at how react-modal generates the modal elements outside of the `<App/>` root in the DOM, it's not surprising this is causing problems. It looks like [buildClassName()](https://github.com/reactjs/react-modal/blob/d93fae17b944b6d50ee5342ac6de03375b07fdaf/src/components/ModalPortal.js#L277) is correctly adding the 'modal-overlay' `className`. I suspect styled-components doesn't inject the CSS as it doesn't see any of it's children, or any of the `<App/>` children using it. Any ideas on how to get this to work to avoid using a global css class for the overlay?

```
const overlayClassName = 'modal-overlay'
const StyledModal = styled(Modal).attrs({
  overlayClassName
})`
  styles: here;

  &.${overlayClassName} {
    doesnt: work;
  }
  .${overlayClassName} {
    also-doesnt: work;
  }
`
```

**Comment by elrumordelaluz** [comment]
I think the problem is based on the fact that `react-modal` [expect an `Object`](https://github.com/reactjs/react-modal#using-css-classes) for its `props` _ className_ and _overlayClassName_ and probably `sc` pass down directly the `attrs` so you'll see rendered in the DOM something like:
 
```diff
<div class="
  ReactModal__Content 
  ReactModal__Content--after-open 
  sc-EHOje 
-  [object Object] 
  inJiKH" tabindex="-1" aria-label="Modal">…</div>
```

**Comment by exogen** [comment]
The issue is that the `styled-components` passes `className`, but the `className` prop to `ReactModal` styles the inner Modal – the other two elements you'd want to target (the Overlay and the Portal) are *parents* of the Modal, not children.

So here's how I do it:

First make a little adapter that rewires `className` to style the Portal. Use a new made-up prop `modalClassName` to style the Modal. So, `className` → `portalClassName`, and `modalClassName` → `className` (like `ReactModal` expects).

```jsx
function ReactModalAdapter({ className, modalClassName, ...props }) {
  return (
    <ReactModal
      className={modalClassName}
      portalClassName={className}
      {...props}
    />
  );
}
```

Then use that with `styled()` instead of `ReactModal` directly:

```jsx
const StyledModal = styled(ReactModalAdapter).attrs({
  overlayClassName: 'Overlay',
  modalClassName: 'Modal'
})`
  /* Portal styles here (though usually you will have none) */

  .Overlay {
    background: rgba(0, 0, 0, 0.5);
  }

  .Modal {
    width: 640px;
    height: 480px;
  }
`;
```

**Comment by kitten** [comment]
@NathanielHill This is certainly surprising given that I cannot believe that anyone would consider to use the de facto standard `className` prop for something else.

@exogen This is the right answer in this case; Just create a small wrapper component according to their classes: https://github.com/reactjs/react-modal#using-css-classes

Another note is to explicitly write `&.yourClass` as I've said in my other comment, so that you expressively indicate that this class should be combined with ours. Then make sure that you make our `className` prop the "base" class (I think that's what they call it)

**Comment by yobacca** [comment]
I made a CodePen to show the correct usage for styling react-modal with styled-components: 

https://codepen.io/yobacca/pen/RQoGdP

I encountered some issues during the development of the showcase, because some of the hints above were misleading. But finally the CodePen works...
