### ISSUE TITLE
Support a simplified version SC?

### ISSUE THREAD

**Issue by WangLarry** [styled-components/styled-components#1500]
In many cases， we don't need theme， even interpolation function.
Why not support a simplified SC, just for static style.
It will decrease bundle size, improve performance, prevent wrong usage(etc: ```<Box margin={2}...>```)

**Comment by mxstbr** [comment]
https://github.com/jxnblk/diet-cola

**Comment by WangLarry** [comment]
@mxstbr 
I think many people use SC with wrong method, for example: <Box margin={2} ...> It config static value in props of component, will have to get options through interpolation function, then calculate result, get same result over and over again.
It is problem of performance, in SSR specially.

**Comment by mxstbr** [comment]
Not really, no, especially once #1311 lands and we cache dynamic style fragments. :blush:

**Comment by WangLarry** [comment]
looks seem very complex, haha

**Comment by mxstbr** [comment]
Slightly complex, but it gives the best development experience without many downsides :blush:

**Comment by WangLarry** [comment]
@mxstbr 
Maybe should give user some advices:
1. can use static theme provider, instead of using context dynamic theme
2. try use mix, helper .. functions to calculate result, instead of  config static value in props of component

**Comment by mxstbr** [comment]
1. Dynamic theme is totally fine
2. Props are totally fine

**Comment by WangLarry** [comment]
I do not say dynamic theme and props are bad, but means user should be noticed there are a performance problem.
Maybe should support another interface which seperate static and dynamic style?
For example, a HOC function ```createStyledComponent({staticStyle, dynamicStyle})```, staticStyle be pre-created

**Comment by WangLarry** [comment]
I still think ```<Box margin={2} ..>``` etc is a wrong usage in current SC.
Its interpolation function will run many many times in server render.
Why not pre-create it.  If need margin=3，can use sc's extend function to create another component.

**Comment by kitten** [comment]
@WangLarry It's easy to overestimate the impact that interpolations have on the performance, but they pale in comparison to much bigger parts of the app. We're talking about nanoseconds vs milliseconds. Mostly our performance characteristics are made up of the React lifecycle, stylesheet management, style injection, style processing (stylis)...

And after this long list then come interpolations and themes.

We have benchmarks without style injection: https://github.com/styled-components/styled-components/pull/1208#issuecomment-336592341

And some with: https://github.com/styled-components/styled-components/pull/1208#issuecomment-359868891

(The numbers won't match up since they're two entirely different stress tests)

It's sufficiently fast, it's fast enough for loads of consumers of the library, and this is really not a bottle neck. We're getting to the point where only side stepping React / Recomputations are meaningful. And that's something we're working on. And the postprocessing will also become more efficient. And who knows, maybe we'll be able to manually modify our inserted rules or use css vars in some edge cases which bumps us up even more.

The point being: We know where the bottlenecks are, they're barely an issue, and I'd recommend you not to spend too much time on this :wink:

Regarding SSR on the other hand, it's always a better idea to instead cache parts of the React tree if you know that it won't change.

And regarding stuff like `<Box margin={2} ..>`, I'm also not a fan of excessive props representing single properties, but they're certainly not "wrong". Just maybe not what you'd prefer 😀

Even if such was true, and it was wrong, then you could still opt for different styles of working with styled-components :wink:

Hope this explains the situation in detail 👍
