### ISSUE TITLE
Possible bug with sibling selectors

### ISSUE THREAD

**Issue by frednomoon** [styled-components/styled-components#1508]
Hello first issue here apologies in advance for any stupidities. I am currently using the latest version (3.1.6).

I think I have encountered a bug while styling an `input` component... here is a Pen which will hopefully elucidate the issue:
https://codepen.io/fredshep/full/aqJOKM

I'm trying to add a style to adjacent divs using the following syntax:
```  &:checked ~ ${Check} {  ...styles   } ```

My expectation is that this should behave exactly as if I were selecting the div by className:
```  &:checked ~ .class-name-of-my-div {  ...styles   } ```

The third point which is really what leads me to think it might be a bug is that the syntax works for pseudo-classes - i.e. the following works as I expect:
```  &:checked ~ ${Check}::before {  ...styles   } ```

It is possible that I have somehow misread the Docs and there is something I am required to add after `${Check}`... Apologies if this is the case. There are also fairly easy workarounds, given that in React we don't really need to use these Pseudo-classes, however thought I would draw this one to your attention in case it is indeed a bug 👍

**Comment by probablyup** [comment]
Could explain what the desired visual state is supposed to be? Having trouble following your example. It'd be great if it was as stripped-down as possible.

One general note: I noticed in the pen you have `Check` defined after it's used in `Input`.

**Comment by kitten** [comment]
Sorry, but this is barely a reproduction. It's just a bunch of code and we have unfortunately no idea of what you expect, what to do with the code, no idea whether you want us to change the HTML, no idea what you'd like to achieve...

Also, codepen might be what you prefer, but it makes this unnecessarily hard, since it's lacking ergonomics make this unnecessarily hard. Or maybe we just got too used to webpackbin and now codesandbox? :wink:

Either way, I'm sorry, but there comes a point and time where I need to point to the `ISSUE_TEMPLATE`: https://raw.githubusercontent.com/styled-components/styled-components/23d1d75/.github/ISSUE_TEMPLATE.md

Specifically the bug template that you unfortunately deleted:

```md
<!-- BUG TEMPLATE -->
## Version
styled-components: 2.2.4
babel-plugin-styled-components: 1.3.0
<!-- Please remove babel-plugin-styled-components if it's not applicable -->

## Reproduction

<!-- If you can't reproduce your bug, make sure to add details on how you've set up your project -->
https://www.webpackbin.com/bins/-KeeZCr0xKfutOfOujxN
https://codesandbox.io/s/rkmNRByE4

## Steps to reproduce

## Expected Behavior

## Actual Behavior
```

The last two points are info we need. As far as I can tell this seems to be working.

**Comment by frednomoon** [comment]
Yeah apologies, I have been caught out by `Check` being defined after it is used as @probablyup noticed. Today I have learnt something new about template literals. Cheers
