### ISSUE TITLE
Avoid duplication properties when extending component with common properties.

### ISSUE THREAD

**Issue by meefox** [styled-components/styled-components#1530]
As a simple example:
`
const Text = styled.div'margin-bottom: 5px';
`
`
const TextLong = Text.extend'margin-bottom: 10px';`

generates class with 2 properties:
`
.TextLong {
    margin-bottom: 5px;
    margin-bottom: 10px;
}
`

is it possible optimize extend to have only last property?
like: `.TextLong {margin-bottom: 10px}`

**Comment by kitten** [comment]
There's two things I can address in here, actually. The first is that `.extend` copies all rules. This has a simple reason: gzip can take care of deduplication, and it avoids us having to deal with potential specificity issues. It also makes the result more readable. However, we also support `styled(Text)` which creates two styledcomponents and two classes.

The other thing is that we currently can't easily deduplicate properties as we don't have a full parser.

But even if we had one, in the `styled(Text)` case we can't do much as with `.withComponent` the underlying component can always be changed. This is important because we ensure that: A) all classes are standalone, decoupled and isolated, and B) the specificity i.e. order of classes is guaranteed to be correct.

So all in all for several reasons, this won't be possible until we introduce a full parser again (longterm plans), and it won't actually yield any positive effects.

**Comment by kitten** [comment]
Closing since this has become stale
