### ISSUE TITLE
[babel-plugin] preprocess breaks pseudo selectors

### ISSUE THREAD

**Issue by oreqizer** [styled-components/styled-components#1559]
styled-components: 3.1.6
babel-plugin-styled-components: 1.5.0

## Reproduction

The `:focus` rule does not exist when using the `preprocess` option in `babel-plugin-styled-components`.

Example component:

```js
const Button = styled.button`
  width: 19px;
  height: 19px;
  cursor: pointer;

  &:focus {
    outline: none;
  }
`;
```

Babel plugin config:
* broken: `["styled-components", { ssr: true, preprocess: true }]`
* working: `["styled-components", { ssr: true }]`

## Steps to reproduce

See above

## Expected Behavior

`Button` should have a `:focus` fule

## Actual Behavior

`Button` does **not** have a `:focus` rule

**Comment by kitten** [comment]
Preprocess is obsolete and will be removed soon. It was an effort to test whether it is a viable technique to implement preprocessing, but it turned out that it wasn't.

Thanks for reporting it anyway :+1:

To others who find the issue, I'll leave a quote from the docs here:

> This is experimental and we don't yet know of all limitations and bugs! Consider this non-production ready for now. ⚠️

It'll most likely be marked a deprecated and removed soon
