### ISSUE TITLE
3.1.0 should have been a major (breaking) release

### ISSUE THREAD

**Issue by gausie** [styled-components/styled-components#1561]
We were duplicating our stylesheet into a separate document by getting its innerHTML and copying it over (whether this was a good idea or not!). The introduction of `insertRule` in 3.1.0 means that the stylesheet rules no longer appeared in text on the DOM, and thus our approach no longer worked.

This is not a huge problem, and made us fix something that wasn't ideal in the first place, but I think there is a strong argument that the DOM is part of the public API of styled-components.

This issue isn't intended super seriously but is worth keeping in mind!

**Comment by kitten** [comment]
This is neither an issue nor a feature request, so I'll label it as a discussion, however I'm sure this doesn't belong into our issue tracker, but maybe on Spectrum :wink:

You're basically using a hack, and both `insertRule` and a change in the stylesheet implementation that will land soon are implementation details. They're abstracted internally and not part of the public API.

This means that it's **not a breaking change**, since the public API won't be broken or changed in any way. Similarly the introduction of `insertRule` is an internal optimisation.

I'd be happy to find another solution with you, but generally, please don't rely on our internals behaving reliably the same across minor and major releases :wink:

**Comment by probablyup** [comment]
Going to go ahead and close this, since there's nothing actionable at this time.

**Comment by kitten** [comment]
@gausie as said before, feel free to ping me on Twitter or start a thread on Spectrum, which is both preferable to a thread here, so we can go through your problem in detail. I feel like the `StyleSheetManager`'s target could help you fix this, but I'd need to know a little more, especially since that API is not 100% reliable yet.
