### ISSUE TITLE
Possibility of custom handlers for templates

### ISSUE THREAD

**Issue by ryall** [styled-components/styled-components#1585]
I'd like to suggest a feature for allowing custom handlers within template literals, if it's possible. I haven't looked through the source so I'm not sure - but I believe something similar is already present to handle arrays/strings/managed objects etc.

# Example
Say we have a `Color` class, which implements various fancy manipulation functions and we want to use it in a component, we could do it something like the following:
```js
class Color {
  toCss() {
    return ...; // CSS safe color string
  }
  lighten() {}
  darken() {}
  ... // etc
}

const Component = styled.div`
  color: ${colors.red.toCss()};
  background-color: ${colors.red.darken(.5).toCss()};
`;
```
However, I propose it'd be cleaner and more flexible to be able to handle `toCss()` implicity, using a custom template handler:
```js
class Color {
  toCss() {
    return ...; // CSS safe color string
  }
  lighten() {}
  darken() {}
  ... // etc
}

const Component = styled.div`
  color: ${colors.red}; // Added directly, without toCss()
  background-color: ${colors.red.darken(.5)};
`;

const colorHandler = (value) => {
  if (value instanceof Color) {
    return value.toCss();
  }

  return value; // Return value as-is if it's not handled
};

registerCustomHandler(colorHandler); // Adds it into the styled-components handler registry
```

**Comment by mxstbr** [comment]
Not sure of the value here. Do you have an example of where this makes the usability 100x better?

**Comment by ryall** [comment]
Consider this as a light example. In reality this would save me typing `toCss()` hundreds of times and makes the code visually more concise. It also allows me to change the way objects are processed further down the line, with minimal changes.

I'm sure there are other examples where this would be useful. Maybe, for example, an abstract size unit that is converted to `px`, `em`, `pt` etc. depending on the view context of the app.

**Comment by kitten** [comment]
```js
export const colors = {
  black: Color('#000000')
  /* ... */
};

export type ColorName = $Keys<typeof colors>;

type ColorOptions = {
  opacity?: number,
  luminance?: number,
  whiten?: number,
  blacken?: number
};

export const color = (name: ColorName, opts: ColorOptions = {}) => {
  let x = colors[name];
  if (opts.opacity !== undefined) x = x.opacity(opts.opacity);
  if (opts.luminance && opts.luminance > 0) x = x.lighten(opts.luminance);
  if (opts.luminance && opts.luminance < 0) x = x.darken(-1 * opts.luminance);
  if (opts.whiten) x = x.whiten(opts.whiten);
  if (opts.blacken) x = x.blacken(opts.blacken);
  return x.toString();
};
```

This is what I have in one project for a similar purpose. I'd really recommend this approach.

However, it's also possible create other helpers, say:

```js
const color = (name: ColorName, f: Function) => theme => f(theme.colors[name]).toCss()
```

Which would work in your case, since then you could do:

```js
import color from './colorHelpers' // what's written above

css`
  color: ${color('red', x => x.darken(0.3))}
`
```

What I basically would like to say is, stay functional and try to embrace this flow. I'm sure everything will turn out to be quite solvable with what we currently have, without a concept of handlers :wink:

I'd be happy to consider any kind of example that you might have to see if I can come up with patterns for all of them :+1:

**Comment by ryall** [comment]
Thanks @kitten - the solution is reasonable but still is less dynamic and requires more effort than simply supplying values in whatever format and handing them while compiling the stylesheet. For one, it breaks intellisense having to supply a string instead of a value. I see you're using TypeScript in your example, which would probably list the keys, but in vanilla JS the color names would need to be remembered or looked up.

The issue here isn't a **lack** of a solution but of the possibly of adding a **cleaner** solution, and additionally, more flexibility to templates. I'm sure there are more complex use cases than we discuss here.

For example, in general, I believe it would be easier to integrate with third-party libraries through handlers rather than adding a wrapper function to every single usage to ensure data is output in the correct format. Tagged template literals are pretty much designed to allow input handlers, so why not expose this power.

**Comment by kitten** [comment]
@ryall That's the point though; We are casting to a string either way, so it won't simply make sense to introduce scalar-type values. It just doesn't hold any intrinsic value for styled-components imho

I don't feel like this would be cleaner; The problem is that this would have to introduce a huge API surface, and we're fans of keeping it simple.

So if you can create a function that does this casting for you, be it with a type system or not, because my example above comes down to a similar effect as your handlers, then that's a simpler API and has the same effect. If you'd be writing the handler, I'm not sure whether it'd be shorter than the above. It'd also add a significant overhead and complexity to our style generation.

> I believe it would be easier to integrate with third-party libraries through handlers rather than adding a wrapper function to every single usage to ensure data is output in the correct format

If you use themes already and want to integrate some value, then wrapping it in a helper function ends up having no added complexity imho :wink: Whether you call it a handler or an interpolation, I'm sure it comes down to the same.

That being said, since we always cast to a string, we could add some explicit support for `valueOf()` on objects being casted to interpolations.

cc @mxstbr: The above would add little to no overhead or added complexity, but a lot of libraries could support this easily.

It'd be as simple as calling `obj.valueOf()` when `obj.valueOf() !== obj`

**Comment by ryall** [comment]
Fair enough :)

`valueOf()` would be a great alternative and I'd be totally happy with that.

**Comment by mxstbr** [comment]
Doesn't really seem worth it imo, I'm still not quite sure of the benefit of this. We should have a RFC process huh...

**Comment by btpoe** [comment]
@ryall if you implement a `.toString()` on your class / object / function, it should do what you're asking for.

**Comment by ryall** [comment]
@btpoe Thanks, will give it a go :)

**Comment by ryall** [comment]
Actually I had tried that. Realised the problem was with TS being too restrictive
