### ISSUE TITLE
Dynamic component tag without creating new styled components

### ISSUE THREAD

**Issue by lazopm** [styled-components/styled-components#1616]
We have components that needs to have their html tag set dynamically based on props/children type.
We are concerned about potential memory leaks from creating styled components in the render method.

For example we have a heading component that needs to set its `h<level>` based on a prop.
Another example is a component that takes on the type of its only child.

The first solution I  thought about was caching the results of `.withComponent` as we go and then reusing them.
Second solution would be to just create all the possible components before rendering.

Has anyone run into this? Any better solutions?

**Comment by kitten** [comment]
I have some rather untested code on CodeSandbox that I wrote because of ppl asking for it :) https://codesandbox.io/s/n5nRmZBv4

I don’t think it’s a good idea to create a whole lot of tags before hand as those can really be a lot after a while. So try to avoid that.

Also, consider making more separate components if possible. Small and specialised styledcomponents definitely beat larger ones in maintainability if you have a good theme ;)

**Comment by maximus-lynn** [comment]
Be great to see this incorporated into the package. You say that we should be creating smaller components however I have a use case for a button being a span within an anchor.
