### ISSUE TITLE
Contextual selectors processed to BEM

### ISSUE THREAD

**Issue by rodocite** [styled-components/styled-components#1630]
Since contextual selectors are allowed, would it be a feasible feature to transform the contextual selectors into standard BEM?

So something like this:
```js
const Element = styled.div`
  & + p {
    color: red;
  }
`

const Block = () => (
    <div>
      <Element />
      <p>Hello</p>
    </div>
  )
```

Would render something like this:
```html
  <div class="Block-[hash]">
    <div class="Block__Element-[hash]" />
    <p class="Block__Element__p-[hash]">Hello</p>
  </div>
```

This is a contrived example using the adjacent-sibling selector, but I was thinking it would improve performance when using more common contextual selectors such as child, nested, parent-child, etc.

Issues I see are:

1. People probably don't use contextual selectors most of the time.
2. There might be problems attaching the generated class in SSR or if the element to be selected is being overridden externally.
3. It might encourage unmaintainable code.

**Comment by kitten** [comment]
No, I don’t see it as being a possible feature.

The element you’re targeting is outside of our reach since it’s not part of what the component renders.

In the styles-component paradigm you’d create another StyledComponent representing that p tag, at which point you could use a reverse selector instead.

https://www.styled-components.com/docs/advanced#referring-to-other-components

I don’t think we should try to make this into something it isn’t. And clearly BEM is great in a situation where you’d like to passively control the styling and relationship of elements and their visual state. But in the context of components you have great ways to couple these visual states to actual state and bind epements together.

So I’m not sure whether it’d make sense. That being said there was an issue where someone experimented with a more BEM-like approach, however I don’t see this having a lot of positive effects on apps
