### ISSUE TITLE
onInvalid is missing in validAttr regex

### ISSUE THREAD

**Issue by SlootSantos** [styled-components/styled-components#1666]
Hey guys,

when using _styled.input_ and then passing an _onInvalid_ handler to the component this handler is never actually called. 
Tried the same with _onBlur, onKeyDown_ and these work.

## System:
 - OS: macOS High Sierra 10.13.4
 - CPU: x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
 - Free Memory: 263.92 MB
 - Total Memory: 16.00 GB
 - Shell: /bin/bash - 3.2.57
## Binaries:
 - Node: 9.7.1
 - Yarn: 1.5.1
 - npm: 5.6.0
 - Watchman: Not Found
### styled-components:
 - wanted: ~3.2.1
 - installed: 3.2.3

## Steps to reproduce
- create styled input component like: 
```
import styled from 'styled-components';

export const TextInput = styled.input`
  color: green;
`;
```

- add onInvalid handler to component
```
<TextInput
     {...props}
      onInvalid={() => console.log('foo')}
      onBlur={() => console.log('bar')}
/>
```

- render component to DOM
- type in input field

## Expected Behavior
- `foo` and `bar` should be logged
## Actual Behavior
- see that only `bar` is logged

**Comment by kitten** [comment]
We don't do anything to your props and will almost always just pass them through (`className` & `innerRef` are exceptions) so this is 100% not a bug with styled-components. You could try to create a reproduction and submit it here, but it's more likely that you'll receive help on Stackoverflow or Spectrum, since this is not specific to styled-components.

I suspect that this is not an event on inputs with any type, so I'd suggest that you should check the input type and what the invalid event shape maybe.

**Comment by SlootSantos** [comment]
@kitten are you sure? just had a look at
https://github.com/styled-components/styled-components/blob/master/src/utils/validAttr.js
and the regex is missing onInvalid.. but it has onBlur and onKeyDown

**Comment by kitten** [comment]
<img width="653" alt="screen shot 2018-04-06 at 16 26 03" src="https://user-images.githubusercontent.com/2041385/38429755-3f5cde46-39b7-11e8-809e-c72a56aba342.png">

**Comment by kitten** [comment]
<img width="776" alt="screen shot 2018-04-06 at 16 26 45" src="https://user-images.githubusercontent.com/2041385/38429786-53766d0c-39b7-11e8-9595-3aa67b7c9745.png">

(Edit: wrong image ugh, was missing the second command)

Seems that you're right. Sorry, I made the assumption that the comment above matches the actual content there. Mind fixing this up for us please? Otherwise I'll try to fix it asap

**Comment by SlootSantos** [comment]
@kitten great! I'll open a PR!
Glad we found it so fast!! 
Thank you :)

**Comment by SlootSantos** [comment]
https://github.com/styled-components/styled-components/pull/1668
