### ISSUE TITLE
Question module made with styled peerDependencies or dependencies ?

### ISSUE THREAD

**Issue by kopax** [styled-components/styled-components#1669]
I just want to make sure, but if we make a module that depends on styled-components. 
Should it be a peerDependencies or a dependencies ?
peerDependencies should be used if the dependencies needs to be singleton (like redux)
Does styled-components needs to be present only one time and If yes, for what feature ?

**Comment by kitten** [comment]
https://www.styled-components.com/docs/faqs#i-am-a-library-author-should-i-bundle-styledcomponents-with-my-library

keeping it a peerDependency is recommended while making sure that styled-components is only bundled once. This is due to our StyleSheet logic and the rather destructive rehydration logic.

**Comment by kopax** [comment]
> This is due to our StyleSheet logic and the rather destructive rehydration logic.

Thanks for the reply. What is the rehydration? If possible, I would like to get further details (technically speaking).
