### ISSUE TITLE
Error when Build Project - Error on Stylis

### ISSUE THREAD

**Issue by EwertonFontes** [styled-components/styled-components#1672]
I am getting an error when I try to build on development mode, the return messsage is about stylis! I don't know how to solve this if someone may help me! Thanks

==ERROR==
Module not found: Error: Can't resolve 'stylis' in '/path/node_modules/styled-components/dist'

styled-component version: 3.2.5,
react version:  16.1.0

**Comment by kitten** [comment]
Can you give us more infos about your environment please? How and where did you install it, what is your toolchain and build pipeline, etc? Since this is not a bug but a usage issue, we'll need more information to help you :wink:

The issue template has a command you can run to gather some information about your environment automatically: https://raw.githubusercontent.com/styled-components/styled-components/master/.github/ISSUE_TEMPLATE.md

**Comment by EwertonFontes** [comment]
To build the project I'm using CI/CD on Codeship, when I build on local machine it's ok! 
But when I build on Codeship I'm getting that error message.

==SOME Information about the enviroment ==
## System:
- OS: Linux 4.4
- CPU: x64 Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz
- Free Memory: 152.44 GB
- Total Memory: 240.09 GB
- Shell: /bin/bash - 4.3.11
## Binaries:
- Node: 8.1.3
- Yarn: 1.5.1
- npm: 5.0.3
- Watchman: Not Found
## npmPackages:
### babel-plugin-styled-components:
- wanted: ^1.5.1
- installed: 1.5.1

**Comment by EwertonFontes** [comment]
Yeah styled-component is a dependency on my app and the stylis is a dependency on style-components

##yarn list styled-components
devpleno@0.1.0 /Users/tuliofaria/Desktop/projetos/devpleno-admin
└── styled-components@3.2.5 

## yarn list stylis
devpleno@0.1.0 /Users/tuliofaria/Desktop/projetos/devpleno-admin
└─┬ styled-components@3.2.5
  └── stylis@3.5.0

Any suggest about this?

**Comment by kitten** [comment]
@EwertonFontes these however are dependencies installed on your local device where everything works fine, right? Can you somehow get some details on what Codeship has installed and set up. I myself am not familiar with Codeship, so I'm not sure if I can guide you through the process perfectly

**Comment by EwertonFontes** [comment]
Ok.
This is the result on Codeship when list.

## npm list styled-components
devpleno@0.1.0 /home/rof/src/bitbucket.org/wedevideas/devpleno-admin
styled-components@3.2.5 

## npm list stylis
devpleno@0.1.0 /home/rof/src/bitbucket.org/wedevideas/devpleno-admin
styled-components@3.2.5
stylis@3.5.0 

It was working on my last successfully build two months ago, but I needed to change one thing and since this the build stoped on stylis.
Part of the process on Codeship is basically to check the code repository on Git and execute the environment configuration.

nvm install 8.1.3
npm update
npm install
npm run build

**Comment by probablyup** [comment]
Going to close this as it's been inactive for some time. Please feel free to re-open if it's still an issue for you and there's a reproduction we can look at.

**Comment by sadsa** [comment]
@probablyup - Can we please re-open this bug? I'm experiencing this same issue when installing style-components via PNPM and Parcel. Perhaps this has something to do with the way stylis is being imported i.e. `stylis/stylis.min`. I'm not sure how Parcel resolves this.

**Comment by sdalonzo** [comment]
@probablyup @sadsa me too. PNPM as well, encountered this in jest while evaluating the rushjs monorepo tool.

```
  ● Test suite failed to run

    Cannot find module 'stylis/stylis.min' from 'styled-components.cjs.js'
```

**Comment by mwill8886** [comment]
@probablyup getting the same issue except im installing packages through Azure. For me it's happening on a local package that has styled-components as a dependency. 

If I install styled-components directly from the public npm registry it works fine. But if I'm installing from our Azure registry with the npm registry upstream it cannot find hte stylis module.

**Comment by probablyup** [comment]
Sounds like an azure problem ¯\_(ツ)_/¯

**Comment by newtriks** [comment]
@probablyup similar issues using `pnpm` and `styled-components` with both `stylis` and also `shallow-equal`:

> `node_modules/styled-components/dist/styled-components.browser.esm.js:1:237: Cannot resolve dependency 'shallowequal'`

**Comment by kitten** [comment]
@newtriks Please don't just leave comments for things you'd like to ask or are searching resolution for in old issues (this one is *over one year old*) That being said, I believe this may be an issue with some resolution or installation issue on your end. If you check the `package.json` file manually (in the repo, and cross compare it with your local one) you can clearly see that the dependencies you mentioned are listed correctly: https://github.com/styled-components/styled-components/blob/1dbb82cf6b5f11242031dd2a5b7e6abb7798a760/packages/styled-components/package.json#L65-L76

That being said, this is also a build tool warning, and you're hinting at `pnpm`, but have you checked whether the packages are installed already?

Anyway, this may be a good question for Stack Overflow / Spectrum, since it's not specifically an issue with styled-components 😅
