### ISSUE TITLE
How to use babel-plugin-styled-components with create-react-app?

### ISSUE THREAD

**Issue by kopax** [styled-components/styled-components#1679]
I am using `create-react-app` and so far we managed not to eject. 

Considering we want to keep it that way, is it possible to optimize our css using `babel-plugin-styled-components`?

**Comment by kitten** [comment]
There'd be react-app-rewired:

- https://github.com/timarney/react-app-rewired
- https://github.com/withspectrum/react-app-rewire-styled-components

**Comment by probablyup** [comment]
Going to close this with @kitten's response. Didn't know about rewired, pretty cool 😀

**Comment by kopax** [comment]
is the plugin from @mxstbr working already ? that look a good tool. Ill have a look

**Comment by moshfeu** [comment]
> There is babel-macro now https://www.styled-components.com/docs/tooling#babel-macro

Is there an option to use macro only in development?

**Comment by cmacdonnacha** [comment]
This is great. Are there any performance implications to using `import styled from 'styled-components/macro';` instead of `import styled from 'styled-components';`.

When I run a production build the component names are still displayed. 

![image](https://user-images.githubusercontent.com/9777763/77765985-f473dc00-7036-11ea-8617-39f90e400433.png)

Personally I don't mind this, just wondering if there's a downside?
