### ISSUE TITLE
Bug with ThemeProvider with only text inside

### ISSUE THREAD

**Issue by robrkerr** [styled-components/styled-components#168]
I've found a bug with ThemeProvider. If you only have text inside the ThemeProvider element (like this: ```<ThemeProvider theme={theme}>hello</ThemeProvider>``` then you get this error:
```
invariant.js:38 Uncaught Error: React.Children.only expected to receive a single React element child.(…)
```

This is because of this check inside ThemeProvider.js:
```js
  render() {
    if (!this.props.children) {
      return null
    }
    return React.Children.only(this.props.children)
  }
```

The `React.Children.only` function appears to be working as intending - according to this thread: https://github.com/facebook/react/issues/1104, but it seems to me that this is not the appropriate check for this case. Is the check needed at all? Does it matter if there are multiple children inside a ThemeProvider? If so, then maybe this should just be extended to also allow a string?

**Comment by mxstbr** [comment]
No, this is actually working exactly as intended. The problem is that the `ThemeProvider` doesn't return any valid DOM nodes, meaning potentially you could return two react components as the root of the app, which breaks everything:

```JS
// This is valid syntax...
ReactDOM.render(
  <ThemeProvider>
    <div />
    <div />
  </ThemeProvider>
)
```

this compiles down to this, essentially:

```JS
// ...but it's totally invalid code
ReactDOM.render(
  <div />
  <div />
)
```

which isn't something that React supports right now.

By having that check in there, we avoid people getting cryptic error messages because React complains about something!

**Comment by geelen** [comment]
Damn. I don't think there's any way to return a string from a `render` method is there? It's only valid as an argument to `createElement` right?

**Comment by mxstbr** [comment]
Yeah, this is working as intended, no way around it. You'll need to wrap that text into some element, probably a `<p>`
