### ISSUE TITLE
Different components defined with the same display name end up having same per-component class name

### ISSUE THREAD

**Issue by Igorbek** [styled-components/styled-components#1715]
## Environment

`styled-components@3.2.6`

## Reproduction

```jsx
const Named1 = styled.div.withConfig({ displayName: 'Name' })`
  color: blue;
`;
const Named2 = styled.div.withConfig({ displayName: 'Name' }) `
  color: red;
`;
```

outputs

```html
<div class="Name-liQCRp iWZgJe">Named1</div>
<div class="Name-liQCRp fGgVaz">Named2</div>
<!--        ^^^^^^^^^^^ same per-component class name -->
```

Code: https://codesandbox.io/s/92o6vrym2w

## Expected Behavior

I expect that even if `displayName` is the same, two components should have different class names like `Name-ibxdXY` and `Name-RefOD`.

## Actual Behavior

Both components have the same per-component class name `Name-liQCRp`.

## Note

The bug was initially filed to `typescript-plugin-styled-components` https://github.com/Igorbek/typescript-plugin-styled-components/issues/10
Please see it for rationale

**Comment by probablyup** [comment]
Hmm, I'm wondering if we should prefer `Component.name` over `Component.displayName` since `.name` is more likely to be unique due to how JS handles variables. Thoughts @kitten?

**Comment by probablyup** [comment]
@Igorbek are you using the babel plugin by chance? The way it generates stable hashes is far superior to the library on its own.

**Comment by Igorbek** [comment]
I am the author of another styled-component plugin, the one that for TypeScript. This issue was originally filed there: https://github.com/Igorbek/typescript-plugin-styled-components/issues/10 and the reporter also opened issue in babel plagin repo: https://github.com/styled-components/babel-plugin-styled-components/issues/141

I think, having a `displayName` defined should not affect on the class names generated as it is purely for debugging/development experience purposes.

To me, the hash should be unique for each component (class, not instance), so it doesn't matter what is the name of it. It just a unique hash.

In my example, if I remove `withConfig`, the following class names are generated:
```html
<!-- without displayName -->
<div class="sc-bdVaJa lpjCXg">Named1</div>
<div class="sc-bwzfXH bukUYK">Named2</div>
<!--           ^^^^^^ different hashes -->
<!--        ^^ same prefix -->

<!-- without displayName -->
<div class="Name-liQCRp iWZgJe">Named1</div>
<div class="Name-liQCRp fGgVaz">Named2</div>
<!--             ^^^^^^ same hashes -->
<!--        ^^^^ same prefix -->
```

So I believe we should only change prefix from `sc` to whatever defined in `displayName`.

Also, regarding your point about `Component.name` vs `Component.displayName`, I don't think it is going to work either. If you have different scopes or modules, your names can be exactly the same and even babel would not try to make them unique. And in general, we should not rely on the fact that users downlevel their nice ES.next into current JS. The new features will be run natively very soon, as does modules in Chrome now.

**Comment by probablyup** [comment]
@Igorbek ok so I'm assuming since you're using typescript, then the babel plugin is not involved. We don't pay any attention to displayName via the babel plugin since the [hashing rewrite](https://github.com/styled-components/babel-plugin-styled-components/pull/112), other than as decoration for debugging when the displayName option is set to true (default).

In terms of creating the hash without babel, it does seem there is a bug in the falsy branch of this ternary https://github.com/styled-components/styled-components/blob/36345f7fd484bd931806f510b22a7b40e8f788d1/src/models/StyledComponent.js#L260-L263

I believe it should honor `options.componentId` and fall back to the generated `componentId` if the former is not available.

I think the fallback `generateId` static function could also be made more intelligent: https://github.com/styled-components/styled-components/blob/36345f7fd484bd931806f510b22a7b40e8f788d1/src/models/StyledComponent.js#L30-L54

It looks like if a displayName is provided, it is assumed that it is unique. If that's not a stable guarantee, we should just always do the n+1 thing.
