### ISSUE TITLE
Can external project use the same component?

### ISSUE THREAD

**Issue by titellergetlinks** [styled-components/styled-components#1719]
I have 2 project (core project and external project) and my styled-components stay in core project
How can i use the same styled-components in core project from external project.

**Comment by mvasin** [comment]
Do you own both? If you do, export a styled component in one project, npm-depend on it in another project and import the exported component there.

If you don't own the external project and the styled component is not exported, ask the project owner to export. If that's not going to happen, resort to copying and pasting.

**Comment by sylvhama** [comment]
You could use nwb in order to develop [React Components and Libraries](https://github.com/insin/nwb/blob/master/docs/guides/ReactComponents.md#developing-react-components-and-libraries-with-nwb). You could archive the same goal with [neutrino](https://neutrino.js.org/packages/react-components/) as well. 

1. Develop your components in a separate project (your future library)
2. Test it locally via [npm link](https://docs.npmjs.com/cli/link)
3. Publish it on npm
4. npm install it in your main app
5. then you will be able to do `import { StyledComponent } from 'myLibrary;'`

**Comment by probablyup** [comment]
@titellergetlinks This is a great question for stack overflow, so going to close this as it isn't a bug or feature request.

To answer your question though, I'd consider a single repo / multiple package setup if you find your projects have heavy reuse. Perhaps look into a tool like lerna.
