### ISSUE TITLE
Layout children from parent (React Native)

### ISSUE THREAD

**Issue by kruyvanna** [styled-components/styled-components#1741]
## Environment

Environment:
  OS: macOS High Sierra 10.13.4
  Node: 8.9.1
  Yarn: 1.6.0
  npm: 6.0.1
  Watchman: 4.9.0
  Xcode: Xcode 9.3.1 Build version 9E501
  Android Studio: 3.1 AI-173.4720617

## Reproduction

https://github.com/kruyvanna/styled-components-layout-child-from-parent-bug

## Steps to reproduce
```javascript

import React from 'react'
import styled from 'styled-components'

const Container = styled.View`
  flex: 1;
  background: #ddd;
  padding-top: 50px;
  > ${Child1} {
    margin-bottom: 30px;
    background: red;
  }
`

const Child1 = styled.Text`
  width: 100%;
`

const Child2 = styled.Text`
  width: 80%;
`

export default class App extends React.Component {
  render() {
    return (
      <Container>
        <Child1>Child 1</Child1>
        <Child2>Child 2</Child2>
      </Container>
    )
  }
}

```
## Expected Behavior
Child margin and background color applied

## Actual Behavior
Child margin and background color not applied

**Comment by sonaye** [comment]
I don't think you can do this in RN, where the concept of a child selector `>` doesn't make any sense to the style system there. Similarly, I would't expect pseudo-classes to work either.

Try this:

```js
const Container = styled.View`
  background: #ddd;
  flex: 1;
  padding-top: 50px;
`;

const Children = Container.withComponent(Text).extend`
  background: red;
  margin-bottom: 30px;
`;

const Child1 = Children.extend`
  width: 100%;
`;

const Child2 = Children.extend`
  width: 80%;
`;
```

**Comment by kitten** [comment]
@sonaye is right.

It's possible tbh, but would introduce some major overhead for little gain. The ecosystem is doing pretty well without selectors (although pseudo selectors are quite nice) and imho everyone's better off, since that means that styles are always 100% predictable and interpsectable. We even recommend the **reverse** child selector (childreferring to itself via a parent) since that's more obvious in the styled-components docs.

We also make a point of not introducing **any** special syntax on web, and we've also decided against it before on React Native. It introduces significant maintenance overhead for us, and is essentially replaceable on the user-level with libraries or structural changes, as is the case with either CSS on Web, or the usual RN styling approach.

Hope this makes sense :+1:

**Comment by probablyup** [comment]
Would this also not have worked due to the order of declared variables? `Child1` is declared after `Container`, but used in a non-function interpolation so I think it would have needed to be assigned at declaration time.

**Comment by kruyvanna** [comment]
@probablyup Tried it. Doesn't work.
