### ISSUE TITLE
Styling based on state instead of props?

### ISSUE THREAD

**Issue by ThomasSkinner** [styled-components/styled-components#1746]
I want to style a component based on it's state (instead of props), which changes with clicking.

However, I don't see any way to do this without pulling state up into a wrapper and passing the down the state to props. Which seems needless. Is there a way to access state with styled-components?

I would like to do something like this:

const styledDiv = styled.div`
  background-color: ${(state) => state.x};
`

**Comment by sonaye** [comment]
Why not [lift the state up](https://reactjs.org/docs/lifting-state-up.html)?

**Comment by sonaye** [comment]
Sorry, just saw that you already mentioned that. It's just the first straightforward idea that popped into my head, plus it's generally a good practice.

**Comment by Keraito** [comment]
Hey @ThomasSkinner, could you provide a more concrete example, like how you have defined the component + it's styled version, and how you use that styled component? From what I understand from SC, if you're trying to define your styled component based on the state of the component, the scope at which you define your styled component might not be optimal. Something similar to https://github.com/styled-components/styled-components/issues/431#issuecomment-276048490, but a more elaborate example of your case will most likely make it easier to help you.

**Comment by kitten** [comment]
Yea, the state needs to be lifted up. Generally this is a conceptual issue/conflict between what styled-components is supposed to be used for (as in good at) and what you're trying to achieve.

If I'm understanding this correctly you'd like to maximise the value of these components, but essentially what you're asking for is a little state machine in each `StyledComponent`. That essentially would make them just components, as in `React.Component`, and we can't get any better than actually using that API, i.e. just lifting the state up.

You'd be mixing styling and UI state directly. This means that it's going to quickly get really non-obvious what your component is doing. You could use recompose's `withState`. But I wouldn't advise that, since you rarely need state in a single component.

You're also blocking your path to refactor. `StyledComponent`s are excellent at the leaf-level where they replace elements. If you are not careful what happens above them, or have anything going on below them, it'd be harder to refactor them later to include more elements in your "conceptual" component. For instance, imagine a button that later on needs to include icons.

**Comment by perenstrom** [comment]
I came to this issue from googling on my specific problem. And realised I was asking the question wrong, or rather did not understand what I was doing.

I had a basic toggle with a boolean in the state. Since I wrote both the styled component and the react component class in the same file. I got confused.

The (now in retrospect, obvious) solution was using props in the styled component as usual, and passing the state to the styled component. Perhaps this helps someone with my problem as well, stumbling on this question.

```
import React from 'react';
import styled from 'styled-components';

const StyledProduct = styled.div`
  background-color: ${(props) => props.big ? "red" : "green"};
`;

class ReactComponent extends React.Component {
  constructor(props){
    super(props);

    this.handleClick = this.handleClick.bind(this);

    this.state = {
      boolVar: false
    };
  }

  handleClick() {
    const newBoolVarStatus = !this.state.boolVar;
    this.setState({boolVar: newBoolVarStatus});
  }

  render() {
    return (
      <StyledProduct onClick={this.handleClick} boolVar={this.state.boolVar} />
    );
  }
}

export default ReactComponent;
```

**Comment by dfmartin** [comment]
@perenstrom :  Forgive me if I'm wrong, but I believe your prop inside of StyledProduct would be boolVar instead of big.

```
const StyledProduct = styled.div`
  background-color: ${(props) => props.boolVar ? "red" : "green"};
`;
```

Just to help others that come across this thread.  And your answer was what came to mind when I read the original question.  Seems like what is really needed in that situation.

**Comment by perenstrom** [comment]
@dfmartin Thanks for the correction, I've edited my comment. I was apparently not thorough enough in generalising my solution.

**Comment by bystrovo** [comment]
I am having the same dilemma. Concrete example:
A Copy (HOC) that renders children and adds a little hover info with CSS that says: "Copy". onClick it copies some text into clipboard. 
I would like the component to briefly show "Copied" when user clicks and then go back to normal.
How would I do this without using internal state here?

```
export styled(Component)(props => `
  position: relative;

  &:after {
    content: ${(state.tempText || 'copy')};
    opacity: 0;
    display: none;
    transition: 0.2s opacity ease-in-out, 0.2s display ease-in-out .2s;


  }
  &:hover:after {
      opacity: 1; 
      display: block;
    }
  }
`);
```

**Comment by mxstbr** [comment]
The exact same way, by wrapping it in a class component! For example, something like this:

```JS
const CopyTooltip = styled(Component)`
  position: relative;

  &:after {
    content: ${props => this.props.text};
    opacity: 0;
    display: none;
    transition: 0.2s opacity ease-in-out, 0.2s display ease-in-out .2s;
  }

  &:hover:after {
    opacity: 1; 
    display: block;
  }
`;

export default class Copy extends React.Component {
  state = { clicked: false };

  onClick = () => {
    this.setState(prev => ({ clicked: !prev.clicked }));

    setTimeout(() => {
      this.setState(prev => ({ clicked: !prev.clicked }));
    }, 1000);
  }

  render() {
    return (
      <CopyTooltip onClick={this.onClick} text={this.state.clicked ? 'Copied!' : 'Copy'} />
    )
  }
}
```
