### ISSUE TITLE
[TypeScript] collectStyles method from ServerStyleSheet causes type error

### ISSUE THREAD

**Issue by rroslaniec** [styled-components/styled-components#1794]
## Environment
```
"styled-components": "3.3.2",
"typescript": "2.9.1",
```
## Reproduction
```
  const sheet = new ServerStyleSheet();
  const foo = renderToString(sheet.collectStyles(<div />));
```
## Expected Behavior
Rendering element with collectStyles method from ServerStyleSheet should not causing type error
## Actual Behavior
![image](https://user-images.githubusercontent.com/3448993/40976225-bb1f88c2-68cd-11e8-9ed5-eec594594059.png)

**Comment by probablyup** [comment]
cc @styled-components/typers

**Comment by Igorbek** [comment]
The error message says `ReactElement<StylesheetComponentProps> is not assignable to parameter of type `ReactElement<any>`, which does not make sense since it is assignable.
I have verified this and it should work. I suspect your `renderToString` and `styled-components` are referring to different versions of `@types/react`. Check your packages graph.

**Comment by probablyup** [comment]
@rroslaniec you'd use this to figure it out:

```bash
npm ls @typed/react
```

There should be one main version at the top and any other ones further should should say "deduped".

**Comment by rroslaniec** [comment]
yes, problem was in two versions of @types/react. Now everything is fine.
