### ISSUE TITLE
injectGlobal (Typescript) Property 'includes' is missing in type 

### ISSUE THREAD

**Issue by serranoarevalo** [styled-components/styled-components#1863]
## System:
 - OS: macOS High Sierra 10.13.6
 - CPU: x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
 - Memory: 6.47 GB / 16.00 GB
 - Shell: 5.3 - /bin/zsh
## Binaries:
 - Node: 10.7.0 - /usr/local/bin/node
 - npm: 6.2.0 - /usr/local/bin/npm
## npmPackages:
 - babel-plugin-styled-components: ^1.5.1 => 1.5.1 
 - styled-components: ^3.3.3 => 3.3.3 

## Reproduction

Just set up typescript and styled components and I'm getting this error:

``` Property 'includes' is missing in type '(props: any) => any'.```

When I do this:

<img width="787" alt="screen shot 2018-07-25 at 12 00 09 am" src="https://user-images.githubusercontent.com/3612017/43165890-c025c060-8f9d-11e8-8d63-55e48e89b9d7.png">

This is the full copy of the error:

```
Argument of type '(props: any) => any' is not assignable to parameter of type 'SimpleInterpolation'.
  Type '(props: any) => any' is not assignable to type 'ReadonlyArray<string | number | false | Styles | StyledComponentClass<any, any, any> | ReadonlyAr...'.
    Property 'includes' is missing in type '(props: any) => any'.

```

**Comment by kitten** [comment]
The error here is a little cryptic unfortunately, but the actual message is telling you that the interpolation type is not what is expected.

This is because functional interpolations don’t make sense in injectGlobal. It’s outside of React and any other context, so it can’t access the theme or props via the usual function arguments. :)

We’re currently working on a Global style component as an alternative.

But for the purposes of basic global styles and some resets I’d recommend to have a good old and small CSS file alongside it.

Hope this helps :)

**Comment by serranoarevalo** [comment]
Got it! Thanks!
