### ISSUE TITLE
TS: set sensible default value in ThemedBaseStyledInterface

### ISSUE THREAD

**Issue by rifler** [styled-components/styled-components#1920]
In some issue I've found a way to use SC with props, e.g.
```
const MenuItem = styled<{ isHighlighted: boolean }, any>(BaseMenuItem)`
	${(p) => p.isHighlighted && activeBg};
`;
```

I don't fully understand the details of typings' implementation, but I suppose that typing `any` in each component definition is redundant. I've tried to add default `any` value to second generic argument and it works for me
https://github.com/styled-components/styled-components/blob/f401eda35ef16065509ea8a7375290fb8b5858a6/typings/styled-components.d.ts#L96

What do you think about it? I can make a PR

**Comment by probablyup** [comment]
Just as a heads up, we are not accepting non-criticals PRs anymore for styled-components 3.0 since 4.0 will be in beta shortly.

In terms of TS, we are [moving the types to DefinitelyTyped](https://github.com/styled-components/styled-components/issues/1778). I won't close this for the moment, but this issue will likely need to move to the other repository.

**Comment by probablyup** [comment]
Hey folks, TS typings for styled-components have been moved to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped), so please feel free to move your issue there where you'll receive better community support.
