### ISSUE TITLE
.withComponent doesn't inherit styles from extending with styled(Component)

### ISSUE THREAD

**Issue by ppozniak** [styled-components/styled-components#1956]
## Reproduction
https://codesandbox.io/s/8ln12qzo68

## Steps to reproduce
1. Create styled component
2. Extend it to another component without using `.extend`. So use `styled(Component)` instead.
3. Create third component that would use the second one with `.withComponent` method.

## Expected Behavior
The third component should have all the stylings (from the first one and the second)

## Actual Behavior
The third component gets styles only from the second one.

_P.S sorry if the title is confusing, naming stuff is hard_
Related to #1546

**Comment by probablyup** [comment]
`withComponent` switches out the underlying component, so the first one that you applied overrides to with the `styled(StyledComponent)` wrapper is not the wrapping target of the second component anymore if that makes sense.

In cases like this, I actually recommend using a polymorphic component pattern because it's more flexible:

```jsx
class Polymorph extends React.Component {
    static propTypes = {
        as: 'div',
    };

    static defaultProps = {
        as: 'div',
    };

    render() {
        const { as: Representation, ...props } = this.props;

        return <Representation {...props} />;
    }
}
```

Then you can do something like this:

```jsx
const Base = styled(Polymorph)`
  color: green;
`

const Override = styled(Base)`
  color: red;
`

<Override as="button">Hi</Override>
<Override as={Link}>Hi</Override>
```

**Comment by ppozniak** [comment]
Wait, so with deprecation of `.extend` that will be preferred way to do this? To be honest it doesn't make much sense.

**Comment by probablyup** [comment]
`.extend` made a full copy of all styles on a component, whereas `styled(StyledComponent)` layers more styles on top of what you pass into it. That's why `withComponent` preserved the styles of component 1 from your original example but the `styled(Component1).withComponent('div')` does not.

It all works fine, just need to adjust your understanding of how the API fits together. I could see about adding the polymorphism as a first-class part of the API though. That might make things easier...

**Comment by donifer** [comment]
I know its not directly related to `styled-components` but is there a way to Type (ts) the Polymorph class? I'm trying to do a `button` and `a` but with `a` typescript is complaining about the `href` attribute.

**Comment by codylawson** [comment]
@probablyup The docs show that `as` is v4, is it accurate to say it's necessary to hold off on refactoring code that uses `withComponent` + `extend` until that release?

**Comment by probablyup** [comment]
@codylawson you can definitely move off of "extend" now, as that's been deprecated a while.

Anything related to "withComponent" though, yeah I'd wait for v4 release or switch to the beta. It should be pretty stable.
