### ISSUE TITLE
How create list with sticky headers?

### ISSUE THREAD

**Issue by MrChe** [styled-components/styled-components#1971]
I need to create a list with sticky headers like this http://take.ms/u67Iv . Maybe you have the best practices?
Please don't show me https://github.com/marchaos/react-virtualized-sticky-tree and solutions with position:sticky.
I need a solution with position:fixed

**Comment by kitten** [comment]
Sorry, but this is not an issue with styled-components but a usage and implementation question. This is probably more suited for StackOverflow or Spectrum.

Please read the issue template and other guides before opening an issue :)

That being said and out of the way, usually I'd be happy to help and post some links, but I'm currently not aware of anything and the question is a little broad. However, there's lots of poly fills for sticky and implementations that just use the window scroll position. It shouldn't be too hard to implement.

Regarding the best practices, we just are a CSS-in-JS library, so since this won't just work in CSS-only there's nothing special to say
