### ISSUE TITLE
"points" prop shows up in HTML

### ISSUE THREAD

**Issue by cbejensen** [styled-components/styled-components#1980]
## System:
 - OS: Windows 10
 - CPU: x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
 - Memory: 16.46 GB / 31.82 GB
## Binaries:
 (Retrieving binaries did not work in my terminal, sorry - I'll have to figure that out)

## Reproduction
[![Edit vq5l97997y](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vq5l97997y)

## Steps to reproduce
Add a prop named "points" to any component with any value.

## Expected Behavior
The prop should not show up in the HTML.

## Actual Behavior
The prop can be seen on the HTML element by using DevTools. Seems to only happen when the property "points" is used (not "point" or "pointy" or anything else).

I recognize it's not a huge deal, plus I might be overlooking something simple, but I thought I should pass it along just in case.

**Comment by probablyup** [comment]
Yeah this is by design. I actually just looked at the docs and the behavior isn't explicitly mentioned, so I'll need to add that.

Basically, we assume all-lowercase props are actual HTML attributes and pass them through. If you want to avoid this and not have the prop go through to the DOM node in the case of a simple component like `styled.div`, you'll want to make the prop camelCase.

The reason why we have this distinction is we currently have no way of knowing what props are specifically used for styling vs functionality vs HTML attributes, so we have to make some assumptions. In v5 we will likely [change our strategy on props](https://github.com/styled-components/styled-components/pull/1682#issuecomment-399496564) and sidestep this issue.
