### ISSUE TITLE
Serverside rendering with Typescript for img tags has mismatching classNames with client

### ISSUE THREAD

**Issue by cloutiertyler** [styled-components/styled-components#2064]
## System:
 - OS: macOS 10.14
 - CPU: x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
 - Memory: 2.91 GB / 32.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 8.9.4 - /usr/local/bin/node
 - npm: 5.6.0 - /usr/local/bin/npm
## npmPackages:
 - @types/styled-components: ^3.0.1 => 3.0.1 
 - styled-components: ^3.3.3 => 3.3.3 

## Reproduction

I am not able to use Babel to do any transforms to the classNames because I'm using Typescript and rendering on the server with:

```
const sheet = new ServerStyleSheet(); // <-- creating out stylesheet
const body = renderToString(sheet.collectStyles(element));
```

I'm therefore only using webpack to build my app. 

## Steps to reproduce

1. Create a typescript project and render a webpage with a single `styled.img` component using the code shown above.
2. Build client side javascript with webpack:

```
const path = require('path');

module.exports = {
  mode: process.env.NODE_ENV === 'production' ? 'production' : 'development',
  entry: {
    Home: './src/pages/Home.tsx',
  },
  devtool: 'inline-source-map',
  module: {
    rules: [
      {
        test: /\.tsx?$/,
        use: 'ts-loader',
        exclude: /node_modules/
      }
    ]
  },
  resolve: {
    extensions: [ '.tsx', '.ts', '.js' ]
  },
  output: {
    filename: '[name].js',
    path: path.resolve(__dirname, 'build/static/scripts')
  }
};
```
3. Load the page on the browser and you'll see a mismatching className warning

## Expected Behavior
The classNames for the client and server components should match. 

## Actual Behavior
The names do not match, but only for `img` tag components. `div`s work fine.

**Comment by probablyup** [comment]
So I'd recommend using @Igorbek's [plugin](https://github.com/Igorbek/typescript-plugin-styled-components) which approximates what we do in babel-plugin-styled-components. Without one of these plugins, there's no guarantee that the classNames generated will be hashed consistently between environments.

**Comment by probablyup** [comment]
If you are able to switch over to the new typescript toolchain via `@babel/preset-typescript` I definitely recommend that + https://github.com/styled-components/babel-plugin-styled-components. It'll give you the best overall experience and allow you to use the whole babel ecosystem as needed.

**Comment by cloutiertyler** [comment]
As far as I can determine I can’t use either of those because there’s no way them to have any effect on the collectStyles that I’m doing in my code? I’m I correct there?

**Comment by mxstbr** [comment]
You don't need them on the server, the client-side code that you're rendering must be transpiled with the Babel plugin.

**Comment by cloutiertyler** [comment]
I'm sorry, how will they babel presets enforce that they will have the same classNames in that case? You're saying that babel makes it so they have the same classNames that are assigned by `sheet.collectStyles(element)`?

**Comment by mxstbr** [comment]
> You're saying that babel makes it so they have the same classNames that are assigned by sheet.collectStyles(element)?

Yes. The Babel plugin is necessary to get consistent class names across the server and the client JavaScript.

> how will they babel presets enforce that they will have the same classNames in that case? 

It does so by adding a unique identifier to each component that is consistent between client and server. (see https://www.styled-components.com/docs/tooling#serverside-rendering)

**Comment by cloutiertyler** [comment]
Hi @mxstbr I'm sorry but I truly do not understand any of this. I've been over the documents that you've linked quite a few times.

@probablyup linked @Igorbek 's plugin above. Correct me if I'm wrong, but there is no way that I could ever possibly get that to work on the server because I'm not using webpack to build my server code. I use `tsc` to build my server executable file. I assume that if I were to use Babel instead I would have to build my client and server in the same way for the names to be consistent?

I also asked a few clarifying questions over here:
https://github.com/styled-components/babel-plugin-styled-components/issues/41#issuecomment-427516293

Any clarification either here or in the docs would be very helpful! It seems like this mismatch issue is a very common concern in the issues here on GitHub. A small explanation of how exactly the Babel transformers work would go a long way towards helping people fix these problems, I think.

**Comment by probablyup** [comment]
> Correct me if I'm wrong, but there is no way that I could ever possibly get that to work on the server because I'm not using webpack to build my server code.

True. You could run your server code through babel with preset-typescript into a dist folder and start your server from that though.

I’m traveling right now so I’m answering from my phone and can’t compose overly detailed responses. I’ll try and come back to this later though when I’m at a computer.

**Comment by mxstbr** [comment]
> I just cannot understand why consistent naming must be a post processing step of the build.

Because JavaScript™️. A function cannot know what the name of the variable is that the returned data is stored in. An abstract example:

```JS
const Name = someFn();
const Name2 = someFn();

function someFn() {
  // How can someFn know what the returned data's variable name is?
  // It can't.
}
```

A more specific example:

```JS
const Button = styled.button();

// The styled.button() fn cannot know that its returned data
// is stored in a variable called "Button".
```

So we hack around that by manually telling the function what the variable name is (we also add some more stuff to make it more unique like the file path, simplifying here):

```JS
const Button = styled.button.withConfig({
  name: 'Button'
})();

// The styled.button.withConfig()() fn now knows it's called Button
```

Now as to why we need every component to have a unique name in the first place.

Every styled component has two classes, a class that is unique to its specific instance (e.g. `<Button primary />` will have a different class from `<Button secondary />`) and a general class for all instances of the component. The instance-specific class is the hash of the resulting CSS string.

But the problem is, every instance might have different CSS, `<Button primary />` will generate a different CSS from `<Button secondary />`. So the class differs. We need all instances of the component to have a shared class though so that component interpolation works:

```JS
const Wrapper = styled.div`
  // Every instance of the Button needs to have a shared class, otherwise
  // this cannot work
  ${Button} {
    color: blue;
  }
`
```

By default, the shared class is simply an incremental counter of components, that's then hashed. We literally just have a global counter that counts from 0 upwards and counts every component that is created.

Unfortunately, for most apps the order in which components are created is not the same on the server as it is on the client, leading to different class names and checksum mismatches.

So that's where the Babel plugin comes in: it adds a unique name to each component, so that all the instances of the component can have a shared class that isn't based on incrementing a counter that differs between server and client.

I hope that makes sense and illuminates why it is necessary?

**Comment by probablyup** [comment]
Can you add that to the FAQs Max? Very clear answer!

**Comment by mxstbr** [comment]
It's such an implementation detail though, that's why I haven't added it to the docs 😅 Maybe we need contribution documentation somewhere that details internal design decisions like this one? (and the difference between a component ID and a component name, which I don't even understand :rofl: @kitten)

**Comment by cloutiertyler** [comment]
@mxstbr @probablyup Wow, thanks so much for the detailed and quick replies. I appreciate you taking the time to humor me!

That's a great answer and definitely get's to the heart of the problem. What I wasn't realizing is that the styledComponentId's purpose is specifically to implement the interpolation feature of targeting other components.

I read through the styled components code and I have some thoughts on what could be done. I'll put them in #2069!
