### ISSUE TITLE
Investigate better ways to create component-specific classes

### ISSUE THREAD

**Issue by mxstbr** [styled-components/styled-components#2069]
I'm going to reopen this can of worms and ask if anybody has ideas for a better way to handle component interpolations that lets us do SSR without the Babel plugin.

> See https://github.com/styled-components/styled-components/issues/2064#issuecomment-427571787 for the background information behind this issue

**Comment by mxstbr** [comment]
There's two broad possibilities I see:

1. Get rid of the component-specific class. For example, instead of only adding a single class, we could maybe keep track of all active instance classes and add them all to the generated CSS:
  
  ```JS
  const Parent = styled.div`
    ${Child} {
      color: blue;
    }
  `

  // Before this would use the component-specific class, which needs the Babel plugin to be consistent between server and client
  // .Child-asdf123 { color: blue; }
  // Could we get a list of all instance-specific classes instead?
  // .sc-fhgurt, .sc-tueqia, .sc-lijgue { color: blue; }
  ```

2. Make the component-specific class consistent without relying on a build-time transform. Not sure how we could make this happen, but it would have to happen without a counter of any sort.

Are these potentially viable? Other ideas?

**Comment by cloutiertyler** [comment]
@mxstbr Thanks so much for opening this! I really appreciate it. I haven't read through all of @probablyup and your replies yet, but I'll do that now.

Having read through the code I now understand the core of the problem. I look forward to working on this!

**Comment by probablyup** [comment]
> you can just hash the content of the CSS that supposed to be associated
with an element and use that as the class.

Not really. We support function interpolations so the end result of the CSS
after flattening and stringification can be very different between renders
depending on props. This also isn’t a safe assumption because multiple
components can have the exact same css, but we need the resulting hash to
be unique despite that.

**Comment by cloutiertyler** [comment]
> We support function interpolations so the end result of the CSS
after flattening and stringification can be very different between renders
depending on props. 

Yes, but if that's the case it _should_ have a different class because it has CSS content. I'm trying to separate the two problems. Using classes which are just the hashed content of the CSS is is just a more efficient way of rendering inline styles, right?

> This also isn’t a safe assumption because multiple
components can have the exact same css, but we need the resulting hash to
be unique despite that.

That may be true for the React component ID specifically, but like I was saying this doesn't have anything to do with associating the CSS blob to a component. Just like above, it's just a more efficient way to do inline styles.

AFAICT the unique styledComponetId solves an entirely different problem.

**Comment by cloutiertyler** [comment]
Also I see you're replying via email, not sure if you can see my edits. You are really fast at replies haha!

**Comment by cloutiertyler** [comment]
Basically the TL;DR of what I'm saying is there are two problems:

1. I would like this rendered CSS content to be applied to these elements
2. I would like to reference another _**React**_ element from within my CSS content

1 is very easy to do
2 is decidedly not so easy

The solution for 1 kinda sorta solves problem 2, but not it's perfect because it's not _quite_ specific enough

**Comment by cloutiertyler** [comment]
Out of the box, I'd like the library to be able to solve problem 1 no matter what without Babel and if I want to use the 2 feature, maybe it makes sense to just require it for that.

**Comment by cloutiertyler** [comment]
At the very least you can definitely have the library output displayNames for debugging without requiring Babel, if I'm understanding correctly.

**Comment by probablyup** [comment]
So the OP prompt of:

> if anybody has ideas for a better way to handle component interpolations that lets us do SSR without the Babel plugin

Is specifically about generating `styledComponentId`. The way the class hashes for styles themselves are generated works perfectly fine at runtime without babel.

The primary issue is `styledComponentId` has to be 100% deterministic and the same between environments. Babel provides a convenient way to accomplish this since all file systems in mainstream use do not allow multiple files to exist at the same path, thus we can hash that unique and stable information (in conjunction with a few other bits as available) to make a hash.

Due to transpilation, runtime order, and other dynamic language concerns, I'm not aware of a way to get equivalent guarantees at runtime. If the files are 100% the same, then they should create the same hash yes, but most people's SSR vs client setups do include minute differences between environments.

**Comment by cloutiertyler** [comment]
@probablyup I'm not sure what you mean when you talk about hashing files. Are you talking about somehow hashing JS files? Just to clarify the only hashing I have been referring to is the hashing of the normalized CSS rules that are passed to the StyledComponent type constructor.

With regard to your first point, I don't think it's possible to generate a unique `styledComponentId` per component for the reasons that you've brought up (or at least I haven't been able to think of a way yet either). However, I don't think that's the equivalent to the prompt you quoted. The method @mxstbr proposed for example has an id per component instance, not a unique `styledComponentId`, if I'm understanding correctly.

**Comment by cloutiertyler** [comment]
I understand that the `styledComponentId` is unique per component meant to refer to all instances. That's not what I'm talking about.

@mxstbr was referencing adding using **per instance** id's to accomplish the same effect:
```
/* Could we get a list of all active instance-specific classes of both components
 * and put a matrix of those in instead, completely alleviating the need for
 * component-specific classes? */
```

**Comment by probablyup** [comment]
That could literally be thousands of classes for a highly used component.

**Comment by mxstbr** [comment]
> That could literally be thousands of classes for a highly used component.

Yes, but it would only happen if you use the component-selector, which we don't advocate anyway, without the Babel plugin, right? In my mind, that seems like a great tradeoff: 

- Upside: No longer required to use the Babel plugin for SSR, TypeScript SSR is easy
- Downside: When using component-selectors (an escape hatch feature that's recommended to use sparingly) and you're not using the Babel plugin you'll get bigger CSS output

Again, that downside would only apply to people who use an escape hatch feature without using the Babel plugin. We could even warn in dev mode if they do that and tell them to use the Babel plugin. 

Right? What am I missing?

**Comment by cloutiertyler** [comment]
Yeah that seems reasonable to me. Honestly, anything that get's it further towards working right out of the box (with debug info) is a great help to people trying to use the library. Otherwise users have to change their build toolchain for reasons they don't understand to fix an issue with a degenerate edge case.

I've thought about this from a few angles and I agree it doesn't seem possible to get the interpolation feature without doing one of the folowing:

1. Relaxing the perfect specificity constraint (i.e. if you have a pair of parent and child components in different files which have the exact same names, css, and are being used for interpolation *and* you use *both* children in one of the parent instances, then it will inadvertently style both children with the inner CSS instead of just one -- a presumably very very rare use case*)
2. Doing something with component instance classes like @mxstbr is saying
3. Just making the interpolation feature require Babel, but allowing users to disable this feature if they don't want to change their build chain

*Note that for number 1 if you just have identical components with identical CSS in two different files then you only need one CSS rule because that CSS rule should apply to both components anyway. In fact you really have to work at it to come up with a degenerate case:

```javascript
// From child-file1.js
const Child = styled.div.withClass("child-1")`
`;

// Somehow imported child from another file and renamed to be Child2,
// but used as Child when creating react components (e.g. <Child />)
// From child-file2.js
const Child2 = styled.div.withClass("child-2")`
`;

const Parent = styled.div.withClass`
    width: 100%;
    ${Child} {
        color: blue;
    }
    ${Child2} {
        color: red;
    }
`

// file1.js
// Child here is imported from child-file1.js
const GrandParent = () => (
    <Parent>
        <Child />
        {props.children}
    <Parent>
);

// file2.js
// Child here is imported from child-file2.js
<GrandParent>
    <Child />
</GrandParent>
```

For number 1 or number 3 you could even include an API to allow users to disambiguate manually. For example:

```
const Child = styled.div.withClass("child-1")`

`;

const Child2 = styled.div.withClass("child-2")`
`;

const Parent = styled.div.withClass`
    width: 100%;
    .child-1 {
        color: blue;
    }
    .child-2 {
        color: red;
    }
`
```

I can't see any other possibilities, but I think that any one of the three could be an acceptable solution, except with the caveat that number 1 is not perfectly backwards compatible in the degenerate case so I could see why you might want to avoid that.

**Comment by cloutiertyler** [comment]
@mxstbr The number 1 in the previous answer assumes that you can get access to the react displayName when generating the classNames for the react elements and for the CSS sheet. Is that possible, or do you need to use the component variable name in class?

e.g.
```
// this name
const Child = styled.div``;
// vs this name (the one that goes into the jsx element and becomes the displayName for that element)
<Child />
```

**Comment by cloutiertyler** [comment]
@mxstbr In general I'm a fan of your proposed trade off though. I'm still not quite sure how you're going to generate unique but deterministically derived classnames per element though. Are you going to use some React Id to create the className which is the same on server and client?

**Comment by kitten** [comment]
Closing due to age, inactivity, missing reproduction, or lack of details.
