### ISSUE TITLE
Cannot style base component in SC4?

### ISSUE THREAD

**Issue by ConneXNL** [styled-components/styled-components#2104]
The following broke for me with Styled Components 4:

```
const Base = styled.div`
    margin: 0;
    padding: 0;
`;

const Red = styled(Base)`
    color: red;
`;

const Wrapper = styled.section`
    ${Base} {
           font-weight: bold;
     }

    ${Red} {
           font-style: italic;
     }
`;

```

Rendering: `<Wrapper><Red/><Wrapper>`

`font-style: italic;` is applied while `font-weight: bold;` is not.

This worked in Styled components v3. Is this intentional? What is the new way to style a base component?

**Comment by mxstbr** [comment]
Yes, this is intentional. Internally we now "fold" styled-components into each other when extended with `styled(Comp)` so that there's less components in your hierarchy and less styles duplicated. 

You probably want something like this:

```JS
const Base = styled.div`
    margin: 0;
    padding: 0;
`;

const Red = styled(Base)`
    color: red;
`;

const Wrapper = styled.section`
    ${Base} {
           font-weight: bold;
     }

    ${Red} {
           font-weight: bold;
           font-style: italic;
     }
`;

```

**Comment by ConneXNL** [comment]
Sounds like a pretty radical move to me if there is no way to get the old behavior somehow.

Now every parent component has to know all of its possible children, and target them individually. Making generic parent components that can use with children of a certain type is now not possible anymore. If this were not styled components this is the same as dropping support for interfaces in a programming language.

I have not upgraded to styled components in one of the bigger projects and I expect a lot of my code to break. I wonder why the changelog or blog doesn't mention anything regarding this.

Am I the only one using this pattern?

**Comment by mxstbr** [comment]
> I wonder why the changelog or blog doesn't mention anything regarding this.

It does, in [this section](https://medium.com/styled-components/announcing-styled-components-v4-better-faster-stronger-3fe1aba1a112#acb4), although to be fair it's not very prominent—we didn't think anybody relied on the previous behaviour like that!
 
----

> Now every parent component has to know all of its possible children, and target them individually. Making generic parent components that can use children of a certain type is now not possible anymore. 
> Am I the only one using this pattern?

I have never seen or heard of anybody use styled-components this way before to be completely honest, so most likely yes.

You should just be using [theming](https://www.styled-components.com/docs/advanced#theming) instead to adapt the child components based on which parent they are rendered in. That way you don't need to know all the possible children. That's why styled-components has theming built-in!

**Comment by ConneXNL** [comment]
> You should just be using [theming](https://www.styled-components.com/docs/advanced#theming) instead to adapt the child components based on which parent they are rendered in. That way you don't need to know all the possible children. That's why styled-components has theming built-in!

I don't think this is a theming related issue. The children (on an individual base) don't have to be changed based on their parent in my use-case.  It's just a composition-pattern I am using which is imo very common to how object oriented programming's inheritance.

For example: Let's say I have a <Table/> component and tens of different <TableCell/> components. The <Table/> component might want to change the base style of the <TableCell/>'s.

With v4 I need to include all the different <TableCell/>: <NumericCell/>, <StringCell/>, <TimeCell/>, simply targeting `TableCell` no longer works. Now let's say I want people to make their own <ABCCell/> component in a different package (that extend <TableCell/>. Now the <Table/> can't style or target that child as it isn't even aware it exists.
 
I guess we will have to find out when others upgrade styled components if my use-case is unique. Then again, I hate I have to go back and target ` td's` and `>divs` again rather than the semantic elements I built using SC in the first place.

**Comment by mxstbr** [comment]
Using the component selector in the way you did never worked intentionally, it only worked due to the internal implementation details (which have now switched in v4). I would not recommend this pattern, even in v3, as it's implicit and the child components get changed without their knowledge or consent. 

> Let's say I have a <Table/> component and tens of different <TableCell/> components. The <Table/> component might want to change the base style of the <TableCell/>'s.
> Now let's say I want people to make their own <ABCCell/> component in a different package (that extend <TableCell/>.

You want to use theming for this, because it is exactly what theming is for! I think the mental wall here is that you don't have to switch individual properties around with theming, you can pass any value through from theming.

Here's what your `Table` could look like:

```JS
// Define any custom table cell style you want, and pass it through via the theming context
const tableCellStyle = css`
  color: blue;
`;

const Table = (props) => (
  <ThemeProvider theme={{ tableCellStyle }}>
    {props.children}
  </ThemeProvider>
)
```

And then from your table cell components you'd use that theme from the context:

```JS
const NumericTableCell = styled.td`
  // Default styles here
  color: red;
  background: yellow;
  // Theme-specific overrides below
  ${props => props.theme.tableCellStyle}
`
```

That way your TableCell can be themed depending on which table it is rendered in. 

Contrary to your implicit mechanism every child component explicitly says that it's theme-able, making it much clearer to any other developer coming to the system a couple months later. ("Why does this table cell suddenly look different? Ohh I see, it's themed.") That's why we built the theming system in the first place, to solve exactly this use case.

**Comment by ConneXNL** [comment]
So @mxstbr , as years went by I accidently continues using using styled-components as in OP.

Am I correct that this is now supported again as of https://github.com/styled-components/styled-components/pull/2239 ?
