### ISSUE TITLE
Integrate SSR benchmarks from material-ui

### ISSUE THREAD

**Issue by mxstbr** [styled-components/styled-components#2118]
These ones: https://github.com/mui-org/material-ui/tree/master/packages/material-ui-benchmark

We should add them to our benchmark suite!

**Comment by oliviertassinari** [comment]
I was recently investigating SSR issue for www.onepixel.com. We were around 2 req/s. That was pretty bad. The stack is Next.js, apollo, express, node, React, Material-UI. Turns out. We where able to get a x2 performance boost by caching the CSS-in-JS in generation server side. I would consider styled-components the bottleneck for SSR, both because it's creating more React components and because the style generation is slower. You might want to look into that, emotion is significantly faster.

**Comment by probablyup** [comment]
> We were around 2 req/s.

That seems quite low. I know at Zocdoc we were at a minimum of 100 reqs/s even with graphql fetching etc.

**Comment by oliviertassinari** [comment]
@probablyup That's on a 1/4 vCPU on AWS Fargate. Some of the leverage have been:
- Removing react-apollo's `getDataFromTree()` (the latest release makes it even slower as they prepare suspense support).
- Optimizing Material-UI (JSS + core components)
- Only keeping Datadog for a fraction of the nodes.

**Comment by darkowic** [comment]
@oliviertassinari may I know with what did you replaced `getDataFromTree` with? Mine SSR is also very slow and I am looking for ways to optimize it
