### ISSUE TITLE
Investigate ServerStyleSheet construction performance

### ISSUE THREAD

**Issue by mxstbr** [styled-components/styled-components#2120]
It seems like `new ServerStyleSheet()` is our biggest SSR perf bottleneck according to the SSR benchmarks added in #2119, which in turn makes it seem like `StyleSheet.clone()` is the actual bottleneck.

Since as of v4 everything is in the component-context, I'm not 100% certain why we need to clone anything anymore on the server. It seems as though creating a cache of styles per each request should be a cheap operation since nothing should be shared anymore between requests?

Going to defer to @kitten's expertise since he wrote most of that—can we maybe speed up or get rid of the cloning entirely?

**Comment by mxstbr** [comment]
I just tried to "stupidly" remove cloning (by making the `clone()` method only `return new StyleSheet()`) and it broke quite a few tests, but I can't quite tell why. Many of the test failures look like this:

```diff
- .sc-a {} .c{color: red;}</style>"
+ .c{color:red;}</style>"
```

Why is the `.sc-a {}` missing?

**Comment by kitten** [comment]
@mxstbr The `.sc-a {}` is injected as part of the deferred injection. It's also what determines the eventual order.

### Current StyleSheet — deferred injection

Basically our current model keeps **order of first injection** per component. When new rules are then injected they're appended to first rule the component injected. However, we care about **order of creation** for components instead, so we want to inject a placeholder as soon as the component is created. Now, because we don't want to immediately inject rules we have deferred injection to "fake insert" as first rules. That's when `.sc-a {}` is also injected.

When we clone a `StyleSheet` (typically `master` to a `ServerStyleSheet`) the `master` has all the deferred rules and the "child" has all the rest. Since we want to preserve the order we've established we copy all of that information over by "cloning".

So what you're seeing is missing "placeholder" rules and component injection order. You should in that change-set see React-render-order instead.

That's 100% @geelen's genius system, which has just been refactored in v3 (?) :100:

### Proposed system — injection by indices

(Hey, this sounds like `z-index`?! Indeed we'll keep track of the order of rules with a number)

To also capture what my proposal is, we can capture the **creation order** with a simple counter. If we then get to `render` we already have a `StyleSheet` from context with fallback to `master` (completely universal, yay). In `render` we can then instruct the `StyleSheet` to inject the component's rendered rules and also give it the **creation index**.

The `StyleSheet` keeps a list of all _creation indices_ and the number of rules that have been inserted for them. (This means that all these numbers added up are equal to the number of inserted rules)

We can then take the **creation index** and walk the complete list of _creation indices_ until either the next index is greater or the current one is equal. All of the _number of rules_ in the list up until the matching index can then be added up. What we get is the **injection index**, which can be passed to `sheet.insertRule` :tada:

This has a couple of advantages:

- No "deferred" effects outside of React's reconciliation process
- We always have a *single* `StyleSheet` that we're referring to
- `StyleSheet`s are unaware of "components" and only group by the **creation index**

Which lead to all benefits we're searching for like faster SSR, correct ordering of rules, context-driven stylesheets, rules that can be in one or more stylesheets, etc.

The structure of the list can be imagined to be:

```
Array<{ index: number, size: number }>
```

But can be simplified to two separate arrays for performance (other optimisations can be made). This'd also mean that the entire StyleSheet API can be expressed pretty functionally, but that's probably sth I'll leave for the implementation, when I get to that.

### Babel-less SSR

Another problem we tried to solve is Babel-less SSR. How can we ensure consistent classes, ordering, and unique names **without** the Babel plugin?

The problem we need to solve is that there has to be a _“single consistent moment”_ between the result of SSR and the rehydration where the client renders the _same result_. What we're trying to achieve is consistency between the two. We can't use our “best guess displayName” since it's ordered by creation, which might be different on the server and the client.

Essentially we can keep another counter for the **render order**. Since in SSR the rendered tree is enforced to be the same on the client we can count upwards for rendered `StyledComponent`s. The first time we encounter a component _while rendering_ we can give it a number to use as its `componentId` instead of a “best guess“ name.

**Comment by mxstbr** [comment]
@kitten that makes a lot of sense, thanks for the detailed write-up! Excited to see where this goes.

**Comment by hilarykitz** [comment]
Bump! This is especially pressing for component libraries that aren't doing any SSR (but their clients are), since visual bugs get published unknowingly 😞 

Very excited to see this merged and happy to contribute in any way that's useful!

**Comment by mxstbr** [comment]
@hilarykitz we've got a RFC coming up that'll detail this work, since none of the core team right now has time to get cracking on this but we're very excited about it. Keep an eye out, soon!

**Comment by probablyup** [comment]
Closed thanks to v5!
