### ISSUE TITLE
Add tests for preact-compat and inferno-compat

### ISSUE THREAD

**Issue by busypeoples** [styled-components/styled-components#216]
Not sure If this has been discussed already, but I think it would be great to see styled-components work with Preact, Inferno and other Virtual Dom implementations. Are there any thoughts regarding making styled-components JSX and especially React agnostic? 
I can help with this, if there is an interest in making this happen and a general idea on how to approach the topic.

**Comment by mxstbr** [comment]
Yes.

Preact should already work (untested), and in general the only React-specific part of `styled-components` is in two or three files. (`StyledComponent.js` and `ThemeProvider.js`) We're looking towards adding support for web components (ref: #128) and I know @trueadm is looking into adding inferno support! I've also experimented with `choo` support, haven't looked too deeply into it but adding that shouldn't be hard.

Since `styled-components` returns a component (in whatever framework you use), making it fully agnostic isn't possible I'm pretty sure, but we're going to continuously add support for more and more libraries and frameworks! The ultimate goal is: `styled-components` everywhere 😎

**Comment by whmountains** [comment]
I'm going to see about implementing inferno support.

**Comment by wenwuwu** [comment]
Me too. Looking for compatible version for inferno and preact. Thx.

**Comment by philpl** [comment]
Styled-components does work with preact-compat perfectly

**Comment by k15a** [comment]
Is there a way we can run our existing tests with `preact-compat` and `inferno-compat` as well?

**Comment by SunHuawei** [comment]
@whmountains and @wenwuwu , any progress?

**Comment by philpl** [comment]
@k15a We should add some additional tests but making the tests 3x longer is a bit overkill ;)

**Comment by whmountains** [comment]
@SunHuawei Nope.  I got busy with other stuff, unfortunately.

**Comment by alvinsight** [comment]
Hey guys, 
Great job on v2! Since it is out now, any chance this issue could be talked about again ? 
Thanks!
Alvin

**Comment by bkazi** [comment]
Has there been any progress on this? Is it still something that needs working on?

Maybe I'm over-simplifying it but, would it be possible to run the existing tests aliasing `react` with `preact-compat` and `inferno-compat` using something like [jest-alias-module-loader](https://www.npmjs.com/package/jest-alias-module-loader)?

**Comment by mxstbr** [comment]
No progress so far, PRs welcome!

**Comment by philpl** [comment]
@bkazi That's a great idea! If you'd like to port it, that'd be amazing :heart: It should probably take the general direction of our native/primitive tests, which are more minimal and still cover a huge chunk of the functionality.

**Comment by bkazi** [comment]
Brilliant, I'll start working on an initial PR

**Comment by bkazi** [comment]
So turns out Jest makes it pretty easy to alias modules with [`moduleNameMapper`](https://facebook.github.io/jest/docs/en/configuration.html#modulenamemapper-object-string-string) config option

I've started working on porting the react-native tests, you can view the commit [here](https://github.com/bkazi/styled-components/commit/7a1032178604d27a14ced406831428d050170eb9). The tests don't pass and I was hoping to get some help

 Should I rather open a PR to discuss and review?

**Comment by mxstbr** [comment]
Let's open a PR and collaborate there; I think you should probably work on the web tests since Preact doesn't have a `View` or `Text`.

**Comment by nickytonline** [comment]
@kitten, with the latest SC and Preact, do both play nice together still, i.e. "Styled-components does work with preact-compat perfectly", https://github.com/styled-components/styled-components/issues/216#issuecomment-294281740 ? It's not officially supported but it should be all good, right?

Just trying to validate this before I propose it on a Preact project.

P.S.: Keep up the great work! 🔥

**Comment by kitten** [comment]
@nickytonline it should still work perfectly :) I’m using preach-compare in some projects in combination with styled-components and I know several other people who do the same so no worries 👍

**Comment by nickytonline** [comment]
Cool beans. Thanks @kitten

**Comment by cryve** [comment]
Just tried to migrate my preact app to styled-components v4.1.1 but sadly thats not possible: preact or preact-compat do not provide the new React features used in SC yet.
For createContext there is a workaround: https://github.com/developit/preact/pull/963#issuecomment-408635151
For forwardRef there is only a pending pullRequest: https://github.com/developit/preact/pull/1234

**Comment by kitten** [comment]
Closing due to age, inactivity, missing reproduction, or lack of details.
