### ISSUE TITLE
Styled components not working in IE11

### ISSUE THREAD

**Issue by gregorianisch** [styled-components/styled-components#2190]
## System:
 - OS: Windows 10
 - CPU: x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
 - Memory: 4.90 GB / 15.94 GB

## Binaries:
 - Node: 8.11.3 
 - Yarn: 1.7.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
 - npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD

## npmPackages:
 - styled-components: ^4.0.3 => 4.0.3

## Browser
 - IE 11.345.17134.0

## Reproduction

Use styled components, extend components like: 
```
export const Flex = styled.div`
	display: flex;
`;

export const ResponsiveFlex = styled(Flex)`
	@media (max-width: 1024px) {
		flex-direction: column;
	}
`;
```

## Expected Behavior

No errors in IE 11, components are rendered and extended successfully.

## Actual Behavior

`
Error: Cannot create styled-component for component: .Flex 
`

Console stacktrace: 
![image](https://user-images.githubusercontent.com/25294888/47986281-e1c8d200-e0e4-11e8-9443-18e28cd31065.png)

**Comment by mxstbr** [comment]
Huh that's very strange. Does it work in other browsers?

**Comment by mxstbr** [comment]
@gaearon any ideas why `react-is` would report `ForwardRef` not to be a valid element type in IE11?

**Comment by gregorianisch** [comment]
@mxstbr works perfectly on Chrome, Firefox, Safari.

**Comment by mxstbr** [comment]
Are you polyfilling everything correctly for React v16 to work? https://reactjs.org/blog/2017/09/26/react-v16.0.html#javascript-environment-requirements

**Comment by gregorianisch** [comment]
@mxstbr my project is bootsrapped with `create-react-app-typescript` polyfilled through
```
import 'react-app-polyfill/ie11';
```

Tried also 
```
import 'core-js/es6/map';
import 'core-js/es6/set';
```
but no help.

Not sure is it related or not, but in the summary of this [article](https://medium.com/@_meandmax_/react-16-cra-and-ie11-giving-me-headaches-c8be43b4fcb2) I found:

> The application made with CRA/react-scripts-ts is not working in IE11 as soon as we update to React 16. It has something to do with 2 connected container components rendered in another container component because as soon as we comment them out the application is working fine. Looking at the transpilled JavaScript, we see that there are errors, because some object literal shorthand notations are not correctly transpilled. If we turn off UglifyJS the application is working fine again.

Will try to investigate futher, but will be grateful for any ideas :)

**Comment by Fer0x** [comment]
@gregorianisch create-react-app now has official TypeScript support and has already migrated from UglifyJS to terser. Maybe upgrade of your toolset can help you.

**Comment by gregorianisch** [comment]
@Fer0x using currently last version of `react-scripts` - `2.1.1`, so that's probably not an issue.

**Comment by probablyup** [comment]
Dumb question, but is your copy of `react-is` fully updated? If it's not in sync with react and react-dom, it might not have the symbol info for ForwardRef

**Comment by dfkadyr** [comment]
I have this issue
![image](https://user-images.githubusercontent.com/30463517/48623297-5390fd80-e9ba-11e8-96bf-cb861374a1f6.png)

**Comment by gregorianisch** [comment]
@probablyup 
Thank you, I've 16.6.0 currently, so it should be fine (?)

![image](https://user-images.githubusercontent.com/25294888/48691094-f1164800-ebd9-11e8-95fd-3d4d3c22ffcf.png)

**Comment by probablyup** [comment]
Hmm yeah that's fine 😕

**Comment by ulich** [comment]
We had the same issue 
```
Cannot create styled-component for component: [object Object].
```

it turned out that the issue of inheriting styles:

```
const DefaultNavbar = styled.nav`
    text-align: center;
`

const ExtendedNavbar = styled(DefaultNavbar)`
    position: fixed;
`
```

create-react-app (react-scripts 2.0.5)
styled-components: 4.1.1

we also polyfill with
core-js: 1.2.7

by doing
```
import 'core-js'
```

i hope this helps.

**Comment by gregorianisch** [comment]
@ulich thank you :) I'm using inheriting quite a lot, so replacing it in the whole project is quite time consuming. Couldn't find any working solution so far.

**Comment by vefimov** [comment]
I have the same issue in IE11.

**Comment by probablyup** [comment]
It sounds like just the symbol polyfill is needed. I wonder if React needs to [add that polyfill to their list](https://reactjs.org/docs/javascript-environment-requirements.html)...

**Comment by probablyup** [comment]
https://github.com/reactjs/reactjs.org/pull/1449

**Comment by lbineau** [comment]
Any news about this issue? I still get the error with react 16.7.0, styled-components 4.1.3, and added core-js 2.6.3 at the very begining of index.js entry point...

**Comment by probablyup** [comment]
React still hasn't updated their documentation but you need to provide a Symbol polyfill because `react-is` uses Symbols.

**Comment by andrew-t-james** [comment]
Any news on this issue? I am still getting this error 16.7.0, styled-components 4.1.3 after added the `Symbol` polyfill.

**Comment by andrew-t-james** [comment]
Any updates on this? I am getting this error in IE11 with 16.7.0, styled-components 4.1.3 after added the Symbol polyfill.

**Comment by admataz** [comment]
I have been grappling with the same error - we are already polyfiling Symbol - the only solution I have found that is reliable is to rewrite my extensions of styled components with the following pattern: 

```js

const childStyledComponent = styled(props => <BaseStyledComponent {...props} />)`
// new styles

`

```

I'd be interested to know if anyone has any views on this approach.

**Comment by keul** [comment]
My two cents on this issue for posterities.

I tried to polyfilling everything as described here, but the issue was fixed only when I moved the import polyfill **at the very beginning** of my main file (yeah... shame on me I was not using webpack for this as described).

Note: the import before the polyfills ones were not related to the component that trigger the error (there where no React stuff up there). Still I had the issue. So: beware of this.

**Comment by oyvindo** [comment]
We found that babel-polyfill solved this better than react-app-polyfill/ie11 as described last in this post: [https://github.com/facebook/create-react-app/issues/4647]
except we use only babel-polyfill.

**Comment by RikuVan** [comment]
Been struggling with what seems this same issue for a few days. Polyfills don't seem to help so perhaps I am on the wrong track.

<img width="1273" alt="Screen Shot 2019-03-26 at 8 04 13" src="https://user-images.githubusercontent.com/7317771/54974797-e3b10600-4f9d-11e9-843d-7af3bd761f8e.png">

**Comment by RikuVan** [comment]
Ok, figured out in my case it was the combination of two plugins: babel-plugin-import & styled-components causing these issues. I removed the first one, use to resolve antd imports and everything is ok.

**Comment by admataz** [comment]
we found relying on runtime loading of polyfills was unreliable - and that the suggestion in @keul's comment [above](https://github.com/styled-components/styled-components/issues/2190#issuecomment-461792826) i.e. to have the `Symbol` polyfill (and some others) loaded before any other JS was loaded was required - otherwise my verbose workaround above did work too

**Comment by Ollemesh** [comment]
I got the same error.

The reason was symbol polyfill was downloaded after react.

styled-components use `isValidElementType` function for detecting react element.
https://github.com/styled-components/styled-components/blob/c3eedbeb79621acd668e15ed2d63107528ed81c3/packages/styled-components/src/constructors/constructWithOptions.js#L14

`isValidElementType` works depends on Symbol existing ($$typeof symbol or number):
https://github.com/facebook/react/blob/master/packages/shared/ReactSymbols.js#L12
https://github.com/facebook/react/blob/master/packages/shared/isValidElementType.js#L26

React was loaded and it made all react elements with numeric `$$typeof` props.
After polyfill downloading isValidElementType waits for Symbols in `$$typeof`.

It's a known issue:
https://github.com/facebook/react/issues/8379
https://stackoverflow.com/questions/40897966/objects-are-not-valid-as-a-react-child-in-internet-explorer-11-for-react-15-4-1
