### ISSUE TITLE
ThemeConsumer, ThemeContext is undefined

### ISSUE THREAD

**Issue by mounlion** [styled-components/styled-components#2213]
ThemeConsumer, ThemeContext is undefined

## Environment
```
## System:
 - OS: macOS 10.14
 - CPU: (4) x64 Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz
 - Memory: 37.91 MB / 8.00 GB
 - Shell: 5.3 - /bin/zsh
## Binaries:
 - Node: 8.12.0 - /usr/local/bin/node
 - Yarn: 1.9.4 - /usr/local/bin/yarn
 - npm: 6.4.1 - /usr/local/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
## npmPackages:
 - babel-plugin-styled-components: ^1.8.0 => 1.8.0 
 - styled-components: ^4.1.1 => 4.1.1 
```

## Reproduction

```
import { ThemeProvider, ThemeConsumer, ThemeContext } from 'styled-components';

console.log(ThemeConsumer, ThemeContext);
```

**Comment by imbhargav5** [comment]
@mounlion This is not much of a reproduction of the issue since apart from the snippet there is not much else. Can you perhaps reproduce the issue on codesandbox or share a repo which shows the behavior?

This seems to be working on codesandbox. Also on my macos. 

https://codesandbox.io/s/mz30w6yow8

**Comment by mounlion** [comment]
i use styled-components on react-native so i can not use codesandbox

**Comment by mounlion** [comment]
@imbhargav5 
Hi 

repo with reproduce error
https://github.com/mounlion/styledComponents/blob/master/App.js

**Comment by mounlion** [comment]
@probablyup Thanks you!
