### ISSUE TITLE
possible styled-component v4 performance issues?

### ISSUE THREAD

**Issue by alansouzati** [styled-components/styled-components#2215]
I'm not sure what is going on, but just for the fact that I'm rendering 1000 boxes using styled components my screen takes almost a second to render, when using regular divs it takes less than 100ms.

## System:
 - OS: macOS 10.14.1
 - CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
 - Memory: 731.01 MB / 16.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 8.12.0 - /usr/local/bin/node
 - Yarn: 1.10.1 - /usr/local/bin/yarn
 - npm: 6.4.1 - /usr/local/bin/npm
## npmPackages:
 - babel-plugin-styled-components: ^1.6.4 => 1.8.0 
 - styled-components: ^4.0.0 => 4.0.3 

## Reproduction

https://codesandbox.io/s/xv1rz10p8q

## Steps to reproduce
1. Open sandbox link
2. Notice that by default I'm not using styled components.
3. Click on "show boxes"
4. Notice that it is basically instant rendering (around 80ms)
5. Swap from `App` to `App2` that uses styled-components
6. Notice that the rendering time now is not instant (around ~600ms)

The progression seems to be exponential. For example, 10000 boxes with styled-components takes 6 seconds, without 600ms.

## Expected Behavior
I'm not sure if I'm doing something wrong, or if my expectations are wrong. But I'm hoping the performance will be similar.

## Actual Behavior
The performance is quite different when including even a very simplistic styled-component div

**Comment by probablyup** [comment]
This is interesting... I did some profiling on the sandbox and only about 10% of that time is styled-components from what I can see. Much of it is just React doing its thing. My guess is the context consumers are slowing things down...

**Comment by probablyup** [comment]
Well I pulled up the standalone app window and ran the chrome performance profiler, then went into bottom-up and sorted by % time. Seemed like the vast majority of the scripting was on the React side.

**Comment by mxstbr** [comment]
There's probably not much we can do to fix that performance hit for the styled-components side unfortunately, it's on the React team to improve it :cry:

**Comment by probablyup** [comment]
cc @gaearon

Here's the standalone link for profiling process: https://k916y5mz6o.codesandbox.io/

<img width="1792" alt="screen shot 2018-11-14 at 3 08 17 pm" src="https://user-images.githubusercontent.com/570070/48512462-23f9be00-e81f-11e8-8acc-646314c4bfd9.png">

As you can see, the vast majority of the scripting work is happening on the React side. I believe this is due to our use of context consumers... is any work being done to optimize this? I'm a bit surprised there's so much work happening since we're just mounting the same component many times.

**Comment by demian85** [comment]
Hi, I'm new to styled-components and I was wondering why it is using the React Context API.
I was checking the generated components with React Devtools and I saw that every component is wrapped below 2 context providers. That is a bit scary to me because I immediately started thinking in performance issues.
Can someone please explain why is this lib using the React Context API? Or is it just used in development mode? (using babel + webpack)

Thanks!

**Comment by demian85** [comment]
I was just asking why you need that functionality. What's the provided context and why is it necessary?

**Comment by probablyup** [comment]
There’s a context for providing the stylesheet instance and one for
providing the user theme.

**Comment by demian85** [comment]
Yeah ok. Thanks for the info but I still don't get it. I thought the styles were injected in the head of the page and then it's just className referencing in each component...
Anyway, I'll investigate myself... Thanks.

**Comment by arianon** [comment]
@demian85 `styled-components` needs to consume the stylesheet instance to **add** a component's styles to the stylesheet, and contexts are the canonical way to pass a global object (in this case the stylesheet) to React components.

Maybe in the future, when hooks are stable, `Context.Consumer`s could be replaced by `useContext`, to avoid React tree pollution.

**Comment by probablyup** [comment]
> Maybe in the future, when hooks are stable, Context.Consumers could be replaced by useContext, to avoid React tree pollution.

Yup, that's correct. But we wouldn't be able to make this change until v5 at the earliest since it requires a new minimum React version and the Hooks RFC isn't finalized yet.

**Comment by alansouzati** [comment]
We are facing the very same problem on Grommet. We need the ThemeContext.Consumer and for every component that we add we have the 2 consumers from styled-components and the Theme consumer from grommet. The React debug tree is a mess, but unfortunately I don't think we can do much regarding debuggability. I'm just hoping the performance issue is fixed in the react side, but it seems we did not get any feedback from the react core team, that's sad. 😢 

createContext is an official API, but by looking at their docs we don't see any disclaimer regarding performance issues. Styled-components is just using an official API and I agree it is needed. The same way Higher Order Components and render props are needed to reuse component lifecycle methods.

**Comment by alansouzati** [comment]
on a side unrelated note, in my local dev environment i've disabled the react dev tools extension and the page loads much faster.

**Comment by arianon** [comment]
@alansouzati I just tried that and I'm seeing similar results as well. Strange.

**Comment by alansouzati** [comment]
Ok, I have more concrete answers now.

I've updated the [codesandbox](https://codesandbox.io/s/xv1rz10p8q).

I added a bunch of nested consumers with `App2` and I'm able to reproduce this problem only with react. This just reinforces the issue is with React.

We already know that disabling React Dev Tools helps with the cause.

Another very important finding is that if I download that codesandbox and run in production mode the issue simply **go away.**

```
npm i
npm run build
npm install -g serve
serve -s build
```

Lessons learned for me, I should never test performance using a dev server. This is one piece of good news.

Although, the developer experience is still not good. Do any of you have any pointers as to why this is so slow using webpack dev server + React?

**Comment by alansouzati** [comment]
I'm closing this issue since I feel this is something that should be fixed in React.

**Comment by ShanonJackson** [comment]
It should be fixed in React but seeing as how its still slow coming into march 2019 can styled-components fix this themselves? wrapping every element in two contexts seems very very inefficient however i'm not a performance expert.

**Comment by mqklin** [comment]
+1, it takes very long to render our pages... Have to wait 4-5 sec after switching some tab

**Comment by DustinDSchultz** [comment]
I'm facing this issue as well. I'm trying to render a table with about 20 columns and anywhere from 10 - 100 rows and it practically crashes IE every time it renders. My company refuses to release the software for internal use because of the performance (which we upgraded to a react stack to fix, ironically). Virtual rendering only makes scrolling performance even worse. I've upgraded to v5 beta but it doesn't seem to be any better. My solution is to strip out any usage of styled-components within the table and replace with JS style objects and className definitions. I see a roughly 10x increase in scrolling and rendering performance this way.

**Comment by mqklin** [comment]
@DustinDSchultz try v5, it works for me very well.

**Comment by nattapon4erudite** [comment]
> @DustinDSchultz try v5, it works for me very well.

But it didn't work for me 😥. I render 500 dynamic styled components every second and it was extremely slow. But when I replaced styled-components with inline-style, it was 100x faster.

**Comment by adrianhelvik** [comment]
A large chunk of components are static. I think this would be a great performance optimisation to create context-free components using the macro. This would possibly remove most of the performance bottleneck related to context usage while only being a minor version update.

```javascript
const Foo = styled.div`
  color: rebeccapurple;
`
```

```javascript
import { contextFree } from 'styled-components'
const Foo = contextFree.div`
  color: rebeccapurple;
`
```

**Comment by lbdremy** [comment]
Thanks for this great library! 

Is there any plan to address the performance issue raised in this issue?

The update from v4 to v5 did make a difference, but it is still there, I wonder if v5 tackles part of the root issue (the switch to hook ?) or the performance gain is due to improvements in other areas. 
From the comments, I understood that the heavy usage of the Context API is the root cause of the performance issue, did anyone went further in the exploration to identify the expensive function calls?

In the meantime did anyone find successful ways to mitigate the issue? (e.g: virtual list?)

Thanks a lot
