### ISSUE TITLE
Cannot use ${Parent}:hover when Parent is imported

### ISSUE THREAD

**Issue by good-idea** [styled-components/styled-components#2262]
Bug: The Parent selector syntax produces confusing results when the `Parent` styled component is imported from another file.

## System:
 - OS: macOS 10.14
 - CPU: (4) x64 Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz
 - Memory: 60.48 MB / 8.00 GB
 - Shell: 5.5 - /usr/local/bin/zsh
## Binaries:
 - Node: 8.12.0 - ~/.nvm/versions/node/v8.12.0/bin/node
 - Yarn: 1.12.3 - /usr/local/bin/yarn
 - npm: 6.4.1 - ~/.nvm/versions/node/v8.12.0/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
## npmPackages:
 - styled-components: ^4.1.1 => 4.1.1

## Reproduction

https://codesandbox.io/s/m5xj0pn3qx

## Steps to reproduce

Import a parent component from another file and use it as a selector within the child styled-component

## Expected Behavior

To have the child's styles adapt from the state of the parent.

## Actual Behavior

The CSS seems to get confused when files are imported.

**Comment by mxstbr** [comment]
That is a webpack-issue, it cannot handle cyclical dependencies correctly. If you resolve the cyclical dependency by moving `Outer` to the `InnerTwo` file (as otherwise InnerTwo depends on Outer, but the Outer file index.js also depends on InnerTwo) it works as expected: https://codesandbox.io/s/6wqkkko9kz

There's nothing we can do from our side to remediate that, you'll have to resolve your production cyclical dependency somehow!

**Comment by good-idea** [comment]
Got it, thanks!
