### ISSUE TITLE
Google Mobile-Friendly Test Failing for Gatsby with no CSS via styled-components 

### ISSUE THREAD

**Issue by ahmadawais** [styled-components/styled-components#2267]
I am using Gatsby + styled-components for my new [VSCode course](https://VSCode.pro) site. Everything looks fine on Desktop/Mobile but Google Mobile-Friendly test is failing miserably. Which is costing me SEO and more. 

I am out of options, searched about it and didn't find anything. I think I added the webfontloader plugin since then I started having this issue. But not sure. I've since removed it. Any help would be appreciated.

![image](https://on.ahmda.ws/d5a94e/c)

This is what I see on Google's Mobile-friendly test.

![image](https://on.ahmda.ws/0ab890/c)

### Steps to reproduce

Here's the HTML in case you need it to test. I opened this HTML up and yes, there is actually no CSS to be found. [Click this raw file, it's huge so not adding it here](https://gist.githubusercontent.com/ahmadawais/61b71d5c417b4b9375223b7494ba490a/raw/715a3f46ab64e253f01961a33965cdd740d41695/index.html).

### Expected result

CSS should be loaded by Google Mobile-Friendly test it is not at the moment. I am out of options so creating this issue to get some pointers on what to do. This is what the site should look like. 

![image](https://on.ahmda.ws/78710d/c)

### Actual result

CSS is not loaded :(

![image](https://on.ahmda.ws/d5a94e/c)

Even if I try loading this HTML that I got from Google Mobile-friendly test, this is exactly what I see. No CSS.

![image](https://on.ahmda.ws/2f9d83/c)

### Environment

```sh
 System:
    OS: macOS High Sierra 10.13.5
    CPU: x64 Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.11.0 - ~/.asdf/shims/node
    Yarn: 1.10.1 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.asdf/shims/npm
  Browsers:
    Chrome: 70.0.3538.110
    Firefox: 57.0.1
    Safari: 11.1.1
  npmPackages:
    gatsby: ^2.0.44 => 2.0.44
    gatsby-cli: ^2.4.6 => 2.4.6
    gatsby-image: ^2.0.20 => 2.0.20
    gatsby-plugin-google-analytics: ^2.0.7 => 2.0.7
    gatsby-plugin-manifest: ^2.0.8 => 2.0.8
    gatsby-plugin-offline: ^2.0.13 => 2.0.13
    gatsby-plugin-react-helmet: ^3.0.1 => 3.0.1
    gatsby-plugin-sharp: ^2.0.12 => 2.0.12
    gatsby-plugin-sitemap: ^2.0.3 => 2.0.3
    gatsby-plugin-styled-components: ^3.0.1 => 3.0.1
    gatsby-source-filesystem: ^2.0.8 => 2.0.8
    gatsby-transformer-sharp: ^2.1.8 => 2.1.8
  npmGlobalPackages:
    gatsby-cli: 2.4.3
```

Looking forward, peace! ✌️

**Comment by ahmadawais** [comment]
Here's the Google Mobile-Friendly test I did. You can try it as well.

https://search.google.com/test/mobile-friendly?id=bYfcuuOi_wXmVp2GFrYjSA

**Comment by mxstbr** [comment]
I'm really not sure—that sounds like an issue with the Gatsby plugin!

**Comment by ahmadawais** [comment]
Thanks anyways. Tracking it here #10277

**Comment by rohanbhangui** [comment]
@ahmadawais  @mxstbr I am running into the same issue, using a base create-react-app. I am not convinced that it *isn't* styled components. Because I ran a similar set up for a client using a scss set up and the styles populated correctly.

@mxstbr  as is my understanding nextjs is an SSR evolution on react no?

**Comment by rohanbhangui** [comment]
I wanted to follow this up, because I think its important to understand what is important in the google crawler. It does not matter that the page is styled correctly, but that the content appears and is parsable. With that said a work around would be to allow for a small css file to be crawlable by google (via a robots.txt) + include a small css file that will quickly load at run time and then is overridden by styled component styles.
