### ISSUE TITLE
I get internal server error while running next js app with styled component

### ISSUE THREAD

**Issue by Rahulkishanm** [styled-components/styled-components#2300]
I'm using Next.js with styledcomponent, It gets no error in Dev mode. but while running in Build production mode. I get an error. without line number or file name.

**ERROR**

> 
> NODE_ENV=production node server.js
> 
> Ready on http://localhost:3000 Error: An error occurred. See https://github.com/styled-components/styled-components/blob/master/src/utils/errors.md#1 for more information. Additional arguments: undefined at new StyledComponentsError (/Users/rahulkishan/Documents/React_Mobile_and_web/ReactWebV1/purchaseweb/node_modules/styled-components/dist/styled-components.cjs.js:161:58) at constructWithOptions (/Users/rahulkishan/Documents/React_Mobile_and_web/ReactWebV1/purchaseweb/node_modules/styled-components/dist/styled-components.cjs.js:2182:13) at styled (/Users/rahulkishan/Documents/React_Mobile_and_web/ReactWebV1/purchaseweb/node_modules/styled-components/dist/styled-components.cjs.js:2126:12) at Object. (/Users/rahulkishan/Documents/React_Mobile_and_web/ReactWebV1/purchaseweb/.next/server/static/i2aIDkRZkhvVhtPxvk4BE/pages/index.js:4504:77)

Why it shows this error in Build mode only. Not in dev mode. We have built a large app. It is really difficult to find the problem.

**Comment by mxstbr** [comment]
The full error message is

```
Cannot create styled-component for component: undefined.
```

It seems like you're trying to create a styled-component from an undefined component. The line number you need to look at is

/Users/rahulkishan/Documents/React_Mobile_and_web/ReactWebV1/purchaseweb/.next/server/static/i2aIDkRZkhvVhtPxvk4BE/pages/index.js:4504:77

Good luck!

**Comment by Rahulkishanm** [comment]
I'm sorry again,
how to reverse engineer that line number.
pages/index.js:4504:77

**Comment by martinratinaud** [comment]
@ericyip I'm sorry but I don't get what should be changed to make it work then ?

**Comment by DebOM** [comment]
I was facing this same issue as well! It was mainly happening on production build, and I was unable to reproduce the bug locally!! I found no solution after several hours googling. At the end, I was running the production build locally and discovered I had circular dependent styled component on my split(lazy-load) pages and when one page was loading it didn’t have reference to the exported styled component defined on another page. It works locally because we have webpack running.
**So the best practice is to move the styled components to a separate un-split file**. Try not to export a styled component from a split page that needed reference on another page.
