### ISSUE TITLE
displayName option doesn't work babel-plugin-styled-components plugin

### ISSUE THREAD

**Issue by thian4** [styled-components/styled-components#2318]
I'm using nextjs with jest, enzyme, and styled-component
I have this in .babelrc

```
{
  "env": {
    "development": {
      "presets": ["next/babel"],
      "plugins": [["babel-plugin-styled-components", { "ssr": true }]],
    },
    "production": {
      "presets": ["next/babel"],
      "plugins": [["babel-plugin-styled-components", { "ssr": true }]],
    },
    "test": {
      "presets": ["env", "react"],
      "plugins": [["babel-plugin-styled-components", { "displayName": true }]]
    }
  }
}
```

this is my index.js

```
const Container = styled.h1`
  font-size: 14px;
`
Container.displayName = 'Container'

export default () => (<div>
    <Container>Hello</Container>
</div>)
```

and index.spec.js
```
import React from 'react'
import { shallow } from 'enzyme'
import IndexPage from './index'


describe('Pages', () => {
  describe('Index page', () => {
    it('should render without error', function () {
      const wrap = shallow(<IndexPage/>)
      expect(wrap.find('Container').text()).toBe('Hello')
    })
  })  
})
```
the test will fail if I commnet out this line

```Container.displayName = 'Container'```

**Comment by thian4** [comment]
But doing that you have to export your styled-component?

index.spec.js
```
import React from 'react'
import { shallow } from 'enzyme'
import IndexPage from './index'
import { Container } from './index'
import { enzymeFind } from 'styled-components/test-utils'

describe('Pages', () => {
  describe('Index page', () => {
    it('should have a container', function() {
      const wrapper = shallow(<IndexPage />)
      expect(enzymeFind(wrapper, <Container />).exists()).toBe(true)
    })
  })
})
```

in my index.js I export the styled component

```
export const Container = styled.h1`
  font-size: 40px;
`
```

but no luck with above code, I got error of `Component is not a styled component.`

**Comment by probablyup** [comment]
Try just Container instead of <Container /> in enzymeFind

**Comment by thian4** [comment]
You mean like this?

```
describe('Pages', () => {
  describe('Index page', () => {
    it('should have a container', function() {
      const wrapper = shallow(<IndexPage />)
      expect(enzymeFind(wrapper, Container).exists()).toBe(true)
    })
  })
})

```
I got this error `TypeError: Cannot read property 'styledComponentId' of undefined`

**Comment by SBoudrias** [comment]
Within the snapshot files, it'll instead of using the `displayName` as the component name, it will render as `ForwardRef`.

It looks like the `displayName` is either ignored by enzyme or not set properly by styled-components.

The issue started with the v4 release, this is all working fine with styled-components v3 (before the move to `forwardRef` basically.)

Any ideas how we can moved forward with this?

**Comment by ForestJohnson** [comment]
So I have been hacking on this

A couple things I found so far: 

The crux of where this is happening appears to be here: https://github.com/styled-components/babel-plugin-styled-components/blob/f308f5c9db323712c502e21eaae579f76f3962cf/src/visitors/displayNameAndId.js#L137

Let me back up a bit. I am using a create-react-app project with styled-components added in.  I found out that this file `babel-plugin-styled-components/src/visitors/displayNameAndId.js` is not even being loaded at all. How? Well, I inserted `throw new Error('asd');` into the global scope of the file, and that did not break anything. However, do not fear!  I then went in search of `asd`, essentially trying to get that file to load so it could break my build. 

There are two steps that I had to go through to get this file to be loaded.

### 1.
I changed 
```
  return {
    presets: [
      ....blahblahblah.....
    ].filter(Boolean),
    plugins: [
      ....blahblahblah.....
```
to 
```
  return {
    presets: [
      ....blahblahblah.....
    ].filter(Boolean),
    plugins: [
      ["babel-plugin-styled-components", { "displayName": true } ],
      ....blahblahblah.....
```
in `./node_modules/babel-preset-react-app/create.js`

(https://github.com/facebook/create-react-app/blob/b8ff97be72c02128c0917437d98e1b672a25ceb4/packages/babel-preset-react-app/create.js#L67)

Why do we have to do this? I don't know exactly. It looks like facebook is overriding the default way of  configuring babel here, and in doing so, they have broken babel-plugin-styled-components for most people.

### 2.

I had to somehow coax the create-react-app build system (webpack + babel) to re-compile my :hankey:  so that it could hit the error.  The most reliable way i could find to do this was to intentionally introduce a really flagrant syntax error and then fix it (but then make sure you fix in a different non-binary-equal way each time :face_with_head_bandage: )

After doing these two steps, finally, I was graced by the appearance of `asd` in my terminal:

```
Compiling...
Failed to compile.

./src/components/PhotoContainer.js
Error: [BABEL] /home/forest/Desktop/<project path>/src/components/PhotoContainer.js: asd
```

Even better, not only is that file being loaded, the function is being called! (I moved the `throw` inside the function and I still got it on build).

That if statement in the main exported function of displayNameAndId.js is a monster and especially considering how when I look at it in my node_modules folder I see a transpiled version, its really hard to read or understand, but that did not stop me from inserting `console.log` statements !!!
1st of all at the top of the function i put 
```
console.log('displayNameAndId.js: ' + String(path).split('\n')[0] + ', path.node.tag: ' + path.node.tag);
```

and then inside the function I put: 

```
console.log('displayNameAndId.js: ' + String(path).split('\n')[0] + ', displayName: ' + displayName);
```

Which outputted:

```
Compiling...
displayNameAndId.js: (() => {})(), path.node.tag: undefined
displayNameAndId.js: styled.div`display:flex;justify-content:center;align-items:center;flex-direction:column;flex-direction:asd;flex-direction:asd;`, path.node.tag: [object Object]
displayNameAndId.js: IT WORKED!styled.div`display:flex;justify-content:center;align-items:center;flex-direction:column;flex-direction:asd;flex-direction:asd;`, displayName: PhotoContainer__PODContainer


displayNameAndId.js: styled.div.withConfig({, path.node.tag: undefined
displayNameAndId.js: styled.div.withConfig({, path.node.tag: undefined
displayNameAndId.js: styled.div`display:flex;flex-direction:row;width:80%;`, path.node.tag: [object Object]
displayNameAndId.js: IT WORKED!styled.div`display:flex;flex-direction:row;width:80%;`, displayName: PhotoContainer__ButtonContainer


displayNameAndId.js: styled.div.withConfig({, path.node.tag: undefined
displayNameAndId.js: styled.div.withConfig({, path.node.tag: undefined
displayNameAndId.js: styled.button`width:40%;height:50px;margin:5%;border-radius:10px;font-family:'Audiowide',cursive;font-size:1.5rem;color:#F24222;`, path.node.tag: [object Object]
displayNameAndId.js: IT WORKED!styled.button`width:40%;height:50px;margin:5%;border-radius:10px;font-family:'Audiowide',cursive;font-size:1.5rem;color:#F24222;`, displayName: PhotoContainer__ButtonStyle


displayNameAndId.js: styled.button.withConfig({, path.node.tag: undefined
displayNameAndId.js: styled.button.withConfig({, path.node.tag: undefined
displayNameAndId.js: console.log(props), path.node.tag: undefined
displayNameAndId.js: useState([]), path.node.tag: undefined
displayNameAndId.js: _slicedToArray(_useState, 2), path.node.tag: undefined
displayNameAndId.js: useEffect(() => {, path.node.tag: undefined
displayNameAndId.js: console.log("hello!", response), path.node.tag: undefined
displayNameAndId.js: setAsop(response.data), path.node.tag: undefined
displayNameAndId.js: console.log("Data is not returning", error), path.node.tag: undefined
displayNameAndId.js: React.createElement(Photo, {, path.node.tag: undefined
displayNameAndId.js: React.createElement(ButtonStyle, {, path.node.tag: undefined
displayNameAndId.js: React.createElement(ButtonStyle, {, path.node.tag: undefined
displayNameAndId.js: React.createElement(ButtonContainer, {, path.node.tag: undefined
displayNameAndId.js: React.createElement(ButtonStyle, {, path.node.tag: undefined
displayNameAndId.js: React.createElement(ButtonStyle, {, path.node.tag: undefined
displayNameAndId.js: console.log("woof", asop.date), path.node.tag: undefined
displayNameAndId.js: React.createElement(PODContainer, {, path.node.tag: undefined
displayNameAndId.js: React.createElement(Photo, {, path.node.tag: undefined
displayNameAndId.js: React.createElement(ButtonContainer, {, path.node.tag: undefined
displayNameAndId.js: React.createElement(ButtonStyle, {, path.node.tag: undefined
displayNameAndId.js: React.createElement(ButtonStyle, {, path.node.tag: undefined
displayNameAndId.js: console.log("woof", asop.date), path.node.tag: undefined
```

Hmmm,  how is it that this library which has 10s of fixtures and probably 100s of tests works exactly 0% of the time in the default configuration, and when we hack it enough that it at least turns on and the code starts running, it works less than 50% of the time?  This is why I hate unit tests :man_facepalming:   Unit tests vs users, users always win! every time! 

This is a screenshot of the inspector in my project right now: 

![half-baked](https://user-images.githubusercontent.com/7119703/73054806-f52e9d00-3e50-11ea-9bd5-4ad6f08eee3e.png)

Guess what this user did ? 

They dared to try to comment out things in css. Now, this may or may not be valid css, but check out what happens when I remove that 1 improperly commented line: 

```
export const Title = styled.div `
    // font-weight: bold;
    font-size: 1.7rem;
    margin: 3%;
    color: #F24222;
    text-shadow: 1px 1px white;
    letter-spacing: 3px;
`;
```

I get a lot more `IT WORKED ` lines in the console and I see this: 

![more-baked](https://user-images.githubusercontent.com/7119703/73055001-640bf600-3e51-11ea-9b37-733686dadd76.png)

So, at the end of all of this, this is not my hill to die on and I need to go to bed. Basically this library is just really fragile / turned off by default by `babel-preset-react-app`.

**Comment by kitten** [comment]
@ForestJohnson Please note that this is not the right repo to bring this up :) If you have a concrete bug report or suggestion please open an issue on the `babel-plugin-styled-components` repo so it's actually actionable :+1: https://github.com/styled-components/babel-plugin-styled-components/issues/261

**Comment by ForestJohnson** [comment]
OMG! this is the actual answer to the problem I was having :  https://styled-components.com/docs/tooling#babel-macro

**Comment by Annie-Huang** [comment]
using https://styled-components.com/docs/tooling#babel-macro will failed all my snapshot unit test, errors complains:
TypeError: macro_1.default.<XXX> is not a function

Where XXX can be span, li, etc
Does anyone got the same problem?

**Comment by kitten** [comment]
Closing due to age, lack in details, missing reproduction, or general inactivity.
