### ISSUE TITLE
4.0 - [SSR] ServerStyleSheet's `collectStyles` fails to collect styles from symlinked modules

### ISSUE THREAD

**Issue by damassi** [styled-components/styled-components#2322]
I've recently begun a styled-components 4.0 upgrade on our apps but ran into a hard blocker around SSR, local development and symlinked modules using `yarn link`, which differs from v3. 

Here's a repo reproducing the issue: https://github.com/damassi/styled-components-ssr-issue

**Scenario**: 
Our main website is a complex host environment (shell) that imports React components (Apps) from other NPM modules. When the host receives a route request it performs an SSR render

```js
const html = renderToString(sheet.collectStyles(<App />)
... 
res.send(html) 
```
and sends a payload down to the client, which is then rehydrated on mount. 

When working from a local dev environment each of these modules is symlinked via `yarn link` so dependency changes don't need to be published to npm after each change. 

Because of v4's new [static context API](https://github.com/styled-components/styled-components/blob/master/src/models/StyleSheetManager.js#L15), its no longer possible to `yarn link` submodules and preserve SSR rendering locally as different styled-component modules are now managing their own list of styled-components to render. From the host app it appears as though there's nothing to extract because no styled components have been created in that scope. 

Due to application complexity, it's fairly common to run into SSR reconciliation issues and so disabling SSR during local development is not an option. Is there a way to work around? This appears to be a regression from v3 since symlinked modules + SSR behaved well. 

(Note that the `--preserve-symlinks` suggestion from [this thread](https://github.com/styled-components/styled-components/issues/1969#issuecomment-418715960) doesn't seem to work, and we're not working from a monorepo like Lerna.) 

### Update: 

Was able to resolve via `require-control`; see [this message](https://github.com/styled-components/styled-components/issues/2322#issuecomment-470389460) below.

**Comment by mxstbr** [comment]
In the OP you said:

> that imports React components (Apps) from other NPM modules

Aren't your React component libraries built with webpack or rollup? How are they created?

**Comment by damassi** [comment]
That's how we currently have it (this is SC 3, from `master`): 
https://github.com/artsy/palette/blob/master/package.json#L46

Which is then read into our another component library: 
https://github.com/artsy/reaction/blob/master/package.json#L10

Which is then merged all together into our app server: 
https://github.com/artsy/force/blob/master/package.json#L208

In the top two instances we install it as a `devDep` for local development, but yeah, let's see what happens... one sec.

**Comment by damassi** [comment]
Yup, that works since the only instance of `styled-components` is in the main app folder.

I guess a somewhat flimsy solution would be to write a script that deletes the folder from target locations, but yeah 😄

**Comment by mxstbr** [comment]
Yay! So now the question is how to fix development 😅

**Comment by damassi** [comment]
If one could define a yarn workspace as a folder within the root project's `node_modules` folder that would effectively solve it (for users of `yarn`). Then you could do 

```
{
  workspaces: [
     'node_modules/linked-package-a'
     'node_modules/linked-package-b'
  ]
}
```

Which would then dedup things automatically for those specific folders. 

🤔 I imagine this would blow things up but that said I haven't tried. Let me see...

**Comment by damassi** [comment]
@mxstbr - Should this issue be reopened?

**Comment by probablyup** [comment]
Well it's not an issue with the library, more an environmental restriction. For that reason I would not reopen this issue. If you feel there's a deficiency in our docs though, I'd welcome a PR there.

**Comment by knieber** [comment]
@damassi We've just started running into the same situation with our project. It works fine when compiling with babel and then adding `styled-components` as a `peerDependency` and pulling down the published code from npm, however it isn't working when linking. I even looked at your component library repo, and it appears we're doing things very similarly. Did you all find a way to get this working with local development? Did using a `yarn workspace` work?

**Comment by probablyup** [comment]
My guess is the Babel plugin needs to be deduped too

**Comment by damassi** [comment]
@knieber - Nope, we weren't able to get things working and a `yarn workspace` is a _very_ tricky thing to bolt on to an already complex app :) 

Our work around was to setup [this command](https://github.com/artsy/force/blob/master/package.json#L31) in our main host app, which is a band-aid:

```
$ main-app/
$ main-app/ cd ../some-dep
$ some-dep/ rm -rf node_modules/styled-components
$ some-dep/ yarn link
$ some-dep/ cd ../main-app
$ main-app/ yarn link some-dep
$ main-app/ yarn start
```

**Comment by knieber** [comment]
@probablyup @damassi appreciate the quick responses! I'm going to be trying both. Currently the steps in that script aren't working for me when using `npm link` instead of `yarn link`, so I'm going to try to refactor to `yarn` to see if that'll help. We have the same exact workflow for our UI team (Using storybook and having multiple component libs depend on other component libs). I may look into the sharing context solution as well and will holler if I find anything substantial.

**Comment by damassi** [comment]
> We have the same exact workflow for our UI team (Using storybook and having multiple component libs depend on other component libs).

This is indeed a common workflow for apps and teams. It worked well with Styled Components 3 so I'm hopeful that a more formal solution can be discovered at some point. Thanks for looking into it @kneiber!

**Comment by damassi** [comment]
Ok @knieber, @probablyup - I think I've found a potential solution via [require-control](https://github.com/theKashey/require-control). Hasn't been extensively tested, but looking good so far:

```
const { setAliases } = require("require-control")
const path = require("path")

setAliases({
  "styled-components": path.resolve(
    path.join(__dirname, "../node_modules/styled-components")
  ),
})
```

Obviously this isn't totally ideal as it's doing some require hacking but seems sufficient for our use-cases.

**Comment by damassi** [comment]
Want to note that I discovered `require-control` via this [react-hooks problems](https://github.com/facebook/react/issues/13991) thread. When rolling hooks out to our codebase we ran into something similar as here.

**Comment by knieber** [comment]
@damassi Sorry, just now getting back to this. Actually, I'm now having a problem with `exports is not defined` when linking our component library (build with babel) with our main app (using webpack on top of Next.js). A lot of things are abstracted away, so I'm getting a little lost on how to fix this problem first before getting styled-components to resolve. I'm assuming it's because of duping issue with babel (since babel is also used in our main app), but it's not as trivial as I expected it to be! It's only an issue when linking though. I'll update you once I get there!

Note: a temp workaround that we found was using [Yalc](https://github.com/whitecolor/yalc) to publish npm packages locally onto your machine, without actually publishing to npm. It's far less than ideal, but thought I'd spread the love.

**Comment by knieber** [comment]
Finally figured out by babel dupe-ing issue (component lib had a babel-core 6 dependency from storybook) and just got back to the styled-components instancing issue. The `require-control` solution worked perfectly @damassi. Thanks so much!

**Comment by damassi** [comment]
Yeah! Our team was psyched to discover it. I should probably open a PR to update SC's docs.

**Comment by mxstbr** [comment]
We would _love_ a PR @damassi!!!

**Comment by carlesnunez** [comment]
I've opened a pr in order to add this info to npm link issues on FAQ. Special kudos to @damassi for his amazing investigation in this issue. You saved my day dude!


https://github.com/styled-components/styled-components-website/pull/468

**Comment by benjamingeorge** [comment]
> ```js
> const { setAliases } = require("require-control")
> ```

Where would this code go?  my webpack config file?

**Comment by vongohren** [comment]
@knieber @damassi Im struggeling a bit with the same setup now.

I have a component library we want to use for web and SSR, which is styled with styled components. We run webpack and babal on this library so we can import it around.
But we also have yarn workspace, meaning the styled-components and the babel plugin is hoisted and then using the same package I guess.

When collecting styles from the SSR app, there is no CSS available. When collecting styles from the component library, the CSS is coming out when run on the server side, crashes when running in the browser of course.

Im just not seeing why this require would help for me? As they are already sharing packages.

Is it something to do with the webpacking im doing that the styles are dissapearing when loaded in an SSR environment?

Because after the client is loaded by next.js, the styles are also applied.

Im a bit lost :(
I tried emotion, that had more problems. I tried https://github.com/callstack/linaria, that worked, but it has not been updated in a while, and do not have react native support. That worked because you could extract css at compile time, and just import it in the ssr environment

**Comment by vongohren** [comment]
I have a reproducable setup here, if anyone are able to get any of the packages, preferebly styled-components, to work here. With no FOUC, I would be super happy!

https://github.com/vongohren/fouc-example

**Comment by vongohren** [comment]
@mxstbr any thoughts, base on this repo?

**Comment by Mathias54** [comment]
For those who're using lernajs adding styled-components as `peerDependencies` should work.

**Comment by WaleedAli070** [comment]
well, for me, adding `styled-components` to `peerDependencies`, in my lerna packages, didn't work with `yarn link`. 

What worked for me was creating a `.tgz` file of my packages using `npm pack` and then installing these packages via `npm install path/to/tgz` in my consumer application. 
The caveat was for each change in my library/packages I had to rebuild the package, clear the npm cache, and then reinstall these dependencies in my consumer application.

I know this is an ugly solution but this is the only one that worked for me.

**Comment by fritzlolpro** [comment]
What worked for me is aliasing styled components to the the instance I need. Without it styles probably got compiled with worng instance of SC.
In my next.config.js I added 

```
module.exports = nextTranslate({
   //...
    webpack: (config, options) => {
        //...
        config.resolve.alias = {
            ...config.resolve.alias,
            'styled-components': path.resolve(
                path.join(__dirname, 'node_modules/styled-components')
            ),
        };
        return config;
    },
});
```

Hope this will help somebody (me in future for example)

**Comment by PrashanPudasaini** [comment]
I was facing similar issue where the myApp was not collecting styles from the symlinked module. I was able to resolve the issue by adding styled-components as a peer dependency in my component library and then doing npm link myApp/node_modules/styled-components from my library's root directory.
