### ISSUE TITLE
Impossible to style ForwardRef using v4

### ISSUE THREAD

**Issue by marcuslindfeldt** [styled-components/styled-components#2325]
This issue https://github.com/styled-components/styled-components/issues/1990 does not seem to be solved yet.

## Environment
```
## System:
 - OS: macOS 10.14.2
 - CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
 - Memory: 490.21 MB / 16.00 GB
 - Shell: 4.4.23 - /usr/local/bin/bash
## Binaries:
 - Node: 10.14.1 - ~/.nvm/versions/node/v10.14.1/bin/node
 - Yarn: 1.12.3 - /usr/local/bin/yarn
 - npm: 6.5.0 - ~/.nvm/versions/node/v10.14.1/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
## npmPackages:
 - babel-plugin-styled-components: ^1.10.0 => 1.10.0
 - styled-components: ^4.1.3 => 4.1.3
```

## Reproduction

See related issue.

## Expected Behavior

styles should be applied when using `styled(ComponentWithForwardRef)`

## Actual Behavior

styles are not applied

**Comment by marcuslindfeldt** [comment]
It seems to be the combination with a default 'as' prop and `React.forwardRef` that is causing the styling to break. See the related codesandbox.

https://codesandbox.io/s/6vrx30rjpk

**Comment by probablyup** [comment]
This is a slightly complicated one but the issue is setting "as" as a defaultProp. forwardRef + styled() hoists that defaultProp all the way to the topmost layer, which the topmost `styled()` picks up and then basically erases the underlying forwardRef(Button) since when you wrap a custom component with styled() it totally swaps out what's rendered.

The fix here is to do `as = 'button'` as a default assignment in the forwardRef function.

**Comment by jquense** [comment]
This seems like bug no? why is the recommendation to not use defaultProps as they are intended?

It's less than ideal that we've got change all our component definitions in react-bootstrap (https://github.com/react-bootstrap/react-bootstrap/issues/3595), which also has effects on typescript typing, because of this.

is there an alternative where SC plays nicely with the underlying component and doesn't assume it owns any prop named `as`. This is likely to effect some of react semanatic-ui as well which also uses the `as` prop in this way

**Comment by jquense** [comment]
what about only hoisting `as` when the underlying component is actual a Styled component, e.g. a component tagged with an internal flag, like [astroturf](https://github.com/4Catalyzer/astroturf/blob/master/src/runtime/styled.js#L17) does
