### ISSUE TITLE
[React Native] attrs ignored unless defaultProps is set

### ISSUE THREAD

**Issue by maxschmeling** [styled-components/styled-components#2345]
## System:
 - OS: macOS 10.14
 - CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
 - Memory: 41.16 MB / 16.00 GB
 - Shell: 5.3 - /bin/zsh
## Binaries:
 - Node: 11.3.0 - ~/.nvm/versions/node/v11.3.0/bin/node
 - Yarn: 1.12.3 - /usr/local/bin/yarn
 - npm: 6.4.1 - ~/.nvm/versions/node/v11.3.0/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
## npmPackages:
 - styled-components: ^4.1.3 => 4.1.3

## Reproduction

https://snack.expo.io/@maxschmeling/styled-components-defaultprops-issue-reproduction

## Steps to reproduce

Create an `ActivityIndicator` styled component and attempt to set `size` with `attrs`.

## Expected Behavior

Size should be set.

## Actual Behavior

The properties in attrs are completely ignored.

## Workaround

Set the returned styled-component's `defaultProps` to `{}`.

**Comment by maxschmeling** [comment]
I realized this is because `ActivityIndicator` defines `size` and `color` in `defaultProps` so I can get around it by doing this:

```
const component = styled(ActivityIndicator).attrs({ color: "green" })` // styles `;
component.defaultProps = { ...ActivityIndicator.defaultProps };
delete component.defaultProps.size;
delete component.defaultProps.color;
```

I'm sure I'm just over-complicating this and there's a simple way to override default props, right?

**Comment by mxstbr** [comment]
This should help, right? #2260

**Comment by maxschmeling** [comment]
@mxstbr unless I'm missing something, I don't think it helps with this issue. The issue here is that `defaultProps` from the underlying component overrides the values being set in `attrs`. What makes it worse is that there is no indication of what is happening. Since I didn't realize that `ActivityIndicator` got its `size` and `color` from `defaultProps`, I didn't have the slightest clue why it was ignoring my `attrs` values.

**Comment by oomathias** [comment]
@mxstbr @maxschmeling  I still have to apply the fix to `StyledNativeComponent`, and defaultProps would be overridable. But as I described here https://github.com/styled-components/styled-components/pull/2258#issuecomment-444950078 since 4.1.2, `ActivityIndicator` which isn't a styled component (div on my graph) will receive the defaultProps color and not attrs color.

This would work, but color would be overridable when you use component.
```js
component.defaultProps = { ...ActivityIndicator.defaultProps, color: 'green' };
```

**Comment by maxschmeling** [comment]
@oomathias That `defaultProps` override definitely works, but there are two things to consider I think:
1. My *expectation* as someone who hasn't worked much with `styled-components` internals is that using `attrs` is essentially the same thing as passing the props when you use the component. Maybe that isn't a good way to look at it, but that was my mental model of it. Which is why I was completely lost when it appeared to be completely ignoring my values.
2. Once you know what is needed, the `defaultProps` override works fine if the value is static. But it doesn't allow for dynamic values based on `props` like `attrs` does, so it is limited.

**Comment by oomathias** [comment]
@maxschmeling I totally agree with you, that's why I started a PR to change how attrs are merged and how dynamic attrs are handled. Even if I don't agree with the actual design, I respect the core team position on it. That's why I created this graph to show how it actually works, I think it should be documented and tested. There is actually no way to handle dynamic attrs (unless we reopen my PR).

**Comment by probablyup** [comment]
This is fixed in later versions of s-c v4
