### ISSUE TITLE
Client-side nonce support

### ISSUE THREAD

**Issue by pgsandstrom** [styled-components/styled-components#2363]
I am trying to craft an intelligent Content-Security-Policy while using styled-component. The suggested solution to this seems to be to [use SSR to set the __webpack_nonce__ variable](https://github.com/styled-components/styled-components/issues/887), ensuring that webpack inlines in in all created style-tags. However, I cant find a solution to this problem when you are not using SSR.

Without knowing the internals of styled-components, it seems to me that it should be possible to specify a nonce in a non-ssr environemt. Something like:

```
import { setNonce } from "styled-components"
setNonce(myNonce)
```

This would allow users to craft their own solutions that is independent from both SSR and webpack. In my use case it would be trivial to inject a unique nonce with every page request, even though SSR is not feasible.

**Comment by mxstbr** [comment]
I think you should be able to set `window.__webpack_nonce__` on the client-side and we will pick it up, maybe? If we don't, we definitely should! /cc @kitten let's build that into #2357 maybe?

**Comment by probablyup** [comment]
I think @mxstbr is right that it should be picked up if put on the window object prior to s-c being instantiated

**Comment by mattcosta7** [comment]
Trying to use the nonce setup in a clientside only environment, and getting some weird behavior, in which even after declaring the __webpack_nonce__, calls to `getNonce()` return undefined, rather than null/nonce. It looks to be a scoping/access issues accessing the raw variable, instead of accessing it on the global/window objects?

I'll take a look and try to get a pr up

**Comment by leoyli** [comment]
Any progress here?!  I think this one is quite important, and it seems already have other CSS-in-JS lib does that.  For example, JSS use `<meta>` tag to pickup nonce: https://github.com/cssinjs/jss/blob/master/docs/csp.md. Could we do the same here?! Although I'm not sure if that is speedy mode compatible? CSSOM is still pretty new to me...

**Comment by leoyli** [comment]
Sorry I get a bit confused... so it seems SC will lookup `window. __webpack_nonce__` and pick up the value for style injection? Am I correct?! So is this issue are trying address the use case like CDN or website generated by SSG and have no server-side capabilities?

**Comment by leoyli** [comment]
After some hard time... I can not get SC works with CSP styled-src nonce (@ v4, v5.beta-8)... I did ensure `__webpack_nonce__= 'myNonce'` get executed before any other scripts, but I still can not see anything except these CSP errors... where I did wrong?

**Comment by leoyli** [comment]
Ah... I now get it worked. I guess it is more on on how to do in the Webpack setup.  And it have to do with Webpack, I can not just inject `window.__webpack_nonce__` in my HTML shell alone.  We need to do `__webpack_nonce__= window.__webpack_nonce__`. Ref: https://github.com/styled-components/styled-components/issues/887#issuecomment-376858712

1. This is a bit daunting... Can you do something similar to JSS folks that uses `<meta>` tag for grabbing nonce?

2. Somewhere in the documentation need to really document this... or is SC already did?!  I can not search in the site with the corresponding keywords about CSP, and `__webpack_nonce__`...

**Comment by flosch-hb** [comment]
Disclaimer: I may not be 100% aware of all the Content-Security-Policy directives implications.

From what I understand of the notion of the `nonce` attribute, it only makes sense if it is used once (e.g. generated per request, using server-side rendering)

If it is statically defined at build-time and served with the same value on every request, there is nothing preventing a malicious person to add that attribute since that person would easily be able to know it (unless I completely misunderstand its purpose)?

However, to have styled-components working on a locked down CSP, on a client-side only environment, it may be possible to use the `hash` policy, which works in a [very similar way](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/style-src), with the same goal: whitelist some part of the inline scripts/styles served with your HTML page, but instead of being attributed a one-shot token by the server, it consists in a hash of that <style> content itself.

I think the scenario would look like (at build time):
- for each style
  - create a sha-* hash of the content and keep it somewhere in memory
- expand all created hashes as part of the `style-src` directive of the CSP

Does `styled-components` currently provide a way to get those hashes at build time?

More informations about `nonce` and `hash`:
https://developers.google.com/web/fundamentals/security/csp/#if_you_absolutely_must_use_it

**Comment by leoyli** [comment]
@flosch-hb, not sure if how the hash would really works here.  If I understand it correctly, the hash is derived from the `<style>...</style>`, which means it is static and expended.  This seems not so desire and may have performance overhead (the same problem with the traditional CSS file that load all rules in a big shot). And if I were correct, the production build will inject rules via CSSDOM, the so call speedy mode.  We still need a `<style>` tag that is CSP accepted, but it would be just an empty tag, then the hash doesn't make sense neither.

And based on the the reference provided.  It seems the current magic that Webpack is playing also not fit with the best practice due to it require us to call inline script to inject `window. __webpack_nonce__`, which is hard to be moved out as a stand lone file due to the fact that they are in a separated resource request.

That is, it seems the best we can get is to use JSS approach to inject nonce via `<meta>` tag, although I'm still doubting as if it really that secure (the vector to get the nonce value is wildly clear...).

**Comment by flosch-hb** [comment]
Very enlightening @leoyli, thanks for the explanations :)

The hash is indeed calculated from the `<style>` content itself, so if there is an API programatically updating that element at runtime, the hash would change, and that strategy will not work.
(I did not know how speedy worked)

Regarding the other strategy: injecting the `nonce` as a meta tag would still be done at build time then?

**Comment by tihuan** [comment]
Our project is currently enhancing CSP and having a similar discussion regarding nonce vs. hash.

It feels like for our publicly cached pages, nonce approach won't work, since nonce won't change per request. And hash is not working too well so far, because we lazyload components, so SC will inject stylesheets that aren't available in the header!

The CSP journey continues lol

**Comment by JoeHart** [comment]
Howdy Gang,

To add another piece of support for client side nonce setting, or more specifically support for setting the nonce *after* intialization, the new way of doing a CSO `nonce` inside nextjs seems impossible to get working with `styled-components`.

For context we initially found that nextjs v10 didn't work with a strict CSP which we raised with them here: https://github.com/vercel/next.js/issues/18557

We've managed to get that approach working fine with CSS Modules, however for styled-components we can't get the nonce to pass to styled components.

This integration test from the nextjs repo is similar to our set up: https://github.com/vercel/next.js/tree/canary/test/integration/css-fixtures/csp-style-src-nonce

Where on each render, server or client, we generate a new nonce and pass it into the head:
```
export default class MyDocument extends Document {


  render() {

    const nonce  = generateNonce()

    return (
      <Html>
        <Head nonce={nonce}>
          <meta httpEquiv="Content-Security-Policy" content={getCSP(nonce)} />
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    )
  }
}
```

Things I've tried:
- Setting `window.__webpack_nonce__` on the page: ❌ Not detected

**Comment by TheoMer** [comment]
@JoeHart Have you managed to resolve csp with next.js/styled-components at all?

I've managed to get an 'un-ideal' solution (no new nonce on each render) working, but that involves specifying
both the nonce and csp on my express entry file, which I do as follows:

server.js
```
const server = express();

csp(server);
```

csp.js
```
module.exports = function csp (server) {
    //Set nonce
    server.set('styleNonce', Buffer.from(uuidv4()).toString('base64'));
    server.set('nonce', `'nonce-${server.get('styleNonce')}'`);

    server.use((req, res, next) => {
        res.locals.styleNonce = server.get('styleNonce'); // Passed to NextJS
        __webpack_nonce__ = server.get('styleNonce');
        next()
    });

    const nonce = `${server.get('nonce')}`;
    const styleSrc = ["'self'", "'unsafe-inline'", 'https://*.myurl.co.uk'];

    // In dev we allow 'unsafe-eval' and 'unsafe-inline', so HMR doesn't trigger the CSP
    if (process.env.NODE_ENV === 'production') {
        styleSrc.push(nonce); //Note: next/image inline styles are still an issue in next 10.0.6-canary.7
    }

    // Content Security Policy
    server.use(
        helmet.contentSecurityPolicy({
            directives: {
                styleSrc,
                ......
            }
        })
    );
}
```

_document.js
```
const inlineScript = (body, nonce) => (
  <script
    type='text/javascript'
    dangerouslySetInnerHTML={{ __html: body }}
    nonce={nonce}
  />
)

export default class MyDocument extends Document<Props> {
  static async getInitialProps (ctx) {
    const sheet = new ServerStyleSheet()
    const originalRenderPage = ctx.renderPage

    try {
      ctx.renderPage = () =>
        originalRenderPage({
          enhanceApp: App => props => sheet.collectStyles(<App {...props} />)
        })

      const initialProps = await Document.getInitialProps(ctx)
      const { styleNonce } = ctx.res.locals

      return {
        ...initialProps,
        styleTags: (
          <>
            {initialProps.styles}
            {sheet.getStyleElement()}
          </>
        ),
        styleNonce
      }
    } catch (error) {
      console.error(error)
    } finally {
      sheet.seal()
    }
  }

  render() {
    const { styleTags, styleNonce} = this.props;
    return (
      <Html lang="en" prefix="og: http://ogp.me/ns#">
        <Head nonce={styleNonce}>
          {inlineScript(`window.__webpack_nonce__="${styleNonce}"`, styleNonce)}
          {styleTags}
        </Head>
        <body>
          <Main />
          <NextScript nonce={styleNonce} />
        </body>
      </Html>
    );
  }
}
```

**Comment by alex-r89** [comment]
@TheoMer have you made any updates to this - specifically in your `_document.js` at all? I also cant get this working with NextJS using the styled-components NextJS example.
I may need to move off of styled-components if I cant get it working with my CSP, which I dont want to do :/

**Comment by TheoMer** [comment]
> @TheoMer have you made any updates to this - specifically in your `_document.js` at all? I also cant get this working with NextJS using the styled-components NextJS example.

Unfortunately not 🙁

**Comment by fr-nevin** [comment]
Sz@TheoMer @alex-r89 Did you guys manage to find any viable solution for SSR inline styles in styled components?

**Comment by fr-nevin** [comment]
@TheoMer Did you manage to find any viable solution for SSR inline styles in styled components?

**Comment by kitten** [comment]
I think this issue has become a bit bloated and long. To give a bit of context, I have never encountered any need to work on CSP nonces and am a little bit unexperienced in the area. The same probably goes for the SC team in general. The problem is that we've never really received much input of the _entire_ space, the goal, and one explanation of what's needed. So we're left with a couple of bits here and there for support. Sometimes we get API suggestions, but without knowing the entire context, it's tough to resolve a proposal or accept it if we only get a proposal for a solution, but not the entire problem statement.

So, my approach to this for now is, this issue is full of unrelated comments potentially, and it's pretty hard to sift through this. I'm happy to discuss any changes that are necessary in new issues, which will no doubt follow ❤️ But I'll lock this issue and am happy to address a wider "strategic change" of the CSP approach for v6.
