### ISSUE TITLE
Use styled-components without wrapping the component

### ISSUE THREAD

**Issue by sylvain-hamel** [styled-components/styled-components#2411]
I would like to be able to call styled-component in a way the will generate a className without wrapping a component. I have a case where I want to get a className from a styled-component style block, but outside a react component.

Maybe something like:

```
var bigTitleClassName = styled`
  font-size: 22px;
`
```

And later pass this className to a component that knows nothing about styled-components?

```
<div className={bigTitleClassName}/>
```

Is this feature already available?

**Comment by probablyup** [comment]
We're considering something like this for v5 as a hook. Feel free to follow along: https://github.com/styled-components/styled-components/issues/2342#issuecomment-456121567

**Comment by InvictusMB** [comment]
@probablyup 
I don't entirely agree that this topic should be a subset of hooks discussion.
It specifically mentions the use outside of react components. This is more of a generic interop concern about style sheets created with styled components.

Anyway, in my case I'm looking for this kind of API to improve interoperability with Material UI components. The approach proposed [here](https://material-ui.com/guides/interoperability/#e-deeper-elements) is not good enough.
It forces using hard coded class names for nested elements which kind of kills the whole premise of using styled components.

I would prefer to have instead a pattern like this:
```es6
const labelStyle = css`
  color: palevioletred;
`;

const StyledButton = styled(MUI.Button).attrs({
  classes: {
    label: labelStyle
  }
})`
 background: papayawhip;
`
```
In fact I was able to do that with `emotion` but I'm hesitant to switch from `styled-components` because of an awful mess (as of April 2019) of APIs and packages in `emotion` ecosystem.

**Comment by InvictusMB** [comment]
@sylvain-hamel 
`css` function from `emotion` package [does exactly what you ask for](https://emotion.sh/docs/emotion#css).
Although it requires some caution to not be confused with `css` from `@emotion/core` which does a different thing.
