### ISSUE TITLE
Context.Consumer.Provider warning

### ISSUE THREAD

**Issue by ingelity** [styled-components/styled-components#2412]
## Steps to reproduce
install react 16.8.3 and styled components 4.1.3 and can reproduce it with any code basically, e.g.:
```
const StyledDiv = styled.div`
  color: red;
`;

const App = () => <StyledDiv>styled div</StyledDiv>;


```
## Expected Behavior
no warning should be logged to console

## Actual Behavior
the following warning is logged to console:
_Warning: Rendering <Context.Consumer.Provider> is not supported and will be removed in a future major release. Did you mean to render <Context.Provider> instead?_

**Comment by probablyup** [comment]
I'm using the latest version as well and don't see this, so it probably is something in how you're using the library. We recommend always trying to make a fresh codesandbox when you have an issue so you know it's reproducible and we have something to actually look at.

**Comment by GiancarlosIO** [comment]
@probablyup @ingelity in my case it was because the babel-loader was not excluding the node_modules folder, I note it because my console shows me a message. After adding the `exclude: /node_modules/` to my webpack-loaders the warning disappeared.

https://stackoverflow.com/questions/29576341/what-does-the-code-generator-has-deoptimised-the-styling-of-some-file-as-it-e/#answer-29854598
