### ISSUE TITLE
Renaming `__DO_NOT_USE_OR_YOU_WILL_BE_HAUNTED_BY_SPOOKY_GHOSTS`

### ISSUE THREAD

**Issue by Glazy** [styled-components/styled-components#2478]
Hey :wave:

After reading through another issue about this (#2475) it seems like there aren't any plans for `__DO_NOT_USE_OR_YOU_WILL_BE_HAUNTED_BY_SPOOKY_GHOSTS` to be deprecated as `jest-styled-components` depends on it.

I think in that case it probably makes sense to rename this back to whatever it was called before or something else :+1:

Let me know what you think, I would be more than happy to submit a PR for this! 👊

**Comment by kitten** [comment]
So some clarification here, it was never called something else and was purely intended to hold the StyleSheet.

The reasoning behind that is rather simple, if we find a new way to manage stylesheets that changes their － otherwise rather stable  －  API then we're left with bumping the major version.

It's a class that is highly connected to how our internals work but doesn't affect our public API otherwise. Hence ServerStyleSheet is also separate.

Even with prior changes we don't change Stylesheet's API that often, but we want to make it clear in the code that it's not a public or stable API that might change to give us room for improvements. It's still exposed as an escape hatch, but the import name makes clear that it's just that.

Hope that makes sense :)

**Comment by Glazy** [comment]
That makes sense, thanks for the quick response @kitten :+1:
