### ISSUE TITLE
Unable to extend custom component's style

### ISSUE THREAD

**Issue by davibe** [styled-components/styled-components#251]
I have created this example

http://www.webpackbin.com/NJ2MWWxGG

WorkingButton.js exports a `styled.button` with custom style.
Button.js exports a `styled(MyButton)` with the same custom style.

In main.js
- the former can be extended with some more styling to create `ButtonBlue`. The rendered style for ButtonBlue is a merged version of the 2 styles.
- the latter can't be extended. Styles stop working as I would expect.

**Comment by mxstbr** [comment]
I can't visit the webpack bin (it's set to live mode, you need to un-live mode it), but I reckon the issue is that you're not attaching the passed in class name to your `MyButton`. See this doc page: https://github.com/styled-components/styled-components/blob/3e5d63fd71ad06c37cfb5fe6bc8e77553ddc0fb2/docs/existing-css.md#styling-normal-react-components

Let me know if that fixes the issue!

**Comment by davibe** [comment]
do you still see it in live mode ?

**Comment by mxstbr** [comment]
I think all of these issues will actually be fixed by #227?
