### ISSUE TITLE
Commented JS inside tagged template literals (strings) will still run

### ISSUE THREAD

**Issue by isaacalves** [styled-components/styled-components#2518]
If there's JS in a tagged template string and it's commented out (like in the example below), it will still run. 

Why does that happen and how can it be prevented?

```
import { createGlobalStyle } from "styled-components";
import reset from "styled-reset";

export default createGlobalStyle`
  /* the following line will run even though it's commented */
  /* ${reset} */
`
```

It's also particularly confusing as I'm using the **vscode-styled-components** extension which properly highlights comments inside styled-components' tagged template strings.

**Comment by aczekajski** [comment]
You cannot prevent executing of javascript inside `${}` because it's how the language works: `/*` is only a string that happened to be before this particular interpolation. The interpolated expression might actually return the comment closing tag (don't ask why someone would do this) and in my opinion it will 
feel inconsistent if the behoviour was different whether `reset` was a function returning it (which technically could be prevented by SC) or just a string with it.

This is related: https://github.com/styled-components/vscode-styled-components/issues/113 - it's a bug in vscode-styled-components which gives misleading code coloring.
