### ISSUE TITLE
"as" prop is breaking rebass component usage

### ISSUE THREAD

**Issue by mikedloss** [styled-components/styled-components#2545]
## Environment
`npx envinfo --system --binaries --npmPackages styled-components,babel-plugin-styled-components --markdown --clipboard`
```
## System:
 - OS: macOS High Sierra 10.13.6
 - CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
 - Memory: 138.20 MB / 16.00 GB
 - Shell: 5.3 - /bin/zsh
## Binaries:
 - Node: 8.11.2 - /usr/local/bin/node
 - Yarn: 1.13.0 - /usr/local/bin/yarn
 - npm: 6.7.0 - /usr/local/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
```

## Reproduction
https://codesandbox.io/s/56pvp6y5x

## Steps to reproduce
I created 2 components directly viewed in the codesandbox link - 1) a custom "passthrough" component that is wrapped by a `styled` tag, and 2) a Rebass component wrapped by a `styled` tag. In the codesandbox link, I have a few examples. The issue comes up when the `as` prop is being used.

## Expected Behavior
Both the passthrough and rebass components should be styled when being passed styling props (according to rebass/styled-system documentation), regardless of there being an `as` prop being passed to either component.

## Actual Behavior
The `as` prop is causing the 1st component to not have any styling, OR render the passthrough component at all.

**Comment by probablyup** [comment]
Please use the new `forwardedAs` prop introduced in 4.3.x 😄 

https://www.styled-components.com/docs/api#forwardedas-prop

**Comment by probablyup** [comment]
So when you wrap a custom component (non primitive, aka "div" or non-styled-component) in our HOC, e.g. `styled(CustomComponent)` if you use the `"as"` prop, that actually totally replaces the underlying component being rendered similar to the `.withComponent` API.

Since rebass components are styled-components, wrapping a rebass `Box` in `styled()` is totally fine, however in the case of your `BoxOne` component which introduces an interim function component, it's no longer a styled-component and you need to use the new `forwardedAs` prop to send your intended `"as"` down to the lower component layer.

Here's your sandbox updated: 
https://codesandbox.io/s/styled-components-rebass-bug-18fnp?fontsize=14

**Comment by probablyup** [comment]
This will be a lot more straightforward if https://github.com/facebook/jsx/issues/81 was implemented, in which case you could just specify where the "as" prop should be consumed via the namespace key :sigh:

**Comment by mikedloss** [comment]
Thanks a lot for updating this @probablyup ! Good to know it was addressed 😃

**Comment by chasemccoy** [comment]
@probablyup Was the `forwardedAs` prop reverted or is it still available?

**Comment by probablyup** [comment]
@chasemccoy It's in 4.3.x
