### ISSUE TITLE
How to use CSS props for Dynamic React Component

### ISSUE THREAD

**Issue by SubhuMS** [styled-components/styled-components#2680]
import React, { Component } from 'react';
import Button from '../Button';
import Link from '../Link';

```
class App extends Component {
 render() {
  let DynamicComponent =props.button ? Button : Link;
  return ( <DynamicComponent css="color: red" /> )
}
}
```
 
When trying to execute the above code, i am getting the below error,

ReferenceError: DynamicComponent is not defined, 

Can anyone help how to use CSS prop in dynamic component.

**Comment by kettanaito** [comment]
Hi. The issue seems to be that `DynamicComponent` doesn't exist. That doesn't look like an issue with Styled Components per say.

What would be the output of `console.log({ DynamicComponent })` if you add that statement after `let DynamicComponent` line? Perhaps `props.button` is wrong, or either of `Button` or `Link` are undefined/exported in a wrong way.

**Comment by probablyup** [comment]
@SubhuMS This _should_ be working with later versions of the babel plugin.

**Comment by mdugue** [comment]
@probablyup we just stumbled upon this problem. Are there any news available?

**Comment by seaneking** [comment]
I'm also seeing this, isolated to styled components because the exact same component worked well with Emotion before porting.
