### ISSUE TITLE
v5 RTL - StyleSheetManager, stylisPlugins and stylisRTLPlugin

### ISSUE THREAD

**Issue by mario-iliev** [styled-components/styled-components#2703]
Hello.

**Off-topic:**
Before everything I want to thank you for your amazing work and making the world a better place :)
Several years ago I had to add RTL support in a fairly big project and it was the biggest pain I've experienced :)
Now I had to do this again in a different project and while researching I got more than happy that SC provided an amazing solution to it.

**On-topic:**
Short problem description: stylisPlugins is not applied dynamically and never re-run;

Packages that I use:
```
"react": "^16.8.6",
"styled-components": "^5.0.0-beta.6",
"stylis-rtl": "^1.0.1"
"i18next": "^17.0.9",
```

I'm using "StyleSheetManager" and "stylisRTLPlugin" to accomplish the RTL support.
It's working if the website is initially loaded with rtl direction.
The problem is that "stylisRTLPlugin" has no "dir" detection so you either use it or not.
If you change the website language trough the UI from ltr language to an rtl nothing happens.
First I tried this:

```
import { StyleSheetManager } from "styled-components";
import stylisRTLPlugin from "stylis-rtl";

<StyleSheetManager stylisPlugins={props.dir === "rtl" ? [stylisRTLPlugin] : null}>
  <App />
</StyleSheetManager>
```

When I change the language in the website, the console says this:
"stylisPlugins are frozen on initial mount of StyleSheetManager. Changing this prop dynamically will have no effect."

Since we don't have any dynamic plugin mechanics, I tried something **very dirty**, I added key={dir} to the `<StyleSheetManager>`.
This of course solved some problems and created ton of others, like creating new styles in parallel of the old ones:

```
.SxmYk {
    margin-right: auto;
}

.SxmYk {
    margin-left: auto;
}
```

Currently my only solution is to refresh the page if I switch between languages with different "dir".
I'll be forever grateful if anyone can give me a solution to this case.

**Comment by ShadOoW** [comment]
Hello @mario-iliev

First of all, I'm a beginner at this, first time trying to solve the RTL problem with styled-component.

I came across the beta for V5 while trying to solve it, but I find it hard to setup with nextjs without an example code, so it would be great of you could share your setup for me to play with.

```
It's working if the website is initially loaded with rtl direction.
The problem is that "stylisRTLPlugin" has no "dir" detection so you either use it or not.
If you change the website language trough the UI from ltr language to an rtl nothing happens.
```

If this is correct then I don't think it is possible to change direction at runtime, because the styles are missing from the loaded css.

To make it work at runtime, the css has to be already loaded, and you should have a css selector to detect if dir is LTR or RTL.
based on this solution here: https://github.com/styled-components/styled-components/issues/844#issuecomment-457568491

I wrote this: https://codesandbox.io/s/styled-components-rtl-5rl5v which adds 2 functions ```dir``` and ```dirLocal``` _too sleepy to think of good names :p_

If the whole site switches direction at once (layout) then it easy to do using the ```dir``` function, as long as you set dir="rlt" on the html tag.

Which I think should be easy, since i18next drops a cookie that you can read in _document.js

```
import { parseCookies } from 'nookies';
static async getInitialProps(ctx) {
...
      const cookies = parseCookies(ctx);
      initialProps.language = cookies['next-i18next'] || 'en';
      initialProps.direction = initialProps.language === 'ar' ? 'rtl' : 'ltr';
...
}
render() {
    const { theme, language, direction } = this.props;

    return (
      <Html
        lang={language}
        dir={direction}
...
}
```
Things get complicated if some part of the site are gonna have different direction, for example data loaded from database, in this case I'm thinking of adding a css selector the dynamic elements and target them using ```dirLocal```, which adds css to the element if it has a "ltr" or "rtl" as class.

Finally, at runetime in the component that triggers the language change, you could directly modify the HTML dir attribute to trigger the css change.
```document.getElementsByTagName("html")[0].setAttribute("dir", "rtl");```

I hope somebody can provide a better solution to this problem.

**Comment by probablyup** [comment]
> Short problem description: stylisPlugins is not applied dynamically and never re-run;

Yes this is true and intentional for performance. If you need to switch this out I recommend putting a `key` prop on the `StyleSheetManager` and flipping it when you need to recalculate all the styles.

**Comment by ROUDALI** [comment]
same problem here

**Comment by ROUDALI** [comment]
@probablyup can you give a code snippet example please

**Comment by probablyup** [comment]
For example.

```jsx
<StyleSheetManager key={props.dir === "rtl" ? 'rtl' : 'ltr'} stylisPlugins={props.dir === "rtl" ? [stylisRTLPlugin] : null}>
   ...
</StyleSheetManager>
```

@ROUDALI your issue is something different I think.

**Comment by ROUDALI** [comment]
Yes, i'm using StyleSheetManager in a Next.js project in order to call stylisRTLPlugin
example : (i'm using styled_components in componentStepper )

example : https://codesandbox.io/s/hello-world-1urec
GO to https://1urec.sse.codesandbox.io/about and start refreshing the page === (FOUC)

the problem is when i load the page in first ms it shows the page without style , then the style is loaded.

**Comment by Migggz** [comment]
Try [stylis-rtlcss](https://github.com/migggz/stylis-rtlcss), it also supports Directives to import lines or block of style
