### ISSUE TITLE
css props not work if `styled` is not imported in same file ? (create-react-app)

### ISSUE THREAD

**Issue by littlee** [styled-components/styled-components#2719]
## System:
 - OS: macOS 10.14.6
 - CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
 - Memory: 703.66 MB / 8.00 GB
 - Shell: 5.3 - /bin/zsh
## Binaries:
 - Node: 10.15.3 - /usr/local/bin/node
 - npm: 6.10.0 - /usr/local/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
## npmPackages:
 - styled-components: ^4.3.2 => 4.3.2

I use `create-react-app` to create my project, no special config
If I put a styled component in another file, say, `Styles.js`, and import it in `App.js`, but `css` props is not working if I don't import `styled-components/macro` in `App.js`

App.js
```js
import React from 'react';
// import styled from 'styled-components/macro';
import { NotWork } from './Styles.js';

const App = () => (
  <NotWork css={`border: 1px solid red;`} />
)
```

Styles.js
```js
import styled from 'styled-components/macro';
export const NotWork = styled.div`
  width: 100px;
  height: 100px;
`;
```

if I umcomment the `// import styled from 'styled-components/macro';` in App.js, the red border will show up

**Comment by ReasonableDeveloper** [comment]
I think that is expected. The css prop is not something that gets passed to a styled-component. Think about it as an inline-style like the `style={{}}` prop just with template string support. 

For a normal html tag, there is no doubt you would need to import it as well.

```JSX
import React from 'react';
import styled from 'styled-components/macro';

const App = () => (
  <p css={`border: 1px solid red;`}> Hello there </p>
)
```

That being said, what I would like to see is maybe configure the css prop globally so that one does not always have to import styled components for each file that's using the prop. There is an eslint rule that can help ensure that we are importing the `/macro` package but it's very frustrating to not get any errors when using the wrong import or none at all. The css prop would silently be applied to the HTML element and you can only really know once you inspect the element in the devtools or realize the styles are missing.

One easy fix for the problem of silently applying the css prop to the element, could also be to use a capital character in the prop name since react warns about custom attributes with a capital letter that are applied straight to the DOM element.

`<p CSS={`font-size: 1rem; }>.</p>` looks weird but maybe an alias like
`<p inlineStyle={`font-size: 1rem`}>.</p>` would help with the confusion of op and warn us in case we forget to import.

**Comment by probablyup** [comment]
The act of importing the macro is what effectively turns on babel transpilation for that file in CRA, and the css prop is enabled by the babel plugin. Annoying, but that's how it works unless they give us a way to apply our babel plugin against the whole repo automatically.
