### ISSUE TITLE
SSR memory leak in DefaultGroupedTag

### ISSUE THREAD

**Issue by casperle** [styled-components/styled-components#2753]
## Environment
*For some reason the envinfo didnt worked, so at least I provide the following.*

node: v12.9.1
yarn: v1.17.3
npm: v6.10.2
styled-components: v5.0.0-beta.8

## Issue
Our setup:
```jsx
...
const styleSheet = new ServerStyleSheet();
const modules = [];

const app = (
  // tslint:disable-next-line
  <Loadable.Capture report={moduleName => modules.push(moduleName)}>
    <ApolloProvider client={client}>
      <StaticRouter context={routerContext} location={url}>
        <StyleSheetManager sheet={styleSheet.instance}>
          <App />
        </StyleSheetManager>
      </StaticRouter>
    </ApolloProvider>
  </Loadable.Capture>
);

try {
  const render = await renderToStringWithData(app); // from react-apollo
  const styleTags = styleSheet.getStyleTags();
  ...
} catch {...}
...
```

High request load is necessary to reproduce this bug in a short period of time. It is needed to provide 5 renders per 1 second. As you can see after a while the large object heap gets fulfilled.
![image](https://user-images.githubusercontent.com/8900497/65158710-33472a80-da33-11e9-85d0-9bdba1eb24fd.png)

During debugging I created few heap snapshots and ended up with this:
![image](https://user-images.githubusercontent.com/8900497/65159050-c54f3300-da33-11e9-9c08-8a176325717a.png)
 
We can see that the problem is caused by allocating too much memory by one `ArrayBuffer` used by `Uint32Array`. This typed array is created inside `DefaultGroupedTag` and assigned to `groupSizes` property. The issue happens here:
```js
...
const oldBuffer = this.groupSizes;
const oldSize = oldBuffer.length;
const newSize = BASE_SIZE << ((group / BASE_SIZE) | 0);

this.groupSizes = new Uint32Array(newSize);
this.groupSizes.set(oldBuffer);
...
```
The new `Uint32Array` copies the values from the old `Uint32Array` using the `typedarray.set()` method, which cause that the internal `ArrayBuffer` is shared between them. You can find this info on *[MDN web docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/set#Parameters)*.

The solution is as simple as:
```js
...
const oldSize = this.groupSizes.length;
const oldBuffer = [];

this.groupSizes.forEach(value => {
  oldBuffer.push(value);
});

// or

const oldSize = this.groupSizes.length;
const oldBuffer = [...this.groupSizes];
...
```
Please confirm this solution and I can create a PR. Thanks in advance.

**Comment by kitten** [comment]
Hiya 👋

There’s no issue with using a typed array buffer instead of an array. That’s not quite the issue here, since set doesn’t cause the buffer to be shared. It’s a distinct location in memory. Even if it was shared and an engine decided to do so, that’d actually save memory and GC time. What MDN is saying is:

> If the source array is a typed array, the two arrays may share the same underlying ArrayBuffer

ArrayBuffers being lean wrappers around raw memory is the key here. They’re saying two types arrays can point to the same location in memory but set will still work.

Moving on from this little detail, I’d suspect that #2754 is a symptom of the same issue you’re experiencing. So I’ll close it for now (unless it’s something else in which case we’ll reopen it of course 👍)

In both issues you’re describing runaway memory leaks that are directly correlated to the _amount_ of StyledComponent instances you’re creating.

The GroupIDAllocator simply counts up for each known component and the `groupSizes` buffer in this issue has a slot with a number for each component so that we can count how many rules each one has injected.

Now, every time you create a component `groupSizes` has to check whether it’s long enough to accommodate for the group’s ID. If it’s too short then it’ll create a new, longer buffer that’s at least as long as the group ID is big.

This doesn’t cause any issues in any usual application, since StyledComponents are only defined once. Hence it’s hard to even get to a size where memory becomes an issue. This holds true unless the number of StyledComponents grows over time!

So I’d suspect that your app is creating StyledComponents dynamically somewhere. Just one component that is created dynamically per request will cause a memory leak eventually given enough time.

Maybe you’re creating a StyledComponent in a render method or programmatically somewhere? This would explain your memory leak and fixing this would also fix the leak 👍

**Comment by casperle** [comment]
@kitten Thank you for explanation. Accordingly to your answer I will search for additional StyledComponents creation in our codebase and let you know.

Also I like to add that this issue raised up after upgrading from v3.2.3. Before that everything went just fine with the same codebase as we have now (little modification was needed during the upgrade of course). When we noticed the leak, we started the debugging. During that I applied my suggested solution and the described leak disappeared. Unfortunately the #2754 raised up :/, so maybe they can be connected but I am not sure in that. We will see.
