### ISSUE TITLE
Allow to custom hash-function to avoid collision with ad-block

### ISSUE THREAD

**Issue by kaikoehn** [styled-components/styled-components#2803]
Hello, I've recently encountered a collision from one of the generated class hashes that by accident matched a blacklisted class on ad-block. 

![image](https://user-images.githubusercontent.com/5606085/66646034-478ed980-ec25-11e9-88be-deab4b41bbfc.png)

I'll probably for now make a custom fork, but I was wondering if you ever heard about this issue or if there is maybe a better way of tackling it. I know ad-block is a third party plugin, but many people are using it and complain about issues.

**Comment by probablyup** [comment]
Hmm. We could potentially offer a workaround for this via `StyleSheetManager`. Perhaps allowing for an arbitrary class prefix. What do you think @kitten @mxstbr?

**Comment by kitten** [comment]
@probablyup I think that's a great idea, however, this doesn't address the underlying issue unfortunately.

I've seen this being addressed in some code before and we should probably patch it in v5. Any class that contains `ad` is going to be an issue unfortunately, due to basic ad-blocking. I think I've seen some other libraries that generate classnames deliberately avoid it and we should probably start doing the same 😢

**Comment by probablyup** [comment]
Hmm. In that case I'm hesitant... first it's "ad" and then there could be hundreds of "stopwords" before long.

**Comment by kitten** [comment]
@probablyup I think adding a fix for “ad” is reasonable. At least in places where I’ve seen it that’s the only workaround I’m aware of.
Currently our alphabet doesn’t include `-` so we could replace `d` with `-` when it’s following `a`, which would be a really low-impact change.
