### ISSUE TITLE
Styling does not applied on first render of a component on react, but it starts working on refresh, is it a bug or my bad?

### ISSUE THREAD

**Issue by umairalii** [styled-components/styled-components#2884]

**Comment by edenstrom** [comment]
Is it related to #2880 or #2629?

**Comment by BrennonG** [comment]
Exact same issue occurred for me this morning - somewhat suddenly. Everything was fine last night, woke up this morning and had lost all styling within elements styled w/ styled-components (sometimes comes back on refresh). No changes to package.json, no changes to webpack, create-react-app, etc. Will continue investigating...

**Comment by shubhambatra** [comment]
I was facing the same issue. I figured out it is coming because of multiple styled-component packages was installing. one is itself in my app and the other is the package we were using. 

You can try to find styled-components in your node_modules. If it was on multiple package.json files then you can either use [normalizr](https://www.npmjs.com/package/normalizr) or just remove one package which you don't need.

This helps in my case. You can try @umairalii @BrennonG

**Comment by BrennonG** [comment]
Unclear what it was, but reverting back to styled-components 3.4.1 seems to have fixed it for now.

**Comment by lccarrier** [comment]
I had the same exact issue described by BrennonG. I reverted back to 4.0.0 and it fixed it.

**Comment by umairalii** [comment]
I am closing this issue, because it were extensions that cause fault.

**Comment by BrennonG** [comment]
@umairalii can you elaborate on that? I just tried fiddling with things again with no luck - do you know what extensions are causing the fault?

**Comment by umairalii** [comment]
> @umairalii can you elaborate on that? I just tried fiddling with things again with no luck - do you know what extensions are causing the fault?

I just disable react extension and redux extension and it started working smoothly.

**Comment by facundocastello** [comment]
Thanks @umairalii ! The problem is solved by disabling some extensions. In my case my problem was with 'Loom extension' now with React and Redux extensions.

**Comment by supernovahs** [comment]
I am having this issue I have tried removing the extensions
