### ISSUE TITLE
A best practice question/dispute about importing

### ISSUE THREAD

**Issue by muscaiu** [styled-components/styled-components#2957]
Someone in our team introduced this way of importing components (using UI) in our app and this created a dispute. 

Can we have some outside opinions about why this is a bad practice? Thanks!

```
import * as UI from './styled/;
...
<UI.Wrapper>
  <UI.Content>Q_Q</UI.Content
</UI.Wrapper>
```
VS
```
import { Wrapper, Content } from './styled'
...
<Wrapper>
  <Content>Q_Q</Content
</Wrapper>
```

PS: Actually this is not related to styled-components, but anyway ... :-) ..Well it kid of is :-D

**Comment by kitten** [comment]
This is more of a question for our Spectrum 😉 https://github.com/styled-components/styled-components/blob/master/CONTRIBUTING.md#how-can-we-help-you-get-comfortable-contributing

I don't want to post any opinions here, since we'd like to keep our issues free of personal preferences and instead keep it related to technical discussions, but feel free to open a discussion over there and leave a link here. 🙌
