### ISSUE TITLE
Yarn check --verify-tree fails when switching to branch with v4 after upgrading to v5

### ISSUE THREAD

**Issue by Jensenks** [styled-components/styled-components#2966]
## Notes

I'm not sure if this is the right place to post this issue. It might just be an issue with the yarn check command, so maybe it belongs in the yarn repository. But since it is related to upgrading to styled-components 5, I feel like it is relevant here as well.

## Environment
On master branch: 

```
## System:
 - OS: macOS 10.15.2
 - CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
 - Memory: 493.09 MB / 16.00 GB
 - Shell: 5.7.1 - /bin/zsh
## Binaries:
 - Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
 - Yarn: 1.21.1 - /usr/local/bin/yarn
 - npm: 6.12.1 - ~/.nvm/versions/node/v12.13.1/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
## npmPackages:
 - styled-components: ^4.4.0 => 4.4.0
```
On v5 branch:
[Same as above except]
```
## npmPackages:
 - styled-components: ^5.0.0 => 4.4.0 
```
## Steps to reproduce
Start on branch with styled-components v4
1. Checkout new branch and run 'yarn upgrade styled-components@^5.0.0'
2. Switch back to branch with styled-components v4.
3. Run 'yarn'
4. Run 'yarn check --verify-tree'
5. See the following error:

## Expected Behavior
```
yarn check v1.21.1
success Folder in sync.
```
## Actual Behavior
```
yarn check v1.21.1
error "styled-components#@babel/traverse#@babel/helper-function-name#@babel/template#@babel/parser" is wrong version: expected "^7.8.3", got "7.6.2"
error Found 1 errors.
```

## Solutions
The only solution I've found so far is to delete node_modules and run yarn again. This installs everything correctly and runs 'yarn check --verify-tree' successfully. It's just very inconvenient if you are in a situation where you regularly have to switch between branches with v4 in some and v5 in others.

**Comment by kitten** [comment]
We’ve got our Babel plugin as a dependency for macros support which in turn has some Babel dependencies. Yarn sometimes plays it save when upgrading and doesn’t deduplicate dependencies when it could.

This in general leads to a build up of duplicates over time in your `yarn.lock` file. This can be prevented by manually checking your dependencies after an upgrading by looking at the Git diff.

Typically I don’t like deleting the lock file and all dependencies since that can lead to some accidental version bumps that I may not like. So upgrade should be minimal in my opinion and shouldn’t accidentally affect transitive dependencies unless necessary.

So typically on upgrades, I upgrade (manually or with interactive-upgrade) then check the lock file, then I run [`yarn-deduplicate`](https://github.com/atlassian/yarn-deduplicate) so I don’t manually have to upgrade or reinstall transitive dependencies, then double check the lock file again.

Hope this helps 👋
