### ISSUE TITLE
Development build of styled-components not liking compiled script containing styled components being embedded

### ISSUE THREAD

**Issue by sattaman** [styled-components/styled-components#2970]
## System:
 - OS: macOS 10.15.2
 - CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
 - Memory: 95.38 MB / 16.00 GB
 - Shell: 5.7.1 - /bin/zsh
## Binaries:
 - Node: 10.17.0 - ~/.nvm/versions/node/v10.17.0/bin/node
 - Yarn: 1.21.1 - /usr/local/bin/yarn
 - npm: 6.11.3 - ~/.nvm/versions/node/v10.17.0/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
## npmPackages:
 - babel-plugin-styled-components: ^1.10.0 => 1.10.6 
 - styled-components: ^3.2.3 => 3.4.10 
`

## Reproduction

When importing a compiled react app into a seperate div on the page, the development versionn of styled-components is going crazy. I do not get an error or warning but some rollover styles are broken.

This doesn't seem to happen when building production builds. 
 
I have looked through other issues but since this is a compiled app being imported it is not quite the same. 

Is this safe to do in production builds? 
Will this PR fix? https://github.com/styled-components/styled-components/pull/2954

**Comment by kitten** [comment]
Sorry for the late reply! I think this hasn’t received a more prompt response because there are a lot of other issues with the same question being answered. I know this is a little confusing since the answer has changed across versions though 😅

Either way, as the issue template states, this is a good one for StackOverflow or Spectrum, but I think the search may also bring up previous issues.

Basically our current note on this is:

- If you’re using SSR you may only have one version at a time on a given page. That’s a limitation due to Rehydration.
- Otherwise you should be able to use multiple versions of styled-components at the same time.

In case you need SSR you do need to ensure that only one instance is active on the page. You could achieve this either by bundling with a DLL shared bundle in a Webpack or by always falling back to the UMD bundle.

Now, this advice applies to v4/5. Have you tried maybe using a newer version, I see you’re on v3 there.
