### ISSUE TITLE
Discourage use of global class names with an escape hatch

### ISSUE THREAD

**Issue by kumar303** [styled-components/styled-components#2971]
This is a feature request.

I have just discovered a code base that abuses global class names all over the place, like this:

```tsx

const StyledDiv = styled.div`
  display: flex;

  .customer-name {
    margin-top: 1em;
  }
`

<StyledDiv>
  <div className="customer-name">
    {name}
  </div>
</StyledDiv>

```

I propose that `styled-components` makes it impossible to do this **by default**. It could offer a configuration flag to turn this behavior *on* for legacy code bases already relying on it.

For the case where one truly needs to use global class names, `styled-components` could follow the [css-modules approach](https://github.com/css-modules/css-modules#exceptions) and introduce a `:global` pseudo-class:

```tsx
const StyledDiv = styled.div`
  display: flex;

  :global(.btn .btn-primary) {
    margin-top: 1em;
  }
`
```

**Comment by kitten** [comment]
This is very much behaviour that we "inherit" from [stylis](https://github.com/thysultan/stylis.js) by default, and to clarify this will (afaik) be transformed to `.StyleDivName .customer-name {}`. This means it's _strictly speaking not global_, but it is indeed something we'd like to discourage.

The problem here is in figuring out what would be the correct alternative behaviour? Writing a stylis plugin to throw or warn? changing this to output `.StyleDivName.customer-name {}` like `&.class {}` would do? I think that'd be even more confusing.

I'm not sure whether there's any alternative behaviour that immediately makes sense. Our first goal is for CSS to continue working mostly as it should in all cases and as expected.

And on the homepage and right in an early section in our docs we do encourage template interpolations: https://styled-components.com/docs/basics#adapting-based-on-props

So even if we'd like to make it impossible, I'm not quite sure what that would look like, especially without breaking intentional escape hatches.

**Comment by kumar303** [comment]
> I'm not sure whether there's any alternative behaviour that immediately makes sense. Our first goal is for CSS to continue working mostly as it should in all cases and as expected.
...
> So even if we'd like to make it impossible, I'm not quite sure what that would look like, especially without breaking intentional escape hatches.

Thanks for the background and insight. After reading through it, I still think my proposal of disallowing a global reference by default (yes, it should throw) and adding an explicit escape hatch to work with global class names is a good solution. It would be great for newcomers and easy enough for legacy users (they could just flip the config flag). Let me know if I'm missing something.

**Comment by The-Code-Monkey** [comment]
Just so I understand are we saying that `styled-components` currently doesn't support the `:global()` in the styles in the same way that `stylis` does.

**Comment by kumar303** [comment]
I was suggesting that `:global()` or something similar should be the *only* way to access global class names. Currently it is possible to reference global class names willy-nilly and this leads to bad patterns. It's likely that most people doing this do not understand the danger of it.

**Comment by kitten** [comment]
Closing since I don't think this is implementable, or has been presented as particularly desireable, since we never got similar issues again. Sorry! Happy to reopen if things change.
