### ISSUE TITLE
input redux-form?

### ISSUE THREAD

**Issue by QGOLab** [styled-components/styled-components#298]
Redux-Form styled.input``?

**Comment by mxstbr** [comment]
Sorry what's the question here?

**Comment by k15a** [comment]
I think you mean

```JS
import { Field } from 'redux-form'
import styled from 'styled-components'

styled(Field)`
  /* You CSS */
`
```

**Comment by vadimshvetsov** [comment]
Solution above doesn't cover some cases like styling border when error occurs. You need `meta` object from `Field` in your styled component props. The good way is to set styled component as presential component.
```
const BasicInput = ({ input, ...props }) => <input {...props} {...input}/>;

export const StyledInput = styled(BasicInput)`
  outline: none;
  border: 1px solid ${({ meta: { touched, error } }) => (touched && error ? 'red' : 'grey')};
`;

const Input = ({ name, ...props }) => (
  <Field name={name} component={StyledInput} {...props}/>
);
```
P.S. Do not render `StyledInput` inside `Field` `component` prop. Fat arrow components [have not supported](https://github.com/erikras/redux-form/releases/tag/v6.0.0-alpha.14) since v6 of `redux-form`.
