### ISSUE TITLE
v5.0.0 UMD errors

### ISSUE THREAD

**Issue by WonSong** [styled-components/styled-components#2986]
## System:
 - OS: macOS 10.15.2
 - CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
 - Memory: 455.82 MB / 16.00 GB
 - Shell: 5.7.1 - /bin/zsh
## Binaries:
 - Node: 12.14.0 - ~/.nvm/versions/node/v12.14.0/bin/node
 - Yarn: 1.21.1 - ~/.nvm/versions/node/v12.14.0/bin/yarn
 - npm: 6.13.4 - ~/.nvm/versions/node/v12.14.0/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
## npmPackages:
 - styled-components: ^4.4.1 => 4.4.1 

## Reproduction
![Screen Shot 2020-01-24 at 11 52 28 AM](https://user-images.githubusercontent.com/5981331/73099293-0ce14200-3ea0-11ea-9d04-4a527979bb6f.png)
![Screen Shot 2020-01-24 at 11 52 40 AM](https://user-images.githubusercontent.com/5981331/73099296-0eab0580-3ea0-11ea-9093-aa223823ef65.png)

* https://jsfiddle.net/ercpqnyb/
* Run it and open console to see the error
* Confirmed this happens on Chrome, Edge, and Safari browsers

## Steps to reproduce
1. Use UMD version of styled components from unpkg.com
2. Site errors out with console error
3. window.styled is not defined

## Expected Behavior
* UMD package does not cause any errors, and make window.styled available

## Actual Behavior
* window.styled is undefined
* website errors out

**Comment by WonSong** [comment]
I have 4.4.1 as devDependencies, and uses webpack to make styled components external.

**Comment by probablyup** [comment]
react-is is now required via cdn as well

**Comment by WonSong** [comment]
@probablyup can you help me find an UMD link for react-is? Don’t see that hosted in unpkg or cdnjs

**Comment by probablyup** [comment]
https://unpkg.com/react-is@16/umd/react-is.production.min.js


On January 25, 2020 at 3:19:52 PM, Won Song (notifications@github.com)
wrote:

@probablyup <https://github.com/probablyup> can you help me find an UMD
link for react-is? Don’t see that hosted in unpkg or cdnjs

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/styled-components/styled-components/issues/2986?email_source=notifications&email_token=AAELFVTDAWFKI42SBRZVQHDQ7SNGPA5CNFSM4KLLHTGKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEJ5EUBY#issuecomment-578439687>,
or unsubscribe

**Comment by WonSong** [comment]
Thank you @probablyup. Adding react-is solved the problem!
