### ISSUE TITLE
Switch to semantic versioning

### ISSUE THREAD

**Issue by okonet** [styled-components/styled-components#3003]
Release notes for v5.0 say that there are no breaking changes in the release. Yet the incrementing the major version implies there might be some breaking changes.

I'm suggesting to switch project's versioning to [semantic release](https://github.com/semantic-release/semantic-release). This will help communicate severity of changes: major means there are breaking changes, minor means new features, patch means bug fixes. 

I believe this is something that's is very welcomed by the community and helps implementing better processes and tools.

Setting it up should be as simple as running `npx mrm semantic-release` which will modify `.travis.yml` to release every time changes are merged to master. See https://github.com/sapegin/mrm/tree/master/packages/mrm-task-semantic-release

Semantic versioning uses commit messages to communicate versions. I suggest using a  simplified [ESLint convention](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-eslint). As for internal processes this change would mean that every PR with commits that doesn't follow the convention should be _squashed_ with the proper commit message. This is a practice I use across my open source repositories for a few years now and I can't complain about it.

Alternatively, [changesets](https://github.com/atlassian/changesets) could be considered as well since they make the process of writing and reviewing changeling more explicit.

**Comment by kitten** [comment]
We are using semantic versioning but without a tool. In fact, there are breaking changes in v5, but what the release notes meant is that they’re either very subtle or for features that have been deprecated prior to v5, e.g.

> Remove deprecated attrs "subfunction" syntax variant

I certainly don’t see the point of automating this and introducing overhead to all the contributors that effectively use and contribute to this repository.

Also given that we have no problem keeping track of changes and keeping our versioning in check, this may be a rather bike-sheddy suggestion 😅

**Comment by okonet** [comment]
Maybe then release notes could make it more prominent that there are braking changes. I think that having breaking changes but saying there are none can be quite misleading.

**Comment by probablyup** [comment]
It says very specifically that we remove the deprecated syntax

**Comment by okonet** [comment]
It says very specifically that there are no breaking changes. That’s what I’m referring to. After reading this I wasn’t even searching for anything that could be a breaking change. And that’s where the confusion and the proposal comes from.

**Comment by probablyup** [comment]
Something that was explicitly deprecated in a former master and removed in
a new one is a “soft” breaking change I guess you could say.

The important thing is no subtractive API changes were made that did not
have ample advance warning.

In any case, we spend a great deal of time and effort crafting our
communications. Thanks for your interest in our process, but we’re happy
with the current state of things.

**Comment by okonet** [comment]
It doesn’t matter if it’s a “soft” or “hard” (very subjective) if the release notes say “no breaking changes” in bold. Even just having a section that would point to “potential breaking changes” could help tremendously. 

But from your reply I read that there is no interest in my opinion anyways so I’ll just close it and let it be.

Thanks for clarification @kitten that you’re following the SemVer!

**Comment by kitten** [comment]
Just to clarify the terminology here. SemVer doesn’t offer a definition of what qualifies as a “breaking change” which has already led to a lot of discussions on other projects.

If we go by the minimal, commonly accepted definition it is any change that potentially causes other components to unexpectedly fail (this is backed up by some open dictionary definitions)

Now, why am I rambling on about semantics and definitions? 😂 Because this doesn’t hold up with “depreciations”.

If we deprecate and add a warning messages months and lots of minor versions in advance, then that API is marked to be changed/removed in the _next major release_. That means that whenever we plan to remove the API, we have to publish this as major, as then only an explicit upgrade will remove it.

Now the next part is controversial, can a removal of a deprecated API be a major release on its own? I’d argue _yes_, because major releases are opportunities to _break_ with past accumulated debt. Not everyone may agree of course! 😅

Now that then brings us back to the original problem: is resolving a deprecation by removing it a breaking change because it requires a major bump? Not necessarily, since that’s an inverse error or denying the antecedent.

Because a breaking change must cause a major bump, doesn’t mean that what causes a major bump is a breaking change. So I’d (maybe again controversially say) when the claim of “no breaking changes” was added to the changelog, it’s correct, although a deprecated API was removed.

Also, to summarise this nicely, I don’t think automating our changelog or release process can protect us from this. This is a definition problem, so automating this relies on us classifying the change. And we would’ve classified it as `major` once we’ve removed the deprecated API. But that doesn’t change the labelling.

@probablyup I think to summarise, we should update our changelog to clearly highlight that this API has been removed.

**Comment by kitten** [comment]
I hope the change above highlights the removal a little more.
I've also left an edit on [our announcement blog post](https://medium.com/styled-components/announcing-styled-components-v5-beast-mode-389747abd987). I think some of confusion in this issue came from the fact that we don't treat these as accurate release notes, while we maybe should. Anyway, it now reads:

> There are no breaking changes*, as long as your app is running the latest version of React, styled-components v5 should just work. ✨(*however we did remove the deprecated “subfunctions on attrs” API)

**Comment by remmythical** [comment]
Hey @kitten, I'm not sure how this is set up, but could you also make sure that the change in the announcement blogpost is also applied to the [release notes on the website](https://styled-components.com/releases#v5.0.0)?

Those are the release notes that show up highest on google, at least to me.
And the slightly misleading description of "**no breaking changes!**" there already gave us a bit of trouble with our upgrade timeline.
