### ISSUE TITLE
Bug? Feature Request? Usage Issue?...Can I use .includes() or .contains() or .indexOf() when searching through react props in a styled component?

### ISSUE THREAD

**Issue by rchrdnsh** [styled-components/styled-components#3010]
So, I don't know if this is a bug, or a lack of a feature, or if I'm doing something wrong...

posted on spectrum:

https://spectrum.chat/styled-components/help/includes-is-coming-up-undefined~7f60b33d-67ef-49e4-aa4b-4940183f8435

and stack overflow:

https://stackoverflow.com/questions/60131567/can-i-use-includes-or-contains-or-indexof-when-searching-through-react

I have an instance of a react component with a prop containing an array of strings, like so:

```jsx
<Keyboard notes={['cp', 'dma', 'ema', 'fp', 'gp', 'ama', 'bma']}/>
```

The intention of the component is to create a piano keyboard and invoke it anywhere in the app I'm building, pass in an array of note names, and then all of those notes will be colored differently according to what I have requested via the string for each note. So, I am trying to create a component that will help me avoid making literally thousands of images of a keyboard for every possible state that a piano keyboard could be in.

In a styled component that belongs to the main `Keyboard` component I am passing the prop to it and trying to conditionally change the background color if an array element exists, like so:

```jsx
const C1 = styled.div`
  ${WhiteKey}
  ${props =>
    // tried this:
    props.notes.contains('cp') ? css`${PerfectKey}` :
    // and this:
    (props.notes.contains('cp')) ? css`${PerfectKey}` :
    css`${UnselectedWhiteKey}`
  }
`
```

...which is then used in a react functional component in the same file, like so:

```jsx

const Keyboard = (props) => {

  return (
    <Container>
      <KeyboardBox>
        <WhiteKeys>
          <C1 {...props}></C1>
          <D1 {...props}></D1>
          <E1 {...props}></E1>
          <F1 {...props}></F1>
          <G1 {...props}></G1>
          <A1 {...props}></A1>
          <B1 {...props}></B1>
        </WhiteKeys>
        <BlackKeys>
          <Db1 {...props}></Db1>
          <Eb1 {...props}></Eb1>
          <Gb1 {...props}></Gb1>
          <Ab1 {...props}></Ab1>
          <Bb1 {...props}></Bb1>
        </BlackKeys>
      </KeyboardBox>
    </Container>
  )
}
```

...where each note is it's own styled-component that is trying to look into the array in the prop on it's parent component and decide whether it needs to do something or not.

...but I'm getting the following error message on the page:

```terminal
TypeError: Cannot read property 'contains' of undefined
```

I tried `indexOf` as well and the same thing happened.

I also tried converting the array into a string, like so:

```jsx
<Keyboard scale={'cp dma ema fp gp ama bma'}/>
```

...and then using `props.scale.includes('cp')` but the same error message again?

What am I doing wrong and is there a more correct and better way to go about conditionally changing css attributes based upon part of the value of a prop, not the whole value?

Or is this a bug and these array methods should work, or is it a lack of a feature that I would find very useful? I don't personally know, so please help if possible. If I can make this work then I will be very happy indeed :-)

Working on a minimal reproduction currently...

## System:
 - OS: macOS 10.15.2
 - CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
 - Memory: 79.73 MB / 32.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 13.7.0 - /usr/local/bin/node
 - Yarn: 1.21.1 - /usr/local/bin/yarn
 - npm: 6.13.7 - /usr/local/bin/npm
## npmPackages:
 - babel-plugin-styled-components: ^1.10.6 => 1.10.6 
 - styled-components: ^4.3.2 => 4.4.1

...

## Reproduction

here is a minimal reproduction in a code sandbox...trying to make it more minimal, but it is something:

https://codesandbox.io/s/keyboard-3u6ci

- working on this...

## Steps to reproduce

- working on this...

## Expected Behavior

`props.scale.contains('')` would be able to look through the array in the `scale={[]}` and see that the string in the quotes is there as well and then alter the style accordingly.

## Actual Behavior

The method return 'undefined'

**Comment by kitten** [comment]
Did you mean to use `includes`? `contains` is not a thing. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes

Also “of undefined” indicates that you’re trying to call this on a prop you haven’t passed.

Maybe try to convert the props spread into an explicit expression of passing the props on one by one, use React dev tools and some console.logs statements, and try to find out what’s missing that way.

Also, yes, this is definitely a question that’s for Stackoverflow or Spectrum because it quickly becomes clear that this is a usage issue, so it doesn’t have anything to do with styled-components, let alone a potential bug.

Also, please keep in mind that it’s better to keep these reports brief. This way you could’ve seen that it boils down to an error that has to do with your code, which means it’s a question for other platforms. I’m happy to help, but on GitHub more issues take more time to run through, which means that chances are lower for us to find important big reports quicker 😅

Hope that helps! I’ll close this, but I hope you can get more help on Spectrum or Stackoverflow, although I think you’ll need to post a code snippet there. 🙂 I’ll also edit the title, since it’s very long and spammy (if you open another issue, try to keep it to a single sentence)

**Comment by rchrdnsh** [comment]
hi @kitten :-)

Ok, I think I have figured out my mistakes...first one, which i totally missed or spaced on, was adding an empty array to my initial state, which i think i filled in subconsciously when creating the minimal reproduction. My second mistake was getting my string and array methods mixed up, as I had it backwards...`contains` for strings and `includes` for arrays, not the opposite, which is how it was in my head. So, with those two fixes...in many places...things seem to be working ok now...i was worried that styled-components could not do this, but i am constantly surprised by how awesome they are :-)

Also, what do you mean by spammy, exactly? I don't understand the issue title now, personally, and I honestly did not know whether it was my mistake(totally was) or a bug or a missing feature, as I'm relatively new to logical programming and react and styled-components, coming from an artist, then design, background. So I did not know how to even ask the question properly. When I'm deep into new ideas and trying to solve new problems without enough knowledge it's pretty hard to know what and where and how to get help, hence posting in multiple places. I also don't really understand the word 'undefined' either, so when i see it, it seems like the issue could be anywhere. This is, again, my lack of skill and understanding, but it's still hard for me to see that at this point.

**Comment by kitten** [comment]
Hiya 👋 no worries at all!

By a spammy issue title I mean that it’s more than a full sentence, starts with multiple questions that are assertions, and ends with a full question.

Typically it’s better to keep them as short as possible while still summarising your issue, so instead of “I’m seeing an error of undefined when doing X” just keep it subject less and short: “error of undefined when doing X”

Or, keep out “labels” like ‘issue’, ‘bug’, or similar keywords (especially with question marks or exclamation marks)

These are rules of thumb, so not required or an exact science, but it makes it easier for others to quickly scan the title and understand what it’s about. Don’t worry too much about the exact title or label, because a maintainer or contributor will try to figure those out 🙌♥️

**Comment by rchrdnsh** [comment]
oh, ok, I was concerned, as I have no intention of being a bad actor, but only to learn and help and grow projects and communities and myself.

Thank you for clarifying 🤗
