### ISSUE TITLE
Add (global) className method (not just React component HOC injecting className)

### ISSUE THREAD

**Issue by neaumusic** [styled-components/styled-components#3021]
I've done tons of research over the last year, seen multiple stack overflow posts and closed issues here.

I've read the docs many times, but cannot find what I'm looking for!

The main usecase is with Kendo React components [which only accept cssStyle and cssClass](https://www.telerik.com/kendo-react-ui/components/layout/api/MenuItemProps/). These components tend not to be 'reactful' and don't accept typical props like className, and will create global 'fixed' components that can't easily be targeted with nested CSS selectors.

As far as I can tell, there's no way to simply export a css style string nor a unique `className` from the same file where the rest of my page's styles are located.

It's up to interpretation for how the semantics would work, but possibly 
```
export const SomeClass = styled.globalClassName`
  direction: 'ltr';
`;
```

and subsequently

```
<MenuItem cssClass={SomeClass} />
```

**Comment by kitten** [comment]
I don’t know much about Kendo components but before I break this out into a longer discussion of this, have you asked them / opened an issue with them asking why they don’t adhere to commonly (if not standard) props?

**Comment by mxstbr** [comment]
This is not something we're likely to include, so I would petition those folks instead to adhere to common patterns like accepting a `className` prop.

**Comment by neaumusic** [comment]
Yea kendo should 100% adopt standards and I'll ask them if there's a reason why they don't.

Is there a technical  reason why styled-components is required to inject className or behave as a HOC rather than just CSS compiler?

**Comment by mxstbr** [comment]
It's not a technical limitation, it's an intended API limitation. A bit part of what make styled-components so nice to use is that you no longer have to think about the (unnecessary) abstraction of classnames, but are instead thinking in terms of components.

As such, adding a method that returns a classname again would be missing the entire point of what makes it so nice to use, if that makes sense.

**Comment by neaumusic** [comment]
Yea I definitely get that too, but I guess I disagree that plugging that prop in is the only real benefit. It is a good feature, but I feel like sometimes it's good to go a bit more granular, somewhat like react lifecycle methods as opposed to just a render function of props.

It's totally up to you guys; I think it would be a good idea and fits some of the other utils like createGlobalStyle, but I totally understand the styled **components** direction.

**Comment by mrmckeb** [comment]
I was looking for this today as well - to solve a similar problem. I can see it also being an issue for render functions and hooks.

Imagine this example, where I want to set a `className` to the components consuming my hook's provided props. I could use `style` for simple things, and I know I could also provide `css` that the consumer could utilise.
```ts
const { outerProps, innerProps } = useSomeThing();

return (
  <MyComponentA {...outerProps}>
    <MyComponentB {...innerProps} />
  </MyComponentA>
);
```

Perhaps there's another way to approach this with `styled-components`?

**Comment by nightpool** [comment]
@neaumusic if the only problem is that the library you're using wants the prop to be named `cssClass` instead of `className`, couldn't you just add a HOC, or an option to styledComponents, that wraps the prop? something like:

```js
const kendoStyled = WrappedComponent => styled(props => <WrappedComponent {...props} cssClass={props.className} />)
```

(obviously there are more nuances you'd want to solve before using this in production, but the concept should be clear)

or, alternatively, with the new `withConfig` api (which doesn't seem to be documented anywhere yet, but you can see an example of here, https://github.com/styled-components/styled-components/pull/3006), styled-components could add a classNameProp option that you could set to `cssClass`. that seems simple enough, and it avoids the encapsulation problems @mxstbr was concerned about.

**Comment by neaumusic** [comment]
@nightpool I tried using a HOC originally and withRef, but somehow kendo doesn’t support prop forwarding either. My guess is their code requires the structure and manual child/parent traversal, eg Menu with MenuIts must be interfacing directly. It doesn’t make sense, but it doesn’t work lol

**Comment by vinay-deshmukh** [comment]
> It's not a technical limitation, it's an intended API limitation. A bit part of what make styled-components so nice to use is that you no longer have to think about the (unnecessary) abstraction of classnames, but are instead thinking in terms of components.

> As such, adding a method that returns a classname again would be missing the entire point of what makes it so nice to use, if that makes sense.

@mxstbr In this case, how would one apply conditional "classname" behaviour?

For example, in certain conditions, I want to apply a classname that adds a border to a component. This behaviour of adding classname is meant to be reusable, so that whenever needed, I just add it to a component, and it get's the className behaviour

Styled-Components suggests to use the `className` prop on the &lt;Component /&gt;, but how do I generate the className in the first place if my styling-library is styled-components?


P.S.

While I was writing this, I can think of one way to achieve my end goal (conditional CSS behaviour), by creating a styled-component that wraps the component on whom I want to add the classname.

Something like,

````
  <div>
    <ConditonalCSSComp check={true}
     <MyComponent />
    </ConitionalCSSComp>
   <div>
````
 and
````
const ConditionalCSSComp = styled(props => 

    React.Children.cloneElement(
        React.Children.only(props.children),
        {
             className: props.className
            //props.className is the one inserted by styled-components
        }
    )

)`
   ${props => props.check && css ` 
             border: 3px solid green;
        `}

`
````

Is this a good way/are there better ways to achieve "conditonal className behaviour (by _creating_ the classname)"?

**Comment by jtwozniak** [comment]
Hey,
in some cases when you mix libraries, not giving the possibility to get className is creating overcomplications.
I have react component that renders ag-grid (js table library) and ag-grid renders react component (some cell in the table).

The library is providing dom elements where your react cell component is rendered, but you don't control the rendering of that placeholder and you can only provide styling in the table configuration object

https://www.ag-grid.com/javascript-grid/cell-styles/#cell-class
https://www.ag-grid.com/javascript-grid/cell-styles/#cell-style

And now you have to do some tricks to use the theme in styles, thus the code is not optimal.
Alternatively, you can style parent component and extract className from it, like:

`
type Props = {
  className: string
}


const Table = ({ className }: Props) =>  (
    <AgGrid
      {...someGridProps}
      columnDefs={generateColumnDefs(className)}
    />
)

export const StyledTable = styled(Table)`
  background-color: palevioletred;
  color: white;
`

But that is similarly bad and that is just because of the intended styled-components API limitation.
In the above case, writing the HOC is not an option. 

Adding a method that returns a classname would be beneficial in similar cases.

**Comment by nightpool** [comment]
@vinay-deshmukh 
> This behaviour of adding classname is meant to be reusable, so that whenever needed, I just add it to a component, and it get's the className behaviour

This is not how styled components is designed to work. The core design philosophy is that every style is contained within a component, so the idea of applying a random `border` to an arbitrary element is completely outside of that. If you just want to reuse the style definition itself, here's one technique you can use:


```js
export const border = css`
  border: 3px solid blue;
`;
```

and in a different file:
```js
import { border } from '@/styleUtils';

const Component = styled.div`
    ${border}
`;
```

see how `Component` is always in control of which styles are applied? and of course you could apply it conditionally just by using && or a ternary statement. You could also—if you *really wanted to* (this is rarely a good idea)—do this from another component, like this:

```js
import { border } from '@/styleUtils';
import { Component } from './Component';

const ParentComponent = styled.div`
  ${Component} {
    margin: none;
    ${border}
  }
`;
