### ISSUE TITLE
@import fails to work properly in Styled Components v5, works fine in v4

### ISSUE THREAD

**Issue by lucaschen** [styled-components/styled-components#3024]
## Reproduction

[https://codesandbox.io/s/delicate-voice-rycf1](https://codesandbox.io/s/delicate-voice-rycf1)

## Why it seems to be broken

In Styled Components v4, the given CodeSandbox would produce two `<style>` tags like so:

![Working](https://user-images.githubusercontent.com/2109121/74598653-acb97680-50c0-11ea-85ee-bed3a2a5fae7.png)

However, in v5 it compacts them into a single `<style>` tag, like so:

![Not working](https://user-images.githubusercontent.com/2109121/74598658-c955ae80-50c0-11ea-8367-fe615b53879d.png)

The issue is that the child component's styles are rendered first (`font-family: Wallpoet;`) - I'm not sure on the specifics but at this point `Wallpoet` is not yet defined, hence it shows the default serif font - even once the font is fully loaded.

## Expected Behavior

Open the attached CodeSandbox and simply change the `styled-components` version from 5.0.1 to any version under major version 4 and it should work just fine.

**Comment by kitten** [comment]
`@import` isn’t properly supported at this time and we’re looking into how best to implement rule hoisting to make this work as expected in all case.

In v4 the implementation of this was flawed and would occasionally fail, but in v5 we’ve changed it to not do anything special for now until we figure out a way forward.

We’ve especially decided to remove this since adding CSS files outside of styles-components is luckily relatively straightforward.

The warning here hopefully adds some clarity:

![D7551D1A-C3D8-4140-A3B9-D585CC4FC342](https://user-images.githubusercontent.com/2041385/74599048-e1eba780-5073-11ea-9aea-67221ad45cf2.jpeg)
