### ISSUE TITLE
Styles not generated for Style Objects in a Node VM context

### ISSUE THREAD

**Issue by keeganstreet** [styled-components/styled-components#3066]
Styles are not generated for components styled with [Style Objects](https://styled-components.com/docs/advanced#style-objects) when run in a [Node VM context](https://nodejs.org/api/vm.html#vm_vm_executing_javascript). Components styled with tagged template literals work perfectly well in the same Node VM context.

This is because the [`isPlainObject`](https://github.com/styled-components/styled-components/blob/master/packages/styled-components/src/utils/isPlainObject.js) function tests whether the constructor of an object is `Object`. If an object is created in a VM context, it's constructor `Object` is not equal to the `Object` prototype object in the main context.

It would be great if this function could be updated so that it doesn't rely on being executed in the same JavaScript context that the component was created in.

## Test case

```
npm i react react-dom styled-components
```

Run the following in Node:
```js
const React = require("react");
const { renderToString } = require("react-dom/server");
const { default: styled, ServerStyleSheet } = require("styled-components");
const vm = require("vm");

const context = vm.createContext({ styled, React, App: null });

vm.runInContext(`
  const Green = styled.div\`
    color: green;
  \`;

  const Red = styled.div(() => ({
    color: "red"
  }));

  App = React.createElement("div", null, [
    React.createElement(Green, { key: 0 }, null),
    React.createElement(Red, { key: 1 }, null)
  ]);
`, context);

const sheet = new ServerStyleSheet();
renderToString(sheet.collectStyles(context.App));
const styleTags = sheet.getStyleTags();
console.log(styleTags);
```

## Expected output

```html
<style data-styled="true" data-styled-version="5.0.1">.lbxPDC{color:green;}
data-styled.g1[id="sc-AxjAm"]{content:"lbxPDC,"}
.dahFIE{color:red;}
data-styled.g2[id="sc-AxirZ"]{content:"dahFIE,"}
</style>
```

## Actual output

`[object Object];` is being rendered instead of `color:red;`.

```html
<style data-styled="true" data-styled-version="5.0.1">.lbxPDC{color:green;}
data-styled.g1[id="sc-AxjAm"]{content:"lbxPDC,"}
.dahFIE{[object Object];}
data-styled.g2[id="sc-AxirZ"]{content:"dahFIE,"}
</style>
```

**Comment by kitten** [comment]
To be honest, I'm not quite sure why we have `isPlainObject` there, cc @probablyup. Maybe it was added when the order between the `isStyledComponent` check was reversed? At least it seems overkill to me either way

**Comment by probablyup** [comment]
I'm fine with switching it to `Object.prototype.toString.call(x) === '[object Object]'` which will reliably give the correct answer across environments

**Comment by keeganstreet** [comment]
Thanks @kitten & @probablyup. Would you like a PR to make that change?

**Comment by probablyup** [comment]
Sure, thank you.

**Comment by keeganstreet** [comment]
`Object.prototype.toString.call(x)` will return `"[object Object]"` for instances too, i.e.:

```
class SomeClass {}
Object.prototype.toString.call(new SomeClass()); // "[object Object]"
```

🤔 Do you know what value `x` might be if it is not a plain object? Maybe we should check that `x` is not of that type rather than checking that it is a plain object.

**Comment by probablyup** [comment]
We’re ruling out symbols, functions, arrays, the object return of react.memo

**Comment by kitten** [comment]
@probablyup I think we're fighting an uphill battle here. We already have a pretty comprehensive failure case: https://github.com/styled-components/styled-components/blob/master/packages/styled-components/src/utils/addUnitIfNeeded.js#L8

We stringify the object in a failure case, which is intended, so we are supporting `toString` making this a little more complicated. But we can modify `flatten.js` with a couple of things in mind first:

- falsey values are not an issue and checked for (in both `objToCssArray` and `flatten`)
- the function check can come first (that's a modification for `objToCssArray`)

Then we can assume that we either stringify or call `objToCssArray` to convert the object to CSS declarations. We could call `typeOf` from `react-is` to check whether it's a React element (or other type) which rules out the most common mistakes.

Then we can assume that if someone passes `new SomeClass` then that was intentional. We only have to figure out whether they wanted to stringify `new SomeClass` or have it converted to CSS. For that I'd propose we'd just check:

```js
typeof x === 'object' && x.toString === Object.prototype.toString
```

If this holds up we call `objToCssArray`, otherwise we drop into `addUnitIfNeeded` (the string case) since clearly the user has a custom `toString` function. This also seems to hold up for the `vm` module btw.

We don't have to handle arrays any differently. They aren't expected in `objToCssArray` and are currently (maybe erroneously) stringified. They are handled upfront in the `flatten` function however.

We also don't have to handle symbols. They aren't handled right now and there's a low to no chance that they'll be passed as an interpolation.

**Comment by probablyup** [comment]
I think the toString call is sufficient for our use case. If someone passes
an es6 class into an interpolation they’ll figure out it doesn’t work

**Comment by kitten** [comment]
Quick note on what this would look like:

```js
import { typeOf } from 'react-is';

const isPlainObject = x =>
  x !== null &&
  typeof x === 'object' &&
  !typeOf(x) &&
  typeof x === 'object' && x.toString === Object.prototype.toString
```

At which point we should rename it, maybe to `isSerializableObject` or `isCSSObject`.

The `toString` approach on its own isn't sufficient:

```js
Object.prototype.toString.call(React.createElement('div'))
// '[object Object]'
```

And `x.toString === Object.prototype.toString` does the trick in `vm` as well 😅

**Comment by probablyup** [comment]
I guess I just don’t think this level of planning is necessarily helpful
for the amount of weight it adds. My guess is people accidentally
interpolating an es6 class or JSX is probably pretty low

**Comment by kitten** [comment]
Well, we do have to cover React-ish stuff, so that's fine. And it'd be great to consistently support custom `toString` functions.

Also, this really doesn't add a lot of weight, we can even drop `x !== null` and we arrive at something that is barely longer compared to other size savings we could have

**Comment by keeganstreet** [comment]
@kitten `x.toString === Object.prototype.toString` will have the same problem as `x.constructor === Object` in terms of relying on `x` being created in the same context as this conditional.

**Comment by kitten** [comment]
Good point, I double checked this and you're absolutely right :+1: I must've misremembered that native functions share the same instances in different contexts.

**Comment by keeganstreet** [comment]
So maybe something like this?

```js
import { typeOf } from 'react-is';

export default (x: any): boolean =>
  x !== null &&
  typeof x === 'object' &&
  x.toString() === '[object Object]' &&
  !typeOf(x);
```

`!typeOf(x)` to make sure it's not a React element.

I used `x.toString() === '[object Object]'` instead of `Object.prototype.toString.call(x) === '[object Object]'` to avoid failing the unit test `flatten › toStrings class instances`. If an object defines its own `toString` method I think it makes sense to call it rather than `toString` from the `Object.prototype object`.
