### ISSUE TITLE
Inject head tag in a different position

### ISSUE THREAD

**Issue by empav** [styled-components/styled-components#3070]
Hi there, regarding styled component head tag:

<img width="817" alt="Screenshot 2020-03-23 at 14 40 41" src="https://user-images.githubusercontent.com/15023919/77323011-e2cbc500-6d14-11ea-8db2-3f7b201a0856.png">

Is there a way to configure in which position inside the HEAD the highlighted tag will be injected ?

**Comment by bornaeon** [comment]
relevant to this topic, I also have an issue with styled-components version `5.0.1`! Since we have this post here, I did not create a new issue thread!
it's fully described in a [stackoverflow post](https://stackoverflow.com/questions/61035323/order-of-styled-components-and-sass-styles-injected-to-a-react-index-page)... would be good to have a follow up on it

**Comment by epavan** [comment]
> relevant to this topic, I also have an issue with styled-components version `5.0.1`! Since we have this post here, I did not create a new issue thread!
> it's fully described in a [stackoverflow post](https://stackoverflow.com/questions/61035323/order-of-styled-components-and-sass-styles-injected-to-a-react-index-page)... would be good to have a follow up on it

It looks like we have roughly the same issue, using both sass and styled components. How can I give priority to those sass styles gathered with minicssplugin rather than styled components stuff?

**Comment by informa** [comment]
Bump on this issue if possible.
It would be good to get a direction on this.

We have an issue whereby we manage a react component library. We want to move to styled-components but in doing so styled-components styles will override our customer's styles due to the position in the head.

So you need to increase specificity from a customer style's point of view. Which could be a breaking change and work for them.

I found an issue: https://github.com/styled-components/styled-components/issues/1707
which said to add a placeholder into the head.

This seems to work ie: `<style data-styled="active" data-styled-version="5.1.1"></style>`. 
Meaning other app styles appear after the styled-components styles.

But I am not sure if this is a recommended direction on this issue.

**Comment by brendonco** [comment]
Have similar issue #3181
