### ISSUE TITLE
Server side rendering: Whats the deal with glamor usage?

### ISSUE THREAD

**Issue by code-punkt** [styled-components/styled-components#308]
As PR #214 falls short of what i'd like to see in quite a few aspects, i'm trying to implement SSR into `styled-components`. `glamor`, which i've always thought this project was based on, has very good  SSR capabilities and also copies the API of `aphrodite`, which is why i'd also want to go that route and reuse most of the existing `glamor` functionality such as `renderStatic`, `renderStaticOptimized` etc.

After starting to implement, i realized that `glamor` is used as a dependency, but only certain things are relied on/used. Also, the sheet.js of glamor is not used from the package, but vendored and changed in some way.

Why is a part of glamor vendored exactly? Was this a conscious decision because you wanted to move away from glamor? Can this be reverted? I'm not sure that copying a lot of glamor functionality is a good decision - i'd rather use it directly instead ;)

**Comment by mxstbr** [comment]
> Why is a part of glamor vendored exactly?

Because it was changed massively.

Contrary to glamor, we have to inject our CSS all at once, not one by one, because we have do it at component creation time to preserve the declaration order. This also means we have to be able to insert CSS at arbitrary places within the style sheet, something glamor doesn't (need to) do either!

See #31 for the bug report, and https://github.com/threepointone/glamor/pull/59 for an abandoned PR to glamor to change that behaviour.

So, no, we cannot revert this I'm afraid. We don't actually really use glamor's functionality, the only thing we can (and do) use is the injection mechanism because it's fast. 

----

Please chime in over at #214 with your suggestions of things you need for server-side rendering, would love to hear which APIs we should add! Thanks!

**Comment by mxstbr** [comment]
Also /cc @threepointone @geelen if they have anything to add.
