### ISSUE TITLE
createGlobalStyle in v5 doesn't work or disappears when any broken styled-component is rendered

### ISSUE THREAD

**Issue by camsjams** [styled-components/styled-components#3081]
## Browser
- Chrome (latest, test 80+)
- Chromium (latest, tested 80+)
- Firefox (latest, tested 74+)

## System:
 - OS: Linux 4.15 Debian GNU/Linux 9 (stretch) 9 (stretch)
 - CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
 - Memory: 2.04 GB / 31.30 GB
 - Container: Yes
 - Shell: 4.4.12 - /bin/bash
## Binaries:
 - Node: 10.19.0 - /usr/local/bin/node
 - Yarn: 1.21.1 - /usr/local/bin/yarn
 - npm: 6.13.4 - /usr/local/bin/npm
## npmPackages:
 - styled-components: 5.0.1 => 5.0.1

## Reproduction
https://codesandbox.io/s/styled-components-v5-basic-qi03i

## Steps to reproduce
1. Make a React app
2. Make a global style with `createGlobalStyle`
3. Create a styled-component with invalid CSS or a template prop function that returns invalid CSS
4. Notice your global styles do not render
5. Remove broken component - global styles render

## Expected Behavior
Global styles should activate, and an error should be thrown, perhaps in the linter.

## Actual Behavior
Global styles don't activate, and no error is thrown.

## Notes
This is likely to occur when upgrading from `< 5.0.0` to `> 5.0.0`, where API changes can cause broken components, which is what happened for my app.

This can also occur on a router page transition or redux state change that causes a bad component to be rendered, **creating a more sinister version of this bug**:
https://codesandbox.io/s/styled-components-v5-reset-redux-yml9g
(in CodeSandbox link, just keep clicking)

**Also, when extracting the global CSS using Webpack, this is a non-issue since the global styles don't break anymore.** So this is purely a local development issue it seems.

**Comment by camsjams** [comment]
This appears to be mostly due in part to an invalid CSS property (in the example an unclosed `var()`, which brings down the whole CSS file, which unfortunately is something that CSS has been doing forever, at least for the last 15+ years.

It's probably prudent to close this ticket if the maintainers agree, and perhaps leave this here as a warning.

**Comment by kitten** [comment]
@camsjams hey 👋 sorry this has happened! I’ve definitely run into problems with unclosed parents/braces/etc a couple of times accidentally myself.

I’d put this down as a problem that is inheeent to stylis currently, which doesn’t differentiate between production and development to output more warnings. I do hope its future version may be able to address some of this however. Or another library for that matter but writing parsers for CSS that are small, fast, and have a good DX is hard.

Currently I’d recommend CSSLint if this becomes a huge issue, which is a tool worth adding alongside ESLint for similar problems (well ignoring TypeScript or Babel there, but still)

I wish it was easier to make this experience better, and due to our stricter requirements by using the CSSOM API we may even get more problems, but that’s what makes the library tremendously faster.

**Comment by camsjams** [comment]
Thanks @kitten - yea this wasn't picked up by stylelint (using the styled-components plugins) but I think its probably more rare than a typical hand-coded invalid CSS rule which stylelint discovers as expected.
