### ISSUE TITLE
"Cannot find a StyleSheet instance" in production error reporting

### ISSUE THREAD

**Issue by nightpool** [styled-components/styled-components#3106]
## System:
 - OS: Linux 4.19 Debian GNU/Linux 9 (stretch) 9 (stretch)
 - CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
 - Memory: 1.10 GB / 3.84 GB
 - Container: Yes
 - Shell: 4.4.12 - /bin/bash
## Binaries:
 - Node: 12.16.1 - /usr/bin/node
 - Yarn: 1.22.4 - /usr/bin/yarn
 - npm: 6.13.4 - /usr/bin/npm
## npmPackages:
 - babel-plugin-styled-components: ^1.10.0 => 1.10.0 
 - styled-components: ^4.1.3 => 4.1.3 

## Reproduction

We're seeing a lot of reported Error 10s in production that we can't reproduce on our own machine or in our development environment—sometimes spiking up to 1% of page loads. We're absolutely certain that we don't have two copies of styled-components in our node_modules, and 99% of our page loads are fine. 

```
$ bin/yarn list styled-components
yarn list v1.22.4
warning Filtering by arguments is deprecated. Please use the pattern option instead.
└─ styled-components@4.1.3
Done in 1.68s.
```

Has anyone else seen this error in production? Besides the node_modules issue mentioned in the errors doc, what are other possible reasons for this error to occur?

**Comment by nightpool** [comment]
We haven't seen any occurrences of this error after upgrading to v5, but it was our biggest library crash when we were on v4. Might be worthwhile to keep this open for those who aren't able to upgrade to v5, or haven't yet.

**Comment by kitten** [comment]
Going through some old issues, but this will be closed due to inactivity. In general, issues without reproductions or many details are more likely to not receive any responses. Sorry!

It used to be that this was caused by duplicate `styled-components` instances. These don't always have to be installed. Sometimes it comes down to your bundle. This is generally then caused by a new instance rehydrating and deleting the style sheet of the other instance. However, this is now less likely since all tags are marked as "active" by their instances, which prevents them from being deleted.

However, this can still occur if _any script_ modifies the `style` tag as styled-components is using it, which can cause it from being detached and it losing all of its styles. You can see the "newer" version of the same error as `17` here: https://github.com/styled-components/styled-components/blob/d96101a102b59a8f9ac4b6f278594674897282bb/packages/styled-components/src/sheet/dom.ts#L43-L58
