### ISSUE TITLE
Support for CSS fallback syntax

### ISSUE THREAD

**Issue by fknop** [styled-components/styled-components#3135]
Hello,

I am using Styled Components with libraries such as `@tailwindcssinjs/macro` which is a macro to resolve TailwindCSS classes. Tailwind has recently added a feature that makes advantage of CSS fallbacks.

The author of `@tailwindcssinjs/macro` offers a nice explanation about this: https://github.com/Arthie/tailwindcssinjs/issues/2#issuecomment-624670282

For example:

```typescript 
"borderColor": ["#fff", "rgba(255, 255, 255, var(--border-opacity))"]
```

This should generate:

```css 
border-color: #fff;
border-color: rgba(255, 255, 255, var(--border-opacity));
```

However, styled-components generates the following, which is not valid css.

```css
border-color: #fff, rgba(255, 255, 255, var(--border-opacity));
```

Currently, Emotion supports this syntax: https://emotion.sh/docs/object-styles#fallbacks.

Is this a feature that could be one day supported by styled-components?

**Comment by fknop** [comment]
Any news on this issue?

**Comment by merrywhether** [comment]
Naively, this seems like a straightforward `Array.isArray` check that then pushes a second (or nth) tuple into the rules set for each array entry (possibly in [this file](https://github.com/styled-components/styled-components/blob/master/packages/styled-components/src/utils/flatten.js)?). Is that on the right track (assuming someone was trying to judge LOE for a contribution)?

**Comment by merrywhether** [comment]
Editing the package locally it seems like this work (editing the cjs version):
```
var objToCssArray = function objToCssArray(obj, prevKey) {
  var rules = [];
  var keys = Object.keys(obj);
  keys.forEach(function (key) {
    if (!isFalsish(obj[key])) {
      if (isPlainObject(obj[key])) {
        rules.push.apply(rules, objToCssArray(obj[key], key));
        return rules;
      } else if (isFunction(obj[key])) {
        rules.push(hyphenateStyleName(key) + ":", obj[key], ';');
        return rules;
      } else if (Array.isArray(obj[key])) { // new entry to the if-else chain
        obj[key].forEach((val) => {
          rules.push(hyphenateStyleName(key) + ": " + addUnitIfNeeded(key, val) + ";");
        });
        return rules;
      }

      rules.push(hyphenateStyleName(key) + ": " + addUnitIfNeeded(key, obj[key]) + ";");
    }

    return rules;
  });
  return prevKey ? [prevKey + " {"].concat(rules, ['}']) : rules;
};
```

**Comment by kitten** [comment]
I think this has been resolved. I may be wrong, but I'm checking this against the implementation: https://github.com/styled-components/styled-components/blob/d96101a102b59a8f9ac4b6f278594674897282bb/packages/styled-components/src/utils/flatten.ts#L25

**Comment by merrywhether** [comment]
Does not look fixed in latest release at least: https://codesandbox.io/s/zen-nobel-dhw13?file=/src/App.js

That line seemingly starts to address this issue, but ends up just creating invalid data.

The [if-check](https://github.com/styled-components/styled-components/blob/main/packages/styled-components/src/utils/flatten.ts#L24)

```ts
if ((Array.isArray(obj[key]) && obj[key].isCss) || isFunction(obj[key])) {
```

is basically the same as the [line that sets the `isCSS` property](https://github.com/styled-components/styled-components/blob/main/packages/styled-components/src/constructors/css.ts#L12-L18) (not really sure what `isCss` is meant to do here):

```ts
const addTag = (arg: ReturnType<typeof flatten> & { isCss?: boolean }) => {
  if (Array.isArray(arg)) {
    // eslint-disable-next-line no-param-reassign
    arg.isCss = true;
  }
  return arg;
};
```

From there, it adds a [single rule with the raw rule value](https://github.com/styled-components/styled-components/blob/main/packages/styled-components/src/utils/flatten.ts#L25)
```ts
rules.push(`${hyphenate(key)}:`, obj[key], ';');
```

Consumers of the `flatten` function then [assume that all the values have been normalized](https://github.com/styled-components/styled-components/blob/main/packages/styled-components/src/models/ComponentStyle.ts#L65-L70) (that cast to `string[]` hints at the problem)
```ts
        const cssStatic = (flatten(
          this.rules,
          executionContext,
          styleSheet,
          stylis
        ) as string[]).join('');
```

And the code yields what you'd expect: a stringified array value for a single key (from the codesandbox above):
<img width="231" alt="Screen Shot 2021-08-15 at 7 54 30 AM" src="https://user-images.githubusercontent.com/4097742/129482960-effa71b4-9465-4aa6-ad59-d0f7f2fb3337.png">

Array handling needs to generate multiple entries for the same key so that css can generate the proper output (from the hand-written version in the codesandbox):
<img width="216" alt="image" src="https://user-images.githubusercontent.com/4097742/129483021-dba3ca6f-5ebf-4b06-9a84-06e07d824ee2.png">
