### ISSUE TITLE
Extended Components don't inherit PropType checks

### ISSUE THREAD

**Issue by xenostar** [styled-components/styled-components#3183]
## System:
 - OS: macOS 10.15.5
 - CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
 - Memory: 404.08 MB / 16.00 GB
 - Shell: 5.7.1 - /bin/zsh
## Binaries:
 - Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
 - Yarn: 1.22.4 - /usr/local/bin/yarn
 - npm: 6.14.5 - ~/.nvm/versions/node/v12.14.1/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
## npmPackages:
 - babel-plugin-styled-components: ^1.10.6 => 1.10.7
 - styled-components: ^5.1.0 => 5.1.1

## Reproduction

https://codesandbox.io/s/naughty-rgb-em3t1?file=/src/App.js

## Steps to reproduce

Extend a simple styled-component with `styled()`. It will not inherit PropTypes checks from the extended component.

## Expected Behavior

In the example provided in the [CodeSandBox](https://codesandbox.io/s/naughty-rgb-em3t1?file=/src/App.js), I would expect the extended component to inherit the PropTypes checks from the parent component. Instead, I'd have to re-implement them with the new name of the component. You can uncomment the secondary PropTypes check to see it work.

## Actual Behavior

PropType checks do not work on extended components, and must be re-implemented. Is this normal/intended behavior? It seems really odd since sometimes I just want to extend one of my components and change one or two CSS values, but I don't want to have to necessarily re-implement all the PropType checks again.

**Comment by kitten** [comment]
That's intentional and comes from `hoist-non-react-statics`: https://github.com/styled-components/styled-components/blob/master/packages/styled-components/src/models/StyledComponent.js#L10

The reason for `PropTypes` checks to not be repeated is because they don't have to be repeated. When you have `const A = styled(B)` where `B` has `propTypes` checks, then `B` will be rendered and will execute its checks anyway.

The issue here likely stems from the fact that you basically have a `StyledComponent` inside another, in that case folding will get confused as to where your prop-types are from and you'll have to recreate them, but luckily `A.propTypes = B.propTypes` will work just as well in that case :)
