### ISSUE TITLE
npm audit failing on lodash vulnerability

### ISSUE THREAD

**Issue by JoannaG33** [styled-components/styled-components#3192]
Since this week, npm audit is flagging a vulnerability in lodash.

 https://npmjs.com/advisories/1523

Lodash has been asked by many to merge PR's to fix the issue, but seems to be ignoring and has been for a long time. Hopes for a fix seems slim, based on them closing the issue:

https://github.com/lodash/lodash/issues/4744

Perhaps it's time to consider dropping lodash from styled-components? Or to fork and fix?

In our case this is now flagged by security and could become a matter of having to refactor our entire portal to drop styled-components.

**Comment by kitten** [comment]
`lodash` is only a dependency of `babel-plugin-styled-components`, so it never ends up in your application if only `styled-components` is used. I don't think `babel-plugin-styled-components` actually needs `lodash` and I'm not sure when it was added, but feel free to open an issue over on the other repository: https://github.com/styled-components/babel-plugin-styled-components

But that being said, this doesn't affect your application and you'll need to always research first where any potential vulnerabilities come from. This one is even a "prototype pollution" vulnerability, which means that in all likelihood it has no effect on your application at all, since we're not talking about anything that'd flow into it. Furthermore it's only in a rarely used utility: `zipObjectDeep`

**Comment by MateuszPrzybyla** [comment]
@kitten we're seeing security vulnerabilities found by the BlackDuck due to `babel-plugin-styled-components` being defined as regular dependency of `styled-components` and as a result we've got `lodash` bundled in our app, shouldn't it rather be a dev dependency so it does not end up in the library bundle together with `lodash`?
![image](https://user-images.githubusercontent.com/5739484/143582298-8789ce28-3430-44a7-878d-f3f76f234830.png)
