### ISSUE TITLE
[React Native] Custom style prop

### ISSUE THREAD

**Issue by sourabhv** [styled-components/styled-components#3214]
I have a component which accepts `style`, `contentContainerStyle` and a few more style props.
These style props are passed down to a child components which is a styled component. 

Styled component (i am guessing) breaks down all margin/padding into individual `-top`/`-bottom`/`-left`/`-right` values. Now, passing `{padding: 10}` to `contentContainerStyle` doesn't work coz individual `-top`/`-bottom`/`-left`/`-right` take preference. And writing `{paddingTop: 10, paddingBottom: 10, ...}` seems too verbose.

So, is there a way to somehow pass the styled component style into a custom prop, or compile CSS to RN styles and pass them down?

**Comment by sourabhv** [comment]
Bump! in case this was somehow missed

**Comment by kitten** [comment]
This is an intentional limitation, but you can work around this by either going through `css-to-react-native` yourself (https://github.com/styled-components/css-to-react-native) or by using styled-components itself to convert the styling, by interpolating the object. (which would also go through css-to-react-native)

Please refer with usage questions to Stack Overflow, as you're more likely to get quicker and helpful answers there ❤️ Repository issues on GitHub are great for that, issues, things that need to be resolved in the library itself, or can't be resolved by anyone but the maintainers. While I (and many others on other repos) are happy to eventually answer usage questions, styled-components is a busy repo and mostly stable and slow moving towards new releases, so you're not likely to get fast responses here
