### ISSUE TITLE
Different output for invalid CSS

### ISSUE THREAD

**Issue by dimaqq** [styled-components/styled-components#3234]
## Environment

`npx envinfo --system --binaries --npmPackages styled-components,babel-plugin-styled-components --markdown --clipboard`

## System:
 - OS: macOS 10.15.6
 - CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
 - Memory: 10.57 GB / 32.00 GB
 - Shell: 3.1.2 - /usr/local/bin/fish
## Binaries:
 - Node: 14.5.0 - /usr/local/bin/node
 - Yarn: 1.22.4 - /usr/local/bin/yarn
 - npm: 6.14.7 - /usr/local/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
## npmPackages:
 - styled-components: ^5.1.1 => 5.1.1

## Reproduction

I made a mistake in my style and forgot units:
```
import styled from "styled-components/macro";

const Foo = styled.div`
  position: absolute;
  bottom: 15;
  right: 15;
`;
```

The result is markedly different depending on how I "build" the project (CRA+SC):

* in dev mode (`yarn start`) the injected style has `15px`,
* in compiled mode (`yarn build`) the fields `bottom` and `right` are quietly removed, and
* in compiled mode with `REACT_APP_SC_DISABLE_SPEEDY=1`, the injected style has `15` like I wrote†

† of course the value without units is invalid and is ignored by the browser; but browser dev tools alerted me to this

The difference between `yarn start` and `yarn build` with default options is the worst for the (silly) developer — there are **no warnings** and the resulting UI **looks different**

**Comment by kitten** [comment]
There's not really any way to resolve this as it comes down to the CSSOM API doing its thing and generating only valid CSS and not treating CSS as raw strings. I believe, this behaviour may differ from browser to browser too, but I may be wrong.

Anyway, sorry, I'll have to close this for now due to inactivity. In general, this is also an issue that's unrelated to the codebase in this repository itself, so there's not really any way forward to resolve this. In other words, no change in this repository has any chance of resolving this, as it's unrelated, which makes this issue open-ended potentially.
