### ISSUE TITLE
Web site

### ISSUE THREAD

**Issue by fermo111** [styled-components/styled-components#3235]
Following the link in the README.md (https://www.styled-components.com/docs) I found a page which sponsorises Biden US Presidential campaign.

Isn't it better to stick to coding rather than using code to promote a political agenda?

**Comment by kitten** [comment]
I'm not quite sure what you're talking about. If you're talking about our documentation site itself with the link you posted, those are in fact our docs.

If you're talking about the banner on the docs site itself linking to the Equal Justice Initiative and Black Lives Matter, then first of all I have to tell you that that initiative isn't donating to Biden's presidential campaign.

In fact we've added it in solidarity with the movement and the human rights issues at hand not only in the US but globally. If it doesn't fit your political view I can only kindly request you to simply ignore it.

**Comment by fermo111** [comment]
Thank you kitten for your kind answer 

Yes, I am talking about  BLM, which as a matter of fact does endorse Biden campaign, as a simple internet search for the word "Biden" and "BLM" would reveal. Infact it has been suggested, with strong arguments, that the found received by the BLM accounts are automatically forwarded to the Biden accounts campaign. 

But the issue here is more general, and does not have to do with my political views (is I have any). It has to do with free software and its motivations, as first explained by Richard Stallman. Free software is a declination of freedom and sharing concepts in general. There have been recently, however, an attack against freedom hidden behind the label of sensible social issues (blacks, LGBT, ecology, feminism, etc. you name it) which uses censorship as the main tool of action. Recently, for few weeks, we have seen it in action in the SW industry. The target was Facebook which refused to apply censorship to conservative ideas (labeled as fake news or hate speech) and the mean was dropping ads in that platform. Motivation were diverse. Microsoft (the owner of Github) did it because Bill Gates is now selling vaccines and had its reasons to censor the antivac movement. Unilever did it because it was useful to regain credibility after the the accusation of crimes against environment and African people. Others did it because it would serve the anti-Trump campaign (Tweeter in primis).
The result has been an unhealthy convergence of scopes between corporate interests and political (leftist) strategy, which is going to be a major factor in changing the approach towards constitutional rights. Censorship is a blow against the Bill of Rights, which is a founding stone of the american dream.
Once censorship is legitimized, the road to totalitarianism is wide open. Who will get the fruits is unclear. Today maybe it would serve the left, but ones the principle is established, how to prevent its exploitation from other groups or ideologies?

So, in the end, what is the relationship between censorship, software and BLM. BLM is integral part of a larger movement that find censorship a useful tool. If you don't believe me, search internet for the many black university professors, who are forced to publish anonymously for fear to loose their job, search for those professors who actually lost their job (Norman Finkelstein
for instance) and are not allowed to teach in USA because their political views does not coincide with the current mantra. 

Can the software freedom movement really pretend to ignore the fact the more fundamentally liberties are not at risk? Are you really sure that associating your software with a particular political movement whose methods seems to defy those principles is a good choice to promote your software? It may not be strictly a software "bug" worthing opening on issue. Consider it as a cry from an old fellow programmer (I started programming in the seventies), politically involved with free software (I wrote the text of a law proposal for the adoption of free software in the public administration of my country) who thinks that free software is part of a more general freedom.

**Comment by kitten** [comment]
BLM is a movement hence by definition it can't endorse anyone in unity. We're talking about the Equal Justice Initiative. So that implication is simply absurd as you're not differentiating between the simple definition of movements, a political call (that BLM stands for as well), and an initiative.

I understand your appeal to free software and I agree that free software doesn't make itself unavailable to any particular group. I find any other idea of Open a Source Software as being "Free" flawed otherwise.

Corporate censorship, governmental censorship is a very clear line. Individuals can not censor any platform or content, they can merely protest, condemn, attack, or threaten either content publishers, organisations, or individuals. Obviously no one in their right mind would endorse the latter, threats.

Now freedom of speech is a very clear right, but rights to individual freedoms stop where the freedom of others is threatened or limited; a fundamental principle. If anyone stands up against harmful content or opinions that threaten a group's rights and livelihood then I and many more will stand out against this. That's not censorship.

Arguably ableist opinions being criticised by individuals is appealing to human rights, appealing against acts that attempt to dehumanise individuals is important. Or would you argue against that?

If anything, the most dangerous movement in the US from my perspective is that opinions are polarising. And polarisation leads to conflict. If two streams of opinions lean more to two extremes I won't stand here and be accused of being on either end of an extreme spectrum. But I will stand up for what is right.

To come back to a very simple conclusion: Open Source is political. Every individual is political, every organisation is political; in the sense of having a stance and opinion. And not acting or not standing for anything is just as much a position as any other.

We have decided that we won't remain silent.

**Comment by probablyup** [comment]
@fermo111 ultimately we can put whatever we'd like on our site. Arguing against an organization that fights blatant racism just looks bad on you 🤷‍♂️
