### ISSUE TITLE
Prop `className` did not match in development (SSR).

### ISSUE THREAD

**Issue by mattcarlotta** [styled-components/styled-components#3238]
# Bug report

I've built a package that [composes styled components](https://github.com/mattcarlotta/composable-styled-components). If I inline the package and reference it locally within a project (`~lib`), no warnings are shown in development. If I utilize the same code from the [npm package](https://www.npmjs.com/package/composable-styled-components), then className mismatch warnings are thrown. This appears to only impact development as production builds don't display any FOUC.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Clone repo: `cd ~/Desktop && git clone git@github.com:mattcarlotta/sc-prop-mistmatch.git` (or download [repo](https://github.com/mattcarlotta/sc-prop-mistmatch))
2. Change to project dir: `cd sc-prop-mistmatch/`
3. Install deps: `yarn`
4. Run project in dev: `yarn dev`
5. Visit http://localhost:3000
6. Open browser dev console
7. Click `Go to Example` button
8. Click `Go home` button
9. Refresh page
10. [Warnings are thrown](https://i.imgur.com/25Slas9.png)
11. Comment out `<PackageComposedButton>Package (warning)</PackageComposedButton>` within `pages/index` and repeat steps 7-9
12. [No warnings are thrown](https://i.imgur.com/zmZCuit.png)
13. Build for production: `yarn build && yarn start`
14. Visit http://localhost:3000 (styles appear to be applied properly upon initial load, client-side navigation, and page refresh)

## Expected behavior

No warnings are thrown in development.

## System information

- OS: LMDE 4
- Version of Next.js: 9.5.2
- Version of Node.js: v10.22.0

## Additional context

Not 100% sure if this is a Next issue or a styled-components issue.

Works fine in CSR apps: 
https://vyzqr.csb.app/

Throws warnings in SSR apps (may require a few hard refreshes):
https://c3yb5.sse.codesandbox.io/

Cross referenced bug on Next: https://github.com/vercel/next.js/issues/16637

**Comment by Fi1osof** [comment]
Any progress?

**Comment by steve-taylor** [comment]
> Not 100% sure if this is a Next issue or a styled-components issue.

This is a long-standing Next issue which has been raised many times and is always closed without resolution. Good luck!

**Comment by kitten** [comment]
My guess is that since `babel-plugin-styled-components` isn't generating consistent `componentId`s for the component you're eventually seeing hashes diverge between the server-side and client-side.

This can quickly happen due to some smaller mismatches in how the components are created, but ultimately will happen if you have styles that generate the same hashes that are then created in a different order. This will generate different `componentId`s quite frequently since the order of creation will differ between the server and client, especially in Next.js

With the current approach there's not much we can do here. The process of composing `styled-components` this aggressively isn't quite recommendable as-is imho.

I'll close this for inactivity, since there hasn't been a new development on matter of 1) this approach in our API, 2) this issue in general across libraries, 3) activity on this issue excluding bumps (see above). Sorry!

**Comment by machineghost** [comment]
>since the order of creation will differ between the server and client, especially in Next.js

Could you clarify this bit: assuming consistent data, which generates consistent elements, why would the order of creation differ between server and client?  Or are you saying "this can only happen if you randomly sort your data"?
