### ISSUE TITLE
How to generate subclasses - probem with layout jumps when swapping classes

### ISSUE THREAD

**Issue by mieszko4** [styled-components/styled-components#3240]
## Environment
`styled-components@4.4.0`, `Chrome Version 84.0.4147.89 (Official Build) (64-bit)`
Using nextjs dev

## Reproduction

Today I've run into the problem of not having subclasses.
Take a look at this example:
```jsx
const activeImage = css = `
  opacity: ${p => p.active ? 1 : 0}; /* this is simplified version */
`;

const Image = styled.img`
  position: absolute;
  top: 0;
  width: 100%;
  height: 100%;

  object-fit: cover;
  object-position: 12px 14px; /* NOTE: this part causes screen jumps/releayoyuts because entire class is replaced instead of just a subclass */

  ${activeImage}
`;
```

https://github.com/mieszko4/styled-components-subclass-jump

### My expectations

I would expect that two classes would be generated:
1. class for `Image` component
2. class for `activeImage` mixin.

### My problem

I am using something similar for my image carousel.
I render a few images and mark only one as active.
The active image changes every few seconds.

Now, when marking another active image happens, **the layout jumps**...
And this is **because the entire class is swapped** instead of swapping only `activeImage` subclass

### My workaround

My workaround is to manually add the class:

```jsx
const Image = styled.img`
  position: absolute;
  top: 0;
  width: 100%;
  height: 100%;

  object-fit: cover;
  object-position: 12px 14px;

  opacity: 0;
  &.active {
    opacity: 1;
  }
`;
<Image className={props.active ? 'active' : ''} />
```

## Questions

Is there a better way to do it with styled-components?
I feel like generating subclasses should be done automatically:
* for mixins
* and/or when inheriting from other styled components.

Or at least there should be a way to force it.
I do not see the reason why it would be problematic?

**Comment by probablyup** [comment]
@kitten can you speak to this?

**Comment by polarathene** [comment]
[I had a similar problem](https://github.com/styled-components/styled-components/issues/2394#issuecomment-464624668) where I only needed about 7 classes, not 200 unique ones for each permutation. You can use the prop in this case for an inline style modification instead:

```jsx
const SpriteSheetIcon = styled.img.attrs( props => {
  // Any additional logic can be done here before returning
  // Below adds the style prop/attribute for only updating opacity inline.
  return {
    style: { opacity: props.active ? 1 : 0 },
  }
})`
  position: absolute;
  top: 0;
  width: 100%;
  height: 100%;

  object-fit: cover;
  object-position: 12px 14px;
`
```

In my linked issue, I attempted a very similar thing with an opacity toggle that unfortunately doubles the amount of classes generated(eg 100 to 200):

```jsx
const Icon = styled(SpriteSheetIconInline)`
 opacity: ${props => (props.isActive ? 1 : 0.2)};
`
```

The linked issue instead resolves it by pre-generating each variation that would change and just adding CSS classes manually instead of relyling on styled-components for that. @probablyup decided it wasn't a valid issue to be concerned about with styled-components and closed the issue.

**Comment by kitten** [comment]
This isn't possible in styled-components and we won't be able to add this. Our ordering guarantee is pretty strong which enforces that rules from created `StyledComponent` have a consistent order. Having a separate order for `css` breaks this guarantee because they may end up interleaving.

> Now, when marking another active image happens, the layout jumps...
And this is because the entire class is swapped instead of swapping only activeImage subclass

I'm not sure how you end up with this conclusion: are you using React concurrent mode which is experimental and your change is heavily delayed? We just insert the styles on render so it should ultimately be just in sync as if you used `style`, which is probably a good suggestion if you're changing a CSS property a lot.

Either way, let's keep the issue report separate from a change suggestion, which is already trying to diagnose the issue 😅 Do you have a reproduction?

@polarathene Your problem is unrelated, since you're talking about interpolations generating a lot of rules, rather than two in this case, but the suggestion is correct 🙌

**Comment by polarathene** [comment]
I assumed this was related in that the `${activeImage}` usage was similar (at a smaller scale), where the solution might have been keeping a separation with distinct classes and handling any specificity concerns for those "child"/dynamic styles with the class repetition [as shown here](https://styled-components.com/docs/faqs#how-can-i-override-styles-with-higher-specificity). 

At least, if this is all happening within styled-components, I assume it can manage it properly in some way. If there's no way for the ordering to remain deterministic, fair enough. Thanks.

**Comment by mieszko4** [comment]
I took a little bit more time here to reproduce this and I started with nextjs app skeleton.
The conclusion is that:
* it happens in chrome (firefox did not cause the issue)
* it happens during development in nextjs (production build did not cause the issue)
* it happens only when custom font is included and used (remote font did not cause the issue)
* this jumpy effect is caused by reapplying the font and it happens only on the first iteration

If you want to check it yourself check https://github.com/mieszko4/styled-components-subclass-jump#how-to-reproduce - just make sure to checkout the correct commit (I did not manage to reproduce this in codepen)

So maybe the issue is the combination of hydrating and applying css rules by chrome when in nextjs dev environment...
In any case the rendering is complex so I will not get deep into that.
I believe chrome should be the one to fix this, but on the other hand maybe there will be situations with a lot of css rules where such situation will be unavoidable?

So, if we put aside this bug,
In the pursuit of faster and more performant apps I am convinced that having an option to generate subclasses would help generating less css so I would not cross out the idea of generating subclasses using styled-components just yet.

**Comment by kitten** [comment]
@mieszko4 If a custom font is included I can explain this. Chrome has an issue/bug where any `CSSStyleSheet` is re-evaluated when new rules are added. This is exactly what this spec is supposed to not do for CSSOm, but Chrome does it with and without.

This means that it'll re-request fonts and sometimes even images. This may delay layouting and rendering sometimes.

When you make sure that these assets have a `Cache-Control` header then often the issue isn't as pronounced (even in development; in production this doesn't occur if it's set up)

But ultimately pulling custom fonts and imports out of styled-components solves this much better for Chrome.

**Comment by mieszko4** [comment]
thnx @kitten If you happen to know the link for that issue in Chrome I think it would be great to paste it here for the reference.

**Comment by R4VANG3R** [comment]
Shouldn't you be able to work around this by making a static base component and extending it with a dynamic one?

```jsx
const BaseImage = styled.img`
  position: absolute;
  top: 0;
  width: 100%;
  height: 100%;

  object-fit: cover;
  object-position: 12px 14px;
`;

const Image = styled(BaseImage)`
  opacity: ${p => p.active ? 1 : 0};
`;

<Image active={active} />
```

**Comment by mieszko4** [comment]
thnx @R4VANG3R 

This still does not work for me.
1. `BaseImage` - will generate `class1` which will always be appended
2. `Image` - will generate **two** classes `class2-active` and `class2-nonActive` and only one will be appended at one time (so this will again cause class swap)

## Solution
**However**, you inspired me to check something that works for me now:
```es
const BaseImage = styled.img`
  position: absolute;
  top: 0;
  width: 100%;
  height: 100%;

  object-fit: cover;
  object-position: 12px 14px;

  opacity: 0; /* this is simplified version */
`;

const activeImageCss = css`
  opacity: 1;
`;

const Image = styled(BaseImage)`
  ${p => p.active && activeImageCss}
`;
```

1. `BaseImage` - will generate `class1` which will always be appended
2. `Image` - will generate only **one** class now  `class2-active` which will be appended only when active is true

(Note the class names are made up)


Thanks again! I will close this ticket now.
