### ISSUE TITLE
5.2 feedback

### ISSUE THREAD

**Issue by probablyup** [styled-components/styled-components#3244]
https://github.com/styled-components/styled-components/releases/tag/v5.2.0-test.10

Please help us test!

```shell
yarn add styled-components@5.2.0-test.12
```

- Preallocate global style placement to ensure cGS is consistently inserted at the top of the stylesheet; note that this is done in _runtime order_ so, if you have multiple cGS that have overlapping styles, ensure they're defined in code in the sequence you would want them injected (see [#3239](https://github.com/styled-components/styled-components/pull/3239))

  **NOTE: This is a behavioral change and might require adjustment in your codebase if you have many `createGlobalStyle` components in use. We do not think it will affect the majority of projects other than fix existing bugs.**

- `createGlobalStyle` is now `React.StrictMode` compliant

- Make sure `StyleSheetManager` renders all styles in iframe / child windows (see [#3159](https://github.com/styled-components/styled-components/pull/3159)) thanks @eramdam!

- Rework how components self-reference in extension scenarios (see [#3236](https://github.com/styled-components/styled-components/pull/3236)); should fix a bunch of subtle bugs around patterns like `& + &`

- Fix `keyframes` not receiving a modified stylis instance when using something like `stylis-plugin-rtl` (see [#3239](https://github.com/styled-components/styled-components/pull/3239))

- Big performance gain for components using [style objects](https://styled-components.com/docs/advanced#style-objects) (see [#3239](https://github.com/styled-components/styled-components/pull/3239))

- We no longer emit dynamic classNames for empty rulesets, so some className churn may occur in snapshots

- Add "engines" to package.json (currently set to Node 10, the oldest supported LTS distribution) (see [#3201](https://github.com/styled-components/styled-components/pull/3201)) thanks @MichaelDeBoey!

**Comment by willheslam** [comment]
Using npm and installing "styled-components": "^5.2.0-test.10", testing this and got the error:
```
TypeError: Cannot use 'in' operator to search for 'HTMLElement' in false
    at Object.<anonymous> ([project]/node_modules/styled-components/dist/styled-components.cjs.js:1:1204)
```

which is originating from:
```
S="HTMLElement"in!1
```
in node_modules/styled-components/dist/styled-components.esm.js
and
node_modules/styled-components/dist/styled-components.cjs.js
which certainly seems incorrect (how can "HTMLElement" be `in` `false`?).
That problem is NOT present in
node_modules/styled-components/dist/styled-components.browser.esm.js
or
node_modules/styled-components/dist/styled-components.browser.cjs.js
which have the correct`"HTMLElement"in window` instead.

It seems like that line comes from:
```
export const IS_BROWSER = typeof window !== 'undefined' && 'HTMLElement' in window;
```
from
packages/styled-components/src/constants.js

So it looks to me like the node-targeted builds are compiling `window` away and producing incorrect code, whereas the browser versions are preserving it.

For context this was encountered in a nextjs project when rendering react components at build time.

**Comment by probablyup** [comment]
That'd be this: https://github.com/styled-components/styled-components/blob/a6b14070c438e25959403c3a9539844ee981c494/packages/styled-components/rollup.config.js#L111-L124

I would have thought terser would have compiled that away to `false` since `typeof false !== 'undefined'` but will look into it further. Thanks for reporting!

**Comment by probablyup** [comment]
@willheslam give 5.2.0-test.11 a try

**Comment by willheslam** [comment]
@probablyup Cheers, that fixed that problem! Thanks for the quick turn around!

It's given rise to another interesting error that only occurs when running `next build`, which, like before, produces a production build of JS then server-side renders some React components:
```javascript
TypeError: Cannot read property 'fonts' of undefined
    at /[project]/.next/server/pages/index.js:621:112
    at ee (/[project]/node_modules/styled-components/dist/styled-components.cjs.js:1:12379)
```
`theme` is undefined:
```typescript
import styled from '../styled'
import { rhythmFromFont } from '../rhythm'

const BoxText = styled.div<{
  readonly standout?: boolean
}>(({ theme, standout }) => {
  return {
    ...rhythmFromFont(theme, theme.fonts.body),
    color: standout ? theme.colors.neutral_white : theme.colors.slate_700,
  }
})

export default BoxText
```

Interestingly this error doesn't occur when when running the nextjs dev server, which to my knowledge doesn't minify any JS before running it. I don't know for sure whether it's rendering the React components on the server side either so I don't want to claim this is a node/browser difference.
(i.e. when running `next dev`, `theme` always has a property called `fonts`)

I'm using a theme provider in an essentially normal way - the biggest difference is that my `styled` import comes from this file:
```typescript
import styled, { ThemedStyledInterface } from 'styled-components'
import { Theme } from './themes'
export * from 'styled-components'
export default styled as ThemedStyledInterface<Theme>
```
rather than importing styled-components directly.

Unfortunately I don't have a small reproduction of the bug beyond what you see above - I'll let you know if I find an easy way to reproduce the problem.

**Comment by probablyup** [comment]
@willheslam No idea on that one, there shouldn't be any difference unless there are somehow two copies of react or s-c in use. A reproduction would definitely be helpful if you can make one.

**Comment by probablyup** [comment]
If you use yarn, you can try using the "resolutions" package.json setting to force any s-c usage to the exact same package version.

```json
{
  "resolutions": {
    "styled-components": "5.2.0-test.11"
  }
}
```

**Comment by willheslam** [comment]
I'm using npm, but I'll check any conflicting copies of react or s-c.

No reproduction yet, but I've noticed that in `5.2.0-test.11`, the conditional here is true, passing in an empty object that directly leads to the TypeError because `theme` is missing, and in `^5.1.1` where the project builds without error, the conditional here is false, and `resolvedAttrs` is an object that contains the `theme` property.
```
  const className = isStatic
    ? componentStyle.generateAndInjectStyles(EMPTY_OBJECT, styleSheet, stylis)
    : componentStyle.generateAndInjectStyles(resolvedAttrs, styleSheet, stylis);
```

`isStatic` equates to `componentStyle.isStatic && !hasAttrs`, and `componentStyle.isStatic` is calculated from the `rules` passed to:
```
new ComponentStyle(
    rules,
    styledComponentId,
    isTargetStyledComp ? ((target: Object).componentStyle: ComponentStyle) : undefined
  );
```

Changing the `rules` parameter to partially revert the change here https://github.com/styled-components/styled-components/commit/44152caa199b0b322aeaf42713804b484208a3e1#diff-b97c58d0b5d2df2981674fb8779b99bb
fixes the problem by causing `isStatic` to be false, no longer making the BoxText component receive an `EMPTY_OBJECT`.

It ends up looking like this:
```
  const componentStyle = new ComponentStyle(
    isTargetStyledComp
      ? // fold the underlying StyledComponent rules up (implicit extend)
        // $FlowFixMe
        target.componentStyle.rules.concat(rules)
      : rules,
    styledComponentId,
    isTargetStyledComp ? ((target: Object).componentStyle: ComponentStyle) : undefined
  );
```
I have no idea if this is an appropriate fix or how much of the intended changes for 5.2 it reverts, but this allows my app to render React components on both on the server side and in the browser, matching the behaviour of 5.1.

(It also explains why this wasn't triggered in dev mode, due to the NODE_ENV check ensuring `isStatic` is always false during development:
`    this.isStatic = process.env.NODE_ENV === 'production' && isStaticRules(rules);`
)

**Comment by willheslam** [comment]
@probablyup I have a small reproduction here:

https://github.com/willheslam/styled-components-wrapped-dynamic-in-static-reprod

The problem is when a dynamic component is wrapped by a static one:
```javascript
const Foo = styled.div(({ theme }) => {
    console.log('theme is', theme) // theme should not be undefined!
    return ({
      color: theme.color.text
  })
})

// `theme` inside Foo is only undefined when Foo is wrapped by Bar
const Bar = styled(Foo)({
  backgroundColor: 'green'
})
```

Rendering `Bar` causes the function inside `Foo` to receive an empty object, because `Foo` is now treated as static when it actually isn't.

**Comment by probablyup** [comment]
5.2.0-test.11 is out with those two PR fixes

**Comment by probablyup** [comment]
@willheslam all good on your end with .12?

**Comment by willheslam** [comment]
@probablyup Yep, my app renders correctly with 5.2.0-test.12 on both the server and client side, and no obvious visual changes (snapshots have changed slightly as expected). 👍

**Comment by greenimpala** [comment]
I am not getting any global styles loading on `5.2.0`. With `5.1.x` it is working fine. Is there a preferred way to debug what's happening? The CSS is not present in the DOM at all.

**Comment by probablyup** [comment]
@greenimpala hey there, do you have a reproduction I can look at?

**Comment by dfernandez79** [comment]
@greenimpala Do you have this problem in tests or it happens in the app?

I'm asking because since upgrading to `5.2.0` I'm having problems with some tests that used `window.getComputedStyle`. (JSDOM implementation is incomplete, but it worked for some tests).

But after a downgrade to `5.1.1` it worked again. I'm not sure about the cause, but if your issues are happening during tests perhaps there is a common cause.

**Comment by eramdam** [comment]
I wanted to give the .test package a try before the release was cut, but it looks like I was too late, and I found a bug 🙈 

I've made a simple repro case on CodeSandbox https://codesandbox.io/s/styled-components-base-forked-ehw35

The TL;DR is that, given a component whose styles are defined like below

```javascript
import styled, { css } from "styled-components";

export const Button = styled.div`
  border-radius: 10px;
  padding: 10px;
  color: black;
  display: inline-block;

  ${(p) => addConditionalStyle(p)};
`;

function addConditionalStyle(props) {
  if (props.isSelected)
    return css`
      color: blue;
      background-color: white;
    `;

  if (props.isDisabled)
    return css`
      color: grey;
      background-color: white;
    `;

  return css`
    color: black;
    background-color: grey;

    .hover-parent:hover & {
      color: red;
      background-color: blue;
    }
  `;
}
```

If `<Button />` is given the `isSelected` or `isDisabled` prop, the `.hover-parent:hover &` style will still apply to it even though it shouldn't (or at least that's how it worked until now, but if it's on purpose, that sounds like a breaking change to me). I'll try to bisect and see when that bug appeared but thought I'd throw that up here.

**Comment by probablyup** [comment]
@eramdam actually the behavior is correct, the previous behavior was a bug

**Comment by probablyup** [comment]
@kitten what do you think about adding a different character to represent the dynamic class? I think it'd be less confusing. Perhaps `%`

```js
const Button = styled.div`
      border-radius: 10px;
      padding: 10px;
      color: black;
      display: inline-block;

      ${p => addConditionalStyle(p)};
    `;

    function addConditionalStyle(props) {
      if (props.isSelected) {
        return css`
          color: blue;
          background-color: white;
        `;
      }

      if (props.isDisabled) {
        return css`
          color: grey;
          background-color: white;
        `;
      }

      return css`
        color: black;
        background-color: grey;

        .hover-parent:hover % {
          color: red;
          background-color: blue;
        }
      `;
    }
```

`%` is already a superset of CSS, so adding another control character seems reasonable to keep this functionality totally separate and actually simplify our runtime parsing too.

**Comment by eramdam** [comment]
> However, you can get around this by using the "precedence boost" variant `&&` which applies the dynamic class instead of the static class: https://codesandbox.io/s/styled-components-base-forked-2wbyg?file=/Button.js

Ah! That's good to hear, can confirm using `&&` in those instances fixes the bug entirely 😄

**Comment by kitten** [comment]
@probablyup I'm not sure anymore when we refer to the static class and when we refer to the dynamic class but mostly I think doesn't this come down to our edge-case handling that we introduced for `& + &`? I'd personally be very interested in making it possible to explicitly actually refer to the static class explicitly rather than the dynamic one in most cases for v6.

I don't believe a custom syntax is the way to go (if it diverges from looking like normal CSS) as that just complicates things.

But we should likely have a larger discussion of what the most intuitive behaviour is here.

**Comment by Leonya** [comment]
It would be great to have a separate character as using the `&&` workaround has an obvious drawback, it increases selector specificity.

**Comment by jwld** [comment]
Would be great if `&` vs. `&&` could be explained in detail in the docs - took me a long time to work out that this was causing a styling bug that arose randomly in one of the latest releases (I think pre-5.2).

**Comment by Lazyuki** [comment]
Yeah even though the change in how `&` expands was probably meant to be a "bug fix", the truth is a lot of people were relying on it to behave like how it had always been behaving (mix of dynamic and static class), which means this was a **breaking change** and should have been a major version update if this library is following semver. 

I was trying to see if I can fix `selfReferenceReplacer` to not use static class names if it sees that there are CSS values inside the selector that change based on props, but it seems that's not possible, or at least I don't know enough to do so.

**Comment by fabb** [comment]
> So I think part of the confusion here is what `&` is meant to represent and how the library works. If you look at https://styled-components.com/docs/basics#pseudoelements-pseudoselectors-and-nesting `&` refers back to the static component. When you render multiple variations of the same component, we don't delete styles previously injected, therefore that previous style that refers back to the static class will still exist and be applied.
> 
> However, you can get around this by using the "precedence boost" variant `&&` which applies the dynamic class instead of the static class: https://codesandbox.io/s/styled-components-base-forked-2wbyg?file=/Button.js

@probablyup 
I ran into visual bugs when updating to 5.2 too, but curiously not in all locations where I used `&` as selector for css rules based on props. Any idea why these constructs do **not** cause issues?

```
const StyledAnchorLink = styled(AnchorLink)<{ active?: boolean }>`
    &:after {
        transform: ${(p) => (p.active ? 'scaleX(1)' : 'scaleX(0)')};
    }
`
```
```
const StyledAnchor = styled.a.attrs(testIdAttribute)<{ underline: UnderlineType }>`
    text-decoration: ${(p) => (p.underline !== 'always' ? 'none' : 'underline')};
    &:hover {
        text-decoration: ${(p) => p.underline === 'hover' && 'underline'};
    }
`
```
```
const MultiLineTextTruncationInner = styled.div<{ bgColor: string }>`
    &::before {
        ${background}
    }
`
// uses styled-system to map the `bgColor` prop to the `background` css attribute
const background = system({
    bgColor: {
        property: 'background',
        scale: 'colors',
    },
})
```

**Comment by Lazyuki** [comment]
The `&` selector immediately followed by `:`, `.`, or `#` is not broken. It's "broken" only when `&` is used as a self reference without any other selectors, i.e. `.parent-class & { ... }`

**Comment by fabb** [comment]
It would be nice if this could be added to the documentation.

**Comment by lifeiscontent** [comment]
@probablyup what about using `$` instead of `%`

```js
styled.div`
  & + $ {
    color: blue;
  }

  & + % {
    color: blue;
  }
`
```

both & and % don't belong in CSS, but between $ and %, $ looks more aligned with what CSS might have.

I'm also worried about the wack-a-mole I'm going to play once I upgrade. is there a way we could show warnings?

**Comment by probablyup** [comment]
I wouldn't want to totally remove `&` at this point since it's a shared API detail between s-c and emotion. Perhaps just changing the docs to recommend `&&` for component instances vs any instance of the component (`&`) is the better choice at this point to differentiate.

**Comment by lifeiscontent** [comment]
@probablyup I wasn't suggesting to remove it, but I was specifically suggesting to use `$` for component instances, but `&&` seems reasonable also, idk if that'd impact perf though.

**Comment by probablyup** [comment]
@lifeiscontent it shouldn't!

**Comment by lifeiscontent** [comment]
@probablyup I don't remember where, but google did some research on selector lookup cost and .a.b is exponential

**Comment by lifeiscontent** [comment]
https://www.stevesouders.com/blog/2009/03/10/performance-impact-of-css-selectors/

**Comment by probablyup** [comment]
Fair enough, we can detect and optimize the `&&` case into a single selector if it's not being used as a precedence booster

**Comment by lifeiscontent** [comment]
@probablyup let me know if you need a test bed, I've got a UI kit I've been working on http://lifetimeui.com with styled components

**Comment by kitten** [comment]
This is very likely premature optimisation and I wouldn't be surprised if this doesn't matter anymore at all 😅 That article is from 2009.

**Comment by ben-rogerson** [comment]
> The `&` selector immediately followed by `:`, `.`, or `#` is not broken. It's "broken" only when `&` is used as a self reference without any other specifiers, i.e. `.parent-class & { ... }`

@probablyup Are there any plans to revert/adjust the behaviour of `&` when used in this way?
[twin.macro](https://github.com/ben-rogerson/twin.macro) uses this method to apply dark mode classes so before I update the selector to `.dark && { ... }` for everyone I need to know if this is how it's going to be from now on.
Cheers

**Comment by lifeiscontent** [comment]
@kitten its still very much an issue. Have you tested it yourself? I'd recommend not sweeping concerns under a rug unless you have benchmarks to back it up.

**Comment by kitten** [comment]
@lifeiscontent Look mate, that's a little snarky. But my main point is that `&&` as precedence booster is not targeting more than one class. The article for instance is not even about this and those are eleven year old results. If we run into trouble for this in a real-world app then it's worth considering but until then selective (meaning tens) of precedence boosts will have negligible impact until a benchmark proves otherwise.
This is not sweeping anything under the rug. If we had numbers that prove otherwise and if we could do something about it then that would sweep things under a rug.

@probablyup on an unrelated note; we may want to flag a discussion about how to deal with `&` resolution in v6 to make it more intuitive.

**Comment by danilowanner** [comment]
@kitten @probablyup I also ran into this issue where it broke some hover styling in subtle ways. It took quite a while to debug, so would be great to see it documented at least.

The current behaviour is quite unexpected. Below some additional findings which were not mentioned above:

```js
css`
  ${Parent}:hover > &,
  ${Parent}:hover > & {
    background: green;
  }
`
```

becomes

```css
.sc-bYEvPH:hover > .sc-kLgntA,
.sc-bYEvPH:hover > .jgWZjm {
  background: green;
}
```

Note the appearance of the *static class* in the first usage and *dynamic class* in the second. I would argue this has to be considered a bug.

This also ties in to previous comments where `&` refers to the  *dynamic class*:

> The `&` selector immediately followed by `:`, `.`, or `#` is not broken. It's "broken" only when `&` is used as a self reference without any other specifiers, i.e. `.parent-class & { ... }`

I would prefer explicit selectors for the static class as well as the dynamic class to make things explicit. The way it is resolved currently is hard to work with.
