### ISSUE TITLE
You are use React.memo for all styled components?

### ISSUE THREAD

**Issue by MaxmaxmaximusAWS** [styled-components/styled-components#3245]
You are use React.memo for all styled components?

Is there some option to enable React.memo by default for all styled components? In fact, they should always be memo. And if children are passed to them, then the children property changes, and the render stream goes to the children. In other words, there are no cases when React.memo will slow down performance, and there are cases when it will speed up =)

By the way, in general, by default, almost all functional components need to be wrapped in React.memo, if they do not use deep props comparison.  What do you think about my suggestion to add a `use memo always` option?

**Comment by probablyup** [comment]
@MaxmaxmaximusAWS there's actually noticeable performance hit for using memo if components are changed often since it has to do a shallow props comparison every time the SFC is called. We do have an internal concept of static styling though, we could potentially memoize components we know to be static.

**Comment by MaxmaxmaximusAWS** [comment]
@probablyup  Yes, but React.memo is pretty smart and can lower the fiber priority of the current branch, or block the child rerender altogether. I mean, in the place where you decide to use the cache, you better give hints for the React rendering system using React.memo =)
