### ISSUE TITLE
Transient props ignored when passed through nested SC

### ISSUE THREAD

**Issue by sandrina-p** [styled-components/styled-components#3257]
## Environment
- styled-components@5.1.1
- react@16.13.1

## Reproduction
I believe I found a bug 🐛. A reproduction can be found [in codesandbox](https://codesandbox.io/s/gracious-cloud-fv5kr?file=/src/index.js). I'm trying to pass down a transient prop `$align` to a nested Styled Component.

```jsx
const BoxStyled = styled.div`
  text-align: ${({ $align }) => $align};
`;

const Box = ({ children, ...props }) => (
  <BoxStyled {...props}>Hello {children}</BoxStyled>
);

Box.defaultProps = {
  $align: "left"
};

const BoxShadow = styled(Box)`
  box-shadow: 1px 1px 1px blue;
`;

```

## Expected Behavior
1. Transient props and `as` prop work fine when passing down directly to an SC. eg (Box -> BoxStyled)
```jsx
// the output is a <section> with the text centered
<Box $align="center" as="section">
      Box center as section
</Box>
```

2. The same should happen when passed from a second level parent (eg BoxShadow -> Box -> BoxStyled)
```jsx
// 2.1 the output is a <div> with the text centered and a shadow

<BoxShadow $align="center">
      BoxShadow center section
</BoxShadow>

// 2.2 the output is a <section> with the text centered and a shadow

<BoxShadow $align="center" as="section">
      BoxShadow center section
</BoxShadow>
```

## Actual Behavior

1.  ✅ It works as expected.
2. 🐛 Both failed:
2.1 `$align` gets ignored. The text is aligned to the left (instead of center).
2.1 `$align` prop gets ignored. The outcome is a `<section>` but without `BoxStyled` styles.

Thank you :)

**Comment by justAdevTV** [comment]
I believe you have the same issue as #3268.

Check out my solution there ^

I hope it helps!

**Comment by sandrina-p** [comment]
@justAdevTV, I tried using `forwardAs` and it didn't work? Can you try it yourself (forking the codesandbox I shared) and share the result?

**Comment by justAdevTV** [comment]
@sandrina-p based on the documentation for transient props, it looks like the `$` is only meant to prevent React from passing it into the react-node/DOM-element. Got that from here: https://styled-components.com/docs/api#transient-props

What's happening is that you're actually just overriding the styles when you pass the component into the styled method.
```JS
styled(ComponentHere)`{
// styles here
}`
```

So if you wanted to pass the props into `Box` instead of `BoxShadow` you'd have to create a HoC for it.
**I forked your code and added an example for you here (check out line 39):** 
https://codesandbox.io/s/sc-transient-props-bug-forked-9pjs1?file=/src/index.js

**Comment by justAdevTV** [comment]
@sandrina-p just wanted to follow up on what you thought about my previous comment ^

**Comment by sandrina-p** [comment]
@justAdevTV, your approach brings us closer to the solution but it's still missing the blue `box-shadow`

**Comment by sandrina-p** [comment]
@justAdevTV did you find a way? :)

**Comment by cjayross** [comment]
Is there a timeline on this? This bug is driving me nuts!

**Comment by cjayross** [comment]
I may be able to help with this if anyone can point me in the right direction. I need this for my project since I frequently use the pattern:
```js
function Item({ children, $data }) {
    ...
}

function ListBase({ children, $items }) {
    ...
}

export const List = Object.assign(ListBase, { Item })
```

From what I've seen, I believe the above situation results in this bug, wherein invoking `<List $items={...} />` fails to pass the `$items` prop to the `ListBase` component.

**Comment by kitten** [comment]
I'm not really sure about the previous replies, but a "transient prop" is only available on the top-level StyledComponent and _no other child component_. It may sometimes become available when a styled component wraps a styled component as then those two get folded together (see #3348), but otherwise the transient prop is intentionally isolated only to the StyledComponent and not passed on.

**Comment by heinpen** [comment]
`const First = styled.div`
    font-size: ${props => props.$sdf};
`

const Second = styled(First)`
  background-color: ${props => props.$sdf}; 
`

const Component = () => {
  return (
    <Second $sdf={'initial'} />
  );
};`

Why in First, $sdf is undefined only if using transient?
Testing the same code in sandbox (works fine, $sdf gets to First), and testing in my project ($sdf is undefined, if use transient).
Versions are the same 6.1.8, the only diff is in my project content is in iframe and inside shadow dom. So I render styles inside shadow dom and not in head

**Comment by Lokua** [comment]
Also please make sure your tests aren't making any new console errors in the DOM or in tests. You can make sure in Circle CI, for example your commit caused some new warnings to appear: https://app.circleci.com/pipelines/github/FoodEssentials/external-styleguide/1330/workflows/9c1138b9-951c-4b6d-8951-4242f04b780d/jobs/1740
