### ISSUE TITLE
Using a component with the "as" prop will ignore pseudo element.

### ISSUE THREAD

**Issue by gbreux** [styled-components/styled-components#3268]
Hi,

I'm struggling with an issue where using a component with the `as` prop will ignore the pseudo element style when surcharging that component.

## Reproduction

https://codesandbox.io/s/lively-feather-ev2ep?file=/src/App.js

## Steps to reproduce

If you surcharge the component style like this:

```
const C styled.div`
  &:after {
    color: red;
    content: " >";
  }
`
const C2 = styled(C)`
  color: red;
  &:after {
    color: yellowgreen;
  }
`;
```

and then call the component with the as prop: `<C2 as="p"/>` the style of the pseudo element (`:after`) from the initial component `C` will be ignore.

## Expected Behavior

Should work just like without the as prop.

**Comment by justAdevTV** [comment]
**Explanation Here:**
You need to use `forwardedAs` instead of `as` in this case because the component you're tossing into `styled()` also uses `as` as a prop.

**Answer Here:**
So to fix your issue, you need to change line 11 in your `App.js` to read as
`<C2 forwardedAs="p">Test</C2>`
instead of 
`<C2 as="p">Test</C2>`

**Live Example Revision:**
I've also fixed your code here so you can see it working!
https://codesandbox.io/s/lingering-cache-dwn59?file=/src/App.js

**Documentation from Styled-Components:**
Read about `forwardedAs` in the docs here:
https://styled-components.com/docs/api#forwardedas-prop

Hope this helps!

**Comment by gbreux** [comment]
Ho nice! I missed this option in the documentation. Thank you!

**Comment by justAdevTV** [comment]
> Ho nice! I missed this option in the documentation. Thank you!

No problem! Glad I could help :)
