### ISSUE TITLE
Breaking change in 5.2.0 around class specificity

### ISSUE THREAD

**Issue by jasondonnette** [styled-components/styled-components#3273]
## Reproduction

https://codesandbox.io/s/sc-specificity-breaking-change-75952?file=/src/App.tsx

## Steps to reproduce

Open the codesandbox and change the version from `5.1.1` to `5.2.0` and observe the color change.

SC used to output one single class when overriding a styled component like this, but in `5.2.0` they show up as 2 separate classes, which changes the specificity in this scenario.

**Comment by Sauloxd** [comment]
I have the same issue but in a different scenario, using the `&` operator:
# Reproduciton
https://codesandbox.io/s/sc-nested-not-updating-90job?file=/src/App.tsx

# Steps to reproduce
Test the code sandbox in styled-component version 5.1.1
When clicking the button in app, it should correctly change color
Test the code sandbox in styled-component version 5.2.0
When clicking the button in app, it changes color once and never again.

It's in the changelogs that the `self-reference` was reworked, due to this PR: #3236 
So maybe the feature in the codesandbox is deprecated or something?

**Comment by steve-taylor** [comment]
Not sure if it's the same issue, but I'm getting classes name collisions in version 5.2.0 onwards. This happens when I display multiple variants of the same styled component. By variant, I mean that each rendered instance passes different props and those props influence the generated CSS rules.

<img width="247" alt="image" src="https://user-images.githubusercontent.com/1135589/97978220-5ee8c800-1e21-11eb-9508-dca0bbebca14.png">

I had to go back to 5.1.1 to get this to work:

<img width="249" alt="image" src="https://user-images.githubusercontent.com/1135589/97979041-9d32b700-1e22-11eb-8095-821b6b7d6ce8.png">
<img width="242" alt="image" src="https://user-images.githubusercontent.com/1135589/97979076-ab80d300-1e22-11eb-8c53-f39157a22c03.png">

If it's helpful, here's a snippet from deep inside the styled component:

```ts
    ${Checkbox}:not(:checked) + & {
        ${darkOrLight({
            dark: (theme) => `background: ${theme.color.gray1};`,
            light: (theme) => `background: ${theme.color.gray3};`,
        })}
    }

    ${Checkbox}:checked + & {
        ${({scColor}) => cssThemeColors({background: scColor})}

        &::after {
            transform: translateX(${forSize(({widthPx, heightPx}) => widthPx - heightPx)}px);
        }
    }

    ${Checkbox}:not(:checked):not(:disabled):hover + & {
        ${darkOrLight({
            dark: theme => `background: ${tint(0.3, theme.color.gray1)};`,
            light: theme => `background: ${shade(0.1, theme.color.gray3)};`,
        })}
    }

    ${Checkbox}:checked:not(:disabled):hover + & {
        ${({scColor}) => darkOrLight({
            dark: theme => `background: ${tint(0.3, theme.color[scColor])};`,
            light: theme => `background: ${shade(0.1, theme.color[scColor])};`
        })}
    }
```

Helpers:

```ts
const defaultThemeTemplate = constant(''); // from lodash/constant

export function darkOrLight<PROPS extends {}>({
    dark = defaultThemeTemplate,
    light = defaultThemeTemplate,
}: {
    dark: ThemeTemplate<PROPS>;
    light: ThemeTemplate<PROPS>;
}) {
    return css<PROPS>`
        ${({theme}) => isTheme(theme) ? (
            theme.isDark ? dark(theme) : light(theme)
        ) : css<PROPS>`
            ${light(lightTheme)}

            @media (prefers-color-scheme: dark) {
                ${dark(darkTheme)}
            }
        `}
    `;
}

export function cssThemeColors(colors: Colors) {
    return css`
        ${({theme}) => isTheme(theme) && theme.color !== undefined ? (
            Object
                .entries(colors)
                .map(([key, color]: [string, ThemeColor]) => `${key}: ${theme.color[color]};`)
        ) : css`
            ${
                Object
                    .entries(colors)
                    .map(([key, color]: [string, ThemeColor]) => `${key}: ${lightTheme.color[color]};`)
            }

            @media (prefers-color-scheme: dark) {
                ${
                    Object
                        .entries(colors)
                        .map(([key, color]: [string, ThemeColor]) => `${key}: ${darkTheme.color[color]};`)
                }
            }
        `}
    `;
}

function isTheme(theme: unknown): boolean {
    return typeof (theme as Theme)?.id === 'string';
}
```

Some types for context:

```ts
type ThemeColors = {
    link: string;
    text: string;
    invertedText: string;
    blue: string;
    brown: string;

    // etc...
}

type ThemeColor = keyof ThemeColors;

type Colors = {
    [key: string]: ThemeColor;
}

type ThemeTemplate<PROPS extends {}> = {
    (theme: DefaultTheme): FlattenInterpolation<ThemedStyledProps<PROPS, DefaultTheme>> | string;
}

type Theme = {
    id: string;
    isDark: boolean;
    color: ThemeColors;
}
```

The gist of it is that it the CSS is somewhat parameterized and dynamic.

**Comment by johnnybenson** [comment]
Downgrading does seem to resolve the immediate issue, but I don't know what I am giving up by doing this. 

Has anyone come up with a workaround that doesn't involve downgrading?

**Comment by kitten** [comment]
This looks like intended behaviour to me. `styled(X)` where `X = styled.tag` folds in on itself, which means that the new component becomes a combination of all rules. This then causes the colour _after_ the media query to take precedence over the media query.
