### ISSUE TITLE
Unable to find readme on npmjs

### ISSUE THREAD

**Issue by jonasdev** [styled-components/styled-components#3277]
![image](https://user-images.githubusercontent.com/26645731/93594435-1d59a600-f9b6-11ea-8cbb-ec3b375df3a4.png)

It works if I jump back to version 5.1.0
https://www.npmjs.com/package/styled-components/v/5.1.0

**Comment by kitten** [comment]
Probably from when we've moved over to the monorepo. Not sure if this is technically crucial to us, since it isn't really that useful anymore apart from linking to styled-components.com which the package.json metadata still does, but we could fix this with a small copy script in Rollup or in `prepublishOnly`.

**Comment by Ravichandra-C** [comment]
@kitten I was going through the package.josn in the root folder and the I see the `cp README.md packages/styled-components/` is already written in the postbuild script. Should I append it in prepublishOnly script too?
