### ISSUE TITLE
How to remove space from bundle in production mode

### ISSUE THREAD

**Issue by nsisodiya** [styled-components/styled-components#3292]
I am using CRA (create react app) and styled-component. 
I noticed that the final bundle has unwanted spaces and newlines.
It is possible to remove these extra spaces and newlines in production mode?
Something like any pre-processor which read all js files and remove space+lines from code which are related to styled-components? 
`gql` and many other projects also use template strings and removing space and lines from their code will result in undesired behavior.

![image](https://user-images.githubusercontent.com/333455/94371190-45fa4200-0112-11eb-8188-11dbb3b94bd2.png)

**Comment by kitten** [comment]
You can use our Babel plugin's `minify` option. You have to be careful though. It's a little aggressive and may not always do what you expect, so test it thoroughly first.

I'd note though that unless you're using comments in the CSS templates you won't see a large size reduction, if that's what you're after. gzipped sizes will likely not change dramatically because CSS template strings compress quite well usually.
