### ISSUE TITLE
Merge all media queries together

### ISSUE THREAD

**Issue by bahmanbs** [styled-components/styled-components#3301]
Hey guys 🖐️

as you know, making responsive components is simple for any styled component, but after running app, there are many media query appeared in the style tag at head of html page

It is good to merge all media queries together (at least as an optional feature)

it can reduce bundle size, and reduce every component size, as media queries are downloaded before as global styles

**Comment by kitten** [comment]
That's simply not possible for a number of reasons:

- Specificity rules in `styled-components` requires us to maintain a strict priority order based on when a component was created. This means that order matters and maintaining that for separate specificity levels, e.g. media queries, would change this rule drastically
- We use the CSSOM method of inserting styles which doesn't allow us to update singular at-rule groups
- Updating styles retroactively is a lot more expensive. If we were able to just update a media query then there's a lot more rules and elements a browser would have to check for style changes and layouting becomes more expensive
- Streamed SSR is chunked so we'd still have multiple media at-rules on a streamed SSR result anyway
- This ignores that duplication is also pretty cheap; duplicate media at-rules with gzipping are trivial in cost and the removed duplication wouldn't save much size in the SSR HTML ouput
- Bundle-size is unaffected either way since the code in JS wouldn't change

Hope that makes sense ✌️
