### ISSUE TITLE
Stylis plugin not working as expected

### ISSUE THREAD

**Issue by hazem3500** [styled-components/styled-components#3319]
So I've created a plugin called [stylis-plugin-logical](https://github.com/hazem3500/stylis-plugin-logical) to convert logical CSS properties and values to values that have better browser support.

I've tried integrating it with styled-components but it doesn't behave correctly while when I use it with emotion v10 it works fine.
here is the [emotion v10 codesandbox](https://codesandbox.io/s/stylis-plugin-logical-emotion-v10-nx9mw?file=/src/App.js) and here is the [styled-components codesandbox](https://codesandbox.io/s/stylis-plugin-logical-styled-components-v5-xfkyw?file=/src/App.js) example.

Is there something that I can do in the plugin to be more compatible with styled-components?

**Comment by tremby** [comment]
I'm having the same problem. It seems to strip out a whole lot of styles.

Did you ever find a solution?

**Comment by kitten** [comment]
We do have a reproduction here, but no information on the actual issue, expected behaviour, or what specifically is an issue, so due to a lack of time I can't unfortunately go after a vague description here 😅 Sorry!

I'm happy to reopen this, if we have an idea of what's going on, or if we get more details added here 🙌
