### ISSUE TITLE
CSSOM Injection performance metrics

### ISSUE THREAD

**Issue by The-Code-Monkey** [styled-components/styled-components#3320]
Im looking for some performance metrics in terms of on a large scale what the difference is between having `StyleSheetManager` with `disableCSSOMInjection` turned on and turned off, the same for `disableVendorPrefixes` as from what i can tell it seems to slow down the initial page load.

If anyone else has any insight into speeding styled-components up even further that would be a great help.

**Comment by kitten** [comment]
We're actually considering to remove the non-CSSOM injection. The reason for its existence is that previously, a lot of browsers used for development would "lock" styles inserted using CSSOM methods. That meant that in development it became impossible to edit styles with Chrome. This restriction has been lifted a while ago now however.

Ultimately that means that non-CSSOM injection is obsolete, and it was only ever meant to be used in development. That being said, some people enabled it because third-party scripts had a tendency to destroy CSSOM-related scripts. This is an unsupported case for us however. Whenever a third-party script is reading or destroying our DOM nodes, then all bets are off, similar to when the same would happen to React's root DOM node.

The entire code that describes the non-CSSOM injection is located here and very compact: https://github.com/styled-components/styled-components/blob/28b4c28f1ebd1ea5a34717df2fe49634461285b1/packages/styled-components/src/sheet/Tag.js#L61-L99

You'll be able to see that per rule we inject one `TextNode`. As you may guess from just looking at this, this is extremely slow compared to CSSOM insertion. So slow in fact, that we wouldn't even bother measuring it. We have a refactoring PR that will improve this, but we may only merge it and then delete it in the next major upgrade immediately: https://github.com/styled-components/styled-components/pull/3295

**Comment by The-Code-Monkey** [comment]
So in theory its best to run `disableCSSOMInjection` then?

**Comment by kitten** [comment]
@The-Code-Monkey no, the opposite. In development by default CSSOM is disabled in production it’s enabled. So for performance, it’s best to leave this prop alone and to make sure that, however you build your app, that `process.env.NODE_ENV === “production”` for production builds (Webpack et al will do that automatically when they’re building for production)
