### ISSUE TITLE
Using styled-components with React-Native in yarn workspaces monorepo

### ISSUE THREAD

**Issue by Ryver966** [styled-components/styled-components#3346]
Hello!
I have issue with usage of styled-components with React-Native in monorepo. The issue comes from that I want to keep styled-components inside global node_modules directory and react-native lib existing in local package node_modules so when I try to use `styled-components/native` I get error which says `Cannot find react-native module from ../../node_modules/styled-components...` because there is no react-native lib in that global node_modules where styled-components lib is installed.

Is there any way to solve that issue?

**Comment by kitten** [comment]
This is a question that's not related to `styled-components`, so Spectrum or StackOverflow are your better bet.

That being said, if you have a monorepo then you have to ensure that it hoists dependencies correctly. I know that Metro bundler has several issues in terms of building a monorepo, but if you use Yarn workspaces, NPM workspaces (upcoming), or Lerna, you will have **hoisting** in place.

Hoisting means that dependencies are as high up in your monorepo as possible, optimally in the root `node_modules` folder. If you have a rule whereby you don't hoist `react-native` then you must also not hoist `styled-components`. This may lead to duplicate versions in the bundle if you have a shared component library, however this can then be fixed with an alias.
