### ISSUE TITLE
The first styled component has comparatively long render duration

### ISSUE THREAD

**Issue by liamqma** [styled-components/styled-components#3378]
Hi 👋

I've experienced a strange behaviour. The **first** styled component has comparatively long render duration. I have created a very simple React App to reproduce it.

```
import React from 'react';
import styled from 'styled-components';

const DummySpan = styled.span`
  border: 1px solid red;
`

const DummyDiv = styled.div`
  border: 1px solid green;
`

function App() {
  return (
    <div>
      <DummySpan>Test</DummySpan>
      <DummyDiv>Test</AnotherSpan>
    </div>
  );
}
```

Then I use React Profiler. As you can see the render duration of 1st component is a lot bigger than the 2nd despite they both are simple.
![image](https://user-images.githubusercontent.com/4413219/104673654-4b69af80-5736-11eb-9b5b-dc4e283b7e18.png)

I guess the 1st component might do some initialisation. I looked into the source code but couldn't find anything. 🤷‍♂️ 
Any help is greatly appreciated.

**Comment by kitten** [comment]
Answered here in terms of CSSOM speed: https://github.com/styled-components/styled-components/issues/3518#issuecomment-888356417

Sorry, I'll have to close this for now due to inactivity. In general, this is also an issue without any way forward to resolve this. In other words, no change in this repository has any chance of resolving this, which makes this issue open-ended potentially.

I suspect this is generally related to the CSSOM issue that's mentioned in the above issue, but I can't be too sure.
