### ISSUE TITLE
one error when testing with jest

### ISSUE THREAD

**Issue by guojun6** [styled-components/styled-components#3379]
Hi,
I am testing with `jest`, there is an error:
Trying to insert a new style tag, but the given Node is unmounted!

    - Are you using a custom target that isn't mounted?
    - Does your document not have a valid head element?
    - Have you accidentally removed a style tag manually?

I found there is only one styled-components module in my node_modules, so what can I do to resolve this error?

I found if the compoment created by styled-compoments is not used in render function, it will occur the error.

example:
const Wrapper = styled.img\`
  width: 100px;
\`;

function Example() {
  return \<div\>\</div\>;
}

The Wrapper compoment is not used, so the error will occur.

**Comment by kitten** [comment]
It seems that there's some blockers in your testing environment that don't provide an entire DOM-like environment to styled-components. There are some ways to work around this with `StyleSheetManager` but generally it needs to have `document.head` in JSDOM to work, which I believe should generally be the case. In general though, this seems to be more of a usage question, since it relates to setting something up _that uses_ styled-components, rather than individually _with_ styled-components. 

Please refer with usage questions to Stack Overflow, as you're more likely to get quicker and helpful answers there ❤️ Repository issues on GitHub are great for that, issues, things that need to be resolved in the library itself, or can't be resolved by anyone but the maintainers. While I (and many others on other repos) are happy to eventually answer usage questions, styled-components is a busy repo and mostly stable and slow moving towards new releases, so you're not likely to get fast responses here
