### ISSUE TITLE
Deno Support?

### ISSUE THREAD

**Issue by shadowtime2000** [styled-components/styled-components#3382]
I think Deno support would be pretty cool. I haven't found any other issues on this topic. Technically using something like skypack or esm.sh should work, but I think there should be Deno support for SSR. You could use [deno_swc](https://github.com/nestdotland/deno_swc) to write an SWC plugin which can do this.

**Comment by kitten** [comment]
I'm not really aware of a lot of Deno runtimes for React SSR, but if it does exist, I don't see what stops this library from being used with Deno? Sorry, I don't really know a lot about its runtime characteristics and the likes.

I'll close this issue since it's not really specific enough to address anything, or potentially unblock Deno support if it's indeed blocked by an issue, but happy to reopen with more details 🙌
