### ISSUE TITLE
textarea  readonly not work

### ISSUE THREAD

**Issue by feifaneric** [styled-components/styled-components#3383]
export const InputTextarea = styled.textarea`
  height: 200px;
  width: 380px;
  padding: 10px;
  font-size: 18px;
  resize: vertical;
`;
<InputTextarea  readonly="true"></InputTextarea >

**Comment by haneenmahd** [comment]
Are you sure you wrapped it around a template literals
```
`Your style`
```

**Comment by kitten** [comment]
This isn't a complete issue adhering to the issue template, so I assume that's why it may not have received more replies. In general, please be a good netizen and reply / close / update the issue as needed, especially if it receives a response as per above 😇 In general, regarding usage-questions:

Please refer with usage questions to Stack Overflow, as you're more likely to get quicker and helpful answers there ❤️ Repository issues on GitHub are great for that, issues, things that need to be resolved in the library itself, or can't be resolved by anyone but the maintainers. While I (and many others on other repos) are happy to eventually answer usage questions, styled-components is a busy repo and mostly stable and slow moving towards new releases, so you're not likely to get fast responses here
