### ISSUE TITLE
 [Feature Request] Callback functions in styled.attrs

### ISSUE THREAD

**Issue by AasmundEndresen** [styled-components/styled-components#3396]
So I've been looking far an wide to find a solution to a problem I'm trying to solve - and unable to come up with a decent answer I figured maybe this feature just simply doesn't exist yet.

My current problem is that I'm trying to create a responsive Menu/Navigation that doesn't rely on media queries.  While its been a good step forward I can't help but feel theres a large unecessary overhead with always doing 3-4 different media queries for various screen widths as this also means that in practice we're still very tightly coupled to other components in the application.

My solution so far has landed me with having to use a ref on my wrapper element to identify when a child element has an offsetTop that is larger then its siblings to identify when my menu starts wrapping elements with flex-wrap.  Its not ideal though because the React folks removed the ability to set a ref directly on a functional component, and adding a forwardRef to the child component just because one of the parents components where it might be used needs it isn't really following the philosophy of creating reusable components IMO.

It should also be mentioned I'm very fond of using a SFC pattern with styled components where I write:

```
import styled from 'styled-components';

const MyComponent = ({ className }) => {
  componentCode();
  return (
    <div className={className}>
      {children}
    </div>
  )
};

export default styled(MyComponent)`
  ${props => css`
      ${someStyles};
    `;
  }
`;
```

This is one of the reasons I'm so fond of styled-components, because it allows me to write code in what I find to be a very logical and legible way.

However, I wish there was more flexibility when working with styled-components this way - and what I find myself lacking now, is the ability to use variables defined in my component.  I imagine the easiest and most logical way to implement this would be by setting a prop as a callback in `styled(MyComponent).attrs({ callback: value => value })` for example, to then get access to the value through the callback function in the styles similar to how you would do in a regular React component when passing props back up to the parent.

In fact I was even expecting this to be possible, but when testing it out I find that my callback function is converted to a string when I try to use it in my styled-component.

Would this be a terribly difficult feature to implement?  Or is there some other, obvious feature I'm missing here that solves the same problem?  I imagine this would be useful in many other scenarios too.

**Comment by kitten** [comment]
The `.attrs()` function now expects a factory function itself, since before otherwise you'd have to pass `.attrs({ prop: () => () => 'value' })` so that's possibly related. I'm not quite sure what the proposal or question here is from the entire write-up, since there's no clear problem statement. Generally, if you use `attrs(() => ({ ... }))` you should be able to pass callback props to your underlying component. 

Although, you do have to be careful in that `attrs` will always be forwarded to the underlying element or target, meaning that they'll be attributes on your HTML element, if they're forwarded, See: https://github.com/styled-components/styled-components/blob/d96101a102b59a8f9ac4b6f278594674897282bb/packages/styled-components/src/models/StyledComponent.ts#L132
