### ISSUE TITLE
Static Site Generation without additional export css without

### ISSUE THREAD

**Issue by IanEdington** [styled-components/styled-components#3405]
We write emails using a similar process to static site generation.

`React -> mustache -> html`

The templates are rendered as mustache in a compilation step. The server consumes the mustache and sends the HTML.
We use styled-components in all our other web-repos and would like to use it with our emails.
I've been able to get it to work using `ServerStyleSheet`, `renderToStaticMarkup` and `sheet.instance.toString()` (snippet below).

However, when I call `sheet.instance.toString()` it adds additional css that is not needed by the template. I'm assuming this css is related to rehydration based on the file name (Rehydration.js).

I started writing my own function to replace `outputSheet`, but it looks like this is considered private and I don't have access to `getIdForGroup` in order to write the function.

## ASK
A method on `ServerStyleSheet` called `getRawCss`(?) that returns the non-hydratable css.

I'm willing to take a crack at implementing if this proposal seems reasonable.

Our email generation setup
```
  const sheet = new ServerStyleSheet();
  const elementWithCollectedStyles = sheet.collectStyles(children);
  const mjmlWithoutStyledComponentsCss = renderToStaticMarkup(elementWithCollectedStyles);
  const css = sheet.instance.toString();
  const mjml = mjmlWithoutStyledComponentsCss.replace("/* inject css here */", css);
  const prettifiedMjml = prettier.format(mjml, { parser: "html", plugins: [parserHtml] });
  const { html, errors } = mjml2html(prettifiedMjml);
```

Anticipated implementation of ServerStyleSheet.getRawCss
```
import { getIdForGroup } from "./GroupIDAllocator";

export const getRawCss = (sheet: Sheet) => {
  const tag = sheet.getTag();
  const { length } = tag;

  let css = "";
  for (let group = 0; group < length; group++) {
    const id = getIdForGroup(group);
    if (id === undefined) {
      continue;
    }

    const names = sheet.names.get(id);
    const rules = tag.getGroup(group);
    if (names === undefined || rules.length === 0) {
      continue;
    }

    // NOTE: It's easier to collect rules and have the marker
    // after the actual rules to simplify the rehydration
    css += rules;
  }

  return css;
};
```

**Comment by kitten** [comment]
So, the thing is that we're not really focused on static output as we're always anticipating that this output would be hydrated into the internal sheet at runtime. Hence we have markers like you've noticed.

That won't change and adding more APIs is in my opinion overall shortsighted. We're in a tricky situation. If you consider a library then there are possibly an infinite amount of use cases it constraints to its API; some coming down to patterns others to use cases.
Overall this means that adding APIs can always be an infinite process with unlimited repercussions on compromising the patterns we lay out. Hence, adding new APIs is only the last resort.

That being said, for your use case there's a solution that works; multiple in fact.
The easiest would be for you to strip out the markers. However, fair enough, that's more trouble than it may be worth, since those can change.

What's also a "private" API but completely accessible to you and much more stable is the sheet API itself.

- The `ServerStyleSheet` is backed by a single `instance` of a `StyleSheet`: https://github.com/styled-components/styled-components/blob/08390f25fa7e353107f0a30080075104cec6426f/packages/styled-components/src/models/ServerStyleSheet.js#L17
- This typically is output to a hydratable string but you can also get access to the underlying `GroupedTag`: https://github.com/styled-components/styled-components/blob/08390f25fa7e353107f0a30080075104cec6426f/packages/styled-components/src/sheet/Sheet.js#L75
- This allows you to output the individual groups of CSS rules: https://github.com/styled-components/styled-components/blob/08390f25fa7e353107f0a30080075104cec6426f/packages/styled-components/src/sheet/GroupedTag.js#L89 (its `length` property gives you the number of groups)

That can be used to bypass the rehydration markers entirely.

You can even go deeper and currently access the underlying `Tag`: https://github.com/styled-components/styled-components/blob/08390f25fa7e353107f0a30080075104cec6426f/packages/styled-components/src/sheet/GroupedTag.js#L20

This is an abstraction of `CSSStyleSheet`s itself, so once you're there you can get all rules individually: https://github.com/styled-components/styled-components/blob/08390f25fa7e353107f0a30080075104cec6426f/packages/styled-components/src/sheet/types.js#L8

**Comment by IanEdington** [comment]
Thanks for the quick response over the weekend 🥳

For those of you who come across this ticket in the future, this is what I came up with

```
function getStyledComponentsStaticCss(sheet: any): string {
  const tag = sheet.getTag();

  return [...Array(tag.length).keys()]
    .map((group) => tag.getGroup(group))
    .join("");
}
```

I still have the `/*!sc*/` "SPLITTER" but it's good enough for my use case and not worth messing with the string IMO.

Thanks for your help!

> So, the thing is that we're not really focused on static output

On a side note. I don't get this libraries desire not to support multiple use cases. styled-components is a very nice human interface (for devs) and it should be possible to make it pluggable for use in multiple environments. Could swapping out stylesheets for different use cases be a possible solution?
