### ISSUE TITLE
problem with file path containing parentheses in css url function after build

### ISSUE THREAD

**Issue by mhsattarian** [styled-components/styled-components#3406]
Hi, thanks for your amazing work.

I'm facing a rather odd issue, when using a file path containing parentheses "()" in the URL CSS function, styles after that line are not applying. 

### System:
 - OS: Linux 5.10 Manjaro Linux
 - CPU: (4) x64 Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz
 - Memory: 1.84 GB / 15.57 GB
 - Container: Yes
 - Shell: 5.8 - /usr/bin/zsh
### Binaries:
 - Node: 14.15.4 - /usr/local/bin/node
 - Yarn: 1.22.10 - /usr/bin/yarn
 - npm: 6.14.10 - /usr/local/bin/npm
### npmPackages:
 - styled-components: 5.2.1 => 5.2.1

## Reproduction

https://codesandbox.io/s/condescending-cori-kf7sz

## Steps to reproduce

just `build` the project.
note: I also tried the `babel-plugin-styled-components` just to see any changes, no change happened.

## Expected Behavior

texts on the screen should be in `red`.

## Actual Behavior

texts appear in black, showing there is some problem in the CSS applied after declaring the `font-face` particularly after the `src: ...` line;

**Comment by kitten** [comment]
This is likely an issue with how `stylis` perceives your input there. Generally, you can try to base64 encode with `url('...')` values for instance, but otherwise there isn't much we can do to resolve this. I believe the upgrade to `stylis@4` may fix this though once it's dropped into styled-components.

For now, I'll go ahead and close this, since there's not much we can do to fix this on our end. But rest assured, you're not doing anything wrong, it's likely stylis that in v3 can't parse this.
