### ISSUE TITLE
Typescript custom props component customisation docs is wrong

### ISSUE THREAD

**Issue by finnmerlett** [styled-components/styled-components#3407]
Just struggled to get a styled component with custom additional props working, in the form of
```
import { Box } from '@material-ui/core';
import styled from 'styled-components';

const Picture = styled(Box)<{ $wide: boolean }>`
  height: 60%;
`;
```
only after a while realising it was
`const Picture = styled(Box)<{ $wide: boolean }>`
not 
`const Picture = styled<{ $wide: boolean }>(Box)`

I think the docs are very confusing on this point, and actually completely wrong. I'm referring to all except the first code box at [typescript/using-custom-props](https://styled-components.com/docs/api#using-custom-props)
For example the second code box is 
```
import styled from 'styled-components';
import Header from './Header';

const Title =
  styled <
  { isActive: boolean } >
  Header`
  color: ${(props) => (props.isActive ? props.theme.primaryColor : props.theme.secondaryColor)}
`;
```
and this throws up loads of errors - it just isn't the right syntax at all.
Instead, it should probably be
```
import styled from 'styled-components';
import Header from './Header';

const Title = styled(Headers)<{ isActive: boolean }>`
  color: ${props =>
    props.isActive
      ? props.theme.primaryColor
      : props.theme.secondaryColor};
`;
```

The third and fourth example code boxes just seem to get more and more confused, with brackets in nonsensical places.

I really don't think I've missed anything stupid, but do let me know if something slipped through my double-checking!

**Comment by ghybs** [comment]
Hi,

I just realized the exact same thing!

The examples are so strange that it might be a bad manipulation that generated such weird code...

Let's dig a little more to figure it out...

**Comment by ghybs** [comment]
Yep, looks like it is quite old already:
- https://github.com/styled-components/styled-components-website/pull/437#issuecomment-474515370 (March 2019)
> The following code from this update does not make any sense (syntax error).
- https://github.com/styled-components/styled-components-website/issues/630 (April 2020)
> The last example in the Using custom props section in the typescript documentation is broken or at least misleading.

The most confusing (last) example seems to have been introduced in PR https://github.com/styled-components/styled-components-website/pull/437: https://github.com/styled-components/styled-components-website/pull/437/commits/a5330a6e27d12dcfb4c32448e8fdb5bf16305453#diff-20e71823214c521f3ae40832915fec17f115815d51be6e5537901c358e079c72R142-R144

While the previous ones just seem to be legacy syntax, probably no longer working since version 5 (maybe since version 4?).

Looks like there had been an attempt to fix it, but the proposed syntax seems a little bit convoluted, and it did not got merged: https://github.com/styled-components/styled-components-website/pull/483

So let's try to do this right! :persevere:

**Comment by kitten** [comment]
@ghybs Merged :+1:

@finnmerlett We don't maintain any TypeScript typings in the main repository and are not updating the ones that live in `definitely-typed`, so we can't offer any help on this here. It's possible that if you browse past issues you'll find similar questions, but overall this repository's issues are not the right place to report these issues or to discuss them.... just on a sidenote 😅

**Comment by ghybs** [comment]
> @ghybs Merged 👍

🎉 ❤️
