### ISSUE TITLE
Using "quotes" Style Breaks Styled Component

### ISSUE THREAD

**Issue by machineghost** [styled-components/styled-components#3413]
## Environment
`npx envinfo --system --binaries --npmPackages styled-components,babel-plugin-styled-components --markdown --clipboard`

> ## System:
>  - OS: Linux 5.4 Linux Mint 20.1 (Ulyssa)
>  - CPU: (8) x64 Intel(R) Core(TM) i7-4810MQ CPU @ 2.80GHz
>  - Memory: 1.22 GB / 23.40 GB
>  - Container: Yes
>  - Shell: 5.0.17 - /bin/bash
> ## Binaries:
>  - Node: 15.10.0 - /usr/bin/node
>  - Yarn: 1.22.5 - /usr/bin/yarn
>  - npm: 7.3.0 - /usr/local/bin/npm
> ## npmPackages:
>  - babel-plugin-styled-components: latest => 1.12.0 
>  - styled-components: latest => 5.2.1 

## Reproduction

Add a `quotes` CSS property to a styled component.  For instance (not sure if every style matters, but for completeness):

```
const Quote = styled.div`
  background: #f9f9f9;
  border-left: 10px solid #ccc;
  margin: 1.5em 10px;
  padding: 0.5em 10px;
  
  &:before {
    color: #ccc;
    content: open-quote;
    font-size: 4em;
    line-height: 0.1em;
    margin-right: 0.25em;
    vertical-align: -0.4em;
  }
  &:after {
    color: #ccc;
    content: close-quote;
    font-size: 4em;
    line-height: 0.1em;
    margin-right: 0.25em;
    vertical-align: -0.4em;
  }
  quotes: "\201c" "\201d";
`;
```

## Steps to reproduce

Try the above code.  In the Chrome debugger you will see the following for the element's code:

```
.cdwbly {
    null: ;
}
```

Now, remove that final style from the component, ie.: `  quotes: "\201c" "\201d";`

Magically everything now works.  Now try one more thing: using the Chrome debugger, add _that exact same line_ directly, as a style on the element.   It works perfectly fine, without issue.

## Expected Behavior

`quotes` is a valid CSS style.  It should not only work, but also it should not break any other styles, simply by it's existence.

## Actual Behavior

Adding quotes breaks everything, making the rendered styles "null".

**Comment by kitten** [comment]
I'm not at a laptop right now and since I haven't got this in a CodeSandbox I can't try this out immediately, but what you have to keep in mind is that `\201c` is an escape code. However, it's an escape code inside a tagged template literal which also supports string escape codes, hence it'll be evaluated to something different entirely which will end up in stylis.

Now, stylis v3 isn't a huge fan of string processing and known to get some of it wrong, but there's a good chance that fixing this by writing `\\201c` will fix this rule. In general, specific properties shouldn't cause this but it's likely the Unicode point at fault.

**Comment by machineghost** [comment]
`\\201c` fixed it, thanks so much!

If someone could stick a footnote about this in the documentation somewhere, that'd be truly awesome, but if not this issue will serve as a (lesser) form of documentation ... so I'll go ahead and close the ticket.  Thanks again!
