### ISSUE TITLE
Bug: style rules end up on the wrong selectors after a URL with a close-paren in it

### ISSUE THREAD

**Issue by tremby** [styled-components/styled-components#3425]
I found that styles go missing or apply to the wrong elements if they come after a URL string which has a close-paren character in it.

My actual use case was an inline SVG in a data URI, with a colour expressed in `rgb(...)` format. I found the next selectors getting appended to the previous selector, which led to styles not applying or applying to the wrong selectors.

I gradually boiled it down to a small case, which I've put in Code Sandbox.

## Environment

Reproducible on Code Sandbox with styled-components 5.2.1.

## Reproduction

https://codesandbox.io/s/styled-components-bug-styles-go-missing-after-a-close-paren-in-a-url-string-406j1

## Steps to reproduce

Run the above sandbox.

## Expected Behavior

Text is red.

## Actual Behavior

Text is not red.

**Comment by kitten** [comment]
This is likely an issue with how `stylis` perceives your input there. Generally, you can try to base64 encode with `url('...')` values for instance, but otherwise there isn't much we can do to resolve this. I believe the upgrade to `stylis@4` may fix this though once it's dropped into styled-components.

For now, I'll go ahead and close this, since there's not much we can do to fix this on our end. But rest assured, you're not doing anything wrong, it's likely stylis that in v3 can't parse this.

**Comment by tremby** [comment]
Thanks. Yeah, I've now confirmed that it was a Stylis 3.x problem and was fixed from 4.0.0 onwards. Is there a roadmap to upgrading the dep within styled-components?

**Comment by kitten** [comment]
@tremby It's already been upgraded on `main` afaik, which is posed to become v6, (ref: #3333). So, it's only a matter of time so far.

**Comment by tremby** [comment]
OK, thanks.
