### ISSUE TITLE
Inheritable styles

### ISSUE THREAD

**Issue by comerc** [styled-components/styled-components#343]
How about inheritable styles like `line-height: 0`?

In PostCSS we have modules `postcss-autoreset` and `postcss-initial` for isolation.

But `styled-components` does not consider this question.

**Comment by k15a** [comment]
If you set line height to 0 it will inherit automatically.

**Comment by geelen** [comment]
This might be worth discussing for https://github.com/styled-components/polished, but it's not going to be part of styled-components core, sorry. Styled components is about enabling CSS in JS projects and inheritance is an important (if misunderstood) part of CSS.

It's pretty straightforward to do yourself, though:

```js
const resetAll = css`
  line-height: initial;
  font-family: initial;
  /* ... etc ... */
`

const Component = styled.div`
  ${ resetAll }
  line-height: 1.0;
`
```

Because it's just CSS, that'll work exactly how you expect.

**Comment by bhough** [comment]
@comerc As @geelen suggested, this would be worth mentioning over at @styled-components/polished for possible inclusion in that library. Definitely something that is more akin to what that project is trying to accomplish.
