### ISSUE TITLE
Breaking change between v4 and v5 with the `as` prop

### ISSUE THREAD

**Issue by Synvox** [styled-components/styled-components#3434]
I updated from styled-components v4 to v5 and ran into a strange issue with the `as` prop. I have a styled `NavLink` that I thought I'd slap a `as="a" href="..."` on to have it link to another site. This works just fine in v4 but doesn't on v5.

The workaround isn't difficult, but I thought I'd create an issue anyway because it was unexpected.

## Environment
See CodeSandbox

## Reproduction

Here is an example app on styled-components v4:
https://codesandbox.io/s/sc4-nilej?file=/src/App.tsx

Here it is on v5:
https://codesandbox.io/s/sc5-bor2r?file=/src/App.tsx

## Steps to reproduce
Upgrade from v4 to v5

## Expected Behavior
It not to crash.

## Actual Behavior
It crashes

**Comment by kitten** [comment]
I'm happy to accept changes for the docs on styled-components' website repository. But I think there's not really any resolution to this. Breaking changes do happen between major versions due to small changes of the implementation. For this change, we don't really have a test that guarantees consistent behaviour, so it's possible that it has changed a little.

In general, I see that you're basically doing `styled(X).attrs({ as: Y })` and are then expecting the `as="..."` prop to still work. That said though, I see this as a major edge case, which I wouldn't expect to see. Hence, I don't think it has been covered and has probably changed a little.

There's not really any way forward to resolve this or address any part of this issue though. In other words, no change in this repository has any chance of resolving this, as it's related to an upgrade that has already been implemented and happened with an edge case that I'd say has no clearly defined behaviour, which makes this issue open-ended potentially. So, I'll close this for now, but happy to discuss resolutions here. I do think though that this is an "expected" change, in so far as its' cause is a specific syntax that, while possible, is not meant to be used in such a way.
