### ISSUE TITLE
Nested items stored in css variables 

### ISSUE THREAD

**Issue by jarkin13** [styled-components/styled-components#3466]
## Environment

```
## System:
 - OS: macOS 10.15.7
 - CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
 - Memory: 83.83 MB / 16.00 GB
 - Shell: 5.7.1 - /bin/zsh
## Binaries:
 - Node: 14.6.0 - ~/.nvm/versions/node/v14.6.0/bin/node
 - Yarn: 1.22.10 - ~/.nvm/versions/node/v14.6.0/bin/yarn
 - npm: 6.14.11 - ~/Workspace/vista/node_modules/.bin/npm
## npmPackages:
 - babel-plugin-styled-components: ^1.10.7 => 1.12.0
 - styled-components: ^5.1.1 => 5.2.1
```

## Reproduction

https://codesandbox.io/s/misty-shadow-lr4tv?file=/src/App.js

## Steps to reproduce

N/A

## Expected Behavior
To be able to store nested items in a `const` using the `css` imported from styled-components, that I am able to return in a parent div. View option 1 for a clearer understanding of the bug. 

## Actual Behavior
No error or styling is returned.

**Comment by kitten** [comment]
I'm not really sure what the issue here is from the description and the sandbox.

The sandbox outputs an error based on something that's not related to styled-components:

> <pre> cannot appear as a descendant of <p>.

That's basically a warning that semantic HTML cannot contain `<pre>` in `<p>` so `<p><pre>...` isn't allowed.

Now the issue with referring to `${Component}` is usage issue. When you write a `css` tagged template you get a return value that _isn't a string._ Instead, it's an intermediate representation that may contain other function interpolations. This means that you can't convert it to a string. So, when I see this:

```js
const Wrapper = styled.div`
  margin-bottom: 10px;

  ${({ isStyle1 }) => {
    return `${isStyle1 ? style1 : style2}`;
    /**
     * This works however:
     * if (isStyle1) {
     *  return style1
     * }
     * return style2
     */
  }}
`;
```

You're returning a _string_ here and not the `css` tagged template literal output. That's the difference here basically. Using `css` allows you to use interpolations, but it's not the same as template literal strings, which can't do the same. If you interpolate `css` into other strings then you'll see some weird outputs.

On the note of usage questions, please refer with usage questions to Stack Overflow, as you're more likely to get quicker and helpful answers there ❤️ Repository issues on GitHub are great for that, issues, things that need to be resolved in the library itself, or can't be resolved by anyone but the maintainers. While I (and many others on other repos) are happy to eventually answer usage questions, styled-components is a busy repo and mostly stable and slow moving towards new releases, so you're not likely to get fast responses here
