### ISSUE TITLE
[Feature Request] Support a `nonce` argument directly in 'getStyleElement' for SSR

### ISSUE THREAD

**Issue by ReesMorris** [styled-components/styled-components#3468]
I've been working on implementing strong CSP headers with Next.js and styled-components, but cannot find a way to provide a nonce attribute to server-rendered content.

Whilst the `__webpack_nonce__` solutions provided in [Issue #2363](https://github.com/styled-components/styled-components/issues/2363) work fine on the client side, the inline styling is rejected before the client hydrates, causing the styling to flash in (or never display if JavaScript is disabled).

As the `getNonce()` function used by `getStyleElement()` relies on a `window` variable being defined, the function will always return `null` when being called on the server. The only workaround I have managed to find for this is to 'mock' a _window_ object on the Next.js server before calling `getStyleElement()`, which works but I don't think is ideal:
`global.window = { __webpack_nonce__: nonce };`

I propose implementing an optional parameter to the `getStyleElement()` method which will allow for the nonce value to be passed in directly. For Next.js users, the _pages/\_document.tsx_ file (where this method is called for SSR) should already know the value of this variable from the `ctx` object, so passing it in directly makes the most sense to me.

I tested a modified version of the method on my own project, and the inline styling loaded perfectly on the server without any issues, whilst also working fine with JavaScript disabled entirely.

```tsx
getStyleElement = ({ nonce }: IStyleElementOptions = {}) => {
    // ...
    const nonceAttr = nonce || getNonce();
    if (nonceAttr) {
      (props: any).nonce = nonceAttr;
    }
   // ...
  };
  ```

Unless a solution already exists for this (please let me know if so!), I think this is the most logical way to approach handling the nonce tag with Next.js' SSR.

**Comment by kitten** [comment]
See comment here: https://github.com/styled-components/styled-components/issues/2363#issuecomment-895464410
We basically lack a coherent explanation and strategy to unify what we're doing about CSP nonces. Basically, I don't believe blindly adding a new API will do us any good so we may need a summary on the situation. Sorry!

**Comment by bwhitty** [comment]
@kitten I would have to say that the current "API" for adding a nonce to SSR-extracted style tags (https://github.com/styled-components/styled-components/pull/1022) is basically *Webpack magic*, and any explicit API would be better than that.

That being said, I don't think `styled-components` should have an internal nonce-creation API (proposed here as `getNonce()`), and #1022 had that same opinion; you must pass your own `nonce` in. The reason being is that an app must know what the `nonce` is since it must be sent in the `Content-Security-Policy` header, and so generating it internally does not make sense since the app cannot know what it is

I think `styled-components` needs an API which looks very much like what [`@loadable/components` ships in their `chunkExtractor.getScriptTags` / `chunkExtractor.getStyleTags` APIs for SSR](https://loadable-components.com/docs/api-loadable-server/).

I think what is needed is an API like Loadable Component's which would allow for setting HTML attributes when using the SSR stylesheet extraction API, like so: 
```js
// serverRender.js, or whatever controller you do SSR in
const nonce = '<nonce here>';

// pass any valid HTML attributes a K:V pairs
const stylesHtml = ServerStyleSheet.getStyleTags({ nonce });
```
This would add the attributes passed in to all output `<style>` tags, thus given us a non-*magical* API.

**Comment by multivoltage** [comment]
Any news?
