### ISSUE TITLE
How to add box-shadow property in normal object ( not literal ) ?

### ISSUE THREAD

**Issue by MenaiAla** [styled-components/styled-components#3472]
I've created a styled Textfield component : 

```
import styled from "styled-components";

export const Textfield = styled.input.attrs(({ placeholder }) => ({
  type: "text",
  placeholder: placeholder,
}))({
  backgroundColor: "#F5F5F5",
  border: "none",
  width: "100%",
  height: "3em",
  fontSize: "1em",
  paddingLeft: "1em",
  paddingRight: "1em",
  borderRadius: "0.5em",
  "&:focus": {
    backgroundColor: "#FFF",
    outlineWidth: 0,
    shadowColor: "#000",
    shadowOffset: { width: "4px", height: "6px" },
    shadowOpacity: 1,
  },
});

```
I wanted to set `box-shadow property when the user focuses on the text field but my code has no effect.

**Comment by kitten** [comment]
I'm really confused by this. You're using `styled.input` and the "web" import, but you're then writing React Native-like styling, like `shadowColor`. Are you writing code for the web? Because if so you'll need to use the web CSS properties for box-shadows, not the React Native ones.

Please refer with usage questions to Stack Overflow, as you're more likely to get quicker and helpful answers there ❤️ Repository issues on GitHub are great for that, issues, things that need to be resolved in the library itself, or can't be resolved by anyone but the maintainers. While I (and many others on other repos) are happy to eventually answer usage questions, styled-components is a busy repo and mostly stable and slow moving towards new releases, so you're not likely to get fast responses here
