### ISSUE TITLE
css prop doesn't work

### ISSUE THREAD

**Issue by 13916253446** [styled-components/styled-components#3473]
## System:
 - OS: macOS Mojave 10.14.6
 - CPU: (8) x64 Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
 - Memory: 19.78 MB / 16.00 GB
 - Shell: 5.3 - /bin/zsh
## Binaries:
 - Node: 15.2.1 - ~/.nvm/versions/node/v15.2.1/bin/node
 - Yarn: 1.9.4 - ~/.yarn/bin/yarn
 - npm: 7.0.8 - ~/.nvm/versions/node/v15.2.1/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
## npmPackages:
 - babel-plugin-styled-components: ^1.12.0 => 1.12.0 
 - styled-components: ^5.2.3 => 5.2.3 

## Steps to reproduce

```tsx
import React from "react";
import ReactDom from 'react-dom'
import "styled-components/macro"


export default function App(): JSX.Element {
  return (
    <div
      css={`
        color: blue;
      `}>
      1
    </div>
  )
}


ReactDom.render(
  <App />,
  document.querySelector('#app')
)
```

## Expected Behavior

Styles applied to elements

## Actual Behavior

![image](https://user-images.githubusercontent.com/20011519/116200904-7d45d580-a76b-11eb-8ba5-b5a65afd677f.png)

**Comment by wojtekmaj** [comment]
That doesn't look like the proper way to apply styles at all, where in the docs have you read about "magic" `css` attribute?

**Comment by 13916253446** [comment]
@wojtekmaj I am coding according to [css-prop](https://styled-components.com/docs/api#css-prop) this document

**Comment by samarmohan** [comment]
Make sure the babel plugin is used [correctly](https://styled-components.com/docs/tooling#babel-plugin) or follow [this](https://egghead.io/lessons/react-using-the-css-prop-to-define-styles-in-styled-components) random video I found that worked for me.

**Comment by karanmelo** [comment]
@13916253446 do you configured [Babel Macro](https://styled-components.com/docs/tooling#babel-macro) plugin?

**Comment by 13916253446** [comment]
> @13916253446 do you configured [Babel Macro](https://styled-components.com/docs/tooling#babel-macro) plugin?

Yes, I have configured the babel macro

**Comment by 13916253446** [comment]
> @13916253446 do you configured [Babel Macro](https://styled-components.com/docs/tooling#babel-macro) plugin?

@karanmelo Yes, I have configured the babel macro

**Comment by 13916253446** [comment]
> Make sure the babel plugin is used [correctly](https://styled-components.com/docs/tooling#babel-plugin) or follow [this](https://egghead.io/lessons/react-using-the-css-prop-to-define-styles-in-styled-components) random video I found that worked for me.

@samarmohan Exactly the same

**Comment by karanmelo** [comment]
@13916253446 did you resolve it?

**Comment by 13916253446** [comment]
> @13916253446 did you resolve it?

No, I don't know what the problem is yet

**Comment by kitten** [comment]
I think this has been pointed out above, but if the macro isn't working then there may be something wrong with your setup. It's also uncommon to see a bare import `import "styled-components/macro"`, so that may be a factor. But even then, it'd be an issue that'd have to be moved to `babel-plugin-styled-components`

Please refer with usage questions to Stack Overflow, as you're more likely to get quicker and helpful answers there ❤️ Repository issues on GitHub are great for that, issues, things that need to be resolved in the library itself, or can't be resolved by anyone but the maintainers. While I (and many others on other repos) are happy to eventually answer usage questions, styled-components is a busy repo and mostly stable and slow moving towards new releases, so you're not likely to get fast responses here

**Comment by prichodko** [comment]
The `css` prop stopped working for me after upgrading to new JSX pragma.

After some googling I came across the fact, that Emotion has addressed this issue by using their own pragma, but didn't find anything related to `styled-components`.

see https://emotion.sh/docs/css-prop

```json
{
  "presets": [
    [
      "@babel/preset-react",
      { "runtime": "automatic", "importSource": "@emotion/react" }
    ]
  ],
  "plugins": ["@emotion/babel-plugin"]
}
```
