### ISSUE TITLE
Components wrapped in `styled` are not correctly linted by the rule `react-hooks/rules-of-hooks` of `eslint-plugin-react-hooks`

### ISSUE THREAD

**Issue by vinassefranche** [styled-components/styled-components#3478]
Sorry if this has already been raised but I could not find this in the existing or closed issues.

# Environment
## System:
 - OS: Linux 5.4 Ubuntu 18.04.5 LTS (Bionic Beaver)
 - CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
 - Memory: 312.68 MB / 15.30 GB
 - Container: Yes
 - Shell: 5.4.2 - /bin/zsh
## Binaries:
 - Node: 12.18.0 - ~/.nvm/versions/node/v12.18.0/bin/node
 - Yarn: 1.22.10 - ~/.nvm/versions/node/v12.18.0/bin/yarn
 - npm: 6.14.4 - ~/.nvm/versions/node/v12.18.0/bin/npm
## npmPackages:
 - styled-components: ^5.2.3 => 5.2.3 

# Reproduction

## Steps to reproduce
You can checkout [this repository](https://github.com/vinassefranche/styled-components-eslint-issue) and run `npm i && ./node_modules/.bin/eslint .` or do the following steps:
- create a react app with typescript with `npx create-react-app my-app --template typescript`
- `cd my-app`
- install styled-components: `npm i styled-components && npm i --save-dev @types/styled-components`
- install eslint : `@types/styled-components @typescript-eslint/eslint-plugin @typescript-eslint/parser eslint eslint-plugin-reacteslint-plugin-react-hooks`
- create a file named `.eslintrc.json` at the root of the folder with this content:
  ```json
   {
    "parser": "@typescript-eslint/parser",
    "parserOptions": {
      "ecmaVersion": 2018,
      "sourceType": "module"
    },
    "plugins": [
      "@typescript-eslint",
      "react-hooks"
    ],
    "extends": [
      "plugin:react/recommended",
      "plugin:@typescript-eslint/recommended"
    ],
    "rules": {
      "react-hooks/rules-of-hooks": "error",
      "react/prop-types": "off"
    },
    "settings": {
      "react": {
        "pragma": "React",
        "version": "detect"
      }
    }
  }
  ```
- add a file named `Test.tsx` in `src/` with this content:
  ```typescript
  import React, { useState } from 'react';
  import styled from 'styled-components';

  export const WorkingLint: React.FunctionComponent<{prop?: string}> = ({prop}) => {
    if(!prop) {
      return null;
    }
    const [] = useState(false);
    return (
      <div> Lint on hook is working </div>
    );
  };

  export const NotWorkingLint = styled(({prop}:{prop?: string}) => {
    if(!prop) {
      return null;
    }
    const [] = useState(false);
    return (
      <div> Lint on hook is not working </div>
    );
  })``;
  ```
- run the lint check: `./node_modules/.bin/eslint .`

## Expected Behavior
Both `WorkingLint` and `NotWorkingLint` should create a lint error

## Actual Behavior
There's a lint error only on the `WorkingLint` (the one not wrapped in `styled`) component:
  ```sh
  /tmp/my-app/src/Test.tsx
    8:14  error  React Hook "useState" is called conditionally. React Hooks must be called in the exact same order in every component render. Did you accidentally call a React Hook after an early return?  react-hooks/rules-of-hooks

  ✖ 1 problem (1 error, 0 warnings)
  ```

Thanks in advance for your answer!

**Comment by vinassefranche** [comment]
I just found out that naming the component makes the lint work:
```typescript
export const NotWorkingLint = styled(function NotWorkingLint({prop}:{prop?: string}) {
  if(!prop) {
    return null;
  }
  const [] = useState(false);
  return (
    <div> Lint on hook is now working </div>
  );
})``;
```
It's a bit sad to have to do that though

**Comment by PupoSDC** [comment]
this doesn't fix the issue @vinassefranche, but on our project we got into the habit of splitting the styled call from the component definition. Something like this:

```ts
const BaseButton : FunctionComponent = () => {
  /** All of our code **/
}

export const Button = styled(BaseButton)``;
```

This provided us with a better linting and debugging experience overall.

**Comment by kitten** [comment]
I'd highly recommend not to write components inline of `styled()`. It's not a HOC, it's a constructor for a styled component. In most if not all cases, if you have a lot of logic inside of `styled()` that's not considered a best practice, as you're adding logic below what I'd consider leaf components for styling. Oftentimes, this isn't necessary as the reverse can be used, adding logic _around_ styled components rather than having any logic beneath / inside of them.

If you really have to wrap a component in `styled()` maybe just give it a name. The eslint plugin doesn't support anything but top-level components due to its component-detection logic.

On a sidenote, Please refer with usage questions to Stack Overflow, as you're more likely to get quicker and helpful answers there ❤️ Repository issues on GitHub are great for that, issues, things that need to be resolved in the library itself, or can't be resolved by anyone but the maintainers. While I (and many others on other repos) are happy to eventually answer usage questions, styled-components is a busy repo and mostly stable and slow moving towards new releases, so you're not likely to get fast responses here

**Comment by PupoSDC** [comment]
The reason why its convenient to do this wrapping is so that you can use this feature: https://styled-components.com/docs/advanced#referring-to-other-components. Altough it would be nice if all our components where `JS free`, in practice most of them do end up having some degree of logic. We still want to make them easily reusable in other parts of the code, ence the need to wrap it in the constructor.

Im curious though, why wouldn't this be considered a best practice? Are there any nefarious consequences to this?

Regarding the side note, this is indeed an issue with the library compatibility with eslint, not a usage question.
