### ISSUE TITLE
5.2.x and 5.3.x: difference in SSR and locally when you extend another component

### ISSUE THREAD

**Issue by macrozone** [styled-components/styled-components#3482]
## System:
 - OS: macOS 11.2.3
 - CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
 - Memory: 4.94 GB / 64.00 GB
 - Shell: 5.8 - /bin/zsh
## Binaries:
 - Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
 - Yarn: 1.22.10 - ~/git/panter/veloplus/veloplus-shop/veloplus-shop-fe/node_modules/.bin/yarn
 - npm: 6.14.12 - ~/.nvm/versions/node/v14.16.1/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
## npmPackages:
 - babel-plugin-styled-components: ^1.10.0 => 1.12.0
 - styled-components: ^5.3.0 => 5.3.0

## Reproduction

given some component:

```

const Foo = styled.div`
   border: 1px solid red;
`
```

now you extend this component:

```

const Bar = styled(Foo)`
    border: 1px solid green;
`

```

Now you mount `<Foo />` on a page, load the page. You see a red border as expected

If you mount now `<Bar />` without reload it will still have a red border!

But if you reload the page and SSR `<Bar />` it will have a green border as expected.

Reason is that the order of the classes change depending and as both have the same specificity, the order matters.

The Bug was introduced with 5.2.0, so downgrading to 5.1.1 fixes this inconsitency.

## Steps to reproduce

see above

## Expected Behavior

`styled(X)` should always have a higher specificity than just X

## Actual Behavior

`styled(X)` has the same specificity as X

**Comment by macrozone** [comment]
more background:

in 5.1.x `styled(X)` would just append its styling at the end of the styling of `X`, where in 5.2.x both styles exist and are selected by class

**Comment by macrozone** [comment]
i think this is clearly a bug, but i am a bit surprised why no one else noticed that (or reported it)

**Comment by shalanah** [comment]
I've experienced it too. Needed to revert to `5.1.1`

**Comment by kitten** [comment]
Can you confirm some things here for me please? There are rigorous expectations around specificity in styled-components that are guaranteed by enforcing the order of styling. However, what I see here doesn't really agree with that, but without a reproduction there's no way I can quickly jump in and check it. The description here is a bit fuzzy for me, but if I understand it correctly you've said that you have an app that does server-side rendering and the following:

- You have a component
- You extend it
- You reload (?)

The reloading here makes me believe that you may be referring to a modified file, so you're not saying your file has these two components, but you're making a change and either due to server-side hot loading or by another process you're getting updated code running, right? There's a big difference here in what we expect, because we _cannot_ control how any given server reloads / reinstantiates files and instances as it hot-reloads, both on the client-side or server-side, so that part really matters, since it determines whether there's something that's actually wrong, or whether it's the SSR implementation thats at fault.

**Comment by macrozone** [comment]
@kitten thank you for your time.

I'll see if i can create a reproduction, it should not be a big effort.

I don't refer to modified files or hot-reloading, but to inconsistency in the styles that the server generates and the styles on the client in the case where you extend a component.

in the example above `Bar`'s styling has no longer a guaranteed higher specificity than  `Foo`, while in 5.2 and below, the order was guaranteed. In 5.3 the specificity now depends on the order in which the stylesheets are genereated and this might indeed vary, as you point out.

**Comment by kitten** [comment]
I actually thought that this commit was reverted, but it wasn't 🙃 https://github.com/styled-components/styled-components/commit/0c029557d8f97bafeb9e67714fe73195c4e9b647#diff-b21a8ac32aafa37184de036ddfff8aabfa56e9192802a65514d560a0e795def4

If we do get a reproduction together though that'd be super valuable as we can drop in a test package that this reverted and see if it did indeed break this case. 🍀

**Comment by macrozone** [comment]
i am working on a reproduction, but i could not reproduce it yet (current state https://github.com/macrozone/styled-components-repro)

whats obvious is that the styling will depend on the ordering:

<img width="693" alt="Bildschirmfoto 2021-08-09 um 17 44 46" src="https://user-images.githubusercontent.com/1972353/128734599-dd4a42ff-4948-462b-bea5-74e84ca97d20.png">

So what i try now is to affect the order, and my suspicion is that it might be related to dynamic loading of components.

**Comment by macrozone** [comment]
@kitten i could reproduce it!

steps to reproduce:

- checkout https://github.com/macrozone/styled-components-repro
- yarn install
- create a production build with **yarn build**
- yarn start
- goto localhost:3000, you will see a red square
- click on the link "Go to other page", you will still see a green square
- now reload the page (localhost:3000/otherpage), the square is now red instead of green

and indeed the order swapped:

<img width="706" alt="Bildschirmfoto 2021-08-09 um 18 05 54" src="https://user-images.githubusercontent.com/1972353/128737783-f0b44929-4b3b-4a3b-ae26-5d77a01aeeed.png">

The issue happens only on production builds in this reproduction.

**Comment by macrozone** [comment]
Update: I tried now to downgrade to 5.1.1, but i still have the issue. But i have to check whether there is some caching here. (already deleted .next and node_modules folder).

In my project where i experienced the issue, i could not reproduce it with 5.1.1. though

**Comment by kitten** [comment]
@macrozone: fwiw, the last unaffected version should be `v5.2.0`, but if it's a different issue I'll need to take a closer look, which I'll hopefully be able to do to resolve this by tomorrow

**Comment by macrozone** [comment]
> @macrozone: fwiw, the last unaffected version should be `v5.2.0`, but if it's a different issue I'll need to take a closer look, which I'll hopefully be able to do to resolve this by tomorrow

seems to be different, also the reproduction does not seem to be the exact issue i had in my project (that did NOT occure with 5.1.1) 😅

**Comment by alana314** [comment]
+1 we are seeing this, wreaking havoc on our prod site but not affecting locally when we run yarn develop (using gatsby).

**Comment by lauriejones** [comment]
We're in a similar boat to Alana, unfortunately. 😢 

We have been experiencing this issue across a number of our gatsby and nextjs sites. It is really alarming from such a normally stable library! All we've been able to do to address it is add `&&&` to each troublesome component as it comes up. The fact that it only happens on a production build and not in dev means we're often catching this issue in production. This is not a sustainable approach.

We are seeing this issue on v4.4.1 as well as multiple v5 versions. We initially saw strange behaviour with v5 versions of styled-components last year (to do with className collisions) and so decided to pin ourselves to v4. This seemed to work but recently we're seeing this different incorrect styling behaviour with increasing frequency on both v4 and v5 of styled components. 

Our issue is like macrozone's reproduction, but inverted: A browser reload has the correct styling order and behaviour whereas a gatsby/next link to a page will load style rules in the wrong order for an "extended" component. _(not actually using the old `.extend` helper, using the `styled(Comp)`)_. Sounds related to hydration?

We have also experience it when there has been any kinda of re-render whilst remaining on the same page (from our tab component or a useEffect hook fetching data on page load).

I have just spent an hour trying to create a small reproduction with no luck so far, but I will keep trying.

**Comment by alana314** [comment]
For now what worked for us was pinning package.json to exactly "5.1.1" (not "^5.0.0")

**Comment by macrozone** [comment]
5.1.1 also works for us.

In our case i strongly assume its because dynamic loading of componets which results in differences in the order of styles

**Comment by kitten** [comment]
I took another look. I indeed typo'ed this and 5.1.1 is the last _working_ version, while 5.2.0 is the first that introduces the change I suspect of introducing this bug, as per the changelog:

> Enable new style rules can be inserted in the middle of existing sheet when rendering on client after rehydrate. GroupIDAllocator is now changed to find nextFreeGroup by checking reverseRegister, instead of setting it to the end of existing groups. (see #3233)

I'll work on testing a revert against the reproduction.

**Comment by kitten** [comment]
I've opened a PR that fixes the group ID minimums. With @marvinhagemeister's help another bug is also fixed there which likely impacted this. I've taken a look at the reproduction here however, and it doesn't seem suitable to verify this fix.

@macrozone: To explain why _this_ reproduction in particular isn't working; I've taken a look and noticed that it uses a dynamic import. When the page loads and the dynamic import is resolved, the dynamically created component will always be created _second_, so without SSR this behaviour is expected. However, it seems that even on the server-side Next.js seems to defer the dynamic import, which makes sense, since it's likely loaded/required on demand. Compare this with your index page, which requires the same component without a dynamic import, which means that when we switch pages the first component is already instantiated; In other words, we can't guarantee a fixed ordering here.

**Comment by macrozone** [comment]
> I've opened a PR that fixes the group ID minimums. With @marvinhagemeister's help another bug is also fixed there which likely impacted this. I've taken a look at the reproduction here however, and it doesn't seem suitable to verify this fix.
> 
> @macrozone: To explain why _this_ reproduction in particular isn't working; I've taken a look and noticed that it uses a dynamic import. When the page loads and the dynamic import is resolved, the dynamically created component will always be created _second_, so without SSR this behaviour is expected. However, it seems that even on the server-side Next.js seems to defer the dynamic import, which makes sense, since it's likely loaded/required on demand. Compare this with your index page, which requires the same component without a dynamic import, which means that when we switch pages the first component is already instantiated; In other words, we can't guarantee a fixed ordering here.

i am aware of the lazy loading, because i use code splitting as well in the affected app. That's why i tried to do a reproduction with dynamic loading, because i could not recreteate the bug without that. But as mentioned, the reproduction does not seem to get resolved by downgrading to 5.1.x while in my production app 5.1.x fully resolves the issue.

**Comment by macrozone** [comment]
@kitten if you have a release, i can test if it fixes the problem in my app! thank you very much for your time and for styled-components in general! <3

**Comment by kitten** [comment]
@macrozone It's released as `v5.3.1`, since I got confirmation that it addresses the issue. There was a prerelease on the PR that was used to verify this: https://github.com/styled-components/styled-components/pull/3563#issuecomment-903098827

**Comment by jlowcs** [comment]
We pretty much confirmed that we have a similar issue, but it was introduced in 5.3.1. Our impacted component is lazy loaded.

on 5.3.0 we had:
![image](https://user-images.githubusercontent.com/3777724/133312793-65635148-6a15-49ec-9580-c68e5ca82bae.png)

on 5.3.1 we now have:
![image](https://user-images.githubusercontent.com/3777724/133312911-3f98ee13-c441-4410-97b3-ced35891c5b2.png)

The first one is what we want.

**Comment by jlowcs** [comment]
I'm starting to wonder whether styled-system might be causing the ordering issue.

**Comment by jlowcs** [comment]
So I found the cause of our issue and want to share it here as someone else might encounter the same issue.

We are using `babel-plugin-styled-components` for processing the classes to make sure they match between CSR and SSR. But what we didn't think of is that a lot of our components are imported from a library of ours which is compiled to ES5. And we weren't processing that library with babel, be it during the client build process (ignoring all `node_modules` for `babel-loader`) or the server build process (ignoring all `node_modules` using `webpack-node-externals`).

So adding our components library to the babel-processed code fixed the issue for us.

**Comment by joanned** [comment]
updating from v5.3.0 to v5.3.1 fixed it for us

**Comment by kondei** [comment]
In my case, downgrading v5.3.1 or upper versions to v5.3.0 fixed it for us.

**Comment by wnadurski** [comment]
In my case we are not able to override styles of components from a components library even using the lastest version of `styled-components`. 
We are using nextjs with `next-transpile-modules` package to transpile the components library and the `babel-plugin-styled-components`

**Comment by UstymUkhman** [comment]
Hi @kitten ! I'm not sure why this issue is closed since #3321 and #3094 are both marked as duplicates of this and the first one seams to be related to the SSR. I'm still facing this with `v5.3.3`, so after reading the comments above I've downgraded first to `v5.3.0`, then to `v5.2.0` and only with `v5.1.1` I was able to see the expected result just because it doesn't create a new class for overwritten rules but adds them at the bottom of the base class. Thanks @macrozone for the hint! 

I think this should be reopened because in my case I don't rely on SSR or babel. It's just a simple SPA with vite (so rollup under the hood) to build everything. Ah, also reproducible only in production builds.

**Comment by dcorb** [comment]
This bug showed up when upgrading styled-components to 5.3.1 (regression)
Upgrading to the latest **babel-plugin-styled-components** fixed it for me

**Comment by serhanguney** [comment]
I have the same issue with one of the private libraries I'm using, which also uses styled-components.
I'm using Next.js and the issue appears on server-side rendering.

1. I import the button component from that library (created by styled-components)
2. I wrap it with `styled` and apply **my-specific-styles** to it.
3. On prod mode **my-specific-styles** get overridden by the styles of the private library.

👉 When I check the page source of the HTML the `className` of **my-specific-styles** is there, but the `className` that comes from the private library is not in the page source.
👉 I'd also like to say that its worth checking this out in the dynamic routes of Next JS. I don't know how but my buttons are not always 'broken'. While they mostly are working fine in static pages (except for header/navigation component**), they seem to definitely break in dynamic routes of next js (`[slug]`)

**The buttons in navigation component 👉  onClick of any **nav-element** I have a **dropdown** that gets rendered. So the **dropdown** is not part of the dom until we click on a **nav-element**. While the buttons I use in the **nav-element** do NOT break, the buttons I use in the **dropdown** itself do break. The interesting part is that when I removed this conditional rendering, and have the dropdown appear below the navigation all the time, the buttons work fine. 🤔 

MY SOLUTION: Downgrading to 5.1.1 didn't do the trick for me, but 5.3.0 works fine.

**Comment by vamcs** [comment]
We've been also experiencing CSS class injection order problems for a while, mostly randomly, due to our component library both using styled-components and being installed as a package in our main Next.js application (that does server side rendering).

What @jlowcs mentioned [above](https://github.com/styled-components/styled-components/issues/3482#issuecomment-920348139) did the trick for us! We use SWC to both build our component library and our Next.js app − which should have now [ported most of the functionality in `babel-plugin-styled-components`](https://github.com/vercel/next.js/issues/30802). But we missed adding this plugin to our component library build, [`@swc/styled-components-plugin`](https://styled-components.com/docs/tooling#swc-plugin), using the `ssr: true` option. We haven't yet tested this thoroughly yet but that fixed one bug we've seen, and it's obviously what was missing.
