### ISSUE TITLE
Error in function eval in

### ISSUE THREAD

**Issue by xbaha** [styled-components/styled-components#3489]
I am trying to style a react-bootstrap tags (Row,Col)
it worked ok, but then I tried to style Nacbar tag, and the site won't load with the above error and pointing at styled where only bootstrap tags are found.

`const RowStyled = styled.Row`
`                               ^              `

After deleting all styles that have bootstrap tags, the site works again.

**Comment by kitten** [comment]
Sorry, there's not enough information here for us to help, but this sounds like an issue with your setup. If you'd like you can post more information here and we can see if we can help, but since this is a usage issue and not an issue specifically with styled-components I'll have to close this for now.

To be more precise, if you post a stack trace, some code, and some information about your setup this becomes a lot more approachable. You can also try asking for help on StackOverflow as soon as you add more information about your setup.
