### ISSUE TITLE
CSS prop on dynamic (runtime) component causes runtime error

### ISSUE THREAD

**Issue by hamlim** [styled-components/styled-components#3491]
I tried to search through other issues but couldn't necessarily find one matching this description - let me know if this is a duplicate!

### System:
 - OS: macOS 10.15.7
 - CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
 - Memory: 344.26 MB / 16.00 GB
 - Shell: 5.7.1 - /bin/zsh
### Binaries:
 - Node: 14.15.1 - /var/folders/tg/7dkh_xvx4z911wsj0rtmt9zw003gy1/T/fnm-shell-243697/bin/node
 - Yarn: 1.22.5 - /usr/local/bin/yarn
 - npm: 6.14.8 - /var/folders/tg/7dkh_xvx4z911wsj0rtmt9zw003gy1/T/fnm-shell-243697/bin/npm
### npmPackages:
 - babel-plugin-styled-components: ^1.12.0 => 1.12.0

## Reproduction

Repo: https://github.com/hamlim/styled-components-css-prop-quirk

## Steps to reproduce

* Author a component that is dynamic (e.g. determined at runtime) that uses the `css` prop
* Run babel with the `babel-plugin-styled-components` plugin
* See runtime error with the code due to css prop transform

## Expected Behavior

* Warn / error during build if the component doesn't exist in the module scope
* Call this limitation out within the documentation for the babel plugin

## Actual Behavior

* Runtime error attempting to wrap an undefined value

**Comment by hamlim** [comment]
Edit: Had to delete the repo temporarily - will re-create it and update the issue when done!

**Comment by raphaelbadia** [comment]
Hello, here is another way to reproduce it : https://codesandbox.io/s/dynamic-styled-component-breaks-88vdz

you just have to uncomment the css prop on line 18 or 19 to see the issue !

**Comment by kitten** [comment]
So far, this is expected behaviour. The `css` prop isn't a special feature or a feature that's supported without the Babel plugin. Because of forwards and backwards compatibility there's no behaviour in styled-components that can basically support this. Because the `css` prop can go onto any element, we cannot do anything or add anything to this library that will prevent errors from happening.

Also, re. this kind of code:

```js
const DynamicComponent = useDynamicComponent();
```

We could issue warnings in `babel-plugin-styled-components` (feel free to open an issue on that repo), but ultimately I think it's sufficiently called out by the documentation when it says that it's doing the following:

> Under the hood, the Babel plugin turns any element with a css prop into a styled component.

(with the following snippet)
