### ISSUE TITLE
Input looses Focus on Hook update

### ISSUE THREAD

**Issue by BND10706** [styled-components/styled-components#3492]
When I am doing either Input with Native Base or TextInput with just react-native every time onChangeText updates the state the keyboard loses focus.

```
<View>
        <Text>Enter your Employee ID</Text>
        <Item rounded style={styles.textBox}>
          <Icon type='Ionicons' name='person' style={{ fontSize: 30 }} />
          <Input
            onChangeText={(text) => setId(text)}
            value={id}
          />
        </Item>
      </View>
```

This renders fine.... so its clearly a stateupdate issue... 

`<Input onChangeText={(text) => {}} />`

**Comment by kitten** [comment]
This is most likely caused by your component completely remounting and hence the element losing its native state, but it's hard to tell. Also, this isn't related to `StyledComponent` and you're not following the issue template, so I'll have to ask you to please take this question to a forum like StackOverflow :v:
