### ISSUE TITLE
stylelint in vscode: auto-fix destroys the file. Any ideas?

### ISSUE THREAD

**Issue by GollyJer** [styled-components/styled-components#3493]
I followed the linting instructions on the [Tooling section of the styled-components docs page](https://styled-components.com/docs/tooling#stylelint).

It finds the errors correctly but when I save the file it auto-fixes from this...
<img src=https://user-images.githubusercontent.com/689204/118061046-069eff80-b349-11eb-949a-5e70b6b9a023.png width=500>

to this

<img src=https://user-images.githubusercontent.com/689204/118061065-10286780-b349-11eb-9602-84c9cd85707f.png width=500>

I have no idea what I'm doing wrong. Any help is greatly appreciated.

**Comment by samarmohan** [comment]
I believe this is a `stylelint` issue, not a problem with `styled-components`.

**Comment by GollyJer** [comment]
Thanks @samarmohan. I posted in both places hoping someone might have dealt with the issue before.

**Comment by Inokcode** [comment]
Anyone know 
"Beware that due to limitations on what is possible for Stylelint custom processors we cannot support the --fix option"
https://styled-components.com/docs/tooling#stylelint

solution for auto fix styled components ?
seems now that lib is archived 
so any alternative recommended ways to do lint styled-components

**Comment by kitten** [comment]
Sorry, I'll have to close this for now due to inactivity. In general, this is also an issue that's unrelated to the codebase in this repository itself, so there's not really any way forward to resolve this. In other words, no change in this repository has any chance of resolving this, as it's unrelated, which makes this issue open-ended potentially.

Please refer with usage questions to Stack Overflow, as you're more likely to get quicker and helpful answers there ❤️ Repository issues on GitHub are great for that, issues, things that need to be resolved in the library itself, or can't be resolved by anyone but the maintainers. While I (and many others on other repos) are happy to eventually answer usage questions, styled-components is a busy repo and mostly stable and slow moving towards new releases, so you're not likely to get fast responses here
