### ISSUE TITLE
Component Composition Best Practice question

### ISSUE THREAD

**Issue by yoni-salt** [styled-components/styled-components#3498]
Hey,
I struggle to decide what is the best practice approach and couldn't find the right answer for this common use case.

Stack: React, Styled-components, Typescript
I've built a component name <Button> which has 5 different presets for coloring(hover, active etc.)

I have added a preset prop: 
`<Button preset="primary">`
the question is should I just use this component with this prop or should I create a component for each preset:
`const PrimaryButton = styled(Button).attr(() => {preset: "primary"})`
and export each component?

Thanks!

**Comment by jnthnk** [comment]
In my case I found more productive and logical to build just the Button component and provides the arguments inside to make changes in appearance.

Other tip I found very useful is to group the most used styled components inside a single file and export an object with all of them.

Like Styled.tsx exports { SWrapper, STitle, SText, SButton... }

**Comment by kitten** [comment]
I think there have been several blog posts on the topic, but none would do more than change your perspective and opinion on it, since it's in a way personal. If they're the same component, then I'd say it makes sense to just switch it as needed and not create wrapping components / separate components. After all, the intention doesn't change. However, I'm sure you could also make arguments for the other approach.

I'd say though that this doesn't really belong in our issues. It's a question that's very open ended, so eventually I have to just close it unfortunately 😅
