### ISSUE TITLE
Does Smart TV support styled-components?

### ISSUE THREAD

**Issue by sulhadin** [styled-components/styled-components#3499]
Hi,

I am planning to begin new React project for Smart TV. I wonder if styled components are supported by Smart TVs.

If yes, would you provide my with some examples or docs? Because I could not find any.

**Comment by kitten** [comment]
Yes and no.

This will purely depend on your specific TV's OS and browser support. It shouldn't be an issue currently with styled-components' fallback to `TextNode` insertion rather than CSSOM insertion, even in older browsers, it's also just CSS after all. But it all comes down to your own research and requirements, so this question isn't suitable for issues.
