### ISSUE TITLE
boolean values not supported?

### ISSUE THREAD

**Issue by sabres207** [styled-components/styled-components#3509]
Hey all, I read in styled components documents that it's possible to use the short-circuit evaluation (prop.width && 'width: prop.width;') to conditionally use a prop to style the component.
They say you can do that because styled components now knows to ignore falsey values (just like react ignore null/false values).

But, when I try to use this short circuit pattern instead of the ternary operator, I get the following error:
``Warning: Received `true` for a non-boolean attribute `first`.``

I see some questions about it with answer to use 0 and 1 instead of false and true, but that goes against the documentation.
Can anyone explain what's the problem here?
Thanks!

**Comment by myteax** [comment]
How do I reproduce this issue?

**Comment by rambabusaravanan** [comment]
I use the prop name `fill`, it throws the below warning. But if I use other names like `bg`, it's all okay and doesn't throw anything

> Warning: Received `true` for a non-boolean attribute `fill`.
> If you want to write it to the DOM, pass a string instead: fill="true" or fill={value.toString()}.

```
interface WrapperProps {
  fill?: boolean;
}

const Wrapper = styled.header<WrapperProps>`
  border-bottom: 1px solid #eaeaea;
  ${(p) =>
    p.fill
      ? `background: ${p.theme.primary}; color: white;`
      : "background: white;"}
`;

function Header(props: Props) {
  return (
    <Wrapper fill={props.fill}>
  )
}
```

**Comment by kitten** [comment]
This is a warning from React. Some prop names are valid DOM attributes and will be set. If you use names like `fill` or `width` then they'll also land on the eventual DOM element.

In this case, React is warning you about those because these attributes are not boolean-based but only accept literal strings.

If you didn't intend for these props to be landing on the DOM element, I'd suggest choosing a different name for them or prefixing them. otherwise; if you do want them on the DOM element then you'll have to listen to the warning, and in this case explicitly use `"true"` instead of the boolean value
