### ISSUE TITLE
Customise className minification

### ISSUE THREAD

**Issue by salyadav** [styled-components/styled-components#3515]
I am using the following configuration for minifying the classnames for prod build:
```
const isDev = process.env.NODE_ENV !== 'production';
return [
    'babel-plugin-styled-components',
    {
      ssr: true,
      displayName: isDev,
      fileName: isDev,
    }
  ]
```

This gives a decent minification with hashes. 
But I want to add my own custom minifying logic which can minify the classnames with single characters like "a_b" etc...

Is there a way to add my own minifying function?

**Comment by kitten** [comment]
That's currently not supported and generally as long as we use hashes, there's no way to achieve this. If we ever use a lookup table and group numbers this may change but will make things more complicated during rehydration, because we'll lose track of which rules have already been inserted. In other words, hashes are important because they allow us to identify what's already been added to the page
