### ISSUE TITLE
Child combinator selectors being encoded to HTML entities

### ISSUE THREAD

**Issue by keeganstreet** [styled-components/styled-components#3516]
## Environment

styled-components: 5.1.1
babel-plugin-styled-components: 1.12.0

## Reproduction

We have a serverside rendered application. When hydrated in the browser, in some cases selectors with a child combinator are having `>` symbols encoded to `&gt;`.

Server rendered styles:

![image](https://user-images.githubusercontent.com/513363/122138130-74c76c80-ce89-11eb-8b90-23c92f98a35e.png)

After hydration:

![image](https://user-images.githubusercontent.com/513363/122138187-8d378700-ce89-11eb-9df3-5d3ef2a74e6b.png)

Unfortunately I don't have a simple reproducible test case to provide, as the issue is happening when seemingly unrelated components are included in the tree. I realise this is hard for you to investigate without a reproducible test case but I am wondering if you have seen something similar or have any suggestions for where I should investigate?

**Comment by Ricardinh0** [comment]
I'm also seeing this case. I've ripped the application down to its bare bones and haven't been able to pin point the issue. Using `styled-components: 5.3.0`. 

The only thing that worked is [this](https://github.com/styled-components/styled-components/issues/1576#issuecomment-370818961). 

However, that issue was off of Styled Components v3.2.0 and looks like it was fixed. Plus I'm not super keen about not using the `>` selector when it'll be too easy for other developers on the project to forget that CSR breaks under that case.

My application works fine using `4.4.1` and only breaks in `v5`.

**Comment by kitten** [comment]
We don't apply any encoding or `>` / `<` XSS protections, as you can see in the code for server-side rendering output: https://github.com/styled-components/styled-components/blob/d96101a102b59a8f9ac4b6f278594674897282bb/packages/styled-components/src/sheet/Rehydration.ts#L8-L38

The question would then be how you add CSS to your SSR output, and whether that affects the encoding. So, while I'm a bit confused, I'll have to ask for a reproduction here please, before an investigation ❤️

**Comment by keeganstreet** [comment]
I found it. We're streaming our responses, which results in multiple `<style data-styled="true" data-styled-version="5.1.1">` elements being added to the HTML. This issue occurs when the `<style data-styled="true" data-styled-version="5.1.1">` is inserted as a child element of an `<svg>`. Reading `innerHTML` from an `<svg>` element seems to yield a result that is encoded differently from reading `innerHTML` from another element like a `<div>`. I should be able to put together a reproduction if you'd like @kitten.
