### ISSUE TITLE
Can't set component attributes

### ISSUE THREAD

**Issue by JoaoCSR** [styled-components/styled-components#3538]
## System:
 - OS: Windows 10 10.0.17763
 - CPU: (12) x64 Intel(R) Xeon(R) E-2186M  CPU @ 2.90GHz
 - Memory: 12.54 GB / 31.78 GB
## Binaries:
 - Node: 14.17.1 - C:\Program Files\nodejs\node.EXE
 - npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
## npmPackages:
 - styled-components: ^5.0.0 => 5.0.0

I'm trying to set an attribute on a input type component, I can setup the component no problem but when I try to set the attr I get an error

Code:

```
const Test = styled.input.attrs({ type: "date" 
	})`
  width: 360px;
  border: 1px solid #ccc;
  border-radius: 5px;
  height: 100%;
  padding: 0px 12px 0px 20px;
`
```

EB: https://codesandbox.io/s/styled-components-base-forked-ghzt2?file=/index.js

AB: 

> Uncaught TypeError: _emotion_styled__WEBPACK_IMPORTED_MODULE_8__.default.input.attrs is not a function

**Comment by kitten** [comment]
Your CodeSandbox seems functional and is hence not a reproduction, since it works as expecteD

However, your console output seems to suggest that you have something going on where the import is pointing at Emotion and not styled-components. This doesn't explain why this error occurs, but then again, I'm not sure whether Emotion now requires a Babel plugin to support the property-access for elements.

Either way, this is unfortunately not on our end, but something you'll have to look into on your end. If you're using Emotion's Babel plugin or a Webpack plugin in parallel that's likely related
