### ISSUE TITLE
StyleSheetManager Does not work if target is set with a ref (useRef) value

### ISSUE THREAD

**Issue by swashata** [styled-components/styled-components#3548]
I am trying to make `StyleSheetManager` render the style tags inside an element, rendered by react within my App.

But that does not work. I suspect it is because during first render, the ref value itself is null. Only after react flushes the content, then it gets the DOM.

Please suggest if it is the intended behavior or if there's a workaround.

```tsx
import styled, { StyleSheetManager } from "styled-components";
import { useRef, useState } from "react";

const H1 = styled.h1`
  color: red;
`;

export default function App() {
  const appRef = useRef(null);
  const [, setVal] = useState(0);
  return (
    <div className="App" ref={appRef}>
      <StyleSheetManager target={appRef.current}>
        <>
          <H1>This should be red</H1>
          <h2>Start editing to see some magic happen!</h2>
          <button
            onClick={(e) => {
              e.preventDefault();
              setVal((v) => ++v);
            }}
          >
            Re Render
          </button>
        </>
      </StyleSheetManager>
    </div>
  );
}
```

## Environment

```
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-scripts": "4.0.0",
    "styled-components": "5.3.0"
```

## Reproduction

https://codesandbox.io/s/winter-leftpad-lp29j?file=/src/App.js

## Steps to reproduce

You can check the output of the App. The heading is not Red, because it is rendered inside a shadow dom. If you use the react devtool or the button to force re-render somehow, the it gets red.

## Expected Behavior

The style tag should've been placed inside the div.

## Actual Behavior

On first render, the style tag is placed inside the head. Possibly related to #3448

**Comment by kitten** [comment]
The component currently doesn't accept refs but instead raw elements as it needs this element to exist at render time, not at a later effect time.

This is also not intended to work consistently for elements controlled by React, which could cause some other footguns if not used carefully.

Basically, what would work is to ensure the element exists before mounting any styles children into it. You'll have to ensure that at mount time of `StyleSheetManager` you have a target element that's safe to add `style` elements to (React mounted elements may not always be safe to modify) and that no components are mounted without this manager unless you have it initialised, otherwise the styles will go into the parent sheet.

So, currently, I'd say there are a couple of ways to work around this. Depending on your use-case, I'd suggest a portal with an isolated element that you can control without React reconciling against it. But overall regarding this issue, I'll close it as this isn't expected to work and unsupported as is ✌️
