### ISSUE TITLE
as prop removes style from styled components

### ISSUE THREAD

**Issue by otakustay** [styled-components/styled-components#3550]
## System:
 - OS: macOS 11.5
 - CPU: (8) arm64 Apple M1
 - Memory: 103.28 MB / 16.00 GB
 - Shell: 5.8 - /bin/zsh
## Binaries:
 - Node: 16.6.1 - /opt/homebrew/bin/node
 - Yarn: 1.22.10 - /opt/homebrew/bin/yarn
 - npm: 7.20.3 - /opt/homebrew/bin/npm

## Reproduction

https://codesandbox.io/s/amazing-http-ezvhk?file=/src/App.js:303-852

https://codesandbox.io/s/styled-components-base-gc367

## Steps to reproduce

See the 3 rows in sandbox

## Expected Behavior

All of them should align text justified

## Actual Behavior

The first row (A component with style prop and wrapped with `styled` given a `as` prop) works unexpectedly, `style` attribute is missing

![CleanShot 2021-08-09 at 19 29 10@2x](https://user-images.githubusercontent.com/639549/128699581-ad8b2997-3164-423c-baa2-e4b09b9be71d.png)

**Comment by kitten** [comment]
Is the question here re the sandbox, why `<Block as="div">`, where `Block` is defined as `styled(FlexJustify)`, doesn't have your custom component and the output doesn't have the `style` prop?

Because if so, the `as` prop changes the rendering target. The target of `styled(Comp)` is `Comp`. The target of `styled("div")` and `styled.div` is a `div` element. So, if you use `as` you change that target, hence `FlexJustify` is changed to `"div"`.

I'd also note while I'm here that I'm not sure why you're mixing inline styles and CSS-in-JS, i.e. full rules, if that's for demonstration purposes feel free to ignore this. However, I'd suggest to keep all styles consistently in place until you have a concrete reason to use inline styles, e.g. a JS-driven animation.

I'll close this issue for now, but let me know if that wasn't what you meant and we can reopen it if needed
