### ISSUE TITLE
dynamically changing a styled component property re-renders whole page

### ISSUE THREAD

**Issue by vgrafe** [styled-components/styled-components#356]
## Version
1.1 to 1.2

## Reproduction
Sorry, I have no time to setup a webpackbin yet, but I will provide within the next days if time permits.

## Steps to reproduce
Create a button with a prop that changes its color i.e

```js
const BuggyButton = styled.button`
  background: ${props => props.active && 'red'};
`
```

Add it to your component, then change the `active` property dynamically after first render, alternatively to `true` and `false`.

## Expected Behavior
The button should change color, without side effects.

## Actual Behavior
The first dom update seem to trigger a full-page re-render (throttle cpu if necessary). Then any further changes to that same property updates the component smoothly. 
I am able to see that render since I am working on very slow devices (smart tvs).

**Comment by mxstbr** [comment]
> The first dom update seem to trigger a full-page re-render

This sounds like it's a problem with your application – how is this `styled-components` related?

Adding `shouldComponentUpdate`s around your bigger components should remedy that situation?

**Comment by vgrafe** [comment]
Good point - I'll give it a try right now.

**Comment by vgrafe** [comment]
The re-render does not happen when, instead of changing the button look via a styled-components prop, I use an inline style with a dynamic value on a styled-component i.e.

```jsx
<BuggyButton style={{color: this.props.active && 'red'}}>
    Woops
</BuggyButton>
```

This code will update the UI without side effects. This is why I suggested this was an undesired behavior when dynamically changing a prop on a styled-component.

That being said, and even though my component is fairly simple, I probably have done something wrong triggering that re-render, so I will keep investigating on my code.

**Comment by mxstbr** [comment]
Since there hasn't been another report of this being unwanted behaviour on top of us becoming much faster in terms of performance I don't see any reason this issue should still be open.

If you think this is something we should fix on the library side feel free to comment again or open another issue!

**Comment by maxxafari** [comment]
I also have this problem. It usually only visible in webkit.

**Comment by brahimmouhamou** [comment]
Also having this proble. I can confirm it is only visible in webkit.

**Comment by eon-lee96** [comment]
Also having this proble. I can confirm it is only visible in webkit.

**Comment by AngeloGiuseppe** [comment]
I just experienced the problem as well , it happens on all browsers but more visible in webkit, I think I will get back to scss :(

**Comment by lukehillonline** [comment]
I too am getting this issue only in Chome, for me, I am updating my body style depending on a prop and it is causing a full page rerender.

```
const GlobalStyles = createGlobalStyle`
    body {
        font-family: ${theme.fonts.body};
        font-size: ${theme.fontSizes.baseFontSize};
        overflow: ${props => (props.modalOpen ? 'hidden' : 'auto')}
    }
`;

export default () => {
    return <GlobalStyles modalOpen={modalOpen} />;
};
```

**Comment by angelo-catuxy** [comment]
> I too am getting this issue only in Chome, for me, I am updating my body style depending on a prop and it is causing a full page rerender.
> 
> ```
> const GlobalStyles = createGlobalStyle`
>     body {
>         font-family: ${theme.fonts.body};
>         font-size: ${theme.fontSizes.baseFontSize};
>         overflow: ${props => (props.modalOpen ? 'hidden' : 'auto')}
>     }
> `;
> 
> export default () => {
>     return <GlobalStyles modalOpen={modalOpen} />;
> };
> ```


I don't want to be bad or rude by suggesting this but I'm just stating my solution, I switched from styled components to emotion , the transition was seamless, almost all was just changing the imports, these renders does not happen when using emotion and if you pass props, for example to change the height of an element each second it looks and work really smooth , I would recommend this instead of using the attrs api in styled-components.

If the author corrects this I will be willing to use styled-components again 

Emotion link; 

[](https://emotion.sh/docs/introduction)

**Comment by vgrafe** [comment]
I don't think Max gets notifications for this closed issue. You guys should open a new one as he suggested. 

I've not really been hanging on this issue for a while now, so I'll unsubscribe to its notifications. Good luck to all!

**Comment by mimiqkz** [comment]
Wow, I also have this problem and I thought I was crazy, since my component is very simple too. Does anyone knows if this problem has a solution or being reopened somewhere?

**Comment by kitten** [comment]
Locking since a duplicate has been created instead of just bumping.

It's worth noting that no one here posted a reproduction or clarified what "rerender" means. If you're saying "rerender in React" this can't possibly be due to styled-components. Check your other code. This is because a `StyledComponent` never changes code above itself.

If you mean repaint in WebKit, we're just using CSSOM. Feel free to provide a detailed reproduction in the new issue and we can look into this. But afaik that'd mean that any library using CSSOM on WebKit would be affected. And a repaint should usually be hardly worth mentioning anyway.
