### ISSUE TITLE
How to automatically prompt css code in character templates in vscode？

### ISSUE THREAD

**Issue by iAudreyhepburn** [styled-components/styled-components#3565]
How to automatically prompt css code in character templates in vscode？

**Comment by kitten** [comment]
This isn't an issue that's directly related to styled-components, the library, so I'll have to go head and close this. It's also a question rather than an issue, so please direct this at StackOverflow or another forum please, where you'll hopefully get a quicker and appropriate answer ✌️ There's also a vscode-styled-components library where you may find more help on the plugin
