### ISSUE TITLE
Give access to child props when styling their parent component

### ISSUE THREAD

**Issue by Adam-Schlichtmann** [styled-components/styled-components#3583]
## Feature Request
I would like the props of Styled children to be available when Styling their parent component

What will it allow you to do that you can't do today?
For this request when styling a component that has styled children, the props for the styled children should be accessible.

## Example of use case
Here is a code sandbox showing what I want to do 
https://codesandbox.io/s/loving-wind-202oc?file=/src/App.tsx

**Comment by kitten** [comment]
This isn't really as detailed as I'd like, but to extract the relevant sections into this issue, I believe you meant to propose this, right?

```js
// I want to be able to style Body using the active prop
const StyledSection = styled(Section)`
  ${Body} {
    color: pink;
    border: ${(p) => (p.active ? `1px cyan solid` : "none")};
  }
`;
```

This actually works. styled-components inserts real CSS and hence this does work. However, it inserts additively. When you say `& ${Body} { border: x; }` then this applies no matter whether `active` is truthy or falsy. That means that when you style children you need to tie the rule to a class for instance, e.g. `&.active ${Body} { border: x; }`.

This is actively discouraged however because styled-components seeks to _isolate_ styles. So, while you can do this it wouldn't make much sense as the goal is to isolate styles to their respective components. This goes so far that we often recommend 'reverse selectors'. This pattern would recommend `Body` to change its styling when its inside its parent, rather than the other way around.

**Comment by ParksDMSI** [comment]
> This isn't really as detailed as I'd like, but to extract the relevant sections into this issue, I believe you meant to propose this, right?
> 
> ```js
> // I want to be able to style Body using the active prop
> const StyledSection = styled(Section)`
>   ${Body} {
>     color: pink;
>     border: ${(p) => (p.active ? `1px cyan solid` : "none")};
>   }
> `;
> ```
> 
> This actually works. styled-components inserts real CSS and hence this does work. However, it inserts additively. When you say `& ${Body} { border: x; }` then this applies no matter whether `active` is truthy or falsy. That means that when you style children you need to tie the rule to a class for instance, e.g. `&.active ${Body} { border: x; }`.
> 
> This is actively discouraged however because styled-components seeks to _isolate_ styles. So, while you can do this it wouldn't make much sense as the goal is to isolate styles to their respective components. This goes so far that we often recommend 'reverse selectors'. This pattern would recommend `Body` to change its styling when its inside its parent, rather than the other way around.

I do not believe the intention of the issue was understood. I believe the original poster wanted to be able to style based on any prop passed into the 'referred component' not just css psudeo selectors. Please reopen

**Comment by kitten** [comment]
These are classes that are added that could be used for targeting, so I'm not referring to pseudo selectors. There's an added technical limitation here, as I've explained, and this limitation also exists because of an "ideological" constraint or rather API constraint, so it's not as cut dry and simple.
So, I'm sorry, but I know where this is going and while I'm happy to answer any questions regarding this when the poster replies here, I'm unable to oblige and keep this opened when it won't be implemented in any form 😅 For future reference, it's also not necessary to speculate what's meant here. I'm sure there's room to elaborate here for the reporter, since the original description here was rather short.
