### ISSUE TITLE
"Component definition is missing display name" Next.js build fail using code from docs

### ISSUE THREAD

**Issue by tr1s** [styled-components/styled-components#3584]
A recent update in my `npm` packages _(probably from Next.js)_ has caused build failures.

The code [styled-components provides in the docs](https://styled-components.com/docs/advanced#nextjs) that you add to `_document.js` in order for styled-components to work in a Next.js project is no longer working.

I can't figure out how to fix this code even when looking at the [react/display-name rules](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/display-name.md). Any help would be appreciated, thank you!

**The error I get in vercel:**

<img width="787" alt="CleanShot 2021-09-18 at 21 13 24@2x" src="https://user-images.githubusercontent.com/19172250/133912377-97e27cc0-ff65-43a2-98f0-81dabf0370a6.png">

**What the error looks like in my code:**

<img width="1113" alt="CleanShot 2021-09-18 at 21 01 36@2x" src="https://user-images.githubusercontent.com/19172250/133912303-69a3896f-5ce4-4480-8faf-1e9105a94fc4.png">

**These are the package updates I made that caused the sudden build failure:**

<img width="1454" alt="CleanShot 2021-09-18 at 21 24 54@2x" src="https://user-images.githubusercontent.com/19172250/133912527-cb4302f7-7e39-4ac2-8536-6cc3110a37ec.png">

**Comment by kitten** [comment]
Just make sure to assign the function that is highlighted to a named variable and return it.
some notes on that 😅

- This is a linting rule and I'm not sure why Next.js is failing your build and if that's their default, but it's not a build error or even an error in general
- This isn't something that is related to styled-components per se, so you may want to ask on the Next.js repo whether the example needs updating there too and why a linting rule errors. Again, not sure if that's because of your setup 😃

**Comment by tr1s** [comment]
Yeah my mistake, I thought there might have been some update that styled-components didn't document.

For anyone who stumbles upon this:

[I tried to name the component but that didn't work](https://github.com/vercel/next.js/issues/28786#issuecomment-922489241). Turns out it 's an [`eslint-config-next` issue](https://github.com/vercel/next.js/issues/28786#issuecomment-913419055) and downgrading from `11.2.1` to `11.1.0` did the trick.
