### ISSUE TITLE
 [Question] Caching & Performance over css files

### ISSUE THREAD

**Issue by fenos** [styled-components/styled-components#359]
Using the traditional approach with **css files** give us the ability to cache over a CDN our assets. 
Plus the browser will store those file too making almost immediate the load of the asset.

_I'm not sure how styled component is generating the css, but I know that it does it pretty good and append the result to the DOM._

- I was wondering if `styled-components` had some overhead on generating the css at runtime over at caching the static asset on a CDN + browser cache?

- Is there any performance consideration that we need to keep in mind when using the library?

- Is there any benefit using styled-components over css files regarding load performance?

Thanks for the great library, I'm enjoying it a lot so far!

**Comment by k15a** [comment]
Because your CSS lives inside JS files it will be cached like normal JS files.

I can't say much about the performance impact of the runtime CSS injecting but technically it can't be as fast as normal CSS because your browser has to parse the JS first and then the CSS which is injected by the JS. On the other hand `styled-components` is only injecting the CSS which you actually need so your browser has to parse less CSS which could increase the performance.

`styled-components` is build on [`glamor`](https://github.com/threepointone/glamor) which is really fast, so you probably won't notice any performance problems.

The only thing you have to keep in mind is, that styled-components isn't a great fit for highly dynamic styles (#134).

**Comment by meglio** [comment]
> styled-components isn't a great fit for highly dynamic styles 

Is it still the case nowadays, or have been any considerable improvements made?

**Comment by k15a** [comment]
You can use the .attrs method when you need to update the styles with high fps.

```js
const Comp = styled.div.attrs({
  style: props => ({
    color: props.color
  })
})`
  // other rules
`
```

This will basically add inline styles to your component.

**Comment by meglio** [comment]
I suppose this advice has been put somewhere in documentation?
Is there a list of all caveats and issues detected when using styled components which are currently unsolved and?

**Comment by k15a** [comment]
There is a section about the [attrs constructor in the documentation](https://www.styled-components.com/docs/basics#attaching-additional-props).
I don't know of a list other than the issues.
