### ISSUE TITLE
React.lazy causing extended styles to not override base styles

### ISSUE THREAD

**Issue by protoEvangelion** [styled-components/styled-components#3598]
This does not work:

```javascript
import { lazy } from "react";

export const Button = lazy(() => import("./Button"));
export const BlueButton = lazy(() => import("./BlueButton"));

```

This works:

```javascript
export { default as Button } from "./Button";
export { default as BlueButton } from "./BlueButton";
```

The base button has a base color of red. The extended button overrides the color to blue:

```javascript
const BlueButton = styled(Button)`
  color: blue;
`;
```

The blue style is inserted before the base style causing the base style to take precedence. Using `&&` as suggested in this similar issue https://github.com/styled-components/styled-components/issues/1816 fixes it. However there can still be an import order issue if you extend multiple times and always use `&&` when you extend.

## Environment

Not sure how to get this info from codesandbox but the version of styled-component is `5.3.1`.

## Reproduction

https://codesandbox.io/s/old-butterfly-etzrq?file=/src/components/index.js

## Steps to reproduce

1. Notice that the button color is not blue
2. Uncomment the non lazy exports in /components/index.js & comment out the lazy exports
3. Notice that the button color is now correctly overriding as blue

## Expected Behavior

The extended style should take precedence over the base style. 

## Actual Behavior

The extended style is inserted before the base style thus causing the issue:

![image](https://user-images.githubusercontent.com/20076677/136299710-66caf4d7-c49f-4af9-bcd2-73b3dba5a029.png)

**Comment by kitten** [comment]
It does, however, `React.lazy` is a stand-in component, meaning that you instantiate `styled(React.lazy(...))` it doesn't matter what the timing of the internal promise is; all that's observable from the outside for `styled` is that you've passed in a component, however it can't even tell that the inner component is a `StyledComponent`.

In other words, you'll have to move the styles that belong together into your lazy boundary and keep that opaque.

In general, I'd recommend to keep `styled(X)` extensions to a minimum, because you'll create yourself similar problems to what'd happen if you weren't using styled-components. The overwrites are going to become extremely confusing as you're starting to pass down more and more "extending" rules 

`React.lazy` however on its own is a special case. You basically have to pretend that its parents and its children are disconnected and accept that having a lazy boundary isn't the same as having none 😅 The timing here is simply too complex otherwise.

Specifically, what's worth saying here is that styled-components attempts to always keep specificity stable. It does so by grouping and ordering styles by creation order. A component that has been created after another will always have its rules inserted after. This explains the lazy behaviour because you cannot control whether both components instantiate in the right order.
If you do need to do this (although with the above constraints it becomes clear that it may create more trouble down the road for unrelated reasons), then you'll need to make sure that all `StyledComponent`s that extend each other are in the same asynchronously imported chunk.
