### ISSUE TITLE
not found props accent-color

### ISSUE THREAD

**Issue by njavilas2015** [styled-components/styled-components#3615]
not found props accent-color
![image](https://user-images.githubusercontent.com/47610140/140587346-5fe8feef-81fc-463b-acd1-1d845599494b.png)
![image](https://user-images.githubusercontent.com/47610140/140587372-6b477dd8-5863-458b-bc04-955f82f721c7.png)
![image](https://user-images.githubusercontent.com/47610140/140587391-07a90519-c57c-42ff-8215-035c8ba61702.png)
![image](https://user-images.githubusercontent.com/47610140/140587409-ffc6722b-8963-404f-9289-676f5d8c4798.png)

**Comment by florianbuehler** [comment]
Hey @njavilas2015,

I think that issue, is not related to styled-components but to [vscode-styled-components](https://github.com/styled-components/vscode-styled-components).

We already have that issue tracked there: [https://github.com/styled-components/vscode-styled-components/issues/335](https://github.com/styled-components/vscode-styled-components/issues/335) - however, we can't resolve it directly because it is due to yet another library (more details are provided in the issue).
