### ISSUE TITLE
Styled components classes losing priority when navegating throught applications (single-spa)

### ISSUE THREAD

**Issue by KevBeltrao** [styled-components/styled-components#3618]
## Stacks used
- React
- Typescript
- Antd
- single-spa
- styled-components

## Description
When I navigate through my microfront application, sometimes elements lose the styles defined on the exported styled component, that happens because they lose priority on the hierarchy as shown in the Example Case.

## Example Case
The next picture shows a button component from antd exported as a styled component. Notice that the styled-component's class (.xhiwhXs) is the second block of style shown with all the styles working (higher priority than other classes, as .ant-btn-primary).
![image](https://user-images.githubusercontent.com/43002117/140982985-4f582ba7-7120-45aa-afc9-5fd0e846db66.png)

This button redirects me to another page, if I go back to the previous page and inspect the button again, that's what's shown (next picture). Notice that the styled-component's class (.xhiwhXs) now has a lower priority (coming after .ant-btn-primary, for example). And that causes the styles to be overwritten.
![image](https://user-images.githubusercontent.com/43002117/140983677-fbb53e7d-a286-432d-ab9f-acbad621c14d.png)

PS: It also happens in other cases when I navigate from one app to another, that's not the only one.

## Question
Is there a way to prevent styled-component's styles from losing priority when navigating?
Does anyone know why it happens?

## Bad solutions that work
- It works if I spam the !important flag in every property.
![image](https://user-images.githubusercontent.com/43002117/140984743-08214705-2aef-41df-8b2f-a196c4ca7a70.png)
- It works if i wrap the styles with multiple "&" to set the styles as priorities. So it becomes like ".xhiwhXs.xhiwhXs {}"
![image](https://user-images.githubusercontent.com/43002117/140984840-e53c3eca-0fcc-49a1-a1b5-a35a3d603298.png)

**Comment by joanned** [comment]
I am also having CSS priority issues with styled-components (v5.3.0), where the extended styled component has less priority than the base component.

Example:
```
const BaseButton = styled.button`
  color: black;
`;

const ExtendedButton = styled(BaseButton)`
  color: white;
`;
```

`BaseButton` has higher priority than `ExtendedButton` but it is inconsistent between local dev, staging, and production.

**Comment by Abel-Johnson** [comment]
this problem confuse me too

**Comment by lucasgmelo** [comment]
This is happening because **antd** is **inicialized** more than once. So when you navigate through your microfront application, everytime you have a package that uses antd, **it will add all new configs _(again)_**. As these configs are being added later, antd classes are "winning" over the styled-components classes. 

The best option is to **inicialize antd just once** in your microfront app, by creating a single-spa **application** / parcel that is present in all packages, for example, **active when '/' and not exact path**. Therefore, no more antd classes will be added later and won't make styled-component classes loses priority.
