### ISSUE TITLE
Download instruction likhbe nahi kiya 

### ISSUE THREAD

**Issue by rameshchandraben** [styled-components/styled-components#3624]
Bhakchonhar salle tumrah readme me likhbe nahi kara hai ki download kaise karna hai. madharjhaat buddhi bech ke kha gayi le ka re?

**Comment by kitten** [comment]
sorry, but unfortunately *Issues* on this repository are used to report and fix issues and collaborate; for questions please check out other sites, like StackOverflow, or alternatives. Specifically, I'm writing this because we can neithe answer questions in languages that we don't speak or read, nor moderate them.
