### ISSUE TITLE
How do you specify which prefixes you want

### ISSUE THREAD

**Issue by seancurtis** [styled-components/styled-components#363]
I noticed a heap of -webkit-calc() and -moz-calc() prefixed rules in the CSS output for my component. Why is it outputting unnecessary styles? I couldn't find any docs on how to specify the browsers that need to be supported.

**Comment by mxstbr** [comment]
See #111. Instead of shipping a 1MB file for every request, we decided to just prefix all the things. Since the "unnecessary" styles are only generated and not sent down the wire, that doesn't really hurt anybody.

**Comment by seancurtis** [comment]
Can you make it so the prefixed rules appear before the un-prefixed ones at least? See https://github.com/Khan/aphrodite/issues/100 and https://css-tricks.com/ordering-css3-properties/ for more info on that.

**Comment by geelen** [comment]
That's already been fixed ([test here](https://github.com/styled-components/styled-components/blob/v2/src/test/css.test.js#L29-L48)) and will ship with v2 quite soon

**Comment by jimmynames** [comment]
so does simply using styled-components auto-prefix the styles or is this something I need to install?

**Comment by philpl** [comment]
@jimmynames It's taken care for you automatically: https://www.styled-components.com/docs/basics#getting-started

> NOTE: The CSS rules are automatically vendor prefixed, so you don't have to think about it.

Please don't comment on old PRs and instead read the docs, or ask questions in new issues, on spectrum, or on Gitter ;) Otherwise we won't have any idea of how many people have asked a certain question, and won't notice whether the docs will need clarification :wink:
