### ISSUE TITLE
insertRule is exponentially slower in development mode

### ISSUE THREAD

**Issue by csvan** [styled-components/styled-components#3632]
## System:
 - OS: macOS 12.0.1
 - CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
 - Memory: 294.21 MB / 16.00 GB
 - Shell: 3.3.1 - /usr/local/bin/fish
## Binaries:
 - Node: 16.11.1 - /usr/local/bin/node
 - Yarn: 1.22.15 - /usr/local/bin/yarn
 - npm: 8.0.0 - /usr/local/bin/npm

React version: 17
Styled Components: 5
Build: Webpack 5

## Reproduction
Sadly, this is a very complex proprietary project so I cannot provide a runnable example. Instead I will provide a snippet of the JS profile:

<img width="692" alt="Screenshot 2021-11-26 at 22 23 55" src="https://user-images.githubusercontent.com/1127729/143655970-56ae6826-73f7-46d4-be51-466abb83d129.png">

The above is taken when running in development mode locally. When running in production mode, renders are extremely fast and SC functions make up less than a few percent of the total CPU usage. In development, `insertRule` in particular makes up roughly 60% of total CPU time, and the page takes much longer to load (10-15s as opposed to < 2).

## Expected Behavior
Renders should be fast in development mode.

## Actual Behavior
Renders is exponentially much slower in development mode as opposed to production mode.

**Comment by kitten** [comment]
This actually looks like CSSOM i.e. insertRule isn't enabled for you. I haven't quite checked that, since in V6 we'll likely get rid of our TextNode-based shim, but if you provide your bundler with this env var to be replaced with `"false"` you can force enable it in development: https://github.com/styled-components/styled-components/blob/9b3457036cfedf1d5336f654f3171657630a9fd8/packages/styled-components/src/constants.js#L17

**Comment by csvan** [comment]
That did the trick, thanks!
