### ISSUE TITLE
In production mode, the generated style tag has no content

### ISSUE THREAD

**Issue by wqhui** [styled-components/styled-components#3652]
### System:
 - OS: macOS 12.1
 - CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
 - Memory: 2.39 GB / 16.00 GB
 - Shell: 5.8 - /bin/zsh
### Binaries:
 - Node: 16.8.0 - /usr/local/bin/node
 - Yarn: 1.22.11 - /usr/local/bin/yarn
 - npm: 7.21.0 - /usr/local/bin/npm
### npmPackages:
 - styled-components: ^5.2.1 => 5.2.1 

### Reproduction
https://codepen.io/wqh/pen/KKqjaWL

## Steps to reproduce
First, Sorry for my bad English, I hope you can understand what I mean.

Open the codepen link and you can see the phenomenon in the developer tools :

![image](https://user-images.githubusercontent.com/16059309/147534729-0eabe85d-87fc-4c06-a347-c871b333a054.png)

the generated style tag has no content, but actually effective.

The example is of a low version, but the `5.3.3` version of my project has the same problem

## Expected Behavior
The content of the generated style tag can also be obtained in production mode.

I saw a previous issue that said that the `insertRule`  will cause the content of the style tag to be unavailable.But I use the  [css-vars-ponyfill](https://github.com/jhildenbiddle/css-vars-ponyfill) to fix vars in IE11, this needs to get the content of the style tag . 

## Actual Behavior
In production mode, the generated style tag has no content, this is inconsistent with the development model

**Comment by kitten** [comment]
This is because it's using CSSOM in production which doesn't show its rules in the devtools as the rules are separate and not text-based as one large string.

Please refer with usage questions to Stack Overflow, as you're more likely to get quicker and helpful answers there ❤️ Repository issues on GitHub are great for that, issues, things that need to be resolved in the library itself, or can't be resolved by anyone but the maintainers. While I (and many others on other repos) are happy to eventually answer usage questions, styled-components is a busy repo and mostly stable and slow moving towards new releases, so you're not likely to get fast responses here

**Comment by steve-taylor** [comment]
Is there any way to disable this? A significant number of my styles are completely broken in production mode and I suspect the CSSOM implementation is the culprit. Since styled-components debugging is non-existent, it would be helpful to at least be able to switch to the non-CSSOM implementation to test that hypothesis.
