### ISSUE TITLE
`checked` attribute not passed to DOM node

### ISSUE THREAD

**Issue by drzamich** [styled-components/styled-components#3663]
I have noticed that when creating a custom checkbox with `styled-components`, the `checked` prop isn't passed to the `input` DOM node. When you want to pass another one, like `disabled` for instance, it works fine.

It breaks accessibility and makes it hard to test, for example using the `.toBeChecked()` matcher.

![image](https://user-images.githubusercontent.com/26330688/149139969-242a8d32-fb79-4946-8d50-477762d69c10.png)

## Environment

```
## System:
 - OS: macOS 12.1
 - CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
 - Memory: 78.36 MB / 32.00 GB
 - Shell: 5.8 - /bin/zsh
## Binaries:
 - Node: 14.15.5 - ~/.nvm/versions/node/v14.15.5/bin/node
 - npm: 6.14.11 - ~/.nvm/versions/node/v14.15.5/bin/npm
 - Watchman: 2021.11.15.00 - /usr/local/bin/watchman
```
## Reproduction

```jsx
import React, {useState} from 'react';
import styled from 'styled-components';

const StyledCheckbox = styled.input.attrs(() => ({type: 'checkbox'}))``;

export default function App() {
  const [checked, setChecked] = useState(false);
  return (
    <div className="App">
      <StyledCheckbox 
        checked={checked} 
        onChange={() => setChecked(curChecked => !curChecked)}
        name="chckbox"
        id="chckbox"
      />
      <label htmlFor="chckbox">Click me</label>
    </div>
  );
}
```
https://codesandbox.io/s/inspiring-feynman-8cnj0?file=/src/App.js

## Steps to reproduce

1. Run the above code
2. Check / uncheck the checkbox

## Expected Behavior

The `checked` attribute should show on the `input` DOM node.

## Actual Behavior

There isn't `checked` prop on the DOM node.

**Comment by kitten** [comment]
Just because React may not set the prop and it may not show up that doesn't necessarily mean it isn't working as intended; https://reactjs.org/docs/dom-elements.html#checked

I've checked this in the sandbox and this looks to be working as intended. The prop passes through to the `input` element and changes as intended

<img width="368" alt="Screenshot 2022-01-18 at 14 40 39" src="https://user-images.githubusercontent.com/2041385/149958462-0be7d49d-3df1-417f-bbaa-fedf014d9e7f.png">
