### ISSUE TITLE
SC and MUI styles mix up, even tho they have separate insertion points

### ISSUE THREAD

**Issue by alexnix** [styled-components/styled-components#3680]
### System:
 - OS: macOS 11.5.2
 - CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
 - Memory: 2.18 GB / 32.00 GB
 - Shell: 5.8 - /bin/zsh
### Binaries:
 - Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
 - Yarn: 1.22.17 - /usr/local/bin/yarn
 - npm: 6.14.10 - ~/.nvm/versions/node/v14.15.4/bin/npm
 - Watchman: 2021.11.15.00 - /usr/local/bin/watchman

## Reproduction

I have a project with both MUI (v4) and SC (v5). I did set insertion points for both of them but still the `style` tags get mixed up and MUI overrides SC styles. The following image shows the two insertion points and the `style` tags.

![image](https://user-images.githubusercontent.com/4078428/152007441-5a95d743-f9d7-4703-a7a3-66968bce38ca.png)

Setting MUI insertion point as:
```
<StylesProvider jss={create({
    ...jssPreset(),
    insertionPoint: document.getElementById("jss-insertion-point")!,
})}>
...
</StylesProvider>
```

and SC insertion point as:

```
<StyleSheetManager target={document.getElementById("sc-insertion-point")!}>
...
</StyleSheetManager>
```

I also experimented with MUI's  `injectFirst` - same issue.

IMO, one of the two insertion points is not working well, or am I missing some other bit of information that is relevant, and influences the order of the insertion?

Also notably, I tried to move SC's insertion point in the body of the HTML, but it does nothing, styles still get inserted in the head. Hence I assume that weather SC only allow insertion point in the header, or the SC insertion point is not working for me.

What else do I need to do, in order to get the style tags in the right order?

## Expected Behavior

I would expect the SC styles to be inserted after all the MUI styles, like:

```
<noscript id="jss-insertion-point"></noscript>
<style data-jss>...</style>
<style data-jss>...</style>
<style data-jss>...</style>
<noscript id="sc-insertion-point"></noscript>
<style data-styled>...</style>
```
## Actual Behavior

See image above.

**Comment by kitten** [comment]
You'll have to ensure that your target contains a placeholder style tag with the styled attribute. This isn't documented because it hasn't quite been stable throughout but if you observe the code `target` determines the parent for styled-components' tag: https://github.com/styled-components/styled-components/blob/0d97a33a42fd62851c2373c5f58c0cf451540c84/packages/styled-components/src/sheet/dom.ts#L25

Rehydration then later on determines that we'll have to replace existing SSR style tags with new ones, so old ones may be deleted. We therefore, before creating the "new style tag" for the client-side, create a new style tag _after_ one that we can already find (if one exists): https://github.com/styled-components/styled-components/blob/0d97a33a42fd62851c2373c5f58c0cf451540c84/packages/styled-components/src/sheet/dom.ts#L14

So that means we're looking for:

```html
<style data-styled></style>
```

As far as I remember, beyond that, this means that the new tag will then be created next to this one. I haven't done this in a while however, so it may not be exactly how this is done.

On a side note, please refer with usage questions to Stack Overflow or our Discord, as you're more likely to get quicker and helpful answers there ❤️ Repository issues on GitHub are great for bugs, issues, and things that need to be resolved in the library itself, or can't be resolved by anyone but the maintainers.

**Comment by alexnix** [comment]
Thanks for the answer <3
Based on the info you provided I did a bit of debugging and looks like the `target` when `makeStyleTag` get called :(, also it is undefined when `StyleSheet.insertRules` is called.
On the other hand, in `StyleSheetManager` is is defined, and the sheet [gets reconstructed](https://github.com/styled-components/styled-components/blob/0d97a33a42fd62851c2373c5f58c0cf451540c84/packages/styled-components/src/models/StyleSheetManager.tsx#L43) using its value.

Will dig in more, but just wanting to point out my setup is not SSR. It is just client-side React. Hopefully this functionality is working for non-SSR env as well?

**Comment by alexnix** [comment]
Just tested by hardcoding `target` in `makeStyleTag` to be `document.getElementById("sc-insertion-point")`, and it worked... So, maybe I am configuring something wrongly, or this could be a bug?

**Comment by alexnix** [comment]
Well, never-mind. Looks like the issue was on my side, the application has two bundles both consuming SC. Apparently setting the `target` was done in one bundle and using the styled components was done in another one, hence what i was seeing was basically output from two bundles (one having the `target` defined, and the other -the one i was interested in- not).

Moving `StyleSheetManager` to the correct bundle fixed it.
