### ISSUE TITLE
Theme is not being provided as prop at tests (jest + react testing lib).

### ISSUE THREAD

**Issue by avivdaniel** [styled-components/styled-components#3685]
Hey, I'm working on a monorepo project by using Nx's + react - typescript + styled components + mui.
 I also have a shred UI lib that contains my overrides to mui components with sc. 

## System:
 - OS: macOS 11.6
 - CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
 - Memory: 571.96 MB / 16.00 GB
 - Shell: 5.8 - /bin/zsh
## Binaries:
 - Node: 14.17.5 - /usr/local/bin/node
 - Yarn: 1.22.11 - /usr/local/bin/yarn
 - npm: 6.14.14 - /usr/local/bin/npm
 
## npmPackages:
 - babel-plugin-styled-components: 1.10.7 => 1.10.7 
 - styled-components: 5.3.3 => 5.3.3 

## Steps to reproduce
1. I have created a custom renderer with a theme provider and passed the theme.
2. I use props.theme inside my component 
3. I get error message **"TypeError: Cannot read property 'backgroundColor' of undefined"**

## Expected Behavior
I just want the theme to be provided as props while testing with react-testing-lib

## Actual Behavior
jest/ typescript has not recognized the props.theme and it's undefined.

**My custom renderer**

```
`
import { ReactElement, ReactNode } from 'react';
import { render as customRender, RenderOptions } from '@testing-library/react';
import { ThemeProvider } from 'styled-components';
import { I18nextProvider } from 'react-i18next';
import i18n from './i18nForTests';

interface IProps {
  children: ReactNode;
}

export interface IRendersOptions extends RenderOptions {}

const mockTheme = {
    colors: {
      backgroundColor: '#41444f'
    }
};

function render(component: ReactElement, { ...renderOptions }: IRendersOptions = {}) {
  const Wrapper = ({children}: IProps) => {
    return (
            <I18nextProvider i18n={i18n}>
              <ThemeProvider theme={mockTheme}>
                {children}
              </ThemeProvider>
            </I18nextProvider>
      </UserSessionContext.Provider>
    );
  }
  return customRender(component, {wrapper: Wrapper, ...renderOptions});
}
export { render };
`
```

**The component file:**

```
import styled from 'styled-components';
import { MenuItem as MuiMenuItem } from '@mui/material';

export const MenuItem = styled(MuiMenuItem)`
  align-items: center;
  justify-content: flex-start;
  &:last-child {
    border-bottom: none;
  }
  &:hover {
    background: ${(props) => `${props.theme.colors.backgroundColor}`};
  }
`;`
```

**Comment by kitten** [comment]
Sorry, I'll have to close this due to inactivity ✌️ The issue doesn't really have anything to do with styled-components per se, but as far as I can tell it seems to be something with your setup that prevents that theme from being provided, e.g. due to duplicate provider instances maybe.

We do have our Discord and StackOverflow for questions. But we're working on setting the former up more visibly

**Comment by oravecz** [comment]
I was _so_ wishing this could have been answered. My exact set up as well. I do think it is related to `styled-components` as it doesn't happen with my React providers which are used in the exact same way.

I have gone through the usual suspects. I am using Vite to bundle and make sure that `styled-components` is a peer dependency. It is a monorepo, so there is only one copy of `styled-dependency` in my single `node_modules` folder. If I publish my package and use the published version, the error is no longer there. But if I try to run my tests in my monorepo, the `theme` property on `styled-components` `ThemeProvider` is an empty object `{}`

Using `vitest` to run the tests.

**Comment by kitten** [comment]
@oravecz Maybe try checking whether you've got two separate installations of styled-components (or even two separate instantiations of the `ThemeContext`)
Apart from that without a reproduction it's simply down to searching for such issues in your codebase to be honest 😅 
We've got a Discord though, as pointed out above that's available for any related questions. To link it directly this time: https://discord.gg/hfGUrbrxaU

**Comment by Newbie012** [comment]
I had pretty much the same issue: monorepo, pnpm, styled components, vite, vitest, and of course undefined theme while testing.

importing ThemeContext from styled-components and then export it to the other packages so they will import ThemeContext from this specific package instead of styled-components has solved my issue.

I'm not exactly sure it happens only in tests, but now everything seems to work just fine.

**Comment by oravecz** [comment]
I think it is due to tests running using UMD (or cjs) bundling and it brings this problem to the surface. Using the components via an ESM loader, and the theme object is populated as expected. Also, noticing the theme object is supplied via the context properly when using a hook to expose it to the child, but not when accessing the theme via styled-component's ${props => props.theme} syntax. Again, only when running tests using my UMD bundle.

**Comment by lobaak** [comment]
Why has this been closed?

**Comment by lyonfuture** [comment]
Any updates on this? Facing the same issue.

**Comment by lobaak** [comment]
Not sure why this has been closed. It's still an issue

**Comment by fmendoza** [comment]
same issue here

**Comment by AnnaVih** [comment]
same issue

**Comment by mateusgf** [comment]
Same issue here.

**Comment by JohayerChowdury** [comment]
same issue

**Comment by zoz-pap** [comment]
In vitest case, replacing 
`import` { ThemeProvider } from "@mui/material/styles";`
to
`import { ThemeProvider } from "@emotion/react";`
has solved my issue.
