### ISSUE TITLE
Order of css injecting

### ISSUE THREAD

**Issue by MagicianPL** [styled-components/styled-components#3692]
I know that StyledComponents injecting css with order of components definition, yes?

So why this h1 tag is not white? Why this hex code overwrite white color?

First I defined this component with h1 hex code color.
In this component I have another component which has StyledWrapper with h1 color white.

So this white color should overwrite hex color. Am I right? Why this is not happen in this case? I'm just very curious.
![274009996_5323106144389808_841660256896945545_n](https://user-images.githubusercontent.com/83660460/154460354-2de77d3c-f363-4577-9742-1ca43e621f5d.jpg)

**Comment by kitten** [comment]
Sorry, I'll have to close this, since it's not an issue report, but a question / usage question, and doesn't immediately give me enough information to write a quick reply or elaborate on the issue. ✌️ 

Feel free to instead send this question into our Discord: https://discord.com/invite/hfGUrbrxaU
or on StackOverflow instead

Generally, what it looks like is that you're confusing the cascade with order of injection. It'll come down to in which order you've declared both components that are targeting the `h1`. In general, though it looks like it'd make more sense to not define this styling by targeting the sub-element since that goes a little against the isolation that `styled-components` provides for your styles
