### ISSUE TITLE
README not visible on npm

### ISSUE THREAD

**Issue by boidushya** [styled-components/styled-components#3694]
README is not showing up on https://www.npmjs.com/package/styled-components

**Comment by kitten** [comment]
It's already been fixed by #3608 but won't be applicable until a new release. That said it hasn't been applied to the `legacy-v5` branch, but isn't critical as it's ultimately covered by the `repository` metadata field in `package.json`, so I don't see it as vital to have this PR applied to `legacy-v5` unless a contribution for it does come in porting #3608 to that branch.
