### ISSUE TITLE
npm install styled-components error

### ISSUE THREAD

**Issue by Licodeao** [styled-components/styled-components#4000]
When I use `npm install styled-components` command，throw a error: 
 npm ERR! Cannot read properties of null (reading 'edgesOut'). 
Finally I solve this problem by using `npm install styled-components@latest`， but  documentation doesn't  mention this command，I think you need to update the documentation.

**Comment by BryantIT** [comment]
I can confirm this.  Having the exact same issue.

**Comment by Licodeao** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Gustavo-Pauli** [comment]
i had the same error, thanks

**Comment by yusufdeepwork** [comment]
Same

**Comment by willianrod** [comment]
Same

**Comment by Aneesh-Pothuru** [comment]
Same

**Comment by abdullahahsan12** [comment]
I was getting the same issue aswell. This has something to do with the package version having `-rc.01` in it i guess. if you try installing any other version which does not have alphabet in version name would work. in my case i was able to install using `npm i styled-components@5.3.10`

**Comment by baufometic** [comment]
Existing issue: `https://github.com/styled-components/styled-components/issues/3998`

**Comment by Rishabh-Singh-Codes** [comment]
Till the time this issue is resolved you have two options.

The latest version of styled-components is v6 but there is some issue while doing `npm i styled-components`. So either

1. Use V5, `npm install styled-components@5.3.10`, OR
2. Use yarn, `yarn install styled-components`.

Also check this [stack overflow answer](https://stackoverflow.com/a/76219567/19688856).

**Comment by Licodeao** [comment]
Fine! My original intention of posting this issue is reminding the team to update the documentation quickly.
