### ISSUE TITLE
SC in React may generate the same class for different components with different props, causing potential styling conflicts when running the build.

### ISSUE THREAD

**Issue by Surfer-Alex** [styled-components/styled-components#4010]
## System:
   - OS: Windows 10 10.0.22000
   - CPU: (4) x64 Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz
   - Memory: 960.55 MB / 7.92 GB
  ## Binaries:
   - Node: 18.13.0 - C:\Program Files\nodejs\node.EXE
   - npm: 8.19.3 - C:\Program Files\nodejs\npm.CMD
  ## npmPackages:
   - styled-components: ^6.0.0-rc.1 => 6.0.0-rc.1
   - react: ^18.2.0

## Reproduction

https://codesandbox.io/p/sandbox/styled-components-base-forked-o74bgp

## Steps to reproduce
- Step 1 : Declare a styled components as below
 ```jsx
const SmallContainer = styled.div`
    padding-right: ${({ pdr }) => pdr};
    padding-left: ${({ pdl }) => pdl};
   `;
 ```
 
- Step 2 : Set props on components as below
 ```jsx
<div>
    <SmallContainer pdr="39px" >
         <div>TWD.799</div>
    </SmallContainer>
    <SmallContainer pdl="39px" >
        <div>TWD.799</div>
    </SmallContainer>
</div>
```

## Expected Behavior
- The expected behavior is that when you run the build with React, it should generate a different random class for each independent prop.

- When running npm start in development mode, the props should work perfectly, and each prop should have a different dynamic class.

- The latest stable version works fine with React when running the build.

## Actual Behavior
- When building with the React framework, if the second "SmallContainer" component has the prop pdl set to "39px", it will generate the same class as the first "SmallContainer" component. As a result, both "SmallContainer" components will have a padding-right of 39px.

**Comment by max80713** [comment]
same here!

**Comment by EricTsai83** [comment]
Same problem.

**Comment by probablyup** [comment]
I think you're misunderstanding how s-c works. The styles are attached to the second class which is separate:

<img width="1840" alt="Screenshot 2023-06-03 at 11 33 58 PM" src="https://github.com/styled-components/styled-components/assets/570070/1524aacc-6e72-4b20-9983-91393c8ed658">

The first class is the static className that is generated for each `styled.*|styled(*)` and used for the component selector pattern.

You reuse `SmallContainer` so that's why you see the same static class twice.
