### ISSUE TITLE
Handle undefined interpolation results

### ISSUE THREAD

**Issue by wmertens** [styled-components/styled-components#402]
In the case of a component like

```js
const Foo = styled.div`
	width: ${p => p.width};
`
```

the function could return an empty string or some invalid value. I noticed that this gets converted to `width: ;`, which then gets ignored by the browser (instead of my expected `width: undefined;`. However, is this safe?

If not, perhaps a better approach would be to remove the rule completely, or to set the value to `unset` (which is not supported in IE)?

**Comment by IljaDaderko** [comment]
@wmertens will `width: ${p => (p.width) ? p.width : 'fallback'}` do the trick?

**Comment by wmertens** [comment]
I never heard of `fallback`, are you sure that is correct? In any case, that is more typing and it seems to me that S-C is also about providing a great DX...

**Comment by IljaDaderko** [comment]
@wmertens my bad, that was just an example, ideally you'd substitute that value to something that wouldn't break your layout i'e `0`

**Comment by wmertens** [comment]
That's the problem, there is the value 'unset' which is supposed to work
for all attributes but it doesn't work in IE and it is effectively the same
as not setting the CSS rule, I think (it could also be removing other
cascading rules, not sure). So maybe S-C can just remove the rule.

**Comment by mxstbr** [comment]
We will have to restrict what people can interpolate sometime anyhow to make static CSS extraction feasible, so I'm sure we can look at this too.

/cc @thysultan @philpl

**Comment by jsvg** [comment]
Is there anything wrong with this approach?
```js
const Foo = styled.div`
  ${({ width }) => `
    ${width && `width: ${width}`};
    // ... other styles
  `};
`
```

**Comment by geelen** [comment]
Sorry, what's wrong with `width: ;`? That's an invalid CSS rule, the browser should just ignore it, it's the same as it not being there, right?

`unset` means something different. It means reset to the `inherit` or `initial`, depending on the property. If the rule isn't present, or is invalid, it simply has no effect (rather than resetting):

```css
.foo {
  width: 50%;
  width: unset;
}
```

`unset` is a real value so it overrides `50%` here but the end result `initial` effectively means `auto`. If you deleted the rule, it would be `50%`. I really don't think this is the sort of thing SC should be bothering itself with. If you want `unset`, use `unset`:

```js
styled.div`
  width: ${p => p.width || 'unset'};
`
```

**Comment by wmertens** [comment]
Myeah, I just don't like it when I see invalid rules in devtools ☺

I suppose we can shelve this until stricter interpolation rules are used,
which would allow better acting on the rule level.

**Comment by philpl** [comment]
Hm, seems I didn't see this in time (bloody github notifications)

I don't think that it's something that we can solve until we split static and dynamic styles. Even then, we'd need to split up the interpolation in a sensible way, to remove the rule completely. The way we're going to do preprocessing now is not going to solve this.

Until then I don't see why `width:;` is any better than `width: undefined;`. It will be invalid either way ^^

**Comment by donaldpipowitch** [comment]
Stupid question: What currently is the expected behaviour of:

```ts
const Foo = styled.div`
  width: ${p => p.width};
`;

const foo = <Foo />;
```

Is it "okay" to return `undefined` in the interpolation? Is this a supported pattern? (If `undefined` is returned -> don't set the rule.) Or could this behaviour change at any time, because it is not specified? I couldn't find anything in the docs.

**Comment by kitten** [comment]
@donaldpipowitch This behaviour is very clearly defined and won't change: https://github.com/styled-components/styled-components/blob/28b4c28f1ebd1ea5a34717df2fe49634461285b1/packages/styled-components/src/utils/flatten.js#L16

**Comment by donaldpipowitch** [comment]
@kitten Thanks for responding. So this is a (common?) pattern to say "if `undefined` don't set this declaration".

```ts
css`
  display: inline-block;
  width: ${p => p.width};
`;

// rendering just "display: inline-block;", if width is undefined
```

**Comment by kitten** [comment]
@donaldpipowitch Yes, it is, also please, if you have a question ask on Spectrum or in a new issue. Replying to unrelated, old issues is not our preferred method of addressing usage questions 😅
