### ISSUE TITLE
Support for container/element queries?

### ISSUE THREAD

**Issue by sunny-g** [styled-components/styled-components#416]
Container/element queries are an extension of the idea behind media queries, with the difference being that instead of querying against CSS properties of the viewport, you can query against properties of the containing element/component. Therefore, you can let your components dictate their rendering and styling depending on their container, rather than the viewport of the device, making them considerably more reusable, e.g. the styling of rows or cells of a table likely depends more on the element that contains the table than the size of the device. 

A few implementations exist already:
https://github.com/ausi/cq-prolyfill (I currently use this with PostCSS, works well)
https://github.com/marcj/css-element-queries
https://github.com/eqcss/eqcss

Just discovered this project so I don't know if it natively supports such syntax, but I've come up empty searching through the issues here and in https://github.com/styled-components/polished.

Any thoughts to what it would take to support these queries in this project or an extension?

**Comment by AntonAderum** [comment]
This is something that would be very helpful for the page we are building at my company as well.

It seems that it would be a nice fit for styled-components since styled-components could parse the container query and "simply" create appropriate classes for the container query options.

Exampel:
```
styled.div`
    background-color: red;
    &:container-query(max-width: 768px) {
        background-color: blue;
    }
`
```
would result in two class: 
`a` : 
```
.a {
    background-color: red;
    width: 100px;   
} 
```
`b`:
```
.b {
    background-color: blue; 
}
```
Then styled-components would set the className property of the element to `a` always and `b` if the width of the element is a match for the container query. 
So if the `element.width <= 768px` the html would be:
```
<div class="a b"></div>
```

Thoughts?

**Comment by tomhodgins** [comment]
I'm with the EQCSS project and I'd love to help if there's anything I can do to make it easier for our projects to work together, or for Styled Components to output EQCSS syntax.

Our plugin can be found here: https://github.com/eqcss/eqcss

And I've been working on a spec for the syntax which might make implementation easier: https://github.com/tomhodgins/element-queries-spec

Here's an example of the syntax that would need to be output for the element queries to be read by the plugin in the browser.

Suppose you have an element called `.widget`, it could look like this in HTML:

```html
<div class=widget>
  <h2>Widget Headline</h2>
  <p>This is some widget content</p>
</div>
```

If you wanted to write a media query, based on the browser's viewport, that would hide the `<p>` tag when the browser was narrower than 600px, you could target that like this:

```css
@media (max-width: 600px) {
  .widget p {
    display: none;
  }
}
```

Now the downsides to this are:

- media queries are based on the browser's viewport, so this rule is layout-dependent
- this style is not scoped, so it would hide every `.widget p` on the page when the breakpoint is hit
- to avoid scoping issues we may need unique names, etc

With EQCSS we can bypass all of that, instead we could write a query for the `.widget` element based on its own width. Instead of `@media` we could write it this way:

```css
@element '.widget' and (max-width: 200px) {
  $this p {
    display: none;
  }
}
```

And there is a description of the following parts:

- `@element` is the start of the element query
- `.widget` is the scoped element, this is what we will be evaluating
- `and (max-width: 200px)` is our responsive condition, whenever this is true the styles apply
- `$this p` refers to only the `<p>` tag in the `.widget` matching the condition

So as you can see here, instead of writing the rule for `.widget p`, or needing a unique name on our element, we can use `$this` to scope the styles to only those elements meeting the condition. This lets us build layout-independent styles and self-responsive elements very simply :)

**Comment by shripadk** [comment]
I'm currently working around this by using `react-container-query`. Here is an example:

```javascript
import React from 'react';
import classnames from 'classnames';
import styled from 'styled-components';
import { ContainerQuery } from 'react-container-query';

const query = {
  'box1': {
    minWidth: 250,
    maxWidth: 599,
  },
  'box2': {
    minWidth: 600,
  },
};

const Box = styled.div`
  color: white;
  background: green;

  &.box1 {
    background: gold;
  }

  &.box2 {
    background: red;
  }
`;

export default BoxContainer = (props) => {
  return (
    <ContainerQuery query={query}>
      {(params) => (
        <Box {...props} className={classnames(params)} />
      )}
    </ContainerQuery>
  );
}
```

But yes, as @AntonAderum mentioned, it would be nice to be able to do this instead:

```javascript
const Box = styled.div`
  color: white;
  background: green;

  &:container-query(min-width: 250px and max-width: 599px) {
    background: gold;
  }

  &:container-query(min-width: 600px) {
    background: red;
  }
`;
```

**Comment by jacobp100** [comment]
@tomhodgins What are your thoughts on how the inter-op would work?

**Comment by tomhodgins** [comment]
@jacobp100 I'm not sure - we haven't heard anything back from the Styled Components side, and I'm not a Styled Components or React user so this is not the area of this question I know about.

But I _am_ curious how I can help make the connection work. We need to hear from @mxstbr or somebody from Styled Components!

I do know:

- right now I'm speccing out container-style element queries and hoping we can eventually get some form of them added to CSS
- until CSS has element or container queries, it will require some JavaScript to work
- Styled components seem to specify for React components (via JS) many of the things element queries would eventually do when styling all HTML
- If right now Styled Components babysits the responsive conditions on the page and outputs styles based on different conditions - perhaps instead Styled Components could output EQCSS and then the EQCSS plugin on the page could be the one to babysit and manage the application of those styles

I'm essentially asking: Could Styled Components be used kind of like a preprocessor for EQCSS synax?

I believe so! But I'm not sure how to move forward with that love connection from my end. I've got a plugin ready to go, dozens of demos, a spec, and an understanding of the kind of code that would need to be output to work - I need somebody who understands Styled Components who can make that bridge between that knowledge and this knowledge :D

**Comment by k15a** [comment]
@tomhodgins styled-components is not babysitting the responsive conditions. The only thing we do is to parse the CSS wrap it in a dynamic class and apply it to a style tag and the class to the component. With this way we don't need to rebuilt all CSS features like pseudo classes or media queries. In my opinion the best way to add element query support would be stylis middleware so users could opt in to use them with some kind of extension but IIRC that's something @mxstbr don't want to add.

**Comment by tomhodgins** [comment]
> The only thing we do is to parse the CSS, wrap it in a dynamic class and apply it to a style tag and the class to the component. With this way we don't need to rebuilt all CSS features like pseudo classes or media queries

Interesting! I was under the impression that it watched the component and was able to re-issue styles when different logic was met inside the component - like React-aware queries that reached beyond what CSS alone could trigger.

Similar to this, if the EQCSS plugin sits on the page like a polyfill or a shim. For most uses you can even CDN host it. If there is EQCSS syntax in a `<style>`, `<link>`, or `<script type=text/eqcss>` it will be parsed and the conditions extracted.

In a similar way to the custom class idea the EQCSS plugin will mark up all affected elements in the DOM with an attribute and use those attributes to represent the relationships different elements represent to the scoped selectors. For example: one of the things we support is a `$parent` selector, so for each query we read we mark the parent element as well. Eventually I believe we may keep this 'registry' of elements internal to the plugin and not interact with the DOM but for now being able to see the attribute and which query it came from can help for debugging purposes. You can read more about how the plugin thinks about elements here: [https://github.com/eqcss/eqcss/wiki/EQCSS-1.0.0-~-Technical-documentation](EQCSS-1.0.0-~-Technical-documentation)

Once EQCSS has parsed the styles and marked up the elements in the DOM they apply to it then babysits all of the different queries it's holding, re-evaluating their conditions based on a number of events. You can learn more about what triggers a recalculation here: [https://github.com/eqcss/eqcss/wiki/Understanding-EQCSS-Triggers](Understanding-EQCSS-Triggers)

Any time a query that the EQCSS plugin is babysitting evaluates to `true`, it processes the CSS it was holding (since that CSS may contain selectors, units, and features that apply to the context of the element on the page they may change over time. Once the 'CSS+extras' code has been rendered as CSS it will be added to the page in a `<style>` tag in the head using the same attributes from before.

I hope that helps explain where the element queries side of things is!

**Comment by k15a** [comment]
> Interesting! I was under the impression that it watched the component and was able to re-issue styles when different logic was met inside the component - like React-aware queries that reached beyond what CSS alone could trigger.

Yeah if some props are changing styled-components will inject the new styles to the head and change the class.

**Comment by tomhodgins** [comment]
> if some props are changing styled-components will inject the new styles to the head and change the class.

Can you give me an example of the kinds of 'props' that might trigger a class change?

For element queries, in the spec we're working on the following conditions:

- element's width
- element's height
- element's # of characters of text
- element's # of lines of text
- element's # of child elements
- element's scroll position on X or Y axis
- element's aspect ratio as it appears on the page
- element's orientation (portrait, square, landscape)

Would the kinds of conditions Styled Components is watching be 'generic' enough like this to be babysat outside of the environment where Styled Components runs? Could you encode what Styled Components does in a syntax with the above features, or does it require more knowledge of the state of the component or what's going on in JavaScript as well?

For me, without understanding the full range of what Styled Components can do on its end it's hard for me to see where that line is between what they can both express, and what might be 'Styled Components-only' functionality.

**Comment by k15a** [comment]
@tomhodgins Here is a minimal example http://www.webpackbin.com/41drY-dtG. So basically it's not watching for anything it's just rerendering the styles everytime the component gets rerendered. It's like a function which get's called everytime the style changes and returns the new dynamic class.

**Comment by tomhodgins** [comment]
Ah thanks, that does help illustrate things @k15a!

To build a quick example demonstrating the EQCSS side of a similar demo it's easier for me to build outside of React…so picture the JS and HTML as though React is the tool rendering them and I'll draw your attention to just a couple things about the styles themselves.

Here's a stylistically equivalent demo:

```html
<button onclick=toggle()>Click me</button>
<p>Color: Red</p>

<style>
  @element 'p' {
    $this {
      color: #222;
      font-size: 1.5em;
      font-family: Helvetica, Arial, sans-serif;
      text-align: center;
      color: eval('color');
    }
  }
</style>

<script>
  // Setting a JS variable to use with EQCSS
  var color = 'red';

  function toggle(){

    var p = document.querySelector('p')
    color = color == 'red' ? 'blue' : 'red'
    p.innerHTML = 'Color: '+color

    // Invoking an instant style recalculation
    EQCSS.apply()

  }
</script>

<script src=http://elementqueries.com/EQCSS.js></script>
```

The first difference is that instead of scoping the style to the element in JS using a CSS-in-JS approach, the EQCSS plugin will read JS-in-CSS. This means what is written in Styled Components as:

```js
const Text = styled.p`
  color: #222;
  font-size: 1.5em;
  font-family: Helvetica, Arial, sans-serif;
  text-align: center;
  color: ${props => props.color};
`;
```

Is going to be similar to the same styles in EQCSS syntax like this:

```css
@element 'p' {
  $this {
    color: #222;
    font-size: 1.5em;
    font-family: Helvetica, Arial, sans-serif;
    text-align: center;
    color: eval('color');
  }
}
```

In my example I've used a `<p>` tag, but this could be selected any way that made sense to the tags and components you're working with. Here's a little breakdown of the different parts of the syntax here:

- `@element 'p' {}` means: the following styles will apply to the HTML document as long as at least one `<p>` tag is present. Since we have listed no  responsive conditions, it applies 100% of the time.

- `$this {}` means: apply these rules to the tag(s) matching the selector(s) in question and their responsive conditions.

- `color: eval('color');` means: at the time this rule is evaluated, use the current value of the global JS variable named `color` as the content for this part of the css. (In our demo it will always be `red` or `blue`, but could be any JS value, a one-liner to compute in-place, or even running a function!

The last little thing I added to the demo make it snappy was `EQCSS.apply()` inside my JS logic (for React users you would want this to happen immediately after the component updates the DOM) to immediately recalculate the styles without waiting (whether it was already going to or not based on other triggers) just so we're sure it's showing up as fast as possible.

Does that makes sense? That example looks like a pretty good one to show how the translation could be made from one syntax to another :D Maybe EQCSS could help serve as a path that people could take to 'export' styles originally written for React components and allow those same styles to be used on HTML outside of React!

Here's a little bit about how the style scoping works: http://codepen.io/tomhodgins/post/how-style-scoping-works-with-element-queries

I've used it in the global scope here, kind of like a CDN-hosted shim or polyfill, but if it a UMD-formatted module so here are instructions on how you could import that and use `EQCSS.apply()` and `EQCSS.throttle()` from within your own modules (as I'm sure you'll want to to if trying to trigger it from within React) http://codepen.io/tomhodgins/post/using-eqcss-as-a-javascript-module-with-webpack

**Comment by dirtyredz** [comment]
I would think the quickest fix for this would be to have styled-components push its generated class name right after `@element` and leave the rest for eqcss to pick up and do its work.

**Comment by philpl** [comment]
I'm going to close this due to inactivity.

Btw we're not looking into supporting non-standard CSS.

**Comment by dirtyredz** [comment]
I used to use the InjectGlobal feature to work around the non support for EQCSS
    import styled, { injectGlobal } from 'styled-components'

    injectGlobal'
      @element .ProjectContainer_EQCSS_1{
          .ProjectContainer_EQCSS_1 {
              font-size: 2.5ew !important;
          }
      }
    ';

but after updating to 2.4

Styled-Componenets now strips the initial curly braces leaving this as a result
    @element .ProjectContainer_EQCSS_1.ProjectContainer_EQCSS_1{font-size:2.5ew !important;}

which breaks EQCSS

**Comment by FreddyFY** [comment]
I have created a new styled-components addon. Where you can use the container-query with styled-components. https://github.com/FreddyFY/styled-container-query

```javascript
import styledContainerQuery from 'styled-container-query';

const Child = styled.span``
const Component = styledContainerQuery.div`
  background-color: green;
  
  &:container(min-width: 500px) {
    background-color: red;
    ${Child} {
          color: white;
      }
  }
  
  &:container(max-width: 600px and max-width: 900px) {
      background-color: yellow;
  }
  
  &:container(min-height: 500px) {
      background-color: blue;
  }
`;
```

Hope this helps someone.

**Comment by episodeyang** [comment]
@FreddyFY just a minor comment:

The syntax for the container query is different from those of media query: 

```
@media (min-width: 801px) and (max-width: 1200px) {
      content: "801 - 1200"
}
```

I understand that this case is a bit different, just want to double check.

**Comment by FreddyFY** [comment]
@episodeyang Thanks for your interest in the plugin.

The syntax is based on [this comment](#issuecomment-276230181) and it was easier in development. Now it would only need another regex to change it.

For discussons please open a new issue on the right repo https://github.com/FreddyFY/styled-container-query to let this issue rest 😉

**Comment by michaeltrilford** [comment]
> I'm going to close this due to inactivity.
> 
> Btw we're not looking into supporting non-standard CSS.

Can't you still use standard CSS, then inject match-media to the application also, that is automagically hooked up?

What @FreddyFY has created looks amazing, and I have been meaning to try this out for a month or so. Hopefully this week!

**Comment by Blazsoul** [comment]
l

**Comment by Blazsoul** [comment]
If anyone still intrested,  I combined the styled components with the new container queries css feature that released in May 2021 to Chrome Canary. I used this css polyfill to support it - [https://github.com/jsxtools/cqfill](url)
And then just attached it to my styled components:
```import React, {useEffect} from 'react';
import styled, {ThemeProvider, createGlobalStyle } from "styled-components";
import "cqfill";

// Make container class unique
const containerClass = `container_${Date.now()}`;
const GlobalStyle = createGlobalStyle`
  .${containerClass} {
    contain: layout inline-size;
    --css-contain: layout inline-size;
  }
`;

const Wrapper = styled.div`
  font-size: 20px;
  position: ${(props: any) => props.theme.wrapper.position};
  color: ${(props: any) => props.theme.wrapper.color};
  display: ${(props: any) => props.theme.wrapper.display};
  font-family: ${(props: any) => props.theme.wrapper.fontFamily};
  font-weight: ${(props: any) => props.theme.wrapper.fontWeight};

  @${containerClass} (max-width: 600px) {
	font-size: 16px;
  }
  @media --css-container and (max-width: 600px) {
	font-size: 16px;
  }
`;

const Text = styled.div`
  font-size: 20px;
  color: red;
 
  @${containerClass} (max-width: 600px) {
	font-size: 14px;
	color: green;
  }
  @media --css-container and (max-width: 600px) {
	font-size: 14px;
	color: green;
  }
`;

const Component = (props) => {
    // Inject CSS Container Queries Polyfill with script if you dont want to use the npm moudle
    // useEffect(() => {
    //     const scriptUrl = "https://unpkg.com/cqfill";
    //     const scriptTag = document.createElement("script");
    //     scriptTag.src = scriptUrl;
    //     document.body.appendChild(scriptTag)     
    // }, [])
    const {theme} = props;
    return (
        <div className={containerClass}>
            <ThemeProvider theme={theme} >
                <GlobalStyle />
                <Wrapper>
                    <Text />
                </Wrapper>
            </ThemeProvider>
        </div>
    );
}

**Comment by jordymeow** [comment]
Hi,

Sorry to ask, but why is this thread closed? It looks like CSS Container Queries will be supported by browsers from now on. Shouldn't it be implemented in Styled Components? Do you have any plans for it?

I would like to avoid adding dependencies just for this feature. Cheers, and thanks for the good work :)

**Comment by barbalex** [comment]
I just spend an hour debugging my container queries. Until I realized that ist is styled-components that is failing.

**Comment by DeathlyBower959** [comment]
Just curious, why is there still not support for container queries? Aren't they stable now?

**Comment by barbalex** [comment]
They are: https://web.dev/cq-stable/

**Comment by slawinski** [comment]
I'm disappointed that after over six years, there is still no official support for container queries in styled-components. It's frustrating that we have to rely on polyfills and workarounds to achieve this functionality.

**Comment by kweigand-uxguy** [comment]
Container Queries are now supported in all major browsers! It's time for official support from styled components, please!!

**Comment by vavra7** [comment]
Is there some good alternative of styled components? It is sad but this thread is a mockery to all its users.

**Comment by jordymeow** [comment]
@vavra7 Have you tried Emotion? (https://emotion.sh/docs/introduction). Considering moving all my projects from Styled Components to Emotion, as it seems lighter, supports container queries, etc.

**Comment by barbalex** [comment]
@vavra7 I migrated three large projects from styled-components to emotion. That was a surprisingly easy task and to 98% worked flawlessly.

**Comment by vavra7** [comment]
> @vavra7 Have you tried Emotion? (https://emotion.sh/docs/introduction). Considering moving all my projects from Styled Components to Emotion, as it seems lighter, supports container queries, etc.

> @vavra7 I migrated three large projects from styled-components to emotion. That was a surprisingly easy task and to 98% worked flawlessly.

The Emotion library looks promising! I'm just testing it and so far it looks that it meets all my requirements.
- good typescript integration
- performant typescript (not this: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/34391)
- webpack/babel plugin for styles optimization
- SSR support
- support of new CSS features

Thank you guys!

**Comment by maciaszczykm** [comment]
Is there any chance of reopening of this issue? As everyone noticed container queries are pretty common right now.

**Comment by maciaszczykm** [comment]
Is there any chance of reopening of this issue? As everyone noticed container queries are pretty common right now.

cc @geelen @mxstbr @kitten @schwers @probablyup @imbhargav5

**Comment by probablyup** [comment]
Use v6 beta, the new version of stylis handles them I believe.
