### ISSUE TITLE
Will styled-components ever support latest react features (server components, streaming, concurrent redering) ?

### ISSUE THREAD

**Issue by jonrrivera** [styled-components/styled-components#4265]
Been a long time fan / user of styled-components. But recently I have found myself using tailwind 😳 because I want to leverage latest React (Server Component) features on Next.js.

I would hugely prefer to continue using styled-components since I love the syntax and already have so many projects using it. But im mainly wondering the interest and possibility for styled-components to adopt these latest react features? is this something this library is looking to get into? 

Would love to hear some thoughts. thank you !!

**Comment by tim-soft** [comment]
Vercel has some vague statement in their docs

https://nextjs.org/docs/app/building-your-application/styling/css-in-js
>We're working with the React team on upstream APIs to handle CSS and JavaScript assets with support for React Server Components and streaming architecture.

I have not seen any updates since they posted this many months ago

Anyone feel free to clue me in if I've missed something

**Comment by eualex** [comment]
@quantizor ?

**Comment by quantizor** [comment]
It would be a different library if we dropped it use of context, which is required for server components. No plans to do so. React is welcome to introduce a useful API we can switch to.

**Comment by tim-soft** [comment]
@leerob @timneutkens @acdlite @gaearon is runtime css-in-js in React dead?

**Comment by quantizor** [comment]
They've been pretty clear that you can still use whatever you want in client components, it's just they won't be as optimized. But like with all things it's a tradeoff. A runtime means you have to ship the runtime, it can't just be compiled away unless your site is entirely static.

**Comment by michal-wrzosek** [comment]
If you need RSC support I rewrote styled-components to make it compatible with new Next.js features. It covers most of the features of the original library: https://github.com/michal-wrzosek/next-styled-components

**Comment by resthedev** [comment]
> If you need RSC support I rewrote styled-components to make it compatible with new Next.js features. It covers most of the features of the original library: https://github.com/michal-wrzosek/next-styled-components

Very interesting. Have you considered working alongside the `styled-components` maintainers to get some of these ideas into the original library?

**Comment by quantizor** [comment]
I'm the current maintainer, removing important library functionality just because the React team has decided to rug pull an important set of APIs isn't going to happen. There are at least four separate threads about this and I will not be changing my mind about it.

**Comment by DanielOrtel** [comment]
have to agree, this is not a styled-components issue, rather the React team's honestly baffling decision to not have a read-only context api, or some other api that can replace context, in server components.

**Comment by gaearon** [comment]
Two notes. 

First: Context API works fine with RSC — from Client components. There’s absolutely nothing wrong with using Client components in the RSC model, they are a vital part of it. If you’re working on a design system, I would argue it is *expected* that most of your “design system” components (Button, Toggle, etc) *should* be Client components. Since you’ll likely need context, event handlers, a bit of state and so on — completely independently of what library you’re using for styling.

Second: The React team has not “decided to rug pull” anything here. Supposing context is downright impossible in Server-only trees because context can change over time and may contain non-serializable values. There is no way for Server components to *know* the context values on the client (which change over time and may be non-serializable). And even if they all *were* serializable (which they’re not), it would be incredibly inefficient to send all context back to the Server on every navigation just in case some part of the Server tree would need to read some of it. So the request here doesn’t make sense. What you’re asking for *can’t work*. What *can* work is what we’ve implemented — seamless interop between the two component types. Most of your “design system” components *should* be Client components, and nothing have changed there.

Please don’t confuse extending the system with changing the system. The Server part is the new part that grows “around” the existing Client part. Nobody has moved your cheese.

**Comment by quantizor** [comment]
Bro all I need is subtree specific data structures during SSR in the RSC model. Thats it. I don't care about sending context BACK to the server at all, it's not a requirement. I've brought this up so many times and frankly I'm sick of talking about it.

**Comment by DanielOrtel** [comment]
@gaearon I understand the sentiment you're coming from, I imagine there were numerous confused feedbacks regarding the server component/client component distinction that you had to deal with over the years, and I apologize if my comment was overly negative. 

I also understand why the decision was made not to have the context api in server components _as is_, and the limitations that lead to said decision. Which is why I specified a `read-only context api, or some api that can replace it in server components`. And yes, I'm well aware that client components are server rendered, however css-in-js cannot be used in server components, which is an important caveat. 

From user perspective though, you can sympathize with the fact that having relied on css-in-js for a long time, the current options are 
- a lengthy refactor back to css(or sass, or tailwind or modules or what-have-you)
- partial refactor of components which can be server rendered and maintaining two separate style systems, two separate theming setups, etc.
- not using server-components in a meaningful way or to their fullest potential(I know I can still nest server components through children in client components, but that has its own limitations) 

And more to the point, the part that I do not agree with is not having a read-only context api in server components. We, as devs, are already dealing with client - server component distinctions, managing where in the tree to set the client directives to achieve the best results, how to ensure that data in server components and client components are in sync, so having an understanding that contexts in server components are isolated from clients components, are not mutable and do not hydrate after initial render would not be an extra hurdle. In some ways, it would be a simplification of the current mental model. 

Obviously, I know far less about the internals of React than you do, but I find it hard to imagine that some _context-like_ api, even with heavy limitations, was not possible in server components.

**Comment by gaearon** [comment]
Sure, let me address these points too.

The reason context works well on the Client is because on the Client, you always have access to the code for the entire tree. Including parent components that specify the context. There’s never a question of _what the context is_ because it’s held in memory. And even if it wasn’t, you could always get it by re-rendering the tree from the root (and it will flow downwards).

On the Server, the situation is very different. Everything is by default ephemeral. You can keep things around during a single request, but it won’t be consistent across requests. You can keep things around for longer but then it needs some explicit caching mechanism.

The case you’re asking about is ephemeral. Why shouldn’t that be possible? One might think you could have it tied to a single request. And indeed — that already exists, and already works. It’s not a React feature, it’s a server environment feature. It’s called AsyncContext (previously AsyncLocalStorage) and is supported by Node.js and some other runtimes. AsyncContext is, for example, how Next.js implements context-like request-specific features like `headers`. Again, this _already works_ and needs no direct support from React.

What _doesn’t_ quite work is making this kind of server contextual information contextual *by a subtree*. Which is probably what you’re actually asking for. The reason is that such an API can’t work consistently across requests. Recall that on the Client, we always _know_ the parent context because we have the parent tree on the same computer. However, on the Server, we don’t always have the parent tree. If the user is navigating _within a route_ (e.g. switching tabs), we only want to refetch that inner part — not the entire tree from top to bottom. If every RSC request always requested the entire tree with no ability to do subroute navigation, it would not scale. The ability to refetch a part of the tree is crucial. However, if we’re rendering a part of the tree (such as a subroute), _we don’t know anything above it_, including the hypothetical Server subtree context. Moreover, we have no way to calculate it without reexecuting the entire parent tree (which again means full re-rendering for every navigation).

This means that the proposed feature (Server-only subtree context) would behave unpredictably. During a full navigation, a component would “see” the correct context values (the closest provider above it). But during a partial refetch, a component would only be able to see the closest provider _within the refetched route_. Anything above it would have to return a default value. So it would be impossible to write components reliably because sometimes they’d read the context value you expect, and sometimes they wouldn’t, even if the their location in the tree has not changed.

We can’t compromise on the ability to do partial refetches — without that, the paradigm is unviable. You can’t make every single navigation or mutation always refetch the entire app’s tree. In many cases it’s not even semantically correct and is noticeable the UI (in addition to tanking performance). Therefore, we have to compromise on the proposed feature — server-only subtree context.

Does that help?

**Comment by tim-soft** [comment]
@gaearon is there anything you could recommend to get this project running properly in this new age of react? I know these discussions are often stuck in the theoretical

In practice, having millions of lines of styled components that completely break SSR in modern nextjs is painful, bc that means it is rewrite time

**Comment by gaearon** [comment]
>In practice, having millions of lines of styled components that completely break SSR in modern nextjs is painful, bc that means it is rewrite time

This is not right. [Client components get SSR'd.](https://github.com/reactwg/server-components/discussions/4) Your pre-RSC Next.js code is equivalent to marking entire routes as `"use client"`. Please make sure this point resonates — I'll repeat: *your pre-RSC Next.js code is equivalent to marking entire routes as `"use client"`.* RSC did not cause your Styled Components to stop SSR'ing. **Client components get SSR'd.**

If you have an existing pre-RSC Next.js app, there is **zero** migration work needed for Styled Components to work. You just mark top-level entry points as `"use client"` which is **equivalent** to how your routes worked before RSC.

The "Server" part in RSC is equivalent to old Next.js `getServerSideProps` (but composable). Obviously you could never "use Styled Components" inside of `getServerSideProps`. So there is no regression there either. There's only a new feature.

In practice, what you're probably referring to is that the root is now implicitly Server, so unless you `"use client"` in the middle (and thus explicitly opt out of the new features), you can't use APIs like context directly. If I was an application developer with a Styled Components codebase, I'd look at these options:

- Keep `"use client"` close to the top of my routes and not change anything in the existing code. Limit RSC usage to top-level similar to `getServerSideProps`, then from that point on keep using Styled Components with `"use client"`.
- Look at the Styled Components implementation. I'm wondering what are the fundamental reasons that `styled` can't return a Client component (but be usable from the Server environment — so that you don't have to add `"use client"` anywhere). There probably are some — I just don't know.
- Look at alternatives that have an API similar to Styled Components but more constrained and that support static CSS extraction. Static CSS extraction is better regardless of RSC. And RSC works fine with static extraction. You really don't want to be sending the same styles over and over again so static extraction naturally solves that.

**Comment by tim-soft** [comment]
In my experience, styled-components with nextjs, even with "use client" at the very root, throws client/server mismatch errors

**Comment by gaearon** [comment]
That sounds unrelated to RSC. Mismatch errors are only relevant for the Client part.

**Comment by tim-soft** [comment]
Exactly, it is a problem with more recent versions of React/nextjs, which is why many of us share the sentiment that the react core team has pulled the rug, so the speak, on css-in-js

**Comment by gaearon** [comment]
I don't know what this means. There have been no changes in the React algorithm with regards to how markup mismatches work.

**Comment by DanielOrtel** [comment]
fyi: @tim-soft I have not had client mismatch errors with styled components on next 15 and react 19, maybe your problem is related to browser extensions(see [this issue](https://github.com/facebook/react/issues/24430)) or incorrect usage of window checks in some components, or incorrect usage of the babel/swc plugin for styled components? . For me adding `suppressHydrationWarning` to the `html` and `body` elements in the root layout muted the hydration warnings caused by browser extensions. 

regarding @gaearon's point 

> This means that the proposed feature (Server-only subtree context) would behave unpredictably. During a full navigation, a component would “see” the correct context values (the closest provider above it). But during a partial refetch, a component would only be able to see the closest provider within the refetched route. Anything above it would have to return a default value. So it would be impossible to write components reliably because sometimes they’d read the context value you expect, and sometimes they wouldn’t, even if the their location in the tree has not changed.

Again, I understand this point, I understand the idea of partial rendering that server components bring. It's a bit difficult for me to reason about this, because I do not have the full context of either react internals or styled components internals, but from my perspective, a _context-like_ api could still work for something like `styled-components`, since on initial render, we would have access to the entire tree, where styles can be collected globally, but on subsequent partial renders of server components, we wouldn't _need_ the entire tree, only the subtree starting from the root server component being rendererd. Any global styles should have been already sent with the initial request, at that point we only care about the subtree specific styles. 

I think it's a bit of a misnomer from my part to keep mentioning `context`, because what I'm asking for is not the current context api in server components, it's an api to replace _parts_ of the functionality that `context` has in server components. I understand your point about unpredictability, but it something that could potentially be mitigated by introducing runtime checks for whether the context is instantiated in the current subtree. And for solutions like styled-components, something akin to a "sub-context" api, that would defer to the root context in initial renders, where the whole tree is available, and use itself when it's not. This would remove the unpredictability factor, since everything is explicit. Basic example: 

```
const ServerContext = createServerContext(something);

// in root-layout.js

<ServerContext value={something}>{children}</ServerContext>

// in some-nested-server-component.js

<ServerContext.SubProvider value={limitedSomething}>{children}</ServerContext.SubProvider> // <-- defers to root ServerContext on initial render. Throws if subtree is using values from ServerContext, but is missing SubProvider. 
```

But even this may not be required, since if the server context is read-only, we only care about `default value` anyway. There can be no other values associated with it. 

Though I won't bother you further than this, since I have to admit my lack of in-depth knowledge of the react internals makes it difficult to reason compellingly about this. I am still just a bit skeptical that it is literally impossible to add some api that css-in-js solutions would be able to use to enable them in server components. Next's docs on css-in-js does mention the following: `We're working with the React team on upstream APIs to handle CSS and JavaScript assets with support for React Server Components and streaming architecture.`, though that was the last time any kind of news regarding this came out, and that snippet was added in v13.

I'm just a bit sad, since even if css-in-js have a performance trade-off, they're still a pattern I prefer over external css solutions, and I do want to use server components to their full extent, not just as data fetch wrappers.

**Comment by WillsB3** [comment]
> styled-components now natively supports React Server Components (RSC) with zero configuration. In RSC environments, styled components automatically emit inline <style> tags that React 19 hoists and deduplicates.

See https://styled-components.com/docs/advanced#react-server-components
