### ISSUE TITLE
toHaveStyleRule assertion fails after upgrading too 6.1.10

### ISSUE THREAD

**Issue by akkadaya** [styled-components/styled-components#4308]
After upgrading  `styled-components` package to 6.1.10, `toHaveStyleRule` assertion started failing!

I'm getting this error
> Error: No style rules found on passed Component

### System:
 - OS: macOS 14.4.1
 - CPU: (10) arm64 Apple M1 Pro
 - Memory: 93.66 MB / 32.00 GB
 - Shell: 5.9 - /bin/zsh
### Binaries:
 - Node: 18.20.2 - ~/.asdf/installs/nodejs/18.20.2/bin/node
 - Yarn: 1.22.22 - /opt/homebrew/bin/yarn
 - npm: 10.5.0 - ~/.asdf/plugins/nodejs/shims/npm
 - pnpm: 9.1.0 - ~/.asdf/installs/nodejs/18.20.2/bin/pnpm
 - bun: 1.1.7 - /opt/homebrew/bin/bun
 - Watchman: 2024.05.06.00 - /opt/homebrew/bin/watchman
### npmPackages:
 - styled-components: ^6.1.10 => 6.1.10 

## Reproduction
- Upgrade `styled-components` package to 6.1.10

## Steps to reproduce
- Upgrade `styled-components` package to 6.1.10
- Run tests

## Expected Behavior
`toHaveStyleRule` to pass

## Actual Behavior
`toHaveStyleRule` failed

**Comment by jaycetde** [comment]
I'm running into a similar issue.  I found that the test would succeed if only a single test was ran, but once multiple tests were run, the first would pass, but all others would fail.

From what I can tell, this is due to using a singleton `StyleSheet` [here](https://github.com/styled-components/styled-components/blob/main/packages/styled-components/src/models/StyleSheetManager.tsx#L8) as the default value for StyleSheetContext that is reused across multiple tests.  This stylesheet will reuse the same `tag` [here](https://github.com/styled-components/styled-components/blob/main/packages/styled-components/src/sheet/Sheet.ts#L78), but assume this `tag` is removed from the DOM as the first tag tears down and does not get added to the new test's DOM automatically.

My current work-around is to delete the `tag` from `StyleSheet` as the the test is rendered:
```tsx
const HackyFix = () => {
  const sheetContext = useContext(StyleSheetContext)

  // delete `tag` on render.  This will make sure `tag` doesn't exist when `MyComponentToTest` renders, so styled will create a new tag and add it to the DOM
  sheetContext.styleSheet.tag = undefined

  return null
}

it('test', () => {
  render(
    <StyleSheetManager> // Not necessary for the fix, just being explicit
      <HackyFix />
      <MyComponentToTest />
    </StyleSheetManager>
  )
  ...
})
```

If `StyleSheet` was exported, I would have preferred to do this: `<StyleSheetManager sheet={new StyleSheet()}>`

**Comment by akkadaya** [comment]
> My issue was due to multiple versions of styled-components being installed in my monorepo incorrectly. Everything is working for me now that I only have 1 instance of styled-components installed.

Same here! I followed the [installation docs](https://styled-components.com/docs/basics#installation) and added `"styled-components": "^6"` to `package.json` `resolutions`. There is an issue with Yarn v1 where it doesn't remove duplicates efficiently.

My `yarn.lock` looked like this before `yarn upgrade styled-components@latest`

Before:
```yaml
styled-components@6.1.9, styled-components@^6:
  version "6.1.9"
  resolved "https://registry.yarnpkg.com/styled-components/-/styled-components-6.1.9.tgz#cf2ac444979a925a3553d0bac3ba7688891e4625"
  integrity sha512-aBOqs0uMsYufFXSE4q6cA6Ty1fwZuMk4BJRHfiGSna59F1otnxiDelwhN4fEwmBtIymmF0ZqXHnpSigr2ps9Cg==
  dependencies:
    "@emotion/is-prop-valid" "1.2.1"
    "@emotion/unitless" "0.8.1"
    "@types/stylis" "4.2.0"
    css-to-react-native "3.2.0"
    csstype "3.1.2"
    postcss "8.4.31"
    shallowequal "1.1.0"
    stylis "4.3.1"
    tslib "2.5.0"
```

And after the upgrade
After:
```yaml
styled-components@^6:
  version "6.1.9"
  resolved "https://registry.yarnpkg.com/styled-components/-/styled-components-6.1.9.tgz#cf2ac444979a925a3553d0bac3ba7688891e4625"
  integrity sha512-aBOqs0uMsYufFXSE4q6cA6Ty1fwZuMk4BJRHfiGSna59F1otnxiDelwhN4fEwmBtIymmF0ZqXHnpSigr2ps9Cg==
  dependencies:
    "@emotion/is-prop-valid" "1.2.1"
    "@emotion/unitless" "0.8.1"
    "@types/stylis" "4.2.0"
    css-to-react-native "3.2.0"
    csstype "3.1.2"
    postcss "8.4.31"
    shallowequal "1.1.0"
    stylis "4.3.1"
    tslib "2.5.0"

styled-components@^6.1.11:
  version "6.1.11"
  resolved "https://registry.yarnpkg.com/styled-components/-/styled-components-6.1.11.tgz#01948e5195bf1d39e57e0a85b41958c80e40cfb8"
  integrity sha512-Ui0jXPzbp1phYij90h12ksljKGqF8ncGx+pjrNPsSPhbUUjWT2tD1FwGo2LF6USCnbrsIhNngDfodhxbegfEOA==
  dependencies:
    "@emotion/is-prop-valid" "1.2.2"
    "@emotion/unitless" "0.8.1"
    "@types/stylis" "4.2.5"
    css-to-react-native "3.2.0"
    csstype "3.1.3"
    postcss "8.4.38"
    shallowequal "1.1.0"
    stylis "4.3.2"
    tslib "2.6.2"
```
