### ISSUE TITLE
Module uses bundled code for building with webpack

### ISSUE THREAD

**Issue by wmertens** [styled-components/styled-components#438]
## Version
2.0

## Steps to reproduce
* Install SC, use webpack to bundle

## Expected Behavior
* Webpack uses `dependencies` for bundling, including some deps that may occur elsewhere in the project

## Actual Behavior
* Webpack includes the rollup .es.js file which bundles everything

In the package.json, `main` is set to `lib/index.js` which is the ES5 modular transpilation. `jsnext:main` is `dist/styled-components.es.js` which is a pre-bundled version that only excludes React. There is also a `module` key set to the same bundle.

I think that `jsnext:main` and `module` should also point to `lib/index.js`, or else the es bundle should exclude regular `dependencies` as well as `peerDependencies`.

**Comment by mxstbr** [comment]
Hmm, @Rich-Harris any ideas why this is the case?

**Comment by mxstbr** [comment]
@k15a I see you're assigned here, have we fixed this yet?

**Comment by k15a** [comment]
Ohh yeah. This is because we point the "module" field in our package.json to "dist/styled-components.es.js". This bundle has all dependencies included except React and Stylis. We can fix this if we exclude all dependencies from the es bundle because this is only used by Rollup and WebPack which can bundle the dependencies anyway.. We only need to include the dependencies in our UMD bundle.

@philpl do you think we should do this? The last time you said that you don't want to introduce bugs right before v2.

**Comment by mxstbr** [comment]
Let's try it. Can you submit a PR maybe?
