### ISSUE TITLE
Weird behaviour of a styled.View inside a react-native ListView

### ISSUE THREAD

**Issue by dbertella** [styled-components/styled-components#465]
## Version
1.4.3

## Reproduction
https://github.com/dbertella/RNstyledPlayground

## Steps to reproduce
Using a `styled.View` inside a `ListView` will may cause issues.
I have a component declared in this way:
```js
const Row = styled.View`
    flex: 1;
    flex-direction: row;
    justify-content: space-between;
`;
```
It should render two different texts one on the left and one on the right inside a View inside a List.

## Expected Behavior
It will render correctly without any part of it being hidden by other components.

## Actual Behavior
It will loose its height causing to be hidden or partially hidden.
If you look at the code in the repository, I put a the exact component but not a styled one so:
```js
<View style={{ flex: 1, flexDirection: 'row', justifyContent: 'space-between' }}>...</View>
```
and it renders correctly.
Just below this line I have my `<Row>...</Row>` component and it ends up cut as you can see in the image preview in the repository.
The exact structure of my code example is this:
```js
  <View style={{ borderBottomWidth: 1 }}>
    <View style={{ flex: 1, flexDirection: 'row', justifyContent: 'space-between' }}>
      <Text>{rowData.name}</Text>
      <Text>{rowData.date}</Text>
    </View>
    <Row>
      <Text>{rowData.name}</Text>
      <Text>{rowData.date}</Text>
    </Row>
    <Text>{rowData.body}</Text>
  </View>
```
What's the difference between my `Row` component and a `View` with the same style then?

**Comment by dbertella** [comment]
Further information about that. If I set `flex: 0` the `Row` component seems to render well.
I even have a weirder behaviour in my real app.
As you can see in the gif every line of the list should be the same, but in the first 10 lines the `Row` component disappear after the initial render, in the last two or three it stays there. In this case the `Row` contains the word POP and the time ago.
![styled-component-bug](https://cloud.githubusercontent.com/assets/2563196/22687762/3f7e9c9a-ed21-11e6-8be7-24f56a2a5404.gif)

**Comment by dbertella** [comment]
Follow up, I tried to make a snapshot test and this is what I get from the two components:
This is the "normal" `View` with style:
```js
<View
    style={
      Object {
        "flex": 1,
        "flexDirection": "row",
        "justifyContent": "space-between",
      }
    } />
```
This is the styled `Row` component
```js
  <View
    style={
      Array [
        Object {
          "flexBasis": 0,
          "flexDirection": "row",
          "flexGrow": 1,
          "flexShrink": 1,
          "justifyContent": "space-between",
        },
        undefined,
      ]
    } />
```

Basically I've found out that `flexShrink` is what it's causing the bug. Could it be a wrong wrap between styled component style and the rn-style then?

**Comment by mxstbr** [comment]
> Could it be a wrong wrap between styled component style and the rn-style then?

@jacobp100?

**Comment by jacobp100** [comment]
`flex` is a shorthand for `flex-grow`, `flex-shrink` and `flex-basis`.

You either want `flex: 1 0` or `flex-grow: 1`.

**Comment by dbertella** [comment]
Is it suppose to be like that then? I think in this case for the RN side it's not a shorthand, it suppose to stay as it is. 
You can see it yourself from the snapshot test.
From the RN documentation:
> ... and the flex parameter only supporting a single number.

I see your point in trying to stick with the css for the web, but in this case it will lead to unexpected behaviours in my opinion.

**Comment by jacobp100** [comment]
I didn't realise the `flex` value was so different from CSS.

> In React Native flex does not work the same way that it does in CSS. flex is a number rather than a string, and it works according to the css-layout library at https://github.com/facebook/css-layout.
>
> When flex is a positive number, it makes the component flexible and it will be sized proportional to its flex value. So a component with flex set to 2 will take twice the space as a component with flex set to 1.
>
> When flex is 0, the component is sized according to width and height and it is inflexible.
>
> When flex is -1, the component is normally sized according width and height. However, if there's not enough space, the component will shrink to its minWidth and minHeight.
>
> flexGrow, flexShrink, and flexBasis work the same as in CSS.

You're right that this will confuse people. This may have caused breakages when we introduced it, but reverting it may also cause breakages (@mxstbr). I'm slightly hesitant about reverting, because this is the first bug report on this. Whatever we choose, this needs to be documented.

When they added the `-grow`, `-shrink` and `-basis` properties, they did not mention intent to deprecate the `flex` property. However, while Yoga (formerly css-layout) supports this flex property, it does not document it. It seems like this is not a property you'd want to use in new code.

In v2, I feel like the right direction to go is to move away from this property and use the shorthand for `flex`. But I'd like to find out more about the intended future and use-cases of the current property before deciding on this.

Possibly beside the point now, but I looked at your example in more detail. Do you actually want `flex` defined at all? You didn't specify a `flex-direction` on the parent, so this defaults to `column`, meaning the child view is resized vertically. I think this is what you're seeing.

**Comment by dbertella** [comment]
Thanks for looking into it! I think you are right and this library should be as possible as close to the web css so it might just needed a bit of documentation. In my specific case I solved using flex={0} but I wanted to understand what was the difference between the two components.

My use case it's more large then the example because I use always the same component and I pass props to use it in different part of the app. 
So sometimes I don't really need to specify the flex property as this time apparently but it will fallback to `flex: 1` where is not specified.
Something like this:
```
const Container = styled.View`
    flex: ${({ flex }) => flex || 1};
    flex-direction: ${({ direction }) => direction || 'column'};
    justify-content: ${({ justify }) => justify || 'flex-start'};
    align-items: ${({ align }) => align || 'stretch'};
    margin: ${({ m }) => m || 0};
    padding: ${({ p }) => p || 0};
`;
```
I have actually another question, but it's not related to the specific issue.
Using a styled-component as mention above in RN can lead to some performance problem in your opinion?
I know the stylesheet Object is heavily cached, and I think styled-component will use it at some point, am I right?
What about passing props at runtime? What's going to happen? 
Because I'm really happy using this component it's really fast to prototype, but if it can be a problem I will find another solution.
Thanks again anyway!

**Comment by jacobp100** [comment]
## On Topic (for Max)

We still need to,

* Decide if the `flex` shorthand should be reverted to RN's `flex` property
    * I think we should keep the shorthand
* Document the decision we make

## Perf Question

I'll answer the question here, but if you want to continue, please open up another issue!

I'm don't think anything has been benchmarked, but it's something I'd like to see. Most of the time spent in styled-components will be parsing, but I don't think we know how much time is spent here.

In RN, every time your props change in a way that changes the CSS text, it gets re-parsed. This is probably negligible for a single component. However, when you load the app, you'll have to parse CSS for every component that gets mounted. If you have a global theme and change a value, that'll trigger a large re-parse for every component that depends on the theme.

If you're concerned about perf, you can set the default styles with styled-components, and override the styles in the `style` property.

```js
const ContainerDefaults = styled.View`
    flex: 1;
    flex-direction: column;
    ...
`;

const Container = ({ flex, direction ... }) => (
    <ContainerDefaults style={{ flex, direction ... }} />
);
```

This will only require one parse, no matter what styles you pass in.

If you want to eliminate the parse time, you can look at my [almost identical project](https://github.com/jacobp100/cssta). It's more limited in what you can do, but I think the limitations are a good thing!

**Comment by dbertella** [comment]
Wow, thank you very much for the complete answer, do you think it will be worthy to open a discussion about it in another issue or something? We can maybe add some benchmark, that should be very interesting from my point of view.

**Comment by jacobp100** [comment]
Please do!

**Comment by mxstbr** [comment]
> I think we should keep the shorthand

Why? Won't that be confusing for everybody picking up styled-components coming from ReactNative?

**Comment by jacobp100** [comment]
I think if we say we support shorthands, and `flex` is a shorthand, then not using the shorthand would be equally confusing—hence we need to document the decision we make.

I think that in most cases, people won't notice we use the shorthand instead. This is the first bug report on this, but in this case, using RN's `flex` property instead of the shorthand was not the solution.

**Comment by emusgrave** [comment]
+1 for documenting this, regardless of the decision on what the proper behavior is. 

I am new to both React Native and Styled-Components, and the `flex: 1` property tripped me up because it is clearly documented on the RN side as being a major difference between React and RN. I never expected that this:
```javascript
const StyledView = styled.View`
    flex: 1;
`;
```
would result in this: 
```javascript
style={
  flexGrow: 1,
  flexShrink: 1,
  flexBasis: 0, // shouldn't this default to `auto`?
}
```
My expectation was that `flex: 1` was going to transfer directly with no translation.

My plan is to drop the use of `flex` altogether and stick to explicitly setting the other 3 parameters.

**Comment by jacobp100** [comment]
It looks like we never got a conclusion on whether to continue to use the flex shorthand. I think it is the right thing to do, but we should have documentation on this (any takers?)

In terms of `flexBasis`, if you use the flex shorthand and omit the flex-basis, it defaults to zero ([relevant part in spec](https://drafts.csswg.org/css-flexbox-1/#valdef-flex-flex-basis)).

**Comment by philpl** [comment]
@jacobp100 I propose we just add some notes to the React Native section of the website. We had that issue on `border` as well, and while there's no definitive solution on either, an entry to the docs would clarify this issue

**Comment by jacobp100** [comment]
I agree! I'll try and find some time to do this!

**Comment by caffodian** [comment]
This seems to apply to use of the styled primitives stuff we have too, which was fun to run into and debug.  Reading this issue helped me understand what was happening

**Comment by mxstbr** [comment]
Closing in favor of https://github.com/styled-components/styled-components-website/issues/182, would love if somebody could add that note to the docs!

**Comment by ralph-dev** [comment]
HOLY I WAS STUCK ON THIS BUG FOR 4 HOURS!!!

**Comment by ralph-dev** [comment]
Someone needs to make a warning that React Native Flex: 1 Does not convert to Styled Components as Flex: 1 but rather Flex: 1 0 (Styled) == Flex: 1 (React Native). :'(

**Comment by jacobp100** [comment]
Sorry about that! I’m not really sure what the best approach is. RN has the CSS defaults for flex grow, shrink, and basis. It’s just that the RN flex prop sets all of these values in a way different from CSS’s flex prop.

I’m not sure we can really warn about this, but we could definitely document it more obviously!

**Comment by jacobp100** [comment]
Would https://github.com/styled-components/styled-components-website/pull/291 have helped you?

**Comment by ralph-dev** [comment]
Hi @jacobp100,

Wow, thanks for the prompt response that's amazing. So yeah as I was searching for the mistake I checked the React Native section of Styled. But I would suggest implementing this for RN -> Styled Inconsistencies.

React Native
-> Flex Section
-> Pixels Section
-> A Section for Each error that the community has come across.

Have sections or at least an appendix can make finding the correct issue much quicker than scrolling through the whole page for a small warning tag. Also maybe citing the CSS official rules as Styled is referencing it might also teach developers WHY it's happening like this and that it's a standard rather than a custom implementation detail by the Styled Components Community.

**Comment by kumarpatel** [comment]
@jacobp100

Is there any way to opt out of this translation for specific styles like flex in this case. (I sifted through some code but couldn't find it. Thought I'd ask to be sure.)

[css-to-react-native's transform api](https://github.com/styled-components/css-to-react-native#api) has a second argument that can be used to opt-out.
Is there anyway to trigger/access this during creation of a Styled Component, for example 

```
styled(View, {transformOptout: ['flex']})`
   flex: 1
`
```
