### ISSUE TITLE
export 'withTheme' was not found in 'styled-components'

### ISSUE THREAD

**Issue by rhysburnie** [styled-components/styled-components#483]
Hi,

Im getting `export 'withTheme' was not found in 'styled-components'` when I attempt to load `withTheme`.

i.e. this fails `import styled, { withTheme } from 'styled-components';`

I can only get it to work when I point directly to the following path:

`import styled, { withTheme } from 'styled-components/lib/index';`

It seems to be when its loading from the .es.js version in dist, which is strange because a search for `widthTheme` shows that it is in the export list.

for now I'll have to alias to `'styled-components/lib/index'`

I was on an older version but then updated to `2.0.0-3` same issue - cheers

**Comment by mxstbr** [comment]
That's super weird. Are you using webpack?

**Comment by rhysburnie** [comment]
Yes using webpack 2

**Comment by mxstbr** [comment]
Possibly an issue with our build setup then, something with the `.es` build?

**Comment by brunolemos** [comment]
Hi @rhysburnie, I believe it's not a bug on our end, but probably on your webpack config, like Max said. Doesn't it happen with other packages? Only `styled-components`?

1. I tested with `styled-components@v2.0.0-4` from npm and it worked fine
2. I tested with `styled-components.es.js` dist file and it worked fine

I'm using [create-react-app](https://github.com/facebookincubator/create-react-app) instead of a custom webpack config.
Have you considered using it?

**Comment by mxstbr** [comment]
> actually it had a 'path' is not defined

Oh no, that's ugly! Could you open an issue for that?

**Comment by JohnLouderback** [comment]
`withTheme` is also missing from the Typescript definitions as well

**Comment by patrick91** [comment]
working on it :)

**Comment by mxstbr** [comment]
Done, coming in the next release!
