### ISSUE TITLE
Override library CSS (React Semantic UI)

### ISSUE THREAD

**Issue by arthurvi** [styled-components/styled-components#501]
Cool lib!
We're using [React Semantic UI](http://react.semantic-ui.com) and we want to use Styled components to override the styles. 

React Semantic UI makes a component like `<Card className="ui card inverted" />`. The selector they are using then is `.ui.card.inverted`. When we add styled components, the component becomes `<Card className="ui card inverted STYLED-COMPONENT-ID" />`. 

The problem here is that the React Semantic UI css rules "win", because they are more specific. 
Is there anything we can do to make the Styled Components CSS "win"?

**Comment by k15a** [comment]
The simplest but not so clean solution would be to append !important to every rule. You could also bump specificity of styled-components with
```JS
const styled = styled.div`
  &&& {
    // You rules
  }
`
```
This should work because your selector would be `.STYLED-COMPONENT-ID.STYLED-COMPONENT-ID.STYLED-COMPONENT-ID` and has the same specificity as React Semantic UI.

**Comment by arthurvi** [comment]
Cool, thanks. Will try that :)

**Comment by cbroberg** [comment]
We are about to decide whether to use Semantic UI in a ReactJS framework and truly love Styled Components. So my question is:
 
Did it work @arthurvi ?

Thanks in advance.

**Comment by philpl** [comment]
@cbroberg It ought to have worked, since this is clearly a specificity issue, that we've seen with a lot of third party css frameworks unfortunately :/

**Comment by geelen** [comment]
You can always add more `&`s too. If only `!` was a valid char for a function name in JS like it is in Ruby. You could write: `styled.div!!!!` to let existing CSS know you mean business 😜 

If you're ever in doubt about specificity (the `&` trick above won't work if you have ID selectors in existing CSS), https://specificity.keegan.st/ is great.

**Comment by Kaisaurus** [comment]
I've played around and using !important seems to be the only things helping to override the semantic UI styles. Any advice on how to get a better method working?

At the moment I am using the following method:
```
import styled from 'styled-components'

const CustomLabel = styled.label`
  font-size: 6em !important;
`

<CustomLabel>What if I</CustomLabel>
```

**Comment by mxstbr** [comment]
@GGAlanSmithee recently added FAQ entries about this topic to our documentation, see here please: https://www.styled-components.com/docs/faqs#how-can-i-override-styles-with-higher-specificity

**Comment by piyushkathayat** [comment]
@Kaisaurus I am also having the same issue. Let me know if you find any better way to style @https://react.semantic-ui.com/

**Comment by Kaisaurus** [comment]
For me the method in the FAQ worked best

```
const TitleHeader = styled(Header)`
  &&& {
    font-size: 1.8rem;
  }
`
```
(as I side note, I didn't figure out how to use site.variables in a create-react-app project yet, if someone is familiar with this I would be incredibly grateful if you could leave an answer on [this stack overflow question](https://stackoverflow.com/questions/48304441/semantic-ui-react-how-to-theme-using-less-variables-in-a-create-react-app-proje/48381901?noredirect=1#comment83760643_48381901))

**Comment by GGAlanSmithee** [comment]
@mxstbr @philpl - just a thought - for postcss, there are plugins which automatically repeats classes n times, see https://github.com/johnotander/postcss-class-repeat as an example.

Could the styled-components bagel plugin do something like this (with a setting)?

**Comment by RevolutionParts-Justin** [comment]
This solution worked perfectly for me. Great solution @k15a. More flexible than !important, but it gets the job done.

const Styledbutton = styled(Button)`
  &&& {
      font-size: 1rem;
   } 
`;

**Comment by mxstbr** [comment]
There's a Babel plugin that does this automatically for you now! https://github.com/QuickBase/babel-plugin-styled-components-css-namespace

**Comment by rivertam** [comment]
A lot of times Semantic UI has specificity that's greater than what the `&&&` solution can offer. For example, when styling menu components, the items will include contexts and pseudoselectors, which I believe doing `&&&` basically can't do anything about. This is generally an issue with CSS/Semantic UI, not with styled-components, but, for what it's worth, I don't know that I'd recommend using Semantic (or any framework like it) with styled-components.

Does anyone know of any frameworks that use styled-components internally in such a way that they are easier to override using `.extend` and theme providers?

**Comment by probablyup** [comment]
I think this prospective feature could help with that scenario: https://github.com/styled-components/styled-components/issues/1789

**Comment by xargr** [comment]
My temporary solution works fine:
```javascript
const Anchor = styled.span`
  a {
    color: black;
    font-weight: bold;
    cursor: pointer;
    font-size: 1.2em;
  }
`;
```
but it's wrong because generate all the time new span element

**Comment by notflip** [comment]
It feels strange that this is so hard to achieve using a component for React, don't we all extend the component in some way? Is theming an option?

**Comment by airtonix** [comment]
ugh. wish semantic-ui just used BEM to begin with, this wouldn't even be a problem then.

**Comment by iweurman** [comment]
For me Semantic UI React goes very well with Styled Components.
In my case I only use the semantic-ui-react for components, I dont use the Semantic styles.
E.g. when the Semantic Dropdown is active you can still use that classes.
e.g.:

```
const StyledDropdown = styled(Dropdown)`
  background: #000;
  padding: 10px;
  &.active {
   background: #f0f0f0;
 }
`
```

In some cases you can even use your own props, so you don't need the Semantic classes e.g.:

```
StyledSidebar = styled(Sidebar)`
  display: ${ props => props.visible ? 'block' : 'none' };
`
```
// isVisible, some state boolean.. ?
```
render (
  <StyledSidebar visible={ isVisible } ></StyledSidebar>
)
```

In this case we don't use the built in Semantic active class, but just toggle the display style.

**Comment by iweurman** [comment]
Hi, One thing you could do, is not use the semantic ui style dependency, which I prefer.. But I don't know how big your project is.
So basically I'm trying to say, just use the semantic components only for their functional purpose.

Other way you can try is to override it like this:

const MyStyledComponent = styled(InlineStyledComponent)`
  &[style] {
    font-size: 12px !important;
    color: blue !important;
  }
`

instead of &&& using &[style]

Regards
________________________________
Van: Ignacio Giagante <notifications@github.com>
Verzonden: woensdag 24 juli 2019 23:22
Aan: styled-components/styled-components <styled-components@noreply.github.com>
CC: iweurman <iweurman@outlook.com>; Comment <comment@noreply.github.com>
Onderwerp: Re: [styled-components/styled-components] Override library CSS (React Semantic UI) (#501)


Hi. I'm having an issue with Semantic UI & Styled-components. Basically, I think Semantic-ui overrides the styles added using &&&. It does not work. Any idea?

[semantic-ui-styled-components]<https://user-images.githubusercontent.com/3419609/61834936-2e5d6480-ae50-11e9-8998-07cc53da1b98.png>

Component & Form

import { Dropdown } from 'semantic-ui-react'
import Chevron from './assets/right-thin-chevron.png'

export const DropdownStyled = styled(Dropdown)`
  &&& {
    display: 'inline-block';
    font-Family: 'Helvetica';
    font-Style: 'italic';
    font-Weight: '300';
    font-Size: '20px';
    line-Height: '23px';
    color: '#BCB4B4';
    padding: '.6em 1.4em .5em .8em';
    width: '100%';
    max-width: '100%';
    box-sizing: 'border-box';
    margin: '0';
    border: '1px solid #AC8B13';
    border-radius: '4px';
    background-color: 'white';
    background-image: 'url(${Chevron})';
    background-repeat: 'no-repeat, repeat';
    background-position: 'right .7em top 50%, 0 0';
    background-size: '.65em auto, 100%';
    appearance: 'none';
  }
`;


import React from 'react'
import { Button, Checkbox, Form } from 'semantic-ui-react'
import { DropdownStyled } from './style'

const options = [
  { key: 1, text: 'Choice 1', value: 1 },
  { key: 2, text: 'Choice 2', value: 2 },
  { key: 3, text: 'Choice 3', value: 3 }
]

const FormExampleForm = () => (
  <Form>
    <Form.Field>
      <label>First Name</label>
      <input placeholder='First Name' />
    </Form.Field>
    <Form.Field>
      <label>Last Name</label>
      <input placeholder='Last Name' />
    </Form.Field>
    <Form.Field>
      <Checkbox label='I agree to the Terms and Conditions' />
    </Form.Field>
    <Form.Field>
      <DropdownStyled placeholder='Bezel' options={options} selection fluid />
    </Form.Field>
    <Button type='submit'>Submit</Button>
  </Form>
)

export default FormExampleForm```

**Comment by Hilltop-norman** [comment]
https://csser.space/questions/avoid-prolonging-lines-in-react-styled-components



Here’s a fresh perspective
