### ISSUE TITLE
How to tell a component to inject it's css at the end

### ISSUE THREAD

**Issue by kopax** [styled-components/styled-components#520]
I have created a component that inject all my CSS utilities, this component wrap my application like this : 

```jsx
    <Provider store={store}>
      <LanguageProvider messages={messages}>
        <BootstrapProvider
          utils={{
            align: true,
            background: true,
            border: true,
            clearfix: true,
            display: true,
            flex: true,
            float: true,
            position: true,
            screenreaders: true,
            sizing: true,
            spacing: true,
            text: true,
            visibility: true,
          }}
        >
          <Router
            history={history}
            routes={rootRoute}
            onUpdate={hashLinkScroll}
            render={
              applyRouterMiddleware(useScroll())
            }
          />
        </BootstrapProvider>
      </LanguageProvider>
    </Provider>,
```

I only use `injectGlobal` for settings the __html__ and __body__ for the font.

I have noticed that the css of this component is injected before all overs in the html.

This make my utility less prioritized. I want to add them at the end, is there a chance to see this in a future version ?

The only fix I have for the CSS is to use `!important` which is not recommended.

**Comment by GGAlanSmithee** [comment]
@kopax see https://github.com/styled-components/styled-components/issues/293, https://github.com/react-boilerplate/react-boilerplate/issues/1589 and https://github.com/webpack/webpack/issues/215

As you can see in the linked issues, the problem is with webpack not being able to ensure the order of CSS inclusion. I think the recommended way for now is to statically add any vendor CSS in your HTML to ensure it's included before styled components. I realize this doesn't play well with your current solution, but AFAIK, there is no other way atm. (except the usage of `!important` or any other method that makes the specificity higher).

**Comment by diondiondion** [comment]
> The only fix I have for the CSS is to use !important which is not recommended.

It's perfectly fine for utilties. (See https://csswizardry.com/2016/05/the-importance-of-important/#forcing-immutability-with-important)

**Comment by kopax** [comment]
@diondiondion I rather use `!important` on the last layer of css.

@mxstbr would it be possible to see this feature one day, or does it purely depend on webpack ?

**Comment by jacobp100** [comment]
It's not really related to webpack. Styles are injected when the component is mounted. Also, if you have dynamic styles,

```js
styled.div`
  color: ${props => props.color};
`
```

you'll generate new styles every time the `color` prop changes. Every time you inject styles, they're injected at the end. There's no real way to control the order in styled-components.

If `!important` on your utility classes fixes it for you, don't feel bad! [Bootstrap](https://github.com/twbs/bootstrap/blob/v4-dev/scss/utilities/_spacing.scss) and [CSS Wizardry](http://www.gpmd.co.uk/blog/scalable-css/) (to name a few) all think this is the way to go—you’re using them to override default styles!

**Comment by mxstbr** [comment]
Yeah to control that would mean to break `styled-components`, we sadly cannot allow you to do that I'm afraid 😕 Because you're rendering `BootstrapProvider` as the first styled component in the entire app, we inject its CSS first, which is why its at the top.

If we removed that behaviour there'd be a lot of ordering bugs based on the fact that your CSS code will change based on where and when you render your components, which is incredibly frustrating and hard to debug, so there's no way we'll allow that in the future. Sorry!

**Comment by kopax** [comment]
@mxstbr from tech to tech, how hard would it bo to implement it on a fork ?

**Comment by kopax** [comment]
@mxstbr I am not asking to remove that behavior, but if it's possible to add it as an extended features for some component. If it's used wisely, this can be a powerful feature.

For example using 

```jsx
const MyWrapper = styled.div`
   & .fixed-top { position: fixed; top: 0; }
`
MyWrapper.styleOrdering = 0; 
```

This of course doesn't have to be enabled by default but will allow developers to customize the dependency injection of their components.

I don't even know if it's possible and how hard would it be, would you mind sharing a more technical explanation.
