### ISSUE TITLE
[V2] CSS transitions are ignored because of class swapping

### ISSUE THREAD

**Issue by wardpeet** [styled-components/styled-components#526]
## Version
2.0.0-4

## Reproduction
http://www.webpackbin.com/N1Wg2dDYM

## Steps to reproduce
Setup a component inside render

## Expected Behavior
Should append these classes so the animation stays active. Now react swaps the components I believe

## Actual Behavior
It rerenders the component with new classNames instead of modifying them.

**Comment by jacobp100** [comment]
I think this is actually more React than styled-components.

If you have a child that is a `ComponentA`, and you change it to a `ComponentB`, the first component is unmounted and the new component is mounted.

Because you're creating a new `Box` component in every time you render, you're effectively changing the component each time. Each time it's unmounting and remounting a new button, so you don't get any animations!

The fix is just to move `Box` outside the render method!
