### ISSUE TITLE
Styled components seems not pass onTouchTap prop in basic tags

### ISSUE THREAD

**Issue by ShinyLeee** [styled-components/styled-components#527]
## Version
1.4.3

## Reproduction
http://www.webpackbin.com/4JNcGFDKG

## Steps to reproduce
Click 4 anchor tags.

## Expected Behavior
All anchor tag show alert message box after touchTap or click.

## Actual Behavior
The first anchor tag not show alert.

## Description
In this reproduction, seems only basic tags can not receive onTouchTap prop.
I am new to styled-components, so if there is something I lost, please tell me.
Thanks!

**Comment by jacobp100** [comment]
Looking into it, this is a non-standard event that is monkey patched into tags via [react-tap-event-plugin](https://github.com/zilverline/react-tap-event-plugin). We [filter out non-standard attributes for html elements](https://github.com/styled-components/styled-components/blob/master/src/utils/validAttr.js). But I think it would be wrong to add this to that list.

This is ultimately caused by the same underlying issue that is effecting #403.

If you need a (hacky) workaround, you can do the following,

```js
const A = (props) => <a {...props} />
const StyledLink = styled(A)`
  color: red;
`

<StyledLink onTouchTap={...}>This should work</StyledLink>
```

**Comment by ShinyLeee** [comment]
Thanks for your reply, I think the workaround is more suitable in this case after find out the reason.

**Comment by jacobp100** [comment]
Moving discussion to #439

**Comment by plankguy** [comment]
I noticed that new [React 16.4.0 pointer events](https://reactjs.org/blog/2018/05/23/react-v-16-4.html#pointer-events) aren't in the "[non-standard attribute](https://github.com/styled-components/styled-components/blob/master/src/utils/validAttr.js)" regex mentioned above. Are there plans to add these in a future release?

**Comment by plankguy** [comment]
@probablyup Done: https://github.com/styled-components/styled-components/pull/1790
