### ISSUE TITLE
Ability to flush and rebuild styles in the browser on demand

### ISSUE THREAD

**Issue by jahglow** [styled-components/styled-components#568]
Hi, 
We're trying to use styled-components in our big-scale production web-app that helps create dashboards, so there arose a question of allowing users change color-scheme and see changes in the view as they type in colors. One of the issues is that whenever a value changes (for instance primaryColor in theme) every of the hundreds or React components on the page that used it have styles swapped and the styles are added to the HEAD. If the user keeps playing with the values that makes the STYLE tag grow to immense size and having 20-ish properties to change in colors multiplied by a number of iterations makes Chrome tab consume >300Mb of memory (from a benchmark we created by randomly generating property value _n_ times). Can you provide an opt-in way to `.flush()` the style tag programmatically and re-render the styles for the whole app (as it's done for the first paint)?

**Comment by griffinmichl** [comment]
Signed! This is the first way I tried to play with styled-components tonight (<ThemeProvider /> connected to a redux store w. some user-defined styles). I ended up with an enormous amount of styles.

Loving styled-components otherwise.

**Comment by mxstbr** [comment]
This seems reasonable, what do you think @geelen? Why don't we do this already?

**Comment by geelen** [comment]
No reason! Never considered this as a use-case, tbh—was always happy for the theme to have control over properties but if someone is grabbing a slider then yeah that's going to be an issue.

With `v2` you can make it so certain properties target the `style` attribute instead of generating classes. Do you think that would be sufficient?

Not documented yet but if you look at #365 and try `styled-components@next` you might be able to solve the issue straight away.

But yeah, I see no problem adding a hook to clear out the existing styles and re-render from scratch, if it's needed.

**Comment by jahglow** [comment]
Well, the general reason of this accumulation is basically lack of separation between static styles and dynamically defined (props/theme dependent) styles. As I'd see it, there has to be a mechanism that takes the array produced by the template string broken by variables and does a search in each item to the previous semicolon and pushes the chunk into the static styles of the class. The second part of the string after the semicolon belongs to the dynamic style property. In the end of the day each class that has inclusions of dynamically defined properties has to assign two `className`s to an element: the static styles class and the dynamic styles class. Thus when properties change and you decide to generate new classNames you don't copy the static styles over and over again. From my experience the style that is dynamic due to theming or properties amounts to 10-20% of styles, but we do manage to copy the other 80-90% along to the new className. I can't see a reason for that. from first paint performance standpoint that might be not the best ever solution but for the second and following generation that is a browser performance issue. To avoid the overhead we need to keep our static styles in PostCSS or SASS and dynamic in styled components to generate themes on the hoof. But that is the worst imaginable trade-off from developer's experience standpoint

**Comment by RomanGotsiy** [comment]
Hey, is there any news? Maybe it is already possible to do in the latest `styled-components`?

I have exactly the same use case as @jahglow.

**Comment by kitten** [comment]
This isn't supported and likely won't be accepted. This issue is pretty stale and inactive. That said, with the `StyleSheetManager` and by creating sheets manually this is kind of supported now, if some extra code isn't an issue. https://github.com/styled-components/styled-components/blob/d96101a102b59a8f9ac4b6f278594674897282bb/packages/styled-components/src/sheet/Sheet.ts#L72-L74
