### ISSUE TITLE
[Question] Output inline styles

### ISSUE THREAD

**Issue by Andreyco** [styled-components/styled-components#579]
## Version
v2

## Expected Behavior
Opt in for inline styles output.

## Actual Behavior
Styles are exported as global css.

Having possibility to opt-in/configure SC to output inline styles would allow us to reuse components in email templates.

**Comment by eric-burel** [comment]
This would also allow to have styled-component to always override other global styles.

So far there are still a lot of interferences, with webpack for example, because we can't guarantee css files order. SC is often loaded _before_ other imported global stylesheets (from 3rd party for example), and thus it is overriden. Having the possibility to opt in for inline style would guarantee a priority to SC.

**Comment by mxstbr** [comment]
We do not want any configuration inside of the main `styled-components` package. That being said we'd be happy to support you in building `styled-components-email` by giving you access to all internals and hosting it under the `styled-components` org if you want to dig in!

**Comment by Andreyco** [comment]
@mxstbr sound reasonable. Creating separate package is way to go. Got some interesting ideas, e.g. allowing "email safe" style properties, ...

Will dig into code repo & setup some POC

**Comment by philpl** [comment]
@Andreyco You can ask Kent if he's open to add this feature to glamorous, since they're already using object-style CSS https://github.com/kentcdodds/glamorous

**Comment by grady-lad** [comment]
@Andreyco By any chance did you get anywhere this? If not @mxstbr if you guys are still open to supporting `styled-components-email` any suggestions on how get setup using the internals to build an initial POC?
