### ISSUE TITLE
Doesn't play well with rapscallion

### ISSUE THREAD

**Issue by siddharthkp** [styled-components/styled-components#600]
## Version
1.4.4 (also tried on 2.0.0-7)

## Reproduction

Have made the smallest reproducible chunk here: [siddharthkp/styled-components-rapscallion](https://github.com/siddharthkp/styled-components-rapscallion)

## Steps to reproduce
Create a simple component: 

```js
const Text = styled.div`
  color: red;
`
const MyComponent = () => <Text>hello</Text>
```

Trying to render this with rapscallion's render methods

```js
render(<MyComponent/>).toPromise()
.then(htmlString => console.log(htmlString));
```

## Actual Behavior

Getting the [error shown here](https://github.com/siddharthkp/styled-components-rapscallion)

**Comment by siddharthkp** [comment]
@oliviertassinari Do you have any insights here?

**Comment by oliviertassinari** [comment]
Aside from suggesting using another styling solution, I don't. I have never been using styled-components on a real project. Sorry.

**Comment by philpl** [comment]
So the line that is creating a component instance in rapscallion is this one in `traverse.js`:



I've seen the cause of this before, but didn't fix it, since it hasn't caused any issues until now. It's the StyledComponent itself. Its constructor has a minor flaw:

```diff
-     constructor() {
-       super()
+     constructor(props, context) {
+       super(props, context)
```

I'll open two PRs (v1 & v2) for this asap. Thanks for reporting! :+1:

**Comment by siddharthkp** [comment]
@philpl Whoa, that was super fast!

Thanks!

**Comment by siddharthkp** [comment]
@philpl patch release?

**Comment by philpl** [comment]
No worries! Regarding the release, that will have to be taken care of by @mxstbr and @geelen. 😉

**Comment by geelen** [comment]
I can push a `v2` prerelease right now if you like? I haven't really been looking at the `1.0` stuff lately I don't wanna tread on max's toes at all.

**Comment by geelen** [comment]
Done. `v2.0.0-8` released with this patch.

**Comment by mxstbr** [comment]
I don't have time to push out a release right now, feel free to do it. I haven't been looking at v1 for a while either!

**Comment by siddharthkp** [comment]
@philpl Not sure if the problem was fully solved. Stream doesn't work.

Reproduced here: https://github.com/siddharthkp/styled-components-rapscallion

**Comment by philpl** [comment]
@siddarthkp we figured out that to actually make this work we'll need a style provider to hold an encapsulated stylesheet. Cc @geelen

**Comment by siddharthkp** [comment]
Sorry for bringing this up again, do you think streaming is possible with v2?

Ran into: https://sc-next-docs.philpl.com/docs/advanced#server-side-rendering

**Comment by geelen** [comment]
@siddharthkp don't be sorry, it's a good question!

It's... probably not going to be possible all that soon, no. The problem is ordering:

```js
const X = styled.div`
  a { color: inherit; }
  ${ props => props.black && css`
    a { color: black; }
  `
`

const Y = styled.div`
  a { color: blue; }
`

// First usage
<X>
  <Y>
    <a href="#">Link...</a>
  </Y>
<X>

// Second usage
<X black>
  <Y>
    <a href="#">Link...</a>
  </Y>
<X>
```

We do a bunch of work behind the scenes to make sure all of `X`s rules appear together and always above `Y`, regardless of when they're rendered. That's an order we will always guarantee, so you can freely use descendant tag selectors like this and you don't get yourself into trouble.

The only way to do that with streaming is to send down the current CSS with each chunk, regardless of what's been sent before. I suppose that's ok—you'd end up sending some rules multiple times, and be duplicating the rules many times over in the DOM, but it should _technically_ work.
