### ISSUE TITLE
File extension for styled-component

### ISSUE THREAD

**Issue by Lehakos** [styled-components/styled-components#606]
How about own file extension for styled-components? This would help to solve such problems as emmet support, syntax highlighting.

**Comment by k15a** [comment]
I don't like the idea of a new file extension because styled components isn't anything more then js.

**Comment by philpl** [comment]
I agree with @k15a, it's just js and doesn't need its own extension. Also, apart from this reason, creating new extensions is not a good idea ^^ Sorry

**Comment by mustofa-binary** [comment]
actually i kinda agree with having extension for styled components just for the sake of differentiating file extension from the others. in my project i separate function component with styled component, currently i just add a suffix xxx.style.js. However, its still hard to differentiate with my other js function component because my editor gave js icon instead of style icon.

**Comment by yashrajb** [comment]
I think this is a cool idea because it is becoming hard to differentiate between components js file and styled-components js file

**Comment by Iris-Ross** [comment]
I have an issue with intellisense and auto completion while using styled components'
