### ISSUE TITLE
Support inlining styles

### ISSUE THREAD

**Issue by tastycode** [styled-components/styled-components#632]
Styled-components is great. It's the approach that i'd like to use in several projects in react-native and web. The problem is, one of those projects involves a page written in react that gets rendered to an email. Best practices for email often involve inlining styles to support the wide variety of clients that render emails. I totally realize there's some irony in requesting that styled-components support this. At this point, i'm curious as to a workaround where i can obtain the list of props for a given styled component to pass into an inline style prop (obviously this wouldn't support media queries / hover etc... ). 

If styled-components supported this, projects that render their email through react would be able to use styled components for their emails. This is super important as a lot of work goes into creating reusable css components across an entire project, and its important that style-guide components are consistent through emails and the work that goes into creating these clean reusable components can be carried into the much more difficult landscape of email html rendering.

```JS
const EmailHeader=styled.div`
  margin-top: ${gap.large};
  ${type.mediumSize()};
  color: ${color.phantomGrey};
`

export default function({user}) => (
    <div> 
      <EmailHeader inlined>Welcome to homeward! {user.name}</EmailHeader>
   </div>
)

```

Another idea 
```javascript
const EmailHeader=css`
  margin-top: ${gap.large};
  ${type.mediumSize()};
  color: ${color.phantomGrey};
`

export default function({user}) => (
    <div> 
      <EmailHeader style={...EmailHeader.cssRules}>Welcome to homeward! {user.name}</EmailHeader>
   </div>
)
```

**Comment by mxstbr** [comment]
We don't want to add any configuration to `styled-components` for a variety of reasons. That being said, this does sound very useful.

I'm wondering, could we make this another package (`styled-components-email`?) which renders to inline styles rather than the DOM and then dynamically switch out the imports?

**Comment by geelen** [comment]
Personally, I think this sort of thing could be better handled as a separate tool, like [this one from Mailchimp](https://templates.mailchimp.com/resources/inline-css/).

**Comment by mxstbr** [comment]
Ohh that sounds like a great idea. Maybe a webpack plugin or something?

**Comment by weaintplastic** [comment]
just in case someone stumbles over this and is looking for a solution: We've built a little library for rendering inline css for emails in javascript/react. https://github.com/researchgate/inline-stylesheet

**Comment by dariuszpaluch** [comment]
@tastycode, @weaintplastic I think that a better solution would be to use this library: [inline-css](https://www.npmjs.com/package/inline-css).

**Comment by JamieYoung891** [comment]
I found a solution for you to grap styles from styled component and send it statically to email with HTML.

it's quite simple.

First, you make your component and styled components as you would.
Then, get the DOM elm you need.
Finally, get head elm and combine both!

Of course this wouldn't work for most builds, since styled-components is a dynamic styling technic which means, there's no style on head or dom as default. If you want to use this solution you have to config your build options. There's an option for styled-components in webpack, to build it into static, not dynamic. After configure this, it would work fine.

Yet, this would only work when you have this on server, since this only sends head with style sheet links, not actual css data. if you want to make it work on serverless, such as on an app or local web. You should write more logics to get those style data.

Although, this is not an ideal way for one to use in services, 'cause it's quite bulky with unnecessary style data request calls, but quite a simple solution for fast fix.

Hope someone find this and feel it usefull.

**Comment by BjoernRave** [comment]
This does the trick for me: 
```
import inlineCSS from 'inline-css'
import ReactDOMServer from 'react-dom/server'
import styled, { ServerStyleSheet, StyleSheetManager } from 'styled-components'

export default async function renderEmail(emailComponent) {
  const doctype =
    '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">'

  const sheet = new ServerStyleSheet()

  const html = ReactDOMServer.renderToStaticMarkup(
    <StyleSheetManager sheet={sheet.instance}>
      {emailComponent}
    </StyleSheetManager>
  )

  const inlinedHtml = await inlineCSS(doctype + sheet.getStyleTags() + html, {
    url: 'empty',
  })

  return inlinedHtml
}
```
