### ISSUE TITLE
How to use atnd components with styled-components 

### ISSUE THREAD

**Issue by Tzelon** [styled-components/styled-components#658]
Hey,
I'm trying to use atnd input component https://ant.design/components/input/ with styled-components
This is my code
```JS
import styled from 'styled-components';
import { Input } from 'antd';
const SearchInput = Input.Search;

const Search = styled(SearchInput)`
  width: 200px;
  background-color: red;

`;

export default Search;
```
But when I use the new search component I can't see the new styles, what I'm doing wrong ?

Thanks

**Comment by k15a** [comment]
They have to pass down the className so we can add a automatically generated className to the component. You should open an issue there so they pass down the className.

**Comment by Tzelon** [comment]
Can I do it manually for now ?

**Comment by k15a** [comment]
If you edit the source code of the Ant Design component yes. ;) But on our side we can't do any magic.

If you take a look at these two components:

```JS
const Search = () => <input type="search" />
const Search = (props) => <input type="search" className={props.className} />
```

The second one will work because it attaches the className from styled-components down to the element. But with the first one we don't have any chance to add the className to the element without some hacky dom manipulation.

**Comment by Tzelon** [comment]
Thanks for the quick replay and very good explanations
