### ISSUE TITLE
How to get the input(StyledComponent) value

### ISSUE THREAD

**Issue by sayll** [styled-components/styled-components#666]
## Version
1.4.4
## T _ T
![image](https://cloud.githubusercontent.com/assets/18632641/24819264/78145fe4-1c16-11e7-851c-1c7afd7842d7.png)

**Comment by k15a** [comment]
You need to use `innerRef` instead of `ref`.

**Comment by sayll** [comment]
thank.

**Comment by Swivelgames** [comment]
@k15a Can you be more specific?

**Comment by k15a** [comment]
I think the [docs](https://www.styled-components.com/docs/advanced#refs) can help you :)

**Comment by Swivelgames** [comment]
A link to the docs! Awesome! 😄 

After doing some Googling, it wasn't immediately apparent what `innerRef` was. But I did end up finding it after a little while sifting digging through the docs. Thanks @k15a!

**Comment by k15a** [comment]
Hey @Swivelgames,

you probably want to access the value of an input field or call some DOM methods like `.focus()`. In React you can access the corresponding DOM element of a React element with refs.

```js
class Form extends React.Component {
	focus = () => {
		// Call .focus() on our input field
		this.input.focus()
	}

	render() {
		return (
			<div>
				<input ref={node => (this.input = node)} />
				<button onClick={this.focus}>Focus the input field</button>
			</div>
		)
	}
}
```

The problem is that we can't forward the ref prop to the underlying component because it's already handled by React and set to the styled wrapper component. That's the reason you need to use `innerRef` because that's just a normal prop we can pass as the ref prop to your underlying component.

**Comment by philpl** [comment]
@Swivelgames:

> After doing some Googling, it wasn't immediately apparent what innerRef was. But I did end up finding it after a little while sifting digging through the docs.

Hiya, may I ask you what the problem is with the example in the docs? Or why you weren't able to find it? :smile: we're still working on refining them
