### ISSUE TITLE
Mounting many components – performance question.

### ISSUE THREAD

**Issue by derek-duncan** [styled-components/styled-components#705]
I've been using styled components for the last few months as the basis for a new app. It's been a great experience. However, as the app has grown, I've been noticing that the styled components are taking slightly longer to render than vanilla JSX, usually freezing the browser in the process 💅.

I've been trying to debug to find the bottlenecks, and styled components is appearing near the top of most Chrome profiles. When rendering lists of ~20 fairly large styled components, the browser freezes until they can mount. Thinking it was a performance bug in my code, I removed the presence of styled components to narrow down the bug, but the problem disappeared. The list loaded React-Fast™.

Most of the styling is handled with base components. e.g. `<Flex />`, `<Box />`, `<Text />` etc. These are styled-components that are setup to accepts props for most of the commonly used CSS properties. e.g. `position`, `display`, `border`, `background-color`, `color`, `flex`, etc. There are about 50 props like this that are accepted on each base component.

[I've created a replication on the issue in WebpackBin](https://www.webpackbin.com/bins/-Ki07F2JPWnEtsxlLjvD). I ported over my Base component factory to expose that code for any potential bottlenecks. The Bin is comparing two lists of 5K (scaled to demonstrate the performance) text rows, one built with styled components, and the other with vanilla jsx. When switching between lists or re rendering a list, try scrolling or interacting with the browser to see the browser lag.

What is going on with this performance lag? My theory is that when 💅 is inserting the styles, the browser forces a re-layout/paint. This is acceptable in minor cases, but seems to scale into a larger issue when there are many styled components mounted/unmounted/rendered at once. Would love some help on this one. Thanks.

**Comment by philpl** [comment]
@derek-duncan Styled Components really shouldn't be a bottleneck after numerous bugs around style-injection and micro-performance were squashed.

Are you using v1 or v2?

**Comment by derek-duncan** [comment]
@philpl gotcha. It seems like the bottlenecks are introduced when functions are used in the tagged template literal. The more you have, the slower the component performs. 
💅 v2.1

**Comment by philpl** [comment]
@derek-duncan I can't test your example unfortunately. It seems broken ;)

I'm wondering if it's just because every 1s you're executing up to (4 x (8 + 1) x 5000) functions. The amount of calls, together with GC pauses, could lead to it taking more than 16-30ms (30-60 FPS). Also remember that per styled component it might take 1ms anyway to rerender.

I'd love to have a look at the profile, but the bin is not working, as I've said :smile:

Btw there's an ongoing issue to improve perf here: https://github.com/styled-components/styled-components/issues/583

But it doesn't sound like the issues, we're discussing there, affect you much

**Comment by derek-duncan** [comment]
@philpl sorry about that... [should be working now.](https://www.webpackbin.com/bins/-Ki07F2JPWnEtsxlLjvD). Profile is pretty interesting to look at... somewhat indicates your theory 👌

**Comment by philpl** [comment]
@derek-duncan So three things you can do:

- Try this; I tried to optimise a couple of things: https://www.webpackbin.com/bins/-Ki0CuaI6IefP2OuPGaP
- Run your code in production, since that removes the React dev overhead (67% total in profile)
- Try our babel plugin with preprocessing enabled

This should remove a lot of overhead and make the update unnoticeable. I find it unrealistic to update 5000 elements at once anyway. Also, there are implementations for lazily rendered lists in React, which solve this as well.

**Comment by derek-duncan** [comment]
@philpl Good stuff, thanks.

I agree that a list of 5000 rows is unlikely. Even so, if styled components are heavily used, it's very likely ~1000 components could be mounted/unmounted at once when changing routes or just displaying a lot of data. I'm just concerned for the overall performance of an app as the number of styled-components on screen grows. 

React does have some problems mounting/unmounted large component trees, so I've been using [a HOC](https://gist.github.com/derek-duncan/a71a8c3f6bade9a4a5c988acb13d7c06) to help defer the rendering to the next animation frame. It's helped a lot with perceived performance, and FWIW, has helped loading complex styled components as well.

Cheers 💅

**Comment by philpl** [comment]
@derek-duncan I'd suggest to test real-world performance, in a production like environment instead, and try to keep your general-purpose components low and optimised.

General purpose components don't add a lot of value IMHO and can introduce hard to fix performance problems in a non-trivial way
