### ISSUE TITLE
Injecting styles in body without global

### ISSUE THREAD

**Issue by santaclauze** [styled-components/styled-components#730]
## Version
2.0.0-13

I have a situation where I am applying styling to a page. 

Can I directly inject css styles to the body in this page without applying them through `injectGlobal`?

Something like the following:
```jsx
const Cover = styled(CoverUnstyled)`
  body {
    height: 100%
  }
`;
```

**Comment by k15a** [comment]
That's not possible. What are you trying to do and why is `injectGlobal` inappropriate?

**Comment by santaclauze** [comment]
`injectGlobal` is inappropriate as I would like to add these css rules only in the body of this specific page rather than the whole project.

**Comment by k15a** [comment]
Probably the best thing you can do is to wrap you page around a Root component.

**Comment by geelen** [comment]
We could also do something like this:

```js
componentWillMount() {
  this.globals = injectGlobal` ... `
}

componentDidUnmount() {
  this.globals.remove()
}
```

Thoughts?

**Comment by probablyup** [comment]
I agree with @k15a about introducing that sort of scoping with a custom top-level styled component.

**Comment by geelen** [comment]
Yeah, generally I do too, but there was an example in another thread where the solution basically became to render a `<style>` tag with `dangerouslySetInnerHTML` because a top level component wasn't possible. injectGlobal currently doesn't return anything, so this might be worth adding anyway.

**Comment by k15a** [comment]
I think that would be a great addition ;)

**Comment by mxstbr** [comment]
I strongly feel like a top-level React component is the way to go here. Introducing another API just to solve one persons use case where a top-level component doesn't work seems weird to me, on top of not being able to imagine how that wouldn't work.

I'm going to close this for now since the question has been answered and I don't think we should add this to the library, if you feel strongly about `this.globals.remove()` feel free to comment again/reopen the issue.

**Comment by chhuang** [comment]
There've been many times that I needed to style something that is outside of the component depending on its props. An example would be a modal where the body tag needs to be 'locked' when the modal is visible.

My workaround for this:
```
  componentWillReceiveProps(props) {
    document.body.classList.toggle('is-locked', props.isVisible);
  }
```

And then in my `theme.js` which has the `injectGlobal`, do `body.is-locked { overflow: hidden; }`

What I'd like to do is:
```
const __Modal = styled.div`
  ${ props => props.isVisible && css`
    body { overflow: hidden; }
  `};
`;
```

**Comment by thysultan** [comment]
@chhuang Making use of the inverted `&` pattern you could do.

```scss
body:not(&) { overflow: hidden; }
```

Which can essentially be used as an inline global styling escape hatch :)

**Comment by chhuang** [comment]
What is this black magic?! Where can I learn more?

Thanks!

**Comment by chhuang** [comment]
Just found out that doing:

```
  ${ props => props.isVisible && css`
    body:not(&) { overflow: hidden; }
  `};
```

It only works when the props changes for the first time. It does not remove the rule on subsequent updates.

**Comment by pencilcheck** [comment]
Take a look at this example, I think if we can have ways to add multiple namespaces for the css content that each component uses, then we have a true global scoped stylesheet solution that is backward compatible with all traditional css libraries. https://github.com/zeit/next.js/pull/2638

**Comment by wmertens** [comment]
@geelen @mxstbr I think there is a good case here for having a react component that does the actual injecting (rendering `null`), removing the CSS when it is unmounted.

instead of 
```js
injectGlobal`...`
```

you'd do
```js
const GlobalStyle = styled.global`
… (including prop interpolation)
`
...
return (
  <App>
    <GlobalStyle darkBg={this.props.dark} />
    ...
  </App>
)
```

The only differences with regular styled components would be:
* renders `null`
* does not wrap the css with an own class

This way:
* Global styles can be easily modified via props
* It works without issues in SSR
* It's obvious what is happening

**Comment by wmertens** [comment]
No opinions for or against?

**Comment by oyeanuj** [comment]
@mxstbr @philpl Do you see @wmertens' suggestion above as a possible v3 solution? Or is the recommendation to do some either `injectGlobal` to `styled.body` for global body styles?

**Comment by export-mike** [comment]
I too recently had the need to add/remove global styles whilst a modal is visible,

I got around it with a few simple lines...

Thoughts suggestions? It un mounts as expected.
![image](https://user-images.githubusercontent.com/2983327/33054917-8b3a43dc-ced0-11e7-847a-c5bdda949d2b.png)

**Comment by wmertens** [comment]
React-helmet can also help in this case. But a nice global css component
would be better

**Comment by 9andresc** [comment]
If you only want to change the overflow-y property from body you could use this snippet which worked well for me in my render function:

```javascript
...
if (props.isVisible) {
  document.body.style.overflowY = 'hidden'
} else {
  document.body.style.overflowY = 'auto'
}
...
```

Hope it helps.

**Comment by oyeanuj** [comment]
I had a usecase recently where I felt the need for something like this: I am using `react-aria-modal` and like many other libraries, it either asks for styles to be passed inline as prop, or via a classname.
Now none of those ideally gel with SC, but since I am writing plain CSS and for ease of reuse, I was writing class based css rules. But since SC doesn't give you an option to just add that, the other option is to add them plainly globally. But that too has to be done in the initial `injectGlobal` since it seems like `injectGlobal` shouldn't be called more than once ideally.

Just wanted to put out another use-case (and I'd be curious to hear if there are better ways to achieve what I'm trying).

**Comment by mxstbr** [comment]
@oyeanuj 

```JS
import AriaModal from 'react-aria-modal'

const dialogClass = 'dialog';

const MyModal = styled(AriaModal).attrs({
  dialogClass,
})`
  .${dialogClass} {
    background: red;
  }
`
```

**Comment by oyeanuj** [comment]
@mxstbr That works well when the classname is being passed through (right?). But in the cases where it isn't, then the need for injecting global style comes in again :/ Another related case that I once ran into was when we need to style by an id of a component (again where classname wasn't being passed through).

**Comment by mxstbr** [comment]
```JS
const MyModal = styled(AriaModal)`
  #someid {
    color: blue;
  }

  .someClass {
    background: red;
  }
`
```

**Comment by wmertens** [comment]
@mxstbr I can't help but note the 9 thumbs-up on https://github.com/styled-components/styled-components/issues/730#issuecomment-320035959 … is that API really not on the table?

**Comment by mxstbr** [comment]
It's a lot more on the table with #1324, since that API would work super well with the global-styles-component. It'd also mean you could have the global styles respond to theming and update dynamically.

Definitely see the value in an API like that, would you mind opening a new issue about that?

**Comment by NathanielHill** [comment]
Is there a solution for targeting a parent element? Using the `attrs` method from #184 and #365, I am able to pass the _className_ prop to a styled react-modal but unable to get _overlayClassName_ working. Currently, I have to pass a global class to _overlayClassName_ and am unable to completely encapsulate the styling in my styled(Modal) component.

```
const className, overlayClassName = btoa(Math.random())
const StyledModal = styled(Modal).attrs({
  className,
  overlayClassName
})`
  &.${className} {
    background-color: ${props => props.theme.boxedViewBackground};
    padding: 2.4rem;
    text-align: center;
    width: 24rem;
  }
  .${overlayClassName} {
    align-items: center;
    display: flex;
    justify-content: center;
    height: 100vh;
    width: 100vw;
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background: transparent;
  }
`
```

**Comment by kitten** [comment]
@NathanielHill Hiya, please create a separate issue next time. Although multiple ones with similar questions have been created, this one is even more unrelated unfortunately.

The solution for complete isolation is relatively simple:

1. Don't generate your own `className`; We have one for you that is being passed down
2. Tie your `overlayClassName` to this generated `className` so it doesn't pollute other styles and is specific to a single component
3. (a little unrelated) Try not to generate a random class, since it'll React's break SSR rehydration

So all in all this will work:

```diff
-const className, overlayClassName = btoa(Math.random())
+const overlayClassName = 'modalOverlay'; // keep this constant

const StyledModal = styled(Modal).attrs({
-  className,
-  overlayClassName
+  overlayClassName // we pass a className prop down, so in this case there's no need for a custom one
})`
-  &.${className} {
-    width: 24rem;
-  }
+  width: 24rem; /* since this will be our generated className, we don't need to use a custom one (see above) */
+
-  .${overlayClassName} {
+  &.${overlayClassName} { /* tie this to the parent class (our generated one) so it doesn't pollute/affect other classes */
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
  }
`
```

**Comment by NathanielHill** [comment]
Yeah, definitely a goof on trying to create my own `className` prop, but I still cannot get either `&.${overlayClassName}` or `.${overlayClassName}` to work. I believe it is because react-modal is generating the modal elements outside of the root `<App/>` in the DOM. It correctly adds the classes to the modal elements, but I guess styled-components is not injecting the CSS because it's not seeing the elements. I will open another issue. #1494
