### ISSUE TITLE
[v2] ThemeProvider is broken on IE <= 10

### ISSUE THREAD

**Issue by procyon** [styled-components/styled-components#765]
## Version
2.0.0-17

## Reproduction

```js
import React from 'react';
import styled from 'styled-components';

const Title = styled.h1`
  font-size: 2em;
  color: ${props => props.theme.color || '#e2e2e2'};
`;
```
## Expected Behavior
The Title component should have the color passed in the ThemeProvider.

## Actual Behavior
The default value is being applied since the theme object is empty.

This works on 1.4.6. Maybe the fix on PR #379 (issue #355) is not applied on v2?

**Comment by anton6** [comment]
Hi

I tried putting that fix into v2 but it did not work. Has anyone else tried it? Can someone please look into this? Thanks.

**Comment by kopax** [comment]
@mxstbr  What is the status of this ? We are really looking to deploy in production and the v2 isn't released yet. It was supposed to be up and ready in February. Could it be possible to sum up all the v2 issues so we can have an overview of the critical bug ? I have seen v2 isn't working with IE10.

**Comment by philpl** [comment]
Seemed simple enough. This should fix it https://github.com/styled-components/styled-components/pull/807

I'm not even sure if we *should* support IE <= 10, but if it comes in such a "cheap package" it's ok I guess.

**Comment by mxstbr** [comment]
> We are really looking to deploy in production and the v2 isn't released yet. It was supposed to be up and ready in February.

It was supposed to be ready when it's finished. I estimated that'd be February, but a bunch of life stuff happened and neither of us core maintainers had time to work on it much. If you want v2 to be finished earlier look at [the milestone](https://github.com/styled-components/styled-components/milestone/5) (which has existed for more than half a year) and start submitting Pull Requests.

FWIW I, and a lot of other folks, are using v2 in production and are perfectly happy. If you've tested your app in all browsers and it works fine nothing can happen anyway! Since you have error tracking you'll also see errors and can fix them.

> I'm not even sure if we should support IE <= 10, but if it comes in such a "cheap package" it's ok I guess.

React supports IE9+ so we support IE9+.

**Comment by philpl** [comment]
Should now be fixed as part of #807.

**Comment by procyon** [comment]
Thank you for the fix.

> FWIW I, and a lot of other folks, are using v2 in production and are perfectly happy.

@mxstbr I'm also using v2 in production for a couple of months and it works pretty well.

Thank you all for the amazing work on styled-components.

**Comment by anton6** [comment]
Thanks for the fix.

Any idea when this is going to be available on npm?

**Comment by philpl** [comment]
@anton6 It is already as v2.0.0-19 or under `@rc` tag. The official release of v2 will be very soon

**Comment by anton6** [comment]
Sweet, thanks
