### ISSUE TITLE
Styled component is destroyed and created when update state of component  

### ISSUE THREAD

**Issue by duytai** [styled-components/styled-components#778]
## Version
1.0.5

## Reproduction

https://www.webpackbin.com/bins/-KjlsG3PM8tF6XX0jc30

## Steps to reproduce
Typing to input field
## Expected Behavior
Must no lose focus
## Actual Behavior
Input loses focus when typing a new character
## 
styled components is destroyed and render again ? why ? It is the annoying problem :D

**Comment by k15a** [comment]
You're declaring your styled-components in the render function. Each time you render the component it will create new styled-components. This way react thinks that it has to rerender them because they changed. You can fix this be moving your styled-components definitions out of the class.

Example: https://www.webpackbin.com/bins/-Kjlukjt6te4NLfU4due

**Comment by duytai** [comment]
@k15a thanks for your support
