### ISSUE TITLE
props.theme is undefined when testing a component

### ISSUE THREAD

**Issue by cocacrave** [styled-components/styled-components#800]
v2.0.0-17
Everything renders fine but with create-react-app, running test:
```
it('renders without crashing', () => {
  const div = document.createElement('div')
  ReactDOM.render(<Heading />, div)
})
```
throws error: TypeError: Cannot read property `x` of undefined.

`x` for me is `colors` property of theme object passed to `ThemeProvider`:
```
const theme = {
  colors: { primary, secondary, etc... }
}
```
Test fails because props.theme is undefined. But everything renders fine. Is this a bug?

**Comment by geelen** [comment]
I just tested this and it looks fine to me. Here's a webpackbin I've just pointed at 2.0.0-17: https://www.webpackbin.com/bins/-KkTI7hqsV0qvukYj3d6

**Comment by geelen** [comment]
What browser are you using? Could it be related to #765?

**Comment by cocacrave** [comment]
I'm using chrome. I don't think it's related to #765. The theme provider passes its props fine and the component renders correctly in browser. The error only shows up with `create-react-app` test console. I tried it with and without `extendWith`.

**Comment by geelen** [comment]
Oh, it's not failing in the browser, just in the test?

**Comment by cocacrave** [comment]
Yeah, it renders fine. Everything works except it fails test.

**Comment by geelen** [comment]
Oh wait, can you post your actual code? Is it something like `${props => props.theme.x.y}`?

**Comment by cocacrave** [comment]
Yep exactly.
```
<ThemeProvider theme={theme}>
  ...
</ThemeProvider>
```

And then somewhere in a child component
`${props => props.theme.x.y}`

throws test error
`TypeError: Cannot read property x of undefined.`

**Comment by bhough** [comment]
@cocacrave I'm assuming the child component is being tested in isolation? If that is the case, your issue is probably that it has no way of getting the theme without the parent component.

You can fix this by explicitly passing the theme in for your test case, or by setting defaults for the theme on the component so it can render when a theme isn't provided. @geelen and crew may have other ways to fix this, but this is how I've handled it.

**Comment by cocacrave** [comment]
Got it, thanks!

**Comment by philpl** [comment]
@cocacrave I'll carefully close this now. I hope you don't mind. Feel free to further comment if you have more problems with testing themed components :)

**Comment by misantronic** [comment]
@bhough @philpl I understand that wrapping the component in the `ThemeProvider` will work because of the missing context. But isn't there a more comfortable way of testing this? You see, I don't want to wrap every single component in a `ThemeProvider`. Maybe there is a way setting a default context for all tests in jest/enzyme?

**Comment by nicholasmaddren** [comment]
I'm also feeling the pain of having to wrap my ThemeProvider around each component. Has anybody found a better method for doing this?

**Comment by probablyup** [comment]
@nicholasmaddren I'd make a utility function that adds it

```jsx
function mountWithTheme(jsx) {
  return enzyme.mount(
    <ThemeProvider theme={theme}>{jsx}</ThemeProvider>
  );
}
```

or something like that

**Comment by lednhatkhanh** [comment]
Get the same problem, `theme` is undefined, does anyone have a solution for this?

**Comment by kitten** [comment]
@lednhatkhanh there are plenty of proposed solutions here, but please open a new issue if you need further help 🙌 this issue is already almost a year old and closed
