### ISSUE TITLE
What was the reason for the order of the arguments that was chosen?

### ISSUE THREAD

**Issue by sebinsua** [styled-components/styled-components#81]
Any reason you [didn't choose to receive the `Target` last](https://github.com/styled-components/styled-components/blob/9301707712678934b291301d896ab767fb4ab2ab/src/constructors/styled.js#L6-L8)?

It would allow this:

```js
import React from 'react';
import styled from 'styled-components';

const styleTitle = styled`
  text-align: center;
  color: palevioletred;
`;

const Title = styleTitle('h1')
const Subtitle = styleTitle('h4')
```

Basically `styled` would return a higher-order component that takes a component and applies the ruleset that was previously created. (It might also create an opportunity at some point to compose rulesets.)

I might not be thinking this through - obviously I only saw the library yesterday. And also, I've been working with [`ramda`](http://ramdajs.com/docs/) and [`recompose`](https://github.com/acdlite/recompose) a lot recently. However, it does feels more right to me that the value you are applying a function to would be the last argument that is supplied to it rather than the first.

**Comment by mxstbr** [comment]
I don't think creating multiple components with the same style is something that should be easier.

A big goal of this API was to "enforce" the components-as-styling-constructs-idea that @chantastic wrote about [here](https://medium.com/learnreact/scale-fud-and-style-components-c0ce87ec9772#.kzjba8lcg) – passing the target _last_ would encourage using the same styles for different components.

That being said, I'd be interested about your use case. Why is `const Title = styleTitle('h1')` better than defining a style fragment or helper function?

**Comment by geelen** [comment]
This is a good question! In terms of data flow, what you describe does make some kind of sense. And I considered it back at the beginning as an alternative (mind you this is before I started doing template strings which I don't think lend themselves to this approach). It's just that in this case, and actually when it comes to anything style-base, pure functional thinking doesn't always lead to the right result.

In particular, I think it's a bad thing to make this kind of all-or-nothing reuse easier — there are (or should be!) extremely few instances where two elements would have precisely the same CSS but different tags. You can always make a component that renders a `h1` or a `h4` depending on props, too.

The other problem is that applying styles to arbitrary elements in this way is actually exactly how CSS classnames work, so there's nothing stopping you using them like this is plain-old HTML & CSS. This project is explicitly about a component-first approach to styling, and so both the tag and the styles are required to build a visual unit.

Hope that helps! Thanks for the question. Btw, this is one reason why I always preferred [fkit](https://github.com/nullobject/fkit) over underscore/lodash, because it got its order of arguments right! :)

**Comment by giuseppeg** [comment]
Probably not a big deal but `styled` as HoC would make it possible to use it as decorator

```javascript
@styled(`
  text-align: center;
  color: palevioletred;
`)
class MyComponent extends React.Component {
  /* ... */
}
```

**Comment by geelen** [comment]
That.... I don't think will work. The presence of the `(` or `)` breaks the tagged template literals. Which we need... ([more info](https://github.com/styled-components/styled-components/blob/master/docs/tagged-template-literals.md)

Would be pretty 😲 if it was possible tho!

**Comment by mxstbr** [comment]
You can actually kind of do that right now @giuseppeg! Not in that specific syntax, but this 99% surely works:

```JS
class MyComp extends Component {
  render() {
    // Attach this.props.className somewhere – it's the styles you pass in below!
    return (<div className={this.props.className}></div>)
  }
}

// Style the component
export default styled(MyComp)`
  background: red;
`;
```

**Comment by giuseppeg** [comment]
@geelen I think that it could be done, for example Babel transpiles tagged template literals to functions.

or this

```javascript
const props = {
  color: 'red'
}

const css = (
  strings, 
  ...interpolations
) => interpolations.map(i=>`${i}Test`)

const styled = styles => tagName => {
  return `<${tagName} style="${css`${styles}`}"></${tagName}>`
}

console.log(
  styled(`color: ${props.color}`)('h1')
)

// > <h1 style="color: redTest"></h1>
```

I've only used template literals for simple use-cases so far so maybe I am missing or doing something wrong. If that's the case please ignore everything I said :)

**Comment by geelen** [comment]
Yeah I don't think that'll work, sorry. Not sure what your `css` function is doing there it seems to be dropping `strings`

In any case, I think we've covered off the original question — should we close this issue?

**Comment by giuseppeg** [comment]
`css` is a simplified / dummy version of the styled-components' one.
It "drops" an array (as you called it `RuleSet`) of `Interpolation`.

What I really meant is: 

```javascript
// src/constructors/styled.js

const styled = (styles: String) =>
    (tag: Target) => styledComponent(tag, css`${styles}`)
```

**Comment by AlexLeung** [comment]
For anyone who wants to use a decorator + styled-components to style a components, just drop this in somewhere:
```
styled.decorator = (strings, ...values) => (Component) => styled(Component)(strings, ...values);
```
Then you can write the following:
```
@styled.decorator`
    padding: 10px;
    background: blue;
    font-size: 12px;
`
class SomeThing extends React.Component {
    render() {
        return <div className={this.props.className}>Hello World</div>
    }
}
```
