### ISSUE TITLE
Upgrading create-react-app from 0.9.5 to 1.0.x breaks styleSheet.rules()

### ISSUE THREAD

**Issue by PlanetIrata** [styled-components/styled-components#811]
Hi, I'm using styled-components v1.4 in an application created with create-react-app. Exporting the CSS to a string with those simple lines of code was working very well until this morning when I upgraded react-scripts to v1.0.5:

```
import styleSheet from 'styled-components/lib/models/StyleSheet';
[render static component...]
let cssRules = styleSheet.rules().map(rule => rule.cssText).join('\n');

```
With react-scripts 0.9.5, everything was working fine, but with react-scripts 1.0.5, styleSheet.rules() now returns an empty array.

Searching in the issues, it seems that this could be due to Webpack 2 now used by react-scripts 1.0.x, but I don't know how to solve it since I'm using create-react-app and don't want to eject.

I revert to react-scripts 0.9.5 and my app works again. 

Any advice on how I could solve this and use SC 1.4  with react-scripts 1.0+ ? I know that SC v2 is on the way with a dedicated SSR API, should I upgrade now and use the release candidate even if the V2 hasn't been released yet ? 

Thanks !

**Comment by geelen** [comment]
Yep, definitely upgrade. The stylesheet.rules API was never officially supported, the new stuff is working well and v2 should be released real soon.

**Comment by PlanetIrata** [comment]
Thanks geelen, I upgraded to V2, but can't find a clear documentation exposing the new v2 SSR API, and any breaking changes introduced by the V2. Could you provide me the equivalent v2 code to get the CSS with V1 styleSheet.rules() ? I tried this:

```
import ServerStyleSheet from 'styled-components/lib/models/ServerStyleSheet';
(...)
let sheet = new ServerStyleSheet();
let html = this.renderForPublish(sheet.collectStyles([my static component...]));
let cssRules = sheet.getStyleTags();
```
But I get an error "BrowserTag cannot be cloned!"

Thanks.

**Comment by mxstbr** [comment]
See the new WIP documentation site, it has a section about our new SSR API: https://sc-next-docs.philpl.com/docs/advanced#server-side-rendering

**Comment by evan-scott-zocdoc** [comment]
I'm seeing this too @mxstbr and I followed the website instructions exactly. Specifically, I'm trying to grab the computed output of the stylesheet in a jest test and do some assertions on it.

![screen shot 2017-05-30 at 3 35 10 pm](https://cloud.githubusercontent.com/assets/25586630/26601377/a4290a34-454d-11e7-8302-9035ae766875.png)

```
BrowserTag cannot be cloned!
```

Any ideas?

**Comment by neezer** [comment]
@evan-scott-zocdoc I'm running into the same issue, and I think it's because Jest sets up a minimal `document` object in your test. `styled-components` does [an internal check](https://github.com/styled-components/styled-components/blob/master/src/models/StyleSheet.js#L146) on whether or not `document` is `undefined`; if so, it uses `ServerStyleSheet`, if not, `BrowserStyleSheet`.

Thus, you'll get `BrowserTag`s instead of `ServerTag`s, which [cannot be cloned](https://github.com/styled-components/styled-components/blob/master/src/models/BrowserStyleSheet.js#L82-L84).

---

The [comment](https://github.com/styled-components/styled-components/blob/master/src/models/StyleSheet.js#L143-L144) in the code says this check might go away with the release of Jest 20, though it neglects to mention how the code would change. 🙁

**Comment by neezer** [comment]
Though honestly it begs the question of why [`new ServerStyleSheet()`](https://github.com/styled-components/styled-components/blob/master/src/models/ServerStyleSheet.js#L87) would ever [return a `BrowserStyleSheet`](https://github.com/styled-components/styled-components/blob/master/src/models/StyleSheet.js#L146), regardless of environment.

**Comment by neezer** [comment]
More on [Jest's `testEnvironment`](http://facebook.github.io/jest/docs/en/configuration.html#testenvironment-string)

**Comment by evan-scott-zocdoc** [comment]
@neezer Jest uses JSDOM, so you get that whole implementation.

**Comment by neezer** [comment]
@evan-scott-zocdoc Yup, so you might have luck adding

```js
/**
 * @jest-environment node
 */
```

... to the top of your test file to avoid the error:

> BrowserTag cannot be cloned!

**Comment by evan-scott-zocdoc** [comment]
@neezer I understand. We can't update to Jest 20 for a bit, but thank you.

**Comment by geelen** [comment]
> Though honestly it begs the question of why new ServerStyleSheet() would ever return a BrowserStyleSheet, regardless of environment.

Hmm I don't think that's the problem. Clone doesn't call `.create()`, it calls the constructor [directly](https://github.com/styled-components/styled-components/blob/master/src/models/StyleSheet.js#L151). I think what you actually need to do is call:

```js
StyleSheet.reset(true)
```

in a `beforeEach`. That's what [we do](https://github.com/styled-components/styled-components/blob/master/src/test/utils.js#L28) in our utils, called with `true` in our [ssr tests](https://github.com/styled-components/styled-components/blob/master/src/test/ssr.test.js#L23).

But yes, Jest 20 should make @neezer's suggestion work too.

**Comment by neezer** [comment]
@geelen `StyleSheet.clone` does indeed call the [constructor directly](https://github.com/styled-components/styled-components/blob/master/src/models/StyleSheet.js#L151); however it is given an argument of [`StyleSheet.instance`](https://github.com/styled-components/styled-components/blob/master/src/models/ServerStyleSheet.js#L87), which will [default](https://github.com/styled-components/styled-components/blob/master/src/models/StyleSheet.js#L136) to `StyleSheet.create()` if no instance is present (which it isn't), so the constructor you end up calling directly is for `BrowserStyleSheet`.

`StyleSheet.reset(true)` does get around the above—basically manually setting the instance instead of relying on the default behavior—but you wouldn't need to do that at all if `new ServerStyleSheet()` couldn't ever return a `BrowserStyleSheet` to begin with.

So my question still stands. 😉

**Comment by PlanetIrata** [comment]
I'm trying for the second time to upgrade to SC v2 (I reverted to 1.4 after opening this issue), but I still have the "BrowserTag" error when creating the new ServerStyleSheet() object. One important thing I don't mention in my previous post: I'm trying to extract the styles with the SSR API, but on the client side. I think this is what's cause the clone error.

Is there any workaround for client side extraction of styles  ? Once again, the styleSheet.rules() was perfectly working in v1.4 on client side, but returns undefined in v2.

Thanks
