### ISSUE TITLE
When installing styled-components Typings export missing ServerStyleSheet

### ISSUE THREAD

**Issue by scundall** [styled-components/styled-components#853]
When we were installing styled-components 2.0.0 (yarn or npm), and then we try to import it as
```
import {
  ServerStyleSheet,
} from 'styled-components';
```
 we were getting error => 
```
ERROR in [at-loader] ./src/server.tsx:11:3 
    TS2305: Module '"/Users/martin.gueswho/notino/Projects/supercoolfeatures/supercoolfeatures-fe/node_modules/styled-components/typings/styled-components"' has no exported member 'ServerStyleSheet'.
```
We checked styled-components.d.ts in the node-modules and they are indeed missing export for
```
export class ServerStyleSheet {
  collectStyles(children: ReactElement<any>): ReactElement<any>
  getStyleTags(): string
  getStyleElement(): ReactElement<any>[]
  static create(): StyleSheet
}
```
Luckily we were able to found styled-components.d.ts here in github that contains missing export, when we manually copy paste the code from styled-components.d.ts in github to nodemodules ...> styled-components....> styled-components.d.ts the problem was fixed

**Comment by philpl** [comment]
It's being worked on

https://github.com/styled-components/styled-components/pull/837
https://github.com/styled-components/styled-components/pull/839

Please refrain from opening issues for things that work on master 😉 It just means that a new version isn't published yet, since we're holding a release until some other PRs are ready. If you have any questions or suggestions regarding the TS typings updates, please look at the PRs above, or comment on them
