### ISSUE TITLE
TypeScript definitions need "extend" functionality

### ISSUE THREAD

**Issue by philipbulley** [styled-components/styled-components#870]
## Version
2.0.0

## Reproduction

Regarding [Extending styles](https://www.styled-components.com/docs/basics#extending-styles):

```ts
// The Button from the last section without the interpolations
const Button = styled.button`
	color: palevioletred;
	font-size: 1em;
	margin: 1em;
	padding: 0.25em 1em;
	border: 2px solid palevioletred;
	border-radius: 3px;
`;

// We're extending Button with some extra styles
const TomatoButton = Button.extend`  // Error: TS2339:Property 'extend' does not exist on type 'ComponentClass<ThemedOuterStyledProps<HTMLProps<HTMLButtonElement>, any>>'.
	color: tomato;
	border-color: tomato;
`;
```
Please note the above error. It looks like the TypeScript definitions are out of sync with the v2 release.

**Comment by philpl** [comment]
They are currently being overhauled: https://github.com/styled-components/styled-components/pull/837

Now, like this issue here: https://github.com/styled-components/styled-components/issues/855
And like this one here: https://github.com/styled-components/styled-components/issues/867

So unfortunately I have to politely ask you to please search or the GitHub issues and PRs for previous stuff first, before opening an issue :wink: If you're unsure you can always send a message on Gitter :+1:
