### ISSUE TITLE
SSR Invalid checksum with async component loading

### ISSUE THREAD

**Issue by scf4** [styled-components/styled-components#883]
I'm getting a markup mismatch error when async loading files with styled-components(*edit).

Example repo: https://github.com/scf4/async-styled-components-issue-example

Run `yarn && yarn start`, go to `http://localhost:8081/`, click to "Page 2", and reload page to server render and check console. 

```
Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) </a><div class="sc-bdVaJa bDWFJH" data-r
 (server) </a><div class="sc-bwzfXH uTxCW" data-re
```

Take a look in `kit/entry` for the SSR stuff.

**Comment by philpl** [comment]
I haven't looked at the repo yet, but this gives me two ideas here already:

1. Are you making sure that the async rendering is not messing with the SSR? If different initial results are produced, you'll see a warning like that.

2. Dynamically creating styled components is not recommended and bad practice. Also it's not necessary. And this is probably breaking ssr for sure

**Comment by scf4** [comment]
I don't seem to get errors without styled components. 

Can you elaborate on #2? How else should this be done?

**Comment by philpl** [comment]
I don't have enough time to read through React async components unfortunately. But since this is the second issue, I'd guess, it's sth with it, not us. Also used react-loadable successfully before with SC. So that makes it less likely as well.

Some ideas on what might be going on: assuming everything is working correctly and you're rendering the same things on the client at the first render cycle, it's our component I'd generation.

Since it's async I'd guess it's changing import order and thus ids. Can you use the ssr option with our babel plugin please, and see if the error persists? :)

**Comment by scf4** [comment]
Yep, looks like the babel plugin fixes it! Thank you :)
