### ISSUE TITLE
`theme` prop name clashes

### ISSUE THREAD

**Issue by khankuan** [styled-components/styled-components#884]
Hi, I'm using ant-design and there are components that uses the `theme` name as a prop. This would cause the `theme` prop in the styled css string to be overwritten. Has anyone found a workaround for that? Thanks!

**Comment by philpl** [comment]
We fully reserve the `theme` prop, and there's nothing that can be done about it. Sorry! 

They're also not inclined to do anything about this: https://github.com/ant-design/ant-design/issues/4873

But for us it's a fundamental part of the library. Chime in here at their repo to get this solved, since it's not something that makes sense to fix on our end. https://github.com/ant-design/ant-design/issues/5570#issuecomment-306147438

We're not really aiming to support these fully fledged base bootstrap-like libs, since they're going into the direction of not styling and building, but picking and mixing, which is inherently going to cause conflicts when building a styling system.

**Comment by khankuan** [comment]
Alright cool! Would love ui-kits to be built on top of styled-components :)

My current workaround is:
```
<StyledMenu
  _theme={theme}>
...
const StyledMenu = styled(Menu)`
  line-height: ${props => props._theme["layout-header-height"]};
`;
```

**Comment by mkralla11** [comment]
This just bit me. I think we need a Reserved Words doc (I apologize if it already exists). I use my own theming technique with styled components and this clash was messing with my defaulting strategy because I didn't know it was reserved. Thanks for the awesome library, btw!

**Comment by philpl** [comment]
@mkralla11 Would you be interested in making a change to our docs, that stresses that this prop is reserved? https://www.styled-components.com/docs/advanced#theming

**Comment by sergoku** [comment]
I don't know how relevant this topic is, but here's a way to avoid conflict between ant design and styled components that worked for me:

You can also create your own type to make this code more readable

export const StyledMenu = styled((props: MenuProps & { menuTheme: MenuProps['theme'] }) => {
  const { menuTheme, ...restProps } = props
  return <Menu {...restProps} theme={menuTheme} />
})`
 // your styles
`

and then use:

`<StyledMenu
            menuTheme="dark"
           // your other props
          />`
