### ISSUE TITLE
How to set up SSR with next.js

### ISSUE THREAD

**Issue by 0xsven** [styled-components/styled-components#912]
I am following the [documentation](https://www.styled-components.com/docs/advanced#nextjs) around sevrer sider rendering and next.

As warned in the docs my app accumulates style rules over time. The docs suggest to `to cache the SSR response to mitigate this for now`. Can someone elaborate on how to do that? This doesn't make much sense to me.

Thank you..

**Comment by philpl** [comment]
This is the official example on the next repo for caching SSR results with a LRU cache.

https://github.com/zeit/next.js/tree/v3-beta/examples/ssr-caching

You can also have a look at the SC website's code, since wereyusing the same.

Note that this doesn't stop CSS from accumulating. Over time, if I'm not mistaken, every page will collect CSS code from across pages.

This is still unresolved as of of now: https://github.com/zeit/next.js/issues/1751

**Comment by 0xsven** [comment]
So in other words: Caching doesn't really help solving the issue.

**Comment by philpl** [comment]
@0xsven No, it just makes it less bad haha
