### ISSUE TITLE
Component created with withComponent() and extend doesn't have all the expected styles

### ISSUE THREAD

**Issue by anikolaev** [styled-components/styled-components#923]
## Version
2.1.0

## Reproduction

https://www.webpackbin.com/bins/-KmiMb8sihntUubq0eF3

## Steps to reproduce

I have one styled component (Button) and an extended one (ButtonRed). I want to create new component (Link) which has all styles of ButtonRed. It should have another tag and some custom styles. I use withComponent() and extend (the only way to do it without creating additional component). 
Here is the code:
```javascript
const Button = styled.span`
  font-family: 'courier';
  font-size: 20px;
  border: 12px solid green;
`
const ButtonRed = styled(Button)`color: red;`
// this one works as expected
//const ButtonRed = Button.extend`color: red;`

const Link = ButtonRed.withComponent('a').extend`
  margin-left: 40px;
`
```

## Expected Behavior
New component should has all styles from components 1 and 2.

## Actual Behavior
New component only has styles from component 2.

**Comment by anikolaev** [comment]
If this is not a bug then maybe some notes should be added to the documentation about the potential side effects of 'styled(...)' comparing to 'extend'.

**Comment by geelen** [comment]
Yep this isn't a bug, it's just confusing (particularly because of how v1 worked).

What you're doing when you do `styled(Button)` is passing a `className` to `Button`. Because `Button` is a styled-component itself, both `classNames` get added and so all styles are present. But when you then do `ButtonRed.withComponent('a')` you're deleting any reference to the `Button`, so there's no way for its styles to be applied. It's the same as doing `styled('a')`, there's just no reference to `Button` at all.

The solution, as you've pointed out, is to use ``const ButtonRed = Button.extend`color: red;` ``. In v1, we had special code handling `styled(X)` that checked if `X` was an SC and we got rid of it for simplicity. Generally, the rule is to use `.extend` if you're trying to generate a few different SCs, and use `styled(X)` if you're trying to put a layer of separation between your SC and whatever `X` is.
