### ISSUE TITLE
reach static (propTypes or other) when importing styled Component

### ISSUE THREAD

**Issue by L3ARNING2B** [styled-components/styled-components#926]
## Version
2.0.1

## Reproduction

https://paste.gnome.org/ppb0vzz3y

## Steps to reproduce
Using react allow access to static `componentId` when imported
When adding styled-component it don't allow access to static `componentId` when imported

## Expected Behavior
console.log(Header.componentId) return the string 'header'

## Actual Behavior
console.log(Header.componentId) return 'undefined'

Thanks for your amazing work.

**Comment by mxstbr** [comment]
That is expected behaviour, sadly I don't think there's anything we can do to fix that.

`styled(Header)` wraps the old component in a second one, and passes in the generated class name, and the wrapper component doesn't have any statics.

What are you trying to do, can we maybe help you achieve it some other way?

**Comment by L3ARNING2B** [comment]
I find `target` and it solve my need !

We can use it as:
`console.log(Header.target.componentId)` return the string 'header'

And if it's a 'double' styled-components' we just have to add another `target` as:
`console.log(Header.target.target.componentId)` return the string 'header'
