### ISSUE TITLE
innerRef example on documentation with styled()

### ISSUE THREAD

**Issue by L3ARNING2B** [styled-components/styled-components#927]
I am trying the following code on the documentation 

https://www.styled-components.com/docs/advanced#refs

```jsx
const Input = styled.input`
	padding: 0.5em;
	margin: 0.5em;
	color: palevioletred;
	background: papayawhip;
	border: none;
	border-radius: 3px;
`;

class Toto extends React.Component {
	render() {
		return (
			<input {...this.props} />
		);
	}
}

const Input2 = styled(Toto)`
	padding: 0.5em;
	margin: 0.5em;
	color: palevioletred;
	background: red;
	border: none;
	border-radius: 3px;
`;

const Form = () => (
	<Input
		placeholder="Hover here..."
		innerRef={x => this.input = x}
		onMouseEnter={() => this.input.focus()}
	/>
);

const Form2 = () => {
	<Input2	placeholder="Hover here..."
		innerRef={x => this.input2 = x}
		onMouseEnter={() => this.input2.focus()}
	/>
}

render(
	<div>
		<Form />
		<Form2 />		
  	</div>
);
```

I would like to see a working demo of the `innerRef` using my demo. I wasn't able to produce it due to JS errors : 

     VM802:29 Uncaught TypeError: Cannot read property 'focus' of null

This seems to happen when I edit too much the javascript in the page.

Could it possible to see both example working ?

**Comment by k15a** [comment]
Could you quickly post a reproduction on codesandbox or webpackbin so I can edit it to show you the issues?

**Comment by L3ARNING2B** [comment]
Of course, here is link to webpack (example)[https://www.webpackbin.com/bins/-KmmdtVFpEYh-J3bQV0e] 

I must comment `Form2` in render cause it make an error.

Thanks for help :+1:

**Comment by k15a** [comment]
Working example: https://codesandbox.io/s/j25wD232z

The innerRef prop doesn't get passed down to the component. styled-components applies the innerRef function to the underlying component as ref so you get the class component `Toto` as ref. So you need to use another prop like `_ref` which gets passed down to the class component which you can then pass down to the input field.

But there is an easier way. If you rewrite this:

```js
class Toto extends React.Component {
	render() {
		return (
			<input {...this.props} />
		);
	}
}

const Input2 = styled(Toto)`
	padding: 0.5em;
	margin: 0.5em;
	color: palevioletred;
	background: red;
	border: none;
	border-radius: 3px;
`;
```
to this:

```js
const Input2 = styled.input`
	padding: 0.5em;
	margin: 0.5em;
	color: palevioletred;
	background: red;
	border: none;
	border-radius: 3px;
`;

class Toto extends React.Component {
	render() {
		return (
			<Input2 {...this.props} />
		);
	}
}
```

You can keep using innerRef. This is also the style we encourage you to write as this is [composition instead of inheritance](https://facebook.github.io/react/docs/composition-vs-inheritance.html) which is more powerful. The `styled(Component)` form exists so you can style third party components like react-routers Link component as well.

Other than that you declare the `Form` and `Form2` component as arrow function which isn't good in this case because the context of the arrow function is always bound to the upper scope. In your example, this is the window object. So `innerRef={x => this.input = x}` basically saves the ref as the input key on the window object. This is probably not the expected behavior from you.

**Comment by L3ARNING2B** [comment]
Thanks you so much for this great example. It's exactly what I needed.

**Comment by joetidee** [comment]
I am having a similar issue. I have a Button styled component:

`<Button innerRef={(elem) => this.btn = elem} />`

but I am getting `null` returned when doing this:

`console.log(this.btn);`

If I use 'ref' instead of 'innerRef', then I get the StyledComponent object back. Are you able to advise?

Gist:
https://gist.github.com/joetidee/5316feb0a39b52bf9b48399888258781

**Comment by joetidee** [comment]
@k15a Could you please provide a quick example of passing down a separate _ref prop?
