### ISSUE TITLE
Test ReactNative

### ISSUE THREAD

**Issue by mxstbr** [styled-components/styled-components#94]
Currently we have some [e2e tests](https://github.com/styled-components/styled-components/blob/master/src/test/e2e.test.js) (and some unit tests, though not enough yet) in place to ensure nothing breaks unexpectedly with changes.

These only test the web version of react though, we somehow need to make sure the changes between `StyledNativeComponent` and `StyledComponent` (and any other possible components) in sync. Any ideas how we could do that?

**Comment by jacobp100** [comment]
I could pick this up. Apart from unit tests (we'll probably want to use jest—#325), we might want to do device snapshot tests.

For snapshot tests, we'll need a RN project—should that be in the core styled-components repo, or should we make a new repo for it? I'm inclined to say new repo because it's easier, and because `css-to-react-native` will also affect the snapshot tests.

I have no idea how to make the CI work either way—if it'll even work with RN 😂

**Comment by mxstbr** [comment]
We test native now! :tada: https://github.com/styled-components/styled-components/blob/master/src/native/test/native.test.js
