### ISSUE TITLE
Not installable via GitHub with new NPM

### ISSUE THREAD

**Issue by codepunkt** [styled-components/styled-components#963]
Hello everyone!

The frequency of styled-components releases to npm is not excessively high. Every small bugfix might potentially be helpful for someone and warrant a patch version release.

Another alternative for those needing a recent commit to master in their working version is the installation via GitHub, e.g. `npm install styled-components/styled-components`. At the moment, this doesn't work because the `dist` and `lib` folders are not committed to the repository 👍 but also not created automatically on installation 👎!

The `prepublish` npm script that is used to build both `dist` and `lib` used to be executed on both publishing a package and installing it. Starting with npm@5 this is no longer the case and `prepublish` is run only when publishing the package.

See https://docs.npmjs.com/misc/scripts#deprecation-note for more information on that topic.

**Comment by mxstbr** [comment]
Wouldn't that mean ever,body who runs `npm install styled-components` would build the package after installing it totally unnecessarioy seeing how the built files are already there?

**Comment by codepunkt** [comment]
That might happen when installing from npm - which virtually everybody will.
Needs to be investigated!

One solution i could think of is checking for build output and only building when it doesn't exist. Needs a cross-operating system node binary to check for existance of files/folders though - something like `rimraf`. Do you know any? Might write one otherwise :)

**Comment by philpl** [comment]
This would need too many changes that aren't reasonable imho:

- moving dev dependencies to dependencies
- dev build weirdness (mentioned above)
- permanent post install hook

I don't think this is sth that a lot of web libraries opt into for these reasons. Have you tried "mom pack" for these purposes?

cc @geelen

**Comment by codepunkt** [comment]
Up until npm @v4, prepublish is a permanent post install hook for everyone running `npm install` without args -
 e.g. cloning a project that uses styled-components on LTS node and running `npm i`.

As long as the post install hook only checks for existance of one or more files/dirs in the overwhelming majority of cases, it might be acceptable?

Not sure about the "moving dev dependencies to dependencies" part. Why?

**Comment by philpl** [comment]
@codepunkt Correct me if I'm wrong, but I think when installing a dependency, even when it's from a repository, yarn/npm won't install any devDependencies. So that means you won't be able to run the build tasks correctly?

We can easily test this by running `npm pack` and then `npm install x.tar.gz` in a separate folder, to see whether the `postinstall` hook succeeds.

Also again, why don't you use `npm pack` and vendor the tarball, when you need a change sooner than we distribute it?

**Comment by codepunkt** [comment]
Afaik, devDependencies are installed by default. There is a cli switch to not install them, which i've never seen someone use.

Never used `npm pack`. Will look into it tomorrow 😁

**Comment by philpl** [comment]
@codepunkt This is only for the current `package.json`. When the package is a dependency of the current project (inside `./package.json`), then the nested dev dependencies (e.g. devDependencies in `node_modules/styled-components/package.json`) won't be installed. This is independent of this flag, since the flag is only for the top level project, not nested dependencies :wink:

Yes, `npm pack` is like "publishing" the current npm project, except that instead of uploading a tarball, it saves it in the current directory

**Comment by philpl** [comment]
I think because of the reasons I've given previously, namely:

- dev build weirdness (mentioned above)
- permanent post install hook

And more:

- moving dev dependencies to dependencies installs lots of "garbage" that people won't need (making installing SC slow)
- making the dev experience worse
- not adhering to web package best practices (GitHub installability is nice for node.js packages, but not for web ones)

And there being an alternative: `npm pack`

Makes this an **undesirable issue** unfortunately 😞

We do have an alternative, that we discussed on Twitter: Semantic Releases. :wink: However, we'll need more discussions around this (Separate issue), since it'd mean that we need to adhere to some Git Message standards.

IMHO we can probably live with just publishing patches more often (e.g. asap when an important change was merged that has at least one issue open)

cc @mxstbr

**Comment by mxstbr** [comment]
Yeah, agreed. Let's start a separate discussion about semantic release!

**Comment by codepunkt** [comment]
Fine with me, thanks for the discussion! 👍 

There's one more possibility: Building and adding `lib` and `dist` on post-commit hook so they're available from GitHub. I've both seen and used that - it has it's own set of tradeoffs, though.

**Comment by k15a** [comment]
Pushing the bundled code to GitHub isn't really a great option because of the extra noise in commits / PRs.

@philpl We could also use the "Squash and Merge" feature from GitHub so we only had to adhere the standard while merging PRs and contributors could write normal commit messages. The downside is that you can't lint the message then.

**Comment by philpl** [comment]
@k15a that's a good idea 🤔 maybe we can use danger and enforce the PR title to contain the correct tag?
