### ISSUE TITLE
HMR [ThemeProvider]

### ISSUE THREAD

**Issue by dmitweb** [styled-components/styled-components#97]
# Version
1.0.5

## Steps to reproduce
Just add theming to your application.

## Expected Behavior
Hot reload application.

## Actual Behavior
![Bug](http://i.imgur.com/wIQjfhx.png)

## Little fix
ThemeProvider:40
`
if (this.context[CHANNEL]) {
  this.unsubscribeToOuter();
}
`
||
define function unsubscribeToOuter previously, maybe in constructor ?
`
this.unsubscribeToOuter = () => ();
`
something like this...

**Comment by mxstbr** [comment]
Hmm, yeah that's because we use the life cycle hooks to subscribe and unsubscribe from context updates. The hack seems to work, but @gaearon might have a better idea how to properly fix this?

**Comment by gaearon** [comment]
I don't see what is hacky there.

The code calls a function in componentWillUnmount that only exists under certain condition. This is not an issue with HMR, it's an issue that will occur in any app that unmounts top-level components.

The fix is to use the same condition in both cases?

(Also ThemeProvider is a bit over-engineered. React Broadcast has concept of "channels" because it is a generic utility. You only need a single "channel" because you are a single purpose tool. So there was no need to use "broadcasts" context field with multiple "channels", you just need to pass a single event emitter down. You can call your context field `styledComponentsTheme` or something like this.)

**Comment by mxstbr** [comment]
@gaearon check the code, I've long done that. Realized it as well!

**Comment by gaearon** [comment]
Ah, got it, right!
Yes, then the fix is to surround `this.unsubscribeToOuter()` with a condition.
I don't see anything hacky about this: the function will only exist for nested providers.
This means SC currently crash any app on unmounting if it has just one provider.
