### ISSUE TITLE
Best practices for exporting styled components 

### ISSUE THREAD

**Issue by corbanbrook** [styled-components/styled-components#972]
When creating styled components is it best practice to export the component as a styled component or non-styled?

In general we have many components that contain complicated logic that wrap style components inside. Take for example a toggle component

![screen shot 2017-07-05 at 4 26 05 pm](https://user-images.githubusercontent.com/62406/27883511-af0bb3ee-619e-11e7-9287-82ad92d02bde.png)

```
export default class ToggleButton extends Component {
   render() {
   ......

    return (
      <StyledContainer className={className}>
        <StyledInput
          type="checkbox"
          id={id}
          name={name}
          checked={checked}
          defaultChecked={defaultChecked}
          disabled={disabled}
          onChange={onChange}/>
        <StyledLabel htmlFor={id}>
          <StyledToggleContainer><StyledToggleSlider/></StyledToggleContainer>
          {children && <div>{children}</div>}
        </StyledLabel>
      </StyledContainer>
    )
  }
}
```

The component itself is not a styled component, but internally uses styles components to make up its structure.

When exporting this non-styled component ToggleButton component we lose the ability to use contextual selectors  as well as `.extend` when importing.

Currently we need to we wrap it in a styled component after importing to add additional styling:

```
import ToggleButton from './ToggleButton'

const AdvancedModeToggleButton = styled(ToggleButton)`
   float: right;
   ...
`
```

This is mainly annoying when we simply want to use contextual selectors like:
```
   const Container = styled.div`
     ${ToggleButton} {
        float: right; 
     }
  `
```

Is it a better practice to export the component wrapped in a styled hoc?:

```
const StyledToggleButton = styled(ToggleButton)`` 

export default StyledToggleButton
```

This seems a little hacky as it creates an additional empty classname.

What are the rest of you doing to handle this?

**Comment by philpl** [comment]
So there's a couple of questions here I guess :smile:

First of all, it's best practice to avoid the contextual selectors as often as possible. Referring from the child to a parent component is most of the times a lot safer, but of course there are some cases where it makes sense. https://www.styled-components.com/docs/faqs#support-for-nesting

Generally speaking `.extend` is only intended for **Styled Components**. Since your class is obviously not one, you should just wrap it in `styled` for the sake of turning it into one.

So this is surely a bit too obvious, but the clue here is: You have two choices, but you're choosing to go with a compromise :wink:

You can either:

- Move the styles inside `StyledContainer` to the `styled` HOC around your class
- Just use the old `styled(Component)` API to additionally style it.

But basically the biggest problem here is:

- `ToggleButton` is a structural component
- You have a second type for it when it's wrapped inside `AdvancedModeToggleButton`
- From the naming I can infer that they'll never be broken up

So the arguably **better** two options are:

- Either create a `AdvancedToggleButton` that is basically `ToggleButton.extend` and use this extended `ToggleButton` inside it directly
- Or refer to `AdvancedToggleButton` inside `ToggleButton` using this selector pattern: `${AdvancedToggleButton} & {}`

Disclaimer: To be clear, I'm not telling you what you *should definitely do*, but it's a suggestion. Go with whatever makes sense for you :smile:

**Comment by hmontes** [comment]
```
Or refer to AdvancedToggleButton inside ToggleButton using this selector pattern: ${AdvancedToggleButton} & {}
```

Can explain that selector pattern with an example, please? I have the same issue.

Thanks

**Comment by mb21** [comment]
@hmontes see https://www.styled-components.com/docs/advanced#referring-to-other-components
