### ISSUE TITLE
Implement a shouldComponentUpdate with a referential equality check

### ISSUE THREAD

**Issue by sylvain-hamel** [styled-components/styled-components#980]
I'm trying to investigate a performance issue (Version : 2.1.1). I have a test case (manual, not automated) that takes 6 seconds when styled-components are enabled but takes 3 seconds if they are disabled.

The profiler reveals that `generateAndInjectStyles` is called very often and takes up most of the time.

If I change my `shouldComponentUpdate` to control the styled component instead of my own `Field` component, then I get back the performance I had before moving to styled-components.

So I can change this:

```
const FieldBase ...
const FieldOptimized = shouldUpdate( props => someConditions)(FieldBase)
const Field  = styled(FieldOptimized)`some styling`;
```

to this:

```
const FieldBase ...
const FieldStyled  = styled(FieldBase)`some styling`;
const Field = shouldUpdate( props => someConditions)( FieldStyled  )
```

and then I get back the performance I had. This is not a viable option because not all my styled-components implement `shouldComponentUpdate` but it demonstrates the issue.

I had a brief look at the project code and I'm wondering if styled-components could be optimized to only recompute the styles (`generateAndInjectStyles`) if the tagged template arguments have changed and otherwise return the _last value_?

This would mean that for styled-components that don't not use props at all, it would only generate the styles once. And for styled-component that do use props, it would only generate the styles when tagged template argument values change (not when any props change because only a small subset of the props may be used in the styling).

I'm willing to work on a PR if you feel like this is the way to go. Otherwise please let me know what you think of the issue and how I should approach it.

**Comment by philpl** [comment]
> if the tagged template arguments have changed and otherwise return the last value

we can't make any assumptions in terms of reference equality. So this would actually worsen performance.

We have an ongoing thread where we've discussed performance problems. And there are two major ones (in this order):

- CSS injection
- CSS parsing (an order of magnitude less of a perf hog)

@geelen is fixing no 1, and no 2 will be fixed in v2 with the addition of preprocessing.

Thank you for your effort, but benchmarking is tough and it's often hard to pin down the exact source of the problem :/ So I can always encourage everyone opening issues to search previous ones with ongoing discussions first

cc @mxstbr

**Comment by mxstbr** [comment]
> we can't make any assumptions in terms of reference equality. So this would actually worsen performance.

Why not? Worst case scenario we're as slow as before (+ one refential eq check which is... fast) because it's a different obj each time, best case scenario we're faster?

That makes sense to me, so I'll reopen this for now until you've replied since I think that'd be a welcome change but I might be missing smth. Should be as simple as `shouldComponentUpdate(nextProps) { return nextProps !== this.props }` right?

**Comment by sylvain-hamel** [comment]
Comparing the props is not enough. Props changes are only relevant to the styled-component if the modified props are used in the style itself. 

I see two cases: 

1 - When no arguments are used in the tagged template (`const RedBox = styled.div`color:red`). 

Maybe styles could only be generated once (`componentDidMount`) during the component lifecycle. Optimizing this may be harder then it looks, but it does look simple at a first glance.

2 - When no arguments are used in the tagged template. 

Unless I'm missing something, all the tagged template arguments are going to be _rendered_ as strings in the css (except for another component reference). Wouldn't comparing each argument's string representation work and be fast?

**Comment by mxstbr** [comment]
> all the tagged template arguments are going to be rendered as strings

That's not true at all, consider functions, `css` templates etc.

**Comment by philpl** [comment]
@mxstbr Then we're kind of back to the old `PureComponent` discussion. There the argument is clearly: We don't want to enforce purity, and it might not be faster since it's all leaf components and it'll need loads of checks.

> Should be as simple as `shouldComponentUpdate(nextProps) { return nextProps !== this.props }` right?

Stuff like this changes the behaviour of our components in a way that affects child components :/ It might not be obvious to the users.

Also, this won't really change much. We're already checking whether the CSS has changed and can further optimise that bit instead

**Comment by mxstbr** [comment]
> Stuff like this changes the behaviour of our components in a way that affects child components

Not really?

The only way child components would change if a parents props didn't is through something global, e.g. theming or redux, both of which would still fire?

**Comment by philpl** [comment]
@mxstbr Let me illustrate what I mean: https://codesandbox.io/s/lJNKRPnV

To highlight the points:

```js
shouldComponentUpdate(nextProps) {
  return nextProps !== this.props // this is always true
}
```

And this will also prevent child components from updating, which for a Styled Component is the target component:

```js
shouldComponentUpdate(nextProps) {
  return false
}
```

So the only optimisation that is safe is: Check whether the props change and prevent unnecessary updates to the DOM element, except that React already does that for us 😉  So the only sensible thing we can do is to prevent the generated classname from even being generated again when it's obviously unnecessary, but that in itself shouldn't be more necessary than making the generation more efficient (think: preprocessing).

**Comment by mxstbr** [comment]
Sure, what about the `styled.x` shorthands?

**Comment by philpl** [comment]
With those React really take care of it for us. We're at the lowest level, so it won't change DOM attributes that we don't change. The only change we can prevent is the generated classname. But since it's just a value that's also no issue.

Really, the only thing we can optimise is preventing regeneration of css when it's obviously not necessary

**Comment by sylvain-hamel** [comment]
We found the root cause of our performance issue. Although `styled-components` made the issue a lot worse, we found out that it's not the cause of the issue. 

The cause is that we had a redux-connected component at the top of the hierarchy that passed down state very deep through props and caused constant rendering of a lot of styled components.

Our issue was a variation of this issue:

> **Inject dispatch and every field in the global state**
> Don’t do this! It kills any performance optimizations because TodoApp will rerender after every state change.
> It’s better to have more granular connect() on several components in your view hierarchy that each only
> listen to a relevant slice of the state.

Source: https://github.com/reactjs/react-redux/blob/master/docs/api.md#inject-dispatch-and-every-field-in-the-global-state

We fixed the issues by changing how things are *connected*.

I'd say you can close this issue.

**Comment by geelen** [comment]
Ok cool. Yeah I remember thinking about this right at the beginning, and couldn't see there being a good implementation of `shouldComponentUpdate` that works for all SCs.

The best possible implementation would be something like the way MobX works—create a proxy object (doesn't have to be a real proxy btw, just an ES5 object with getters), that records which fields were accessed on `props` and `theme`, then do a referential equality check on all used properties. But that seems like pretty unnecessary complexity to be adding to _every_ SC.

In my experience, `shouldComponentUpdate` helps the most when used only in a few key points in the view hierarchy. `styled(x)` will introduce a constant overhead of rendering `x`, sure, but there are lots more ways to prevent `x` being rendered as often.

Plus the parse time for V3 is going to drop through the floor anyway so I'm going to do as you suggested and close this.
