### ISSUE TITLE
handle onMouseOver and onMouseLeave

### ISSUE THREAD

**Issue by webchaz** [styled-components/styled-components#981]
Is there anyway to handle events and pass it directly into the styled component without dealing with state? I was thinking being able to do something like:

`<MyComponent onMouseOver={() => true} onMouseLeave={() => false}></MyComponent>`

**Comment by philpl** [comment]
We don't want to make state part of the equation obviously since you could very easily create a HOC wrapper for it or just embed the logic into one of your components yourself, but there are some other solutions obviously.

You could also just use the `:hover` pseudo selector where you just want to change styling based on mouse hovers. But apart from that hovers will be application UI state, which is not what we manage ;)
