### ISSUE TITLE
Duplications in the generated stylesheet.

### ISSUE THREAD

**Issue by Aftabnack** [styled-components/styled-components#986]
**Possibly a bug**

* Version: 2.1.1
* Reproduction: [Webpack bin](https://www.webpackbin.com/bins/-KopkoqT3ioF_5RZZkT3)

## Expected behaviour

* If you inspect the output area in webpack bin, you can see that the stylesheet generated by the styled component has one common component id (className) style definition, and two variant style definitions
* But there is nothing in the common style definition, and both the variant css definitions are same expect one property that is changing
* I would expect all my static styles to be put into the common class, and only the property which is changing into the two variant definitions

**Comment by philpl** [comment]
We regeneratw the css class to preserve nested specificity correctly. The component I'd class is for ordering in our stylesheet and debugging.

It's expected behaviour ;)

**Comment by Aftabnack** [comment]
Can you give me some example for `nested specificity`. I don't understand that.

Also isn't it more optimal to have the static styles in common class definition?
It's **WAY** less size.

**Comment by philpl** [comment]
It's easily said, but almost impossible due to our DX. We make it easy to mix dynamic mixins and rules inside a component that are dynamic and static. So extracting static styles is almost impossible for us, since dynamic styles don't always take precedence over dynamic ones.

https://gist.github.com/philpl/7b8a021f19ead2ec534091976a1ff6dc#file-2-specificity-md

We talked about it a lot, but these optimisations aren't worth it (perf and DX wise), and are almost impossible with our current usage. Emotion solves it for example by constraining and breaking with previous assumptions. In emotion all dynamic rules take precedence over static ones.

**Comment by Aftabnack** [comment]
Cool. I'll try to go over all the principles that you have mentioned in that. And try a shot at seeing if it's possible to extract till some extent.

Cuz this is the only deal breaker for me, not using this right now.

PS: That Input component in the webpack bin example is my first shot at using `styled-components`.

**Comment by philpl** [comment]
By all means please do and let us know if you have an idea! But don't get me wrong since I don't want to get your hopes up: Glen and I don't think it's possible without compromises which we're not willing to make.

It might be possible that we can provide a way to switch to emotion's behaviour in v3 when the css pipeline is more separate, but that's just an idea of mine right now

Do note that css injection is the slowest part in SC right now and that Glen is fixing this and we'll have a patch ready soon.

Once that's your of the way there's not really a point for static extraction with SSR and preprocessing in v3.

**Comment by philpl** [comment]
Also, feel free to message me on Twitter or Spectrum if you'd like to discuss it in detail :)
